import type { Landform } from './types'

type Range = Omit<Landform, 'kind'>
const range = (r: Range): Landform => ({ ...r, kind: 'range' })

export const mountains: Landform[] = [
  range({
    id: 'himalayas', name: 'Himalayas', continent: 'Asia', countries: ['IN', 'NP', 'BT', 'CN', 'PK'], ne: ['HIMALAYAS', 'Siwalik Hills'],
    stats: [{ label: 'Highest', value: 'Mount Everest, 8,849 m' }, { label: 'Length', value: 'about 2,400 km' }, { label: 'Peaks over 8,000 m', value: '10 of the world\'s 14 (the rest are in the Karakoram)' }],
    summary: 'The highest mountains on Earth, a wall between the Indian subcontinent and the Tibetan Plateau.',
    looks: ['From the road: steep green foothills with terraced fields, pine and rhododendron forest, then white peaks behind; roads cut into cliffs with prayer flags on the passes.', 'In GeoGuessr you are almost always in the foothills (Nepal, Bhutan, northern India): steep terraces, landslides, switchback roads.'],
    formed: ['India broke off from Gondwana and drifted north, colliding with Asia about 50 million years ago. It is still pushing north by about 5 cm a year, so the Himalayas are still rising (a few millimetres a year) and earthquakes are frequent.', 'The rock at the summit of Everest is marine limestone with fossils of sea creatures: it was once the floor of the Tethys Ocean.'],
    history: ['Everest was identified as the highest peak by the Great Trigonometrical Survey of India in 1852 and named after the former Surveyor General George Everest (who objected). Its local names are Sagarmatha (Nepali) and Chomolungma (Tibetan).', 'Tenzing Norgay and Edmund Hillary made the first confirmed ascent on 29 May 1953. George Mallory and Andrew Irvine disappeared near the summit in 1924; Mallory\'s body was found only in 1999.', 'The range has been a barrier and a crossing for trade and pilgrims for millennia: salt, wool and Buddhism moved over passes between Tibet and India.'],
    facts: ['Himalaya is Sanskrit for "abode of snow".', 'The Himalayas and the Tibetan Plateau hold more ice than anywhere outside the poles: the "third pole". Their meltwater feeds the Indus, Ganges, Brahmaputra, Yangtze, Mekong and more, rivers that nearly 2 billion people depend on.', 'The Himalayas block cold air from Central Asia, which is why northern India is warmer than places at the same latitude elsewhere, and they wring the monsoon rain out of the air.'],
    tips: ['Steep terraced hills with prayer flags and Devanagari signs: Nepal or Uttarakhand/Himachal (India). Dzongs and Bhutanese script: Bhutan.'],
    remember: 'The Himalayas are the crumple zone of a car crash: India hit Asia and the bonnet is still folding up.',
    wikipedia: 'Himalayas', photoSearch: 'Himalaya road Nepal',
  }),
  range({
    id: 'karakoram', name: 'Karakoram', continent: 'Asia', countries: ['PK', 'IN', 'CN'], ne: ['KARAKORAM RA.'],
    stats: [{ label: 'Highest', value: 'K2, 8,611 m' }, { label: 'Length', value: 'about 500 km' }],
    summary: 'The most heavily glaciated mountains outside the polar regions, home of K2.',
    looks: ['Bare, brown, jagged rock rising straight from dusty valleys, with grey glaciers and tiny green irrigated oases of poplars and apricot trees.'],
    formed: ['Part of the same India–Asia collision as the Himalayas; the steep relief and dry climate leave rock bare.'],
    history: ['K2 got its name from a survey notebook: it was simply peak 2 of the Karakoram in 1856, and the label stuck. It was first climbed in 1954 by an Italian expedition.', 'The Karakoram Highway, finished in 1979 between Pakistan and China, crosses the Khunjerab Pass at 4,693 m, one of the highest paved border crossings in the world. It follows a branch of the old Silk Road.'],
    facts: ['K2 is called the "Savage Mountain": for decades, about one climber died for every four who reached the top.', 'The Siachen Glacier is the world\'s highest battlefield: India and Pakistan have stationed troops there since 1984.', 'Karakoram means "black gravel" in Turkic.'],
    tips: ['Grey desert mountains with poplar-lined villages in Gilgit-Baltistan are not on Street View (except a few trekkers); think Ladakh in India for a similar look.'],
    remember: 'K2 kept its notebook name: the surveyors never found a local name in time.',
    wikipedia: 'Karakoram', photoSearch: 'Karakoram Highway',
  }),
  range({
    id: 'hindu-kush', name: 'Hindu Kush', continent: 'Asia', countries: ['AF', 'PK'], ne: ['HINDU KUSH', 'Paropamisus Ra.'],
    stats: [{ label: 'Highest', value: 'Tirich Mir, 7,708 m' }, { label: 'Length', value: 'about 800 km' }],
    summary: 'The mountains of Afghanistan, historically the gateway between Central and South Asia.',
    looks: ['Dry, bare brown mountains with snow on top, and green valleys only where rivers flow.'],
    formed: ['A western continuation of the Himalayan–Pamir collision zone; very earthquake-prone.'],
    history: ['Alexander the Great crossed it in 329 BC to reach Bactria and later India. Later Mughal emperors and the armies of the Great Game all used its passes, especially the Khyber Pass to the south-east.', 'The Salang Tunnel, built by the Soviet Union in 1964 at about 3,400 m, links Kabul to northern Afghanistan.'],
    facts: ['The name is often translated as "Hindu killer", said to refer to people who died crossing it; the origin is disputed.', 'Lapis lazuli has been mined in its Badakhshan valleys for over 6,000 years; it was used in Tutankhamun\'s mask.'],
    tips: ['Not on Street View (Afghanistan has almost no coverage).'],
    remember: 'The Hindu Kush is the old gate between Central Asia and India: Alexander walked through it.',
    wikipedia: 'Hindu Kush',
  }),
  range({
    id: 'tian-shan', name: 'Tian Shan', continent: 'Asia', countries: ['KG', 'KZ', 'CN', 'UZ'], ne: ['TIAN SHAN', 'Borohoro Mts.', 'Alataw Mts.'],
    stats: [{ label: 'Highest', value: 'Jengish Chokusu, 7,439 m' }, { label: 'Length', value: 'about 2,500 km' }],
    summary: 'The "Celestial Mountains" of Central Asia, covering most of Kyrgyzstan.',
    looks: ['Huge green grassy valleys with yurts and horses under snow-capped peaks; spruce forest on north-facing slopes, bare slopes facing south.'],
    formed: ['Uplifted far from any plate boundary, by the distant push of India into Asia.'],
    history: ['The northern Silk Road ran along its foothills. Issyk-Kul lake, between its ranges, was a stop on the route.', 'Russian explorer Pyotr Semyonov was the first European to describe it in detail in 1856–57, and was honoured with the name Semyonov-Tyan-Shansky.'],
    facts: ['Tian Shan is Chinese for "heavenly mountains".', 'Issyk-Kul, surrounded by the range, is one of the largest mountain lakes in the world and never freezes, despite being at 1,600 m.'],
    tips: ['Wide grassy valleys with snowy peaks and Cyrillic signs: Kyrgyzstan (or south-east Kazakhstan around Almaty).'],
    remember: 'Tian Shan = heaven\'s mountains, where nomads still move their yurts in summer.',
    wikipedia: 'Tian Shan', photoSearch: 'Kyrgyzstan valley mountains road',
  }),
  range({
    id: 'altai', name: 'Altai Mountains', continent: 'Asia', countries: ['RU', 'MN', 'KZ', 'CN'], ne: ['ALTAY MOUNTAINS'],
    stats: [{ label: 'Highest', value: 'Belukha, 4,506 m' }],
    summary: 'Where Russia, Mongolia, Kazakhstan and China meet: forests, steppe and turquoise rivers.',
    looks: ['Larch forests, turquoise glacial rivers (the Katun) and open steppe valleys; drier and barer towards Mongolia.'],
    formed: ['Old mountains re-lifted by the India–Asia collision, like the Tian Shan.'],
    history: ['Frozen tombs of the Pazyryk culture (about 2,500 years old) preserved tattooed mummies, felt carpets and horses in the permafrost, including the "Ice Maiden" found in 1993.', 'Denisova Cave in the Russian Altai gave its name to the Denisovans, a human species identified in 2010 from the DNA of a single finger bone.'],
    facts: ['Many Turkic and Mongolic peoples trace their origins to the Altai, which gave its name to the (debated) "Altaic" language family.', 'Belukha is sacred to local Altaians and was thought by some to be the gate to Shambhala.'],
    tips: ['Turquoise rivers and larch in Russia: the Altai Republic (the Chuysky Trakt road).'],
    remember: 'The Altai keeps secrets in ice: frozen tattooed mummies and a whole new kind of human.',
    wikipedia: 'Altai Mountains', photoSearch: 'Katun river Altai',
  }),
  range({
    id: 'alps', name: 'Alps', continent: 'Europe', countries: ['FR', 'CH', 'IT', 'AT', 'DE', 'SI', 'LI', 'MC'], ne: ['ALPS'],
    stats: [{ label: 'Highest', value: 'Mont Blanc, 4,806 m' }, { label: 'Length', value: 'about 1,200 km' }],
    summary: 'Europe\'s great range, curving from Nice to Vienna.',
    looks: ['Steep green meadows and dark spruce forest below grey limestone or granite peaks, glaciers, wooden chalets with flowers on balconies, and neat villages in U-shaped valleys.'],
    formed: ['Africa pushing into Europe folded and stacked the rock into huge sheets (nappes) over the last 35 million years. Ice-age glaciers carved the U-shaped valleys and the lakes (Geneva, Como, Garda).'],
    history: ['Ötzi, a man who died about 5,300 years ago, was found frozen in a glacier on the Austria–Italy border in 1991, with his copper axe, clothes and last meal.', 'Hannibal crossed the Alps with elephants in 218 BC to attack Rome; which pass he used is still argued about.', 'Mont Blanc was first climbed in 1786, often counted as the birth of mountaineering. The Matterhorn\'s first ascent in 1865 ended with four of the seven climbers falling to their deaths.', 'The Gotthard Base Tunnel (2016) is the world\'s longest railway tunnel at 57 km.'],
    facts: ['The Alps are the "water tower of Europe": the Rhine, Rhône, Po and major Danube tributaries start here.', 'Mont Blanc\'s summit is officially disputed between France and Italy.'],
    tips: ['Wooden chalets with flower boxes and very neat villages: Switzerland, Austria, Bavaria or South Tyrol. Italian-speaking valleys with stone roofs: the Italian Alps or Ticino.'],
    remember: 'The Alps are Africa\'s bumper dent in Europe, and the source of Europe\'s great rivers.',
    wikipedia: 'Alps', photoSearch: 'Alps road village',
  }),
  range({
    id: 'pyrenees', name: 'Pyrenees', continent: 'Europe', countries: ['ES', 'FR', 'AD'], ne: ['PYRENEES'],
    stats: [{ label: 'Highest', value: 'Aneto, 3,404 m' }, { label: 'Length', value: 'about 430 km' }],
    summary: 'The wall between Spain and France, with Andorra in the middle.',
    looks: ['Green and wet on the French side, drier and browner with stone villages on the Spanish side; few glaciers.'],
    formed: ['The Iberian microplate rotated and collided with France about 55–25 million years ago.'],
    history: ['The Treaty of the Pyrenees (1659) fixed much of the Spain–France border along the crest, and left Llívia as a Spanish town completely surrounded by France.', 'Andorra has been ruled jointly by the Bishop of Urgell and the French head of state since 1278: today the French president is one of its two princes.', 'Thousands escaped Nazi-occupied France over its passes during the Second World War.'],
    facts: ['The Basque language, spoken at the western end, is unrelated to any other language in the world.', 'Unlike the Alps, the Pyrenees had few low passes, which is why it was so much easier to cross into Spain along the coasts.'],
    tips: ['Andorran plates and duty-free shops in a narrow valley: Andorra. Catalan or Basque signs in mountains: the Spanish Pyrenees.'],
    remember: 'The Pyrenees are Spain\'s front door: a wall with a tiny country (Andorra) in the middle.',
    wikipedia: 'Pyrenees', photoSearch: 'Pyrenees road village',
  }),
  range({
    id: 'carpathians', name: 'Carpathians', continent: 'Europe', countries: ['RO', 'UA', 'SK', 'PL', 'CZ', 'HU', 'RS'], ne: ['CARPATHIAN MOUNTAINS', 'Transylvanian Alps', 'Tatra Mts.'],
    stats: [{ label: 'Highest', value: 'Gerlachovský štít, 2,655 m (Tatras)' }, { label: 'Length', value: 'about 1,500 km' }],
    summary: 'A long arc from Slovakia to Romania, with Europe\'s largest old-growth forests.',
    looks: ['Rounded, forested mountains of beech and spruce with hay meadows and wooden villages; only the Tatras and Făgăraș are sharp and rocky.'],
    formed: ['Part of the same collision belt as the Alps.'],
    history: ['The arc surrounds Transylvania, whose Saxon fortified churches and castles (such as Bran, marketed as "Dracula\'s castle") are famous. Bram Stoker never visited.', 'The Transfăgărășan road over the Făgăraș mountains was built in 1970–74 by Ceaușescu as a military route; Top Gear called it the best road in the world.'],
    facts: ['The Carpathians hold Europe\'s biggest populations of brown bears (about 6,000–8,000 in Romania alone), wolves and lynx.', 'The Carpathians carry more old-growth beech forest than anywhere else in Europe (UNESCO-listed).'],
    tips: ['Forested hills with haystacks on poles and wooden churches: Romania (Maramureș), Ukraine or Slovakia.'],
    remember: 'The Carpathians are bear country wrapped round Transylvania like a horseshoe.',
    wikipedia: 'Carpathian Mountains', photoSearch: 'Transfăgărășan',
  }),
  range({
    id: 'caucasus', name: 'Caucasus', continent: 'Europe', countries: ['RU', 'GE', 'AZ', 'AM'], ne: ['CAUCASUS MTS.', 'Lesser Caucasus'],
    stats: [{ label: 'Highest', value: 'Mount Elbrus, 5,642 m' }, { label: 'Length', value: 'about 1,200 km' }],
    summary: 'The range between the Black and Caspian Seas, often counted as the edge of Europe.',
    looks: ['Very steep green valleys with medieval stone watchtowers (Svaneti, Ingushetia), glaciers and snow peaks; drier and browner towards Azerbaijan and Dagestan.'],
    formed: ['The Arabian plate pushing north into Eurasia; Elbrus and Kazbek are dormant volcanoes on top.'],
    history: ['In Greek myth, Prometheus was chained to the Caucasus for giving fire to humans.', 'The Georgian Military Road over the Jvari Pass has linked Tbilisi and Vladikavkaz since antiquity; Pushkin and Lermontov wrote about it.', 'The region has more languages per square kilometre than almost anywhere: over 50, including Georgian, Chechen and dozens in Dagestan.'],
    facts: ['If the Caucasus is the border of Europe, Elbrus (5,642 m) is Europe\'s highest mountain, not Mont Blanc.', 'Svaneti\'s towers were family refuges during blood feuds and raids; some are 1,000 years old.'],
    tips: ['Stone towers in green valleys with Georgian script: Svaneti, Georgia.'],
    remember: 'The Caucasus is the tower country between two seas, and Elbrus steals Mont Blanc\'s title.',
    wikipedia: 'Caucasus Mountains', photoSearch: 'Svaneti towers',
  }),
  range({
    id: 'urals', name: 'Ural Mountains', continent: 'Europe', countries: ['RU', 'KZ'], ne: ['URAL MOUNTAINS'],
    stats: [{ label: 'Highest', value: 'Narodnaya, 1,895 m' }, { label: 'Length', value: 'about 2,500 km' }],
    summary: 'The low, old range that marks the traditional boundary between Europe and Asia.',
    looks: ['Surprisingly low, rounded, forested hills; in many places you would not notice you had crossed them.'],
    formed: ['Formed about 300 million years ago when Europe and Siberia collided; worn down ever since.'],
    history: ['Rich in iron, copper, gold and gemstones, they became Russia\'s industrial heart in the 1700s; many factories were evacuated here from the Nazis in 1941.', 'The last Tsar, Nicholas II, and his family were shot in Yekaterinburg in 1918.', 'The Dyatlov Pass incident (1959), when nine hikers died in mysterious circumstances in the northern Urals, is still debated.'],
    facts: ['There are Europe–Asia boundary monuments along the roads near Yekaterinburg where tourists stand with a foot on each continent.', 'Their age shows: they are only about a fifth as high as the Himalayas.'],
    tips: ['Low forested hills and industrial towns in Russia: Sverdlovsk, Chelyabinsk or Perm.'],
    remember: 'The Urals are an old man now: once as high as the Alps, worn down to hills.',
    wikipedia: 'Ural Mountains', photoSearch: 'Ural mountains road',
  }),
  range({
    id: 'scandinavian', name: 'Scandinavian Mountains', continent: 'Europe', countries: ['NO', 'SE', 'FI'], ne: ['KJØLEN MOUNTAINS', 'Hardanger-vidda'],
    stats: [{ label: 'Highest', value: 'Galdhøpiggen, 2,469 m' }, { label: 'Length', value: 'about 1,700 km' }],
    summary: 'The spine of Norway and Sweden, cut by fjords on the Norwegian side.',
    looks: ['Bare, rounded plateaus above the tree line, snow patches in summer, deep fjords with waterfalls on the west side; gentle slopes into Sweden.'],
    formed: ['An ancient range (the Caledonian mountains, about 400 million years old) re-lifted and then carved by ice-age glaciers into fjords and U-shaped valleys.'],
    history: ['Norway\'s mountain roads and railways are engineering feats: the Flåm Railway, Trollstigen\'s hairpins and the Lærdal Tunnel (24.5 km, the world\'s longest road tunnel).', 'The Sámi have herded reindeer across the northern mountains for centuries.'],
    facts: ['The same Caledonian mountains continue in Scotland, Ireland and the Appalachians: they were one range before the Atlantic opened.', 'Norway\'s Sognefjord reaches over 1,300 m deep.'],
    tips: ['Treeless snowy plateaus with orange snow poles: the Norwegian or Swedish mountains (compare the snow-pole reflectors).'],
    remember: 'The Scandinavian mountains are the Appalachians\' long-lost twin, split by the Atlantic.',
    wikipedia: 'Scandinavian Mountains', photoSearch: 'Norway mountain road plateau',
  }),
  range({
    id: 'dinaric', name: 'Dinaric Alps', continent: 'Europe', countries: ['HR', 'BA', 'ME', 'RS', 'AL', 'SI'], ne: ['Dinaric Alps'],
    stats: [{ label: 'Highest', value: 'Maja Jezercë, 2,694 m (Albania)' }, { label: 'Length', value: 'about 650 km' }],
    summary: 'Grey limestone mountains along the Adriatic, from Slovenia to Albania.',
    looks: ['Bare, white-grey limestone slopes with scrub, dry-stone walls and sinkholes above the blue Adriatic; forested inland.'],
    formed: ['Folded limestone that dissolves in rain, producing caves, sinkholes and underground rivers.'],
    history: ['The word "karst" comes from the Kras plateau at the range\'s north end (Slovenia/Italy): the landform is named after this region.', 'The mountains sheltered Tito\'s partisans in the Second World War.'],
    facts: ['Plitvice Lakes are a staircase of 16 lakes separated by natural travertine dams that are still growing.', 'Postojna Cave (Slovenia) has been a tourist cave since 1819 and has its own underground railway.'],
    tips: ['White rock, dry scrub and the sea below: the Croatian or Montenegrin coast. Green forested inland: Bosnia.'],
    remember: 'The Dinaric Alps gave the world the word "karst": limestone that rain dissolves into caves.',
    wikipedia: 'Dinaric Alps', photoSearch: 'Dinaric Alps road Croatia',
  }),
  range({
    id: 'apennines', name: 'Apennines', continent: 'Europe', countries: ['IT', 'SM'], ne: ['APPENNINI', 'Calabria'],
    stats: [{ label: 'Highest', value: 'Corno Grande, 2,912 m' }, { label: 'Length', value: 'about 1,200 km' }],
    summary: 'The backbone of Italy, running the whole length of the peninsula.',
    looks: ['Rolling green and brown hills with hilltop towns, oak and beech woods and sheep pasture; limestone crags in the centre.'],
    formed: ['Young mountains still rising and very earthquake-prone (L\'Aquila 2009, Amatrice 2016).'],
    history: ['Hilltop towns were built for defence in the Middle Ages and are why central Italy looks like it does.', 'Sheep were moved along ancient drove roads (tratturi) between the mountains and the plains of Puglia for over 2,000 years.'],
    facts: ['Vesuvius and Etna are volcanoes linked to the same subduction zone that raises the Apennines.', 'The word "apennine" may come from a Celtic word for "peak".'],
    tips: ['Stone hilltop towns on green hills: central Italy.'],
    remember: 'The Apennines are Italy\'s spine, with a medieval town sitting on every vertebra.',
    wikipedia: 'Apennine Mountains', photoSearch: 'Apennines hilltop village road',
  }),
  range({
    id: 'atlas', name: 'Atlas Mountains', continent: 'Africa', countries: ['MA', 'DZ', 'TN'], ne: ['ATLAS MOUNTAINS', 'HAUT ATLAS', 'ATLAS SAHARIEN', 'Anti Atlas', 'Moyen Atlas', 'Atlas Tellien', 'Er Rif'],
    stats: [{ label: 'Highest', value: 'Toubkal, 4,167 m' }, { label: 'Length', value: 'about 2,500 km' }],
    summary: 'The mountains that separate the Mediterranean coast of North Africa from the Sahara.',
    looks: ['Red and ochre bare mountains with Berber villages of earth and stone (kasbahs) and green valleys of walnut and almond trees; cedar forests in the Middle Atlas; snow on top in winter.'],
    formed: ['Africa and Europe colliding, like the Alps; the High Atlas rose mainly in the last 60 million years.'],
    history: ['In Greek myth the Titan Atlas was turned to stone here and holds up the sky: the Atlantic Ocean is named after him.', 'Berber (Amazigh) peoples have lived in the mountains for thousands of years; Aït Benhaddou, a fortified village on an old caravan route, appears in many films.'],
    facts: ['Barbary macaques, the only macaques outside Asia, live in the Middle Atlas cedar forests.', 'The Tizi n\'Tichka pass road (2,260 m) links Marrakesh with the desert side.'],
    tips: ['Red earth villages and bare mountains with Arabic and Tifinagh (ⵜⵉⴼⵉⵏⴰⵖ) script: Morocco.'],
    remember: 'The Atlas is the Titan who holds up the sky, and keeps the Sahara off Morocco\'s coast.',
    wikipedia: 'Atlas Mountains', photoSearch: 'High Atlas road village',
  }),
  range({
    id: 'ethiopian-highlands', name: 'Ethiopian Highlands', continent: 'Africa', countries: ['ET', 'ER'], ne: ['ETHIOPIAN HIGHLANDS'],
    stats: [{ label: 'Highest', value: 'Ras Dashen, 4,550 m' }],
    summary: 'The "roof of Africa": a huge high plateau split by the Great Rift Valley.',
    looks: ['High green plateaus with eucalyptus, round thatched huts and dramatic flat-topped mountains (ambas) and canyons.'],
    formed: ['Massive floods of lava about 30 million years ago, then lifted and split by the Rift Valley.'],
    history: ['The plateau\'s height and cool climate helped Ethiopia stay independent: apart from Italy\'s 1936–41 occupation, it was never colonised.', 'Lalibela\'s churches were carved down into solid rock in the 12th–13th centuries.', 'Coffee originated in these highlands.'],
    facts: ['The Blue Nile starts at Lake Tana in the highlands and supplies most of the Nile\'s water in Egypt.', 'Lucy (Australopithecus, 3.2 million years old) was found in the lowlands below, in the Afar.'],
    tips: ['Not on Street View; Kenya and Uganda have similar high green plateaus.'],
    remember: 'The Ethiopian Highlands are Africa\'s rooftop: they gave the world coffee and the Nile its water.',
    wikipedia: 'Ethiopian Highlands',
  }),
  range({
    id: 'drakensberg', name: 'Drakensberg', continent: 'Africa', countries: ['ZA', 'LS'], ne: ['DRAKENSBERG'],
    stats: [{ label: 'Highest', value: 'Thabana Ntlenyana, 3,482 m (Lesotho)' }, { label: 'Length', value: 'about 1,000 km' }],
    summary: 'The great escarpment of southern Africa, with Lesotho on top.',
    looks: ['A basalt wall of cliffs above green, grassy foothills; treeless highlands in Lesotho with round stone huts and blanket-wrapped horsemen.'],
    formed: ['The eroding edge of a thick lava plateau (about 180 million years old).'],
    history: ['The San people left tens of thousands of rock paintings here, some thousands of years old.', 'Voortrekkers crossed it in ox wagons in the 1830s; the Zulu and Boers fought nearby.', 'Lesotho, entirely surrounded by South Africa, is the only country whose lowest point is above 1,000 m.'],
    facts: ['Drakensberg means "dragon mountains" in Afrikaans; the Zulu name uKhahlamba means "barrier of spears".', 'Sani Pass is the only road link from KwaZulu-Natal into eastern Lesotho, famous for its hairpins.'],
    tips: ['Grassy treeless highlands with round stone huts: Lesotho.'],
    remember: 'The Drakensberg is a dragon\'s back with a whole country (Lesotho) sitting on top.',
    wikipedia: 'Drakensberg', photoSearch: 'Drakensberg road',
  }),
  range({
    id: 'andes', name: 'Andes', continent: 'South America', countries: ['VE', 'CO', 'EC', 'PE', 'BO', 'CL', 'AR'], ne: ['ANDES', 'CORDILLERA OCCIDENTAL', 'CORDILLERA ORIENTAL', 'CORD. CENTRAL', 'CORD. OCCIDENTAL', 'CORDILLERA  REAL', 'Cord. de Mérida'],
    stats: [{ label: 'Highest', value: 'Aconcagua, 6,961 m' }, { label: 'Length', value: 'about 7,000 km (the longest continental range)' }],
    summary: 'The longest mountain range above sea level, down the whole west side of South America.',
    looks: ['Very different along its length: green terraced valleys and páramo in Colombia and Ecuador, dry brown puna with llamas and adobe in Peru and Bolivia, the Atacama\'s bare volcanoes, and forests, lakes and glaciers in Patagonia.'],
    formed: ['The Nazca plate diving under South America: the same process makes volcanoes and huge earthquakes (Chile 1960, magnitude 9.5, the strongest ever recorded).'],
    history: ['The Inca built an empire along the Andes, joined by a road network of about 40,000 km (Qhapaq Ñan) and suspension bridges of woven grass.', 'Machu Picchu, built around 1450, was never found by the Spanish and was brought to world attention in 1911.', 'The potato was domesticated in the Andes around Lake Titicaca about 8,000 years ago.', 'San Martín led an army across the Andes in 1817 to free Chile from Spain.'],
    facts: ['Because the Earth bulges at the equator, the summit of Chimborazo in Ecuador is the point furthest from the Earth\'s centre, farther than Everest.', 'La Paz is the highest seat of government in the world (about 3,600 m).', 'Aconcagua is the highest mountain outside Asia.'],
    tips: ['Adobe villages and llamas on brown high plains: the Peruvian or Bolivian altiplano. Snow volcanoes over desert: northern Chile or Argentina.'],
    remember: 'The Andes are a 7,000 km wall where the Inca ran a mountain empire on foot.',
    wikipedia: 'Andes', photoSearch: 'Andes road altiplano',
  }),
  range({
    id: 'rockies', name: 'Rocky Mountains', continent: 'North America', countries: ['US', 'CA'], ne: ['ROCKY MOUNTAINS', 'Front Range', 'Wasatch Range', 'Bitterroot Range', 'Salmon River Mts.'],
    stats: [{ label: 'Highest', value: 'Mount Elbert, 4,401 m' }, { label: 'Length', value: 'about 4,800 km' }],
    summary: 'The mountain spine of western North America, from New Mexico to British Columbia.',
    looks: ['Pine, spruce and aspen forest below bare grey peaks; wide ranch valleys; the mountains rise abruptly from the flat Great Plains on their eastern side.'],
    formed: ['Unusually far from the coast: a plate subducting at a shallow angle pushed up mountains far inland about 80–55 million years ago. Ice-age glaciers carved the valleys.'],
    history: ['Lewis and Clark crossed them in 1805 looking for a route to the Pacific.', 'The Continental Divide runs along the crest: rain on one side flows to the Pacific, on the other to the Atlantic or Arctic.', 'Gold and silver rushes (Colorado 1858, Montana 1860s) filled the valleys with mining towns; many are now ski resorts or ghost towns.'],
    facts: ['Yellowstone (the first national park in the world, 1872) sits on a supervolcano in the Rockies.', 'Denver is exactly one mile (1,609 m) above sea level; a step of the state capitol marks the height.'],
    tips: ['Flat plains suddenly ending at a wall of mountains: the Colorado Front Range. Rockies with green-and-white Canadian signs: Alberta or BC.'],
    remember: 'The Rockies are the Continental Divide: pour a glass of water on the crest and half goes to each ocean.',
    wikipedia: 'Rocky Mountains', photoSearch: 'Rocky Mountains highway',
  }),
  range({
    id: 'sierra-nevada-us', name: 'Sierra Nevada (California)', continent: 'North America', countries: ['US'], ne: ['SIERRA NEVADA'],
    stats: [{ label: 'Highest', value: 'Mount Whitney, 4,421 m' }, { label: 'Length', value: 'about 650 km' }],
    summary: 'The granite range along eastern California, with Yosemite.',
    looks: ['Pale granite domes and cliffs, giant sequoias and pines on the gentle western side; a steep wall dropping to the desert on the east.'],
    formed: ['A huge block of granite tilted up along a fault on its east side, then carved by glaciers.'],
    history: ['The 1848 discovery of gold in its foothills started the California Gold Rush.', 'The Donner Party were trapped by snow in 1846–47, and some survivors resorted to cannibalism.', 'John Muir campaigned for Yosemite, which became a national park in 1890.'],
    facts: ['Mount Whitney (4,421 m) and Death Valley\'s Badwater Basin (−86 m), the highest and lowest points in the contiguous US, are less than 140 km apart.', 'Giant sequoias here are the largest trees on Earth by volume.'],
    tips: ['Granite and tall conifers in California: the Sierra; brown desert just east of it: the Owens Valley on US-395.'],
    remember: 'The Sierra Nevada is a tilted block of granite: gentle on the west, a cliff on the east.',
    wikipedia: 'Sierra Nevada', photoSearch: 'Sierra Nevada highway granite',
  }),
  range({
    id: 'cascades', name: 'Cascade Range', continent: 'North America', countries: ['US', 'CA'], ne: ['CASCADE RANGE'],
    stats: [{ label: 'Highest', value: 'Mount Rainier, 4,392 m' }],
    summary: 'A chain of snow-capped volcanoes from northern California to British Columbia.',
    looks: ['Isolated white volcanic cones (Rainier, Hood, Shasta) above dark, dense evergreen forest; wet and green on the west side, dry pine and sagebrush on the east.'],
    formed: ['The Juan de Fuca plate sliding under North America feeds the volcanoes.'],
    history: ['Mount St. Helens erupted on 18 May 1980, blowing 400 m off its top in the deadliest volcanic event in US history.', 'The range divides the rainy Pacific Northwest from the dry interior, which shaped where people farmed and where timber towns grew.'],
    facts: ['Mount Rainier is considered one of the most dangerous volcanoes in the world because of the mudflows (lahars) it could send towards Seattle–Tacoma.', 'Crater Lake, in a collapsed Cascade volcano, is the deepest lake in the US (594 m).'],
    tips: ['A single huge snowy cone above evergreen forest: Washington or Oregon.'],
    remember: 'The Cascades are a line of sleeping volcanoes, and St. Helens woke up in 1980.',
    wikipedia: 'Cascade Range', photoSearch: 'Mount Hood highway',
  }),
  range({
    id: 'appalachians', name: 'Appalachian Mountains', continent: 'North America', countries: ['US', 'CA'], ne: ['APPALACHIAN MTS.', 'Blue Ridge'],
    stats: [{ label: 'Highest', value: 'Mount Mitchell, 2,037 m' }, { label: 'Length', value: 'about 2,400 km' }],
    summary: 'The old, low, forested mountains of the eastern US.',
    looks: ['Long parallel wooded ridges and valleys running south-west to north-east, rounded summits, dense hardwood forest that turns red and orange in autumn.'],
    formed: ['Once as high as the Himalayas (about 300 million years ago), when Africa collided with North America to form Pangaea. Eroded ever since.'],
    history: ['They blocked westward settlement for more than a century; the Cumberland Gap became the main route west in the 1770s.', 'Coal from Appalachia powered American industry; mining and its decline shaped the region\'s culture and poverty.', 'The Appalachian Trail (3,500 km, completed 1937) runs from Georgia to Maine.'],
    facts: ['Rocks of the same ancient range are found in Scotland, Norway and Morocco\'s Anti-Atlas: the Atlantic opened through the middle of it.', 'The Blue Ridge looks blue from a distance because of the haze (isoprene) given off by the trees.'],
    tips: ['Parallel forested ridges with valleys between them: Pennsylvania, Virginia, West Virginia.'],
    remember: 'The Appalachians were once as tall as the Himalayas: now they are the grandparents of mountains.',
    wikipedia: 'Appalachian Mountains', photoSearch: 'Blue Ridge Parkway',
  }),
  range({
    id: 'sierra-madre', name: 'Sierra Madre (Mexico)', continent: 'North America', countries: ['MX'], ne: ['SIERRA MADRE OCCIDENTAL', 'SIERRA MADRE ORIENTAL', 'Sierra Madre del Sur'],
    stats: [{ label: 'Highest', value: 'Cerro Gordo, about 3,350 m (Occidental)' }],
    summary: 'The two long ranges on either side of Mexico\'s central plateau, plus a third in the south.',
    looks: ['Occidental: pine-oak forest and deep canyons. Oriental: folded limestone ridges around Monterrey. Del Sur: rugged mountains behind Acapulco and in Oaxaca.'],
    formed: ['The Occidental is one of the largest volcanic plateaus on Earth, cut into canyons; the Oriental is folded limestone.'],
    history: ['Copper Canyon (Barranca del Cobre) is a system of canyons larger and deeper in places than the Grand Canyon; the Chihuahua al Pacífico railway (finished 1961) crosses it.', 'The Rarámuri (Tarahumara) people of the Occidental are famous long-distance runners.', 'Apache leaders like Geronimo used the Sierra Madre as a refuge in the 1880s.'],
    facts: ['The ranges trap moist air, which is why Mexico\'s central plateau is dry.', 'The Sierra Madre Occidental\'s highway 40D includes the Baluarte Bridge (2012), once the world\'s highest cable-stayed bridge.'],
    tips: ['Jagged grey limestone peaks behind a big Mexican city: Monterrey (Oriental). Pine forests and canyons: Chihuahua/Durango (Occidental).'],
    remember: 'The Sierra Madre is Mexico\'s two arms hugging the central plateau.',
    wikipedia: 'Sierra Madre Occidental', photoSearch: 'Copper Canyon Chihuahua',
  }),
  range({
    id: 'zagros', name: 'Zagros Mountains', continent: 'Asia', countries: ['IR', 'IQ', 'TR'], ne: ['ZAGROS MOUNTAINS'],
    stats: [{ label: 'Highest', value: 'Mount Dena, 4,409 m' }, { label: 'Length', value: 'about 1,600 km' }],
    summary: 'Long folded ridges across western Iran, where farming may have begun.',
    looks: ['Long parallel folded ridges like a rumpled carpet, oak woodland and dry valleys.'],
    formed: ['Arabia pushing into Iran folds the rock into ridges; the folds trap the Middle East\'s oil.'],
    history: ['Goats and sheep were first domesticated in the Zagros about 10,000 years ago, and some of the earliest farming villages are here.', 'The first oil in the Middle East was struck in 1908 at Masjed Soleyman in the Zagros.', 'The Behistun inscription, carved in a Zagros cliff by Darius the Great, helped scholars decipher cuneiform.'],
    facts: ['Seen from space, the Zagros look like wrinkles in a tablecloth pushed from one side.'],
    tips: ['Not really on Street View (Iran has almost none); Iraqi Kurdistan\'s mountains are similar.'],
    remember: 'The Zagros are where goats became farm animals, and where the Middle East\'s oil was first found.',
    wikipedia: 'Zagros Mountains',
  }),
  range({
    id: 'great-dividing', name: 'Great Dividing Range', continent: 'Oceania', countries: ['AU'], ne: ['GREAT DIVIDING RANGE', 'Blue Mts.', 'Australian Alps'],
    stats: [{ label: 'Highest', value: 'Mount Kosciuszko, 2,228 m' }, { label: 'Length', value: 'about 3,500 km' }],
    summary: 'The long, low range down eastern Australia that splits the wet coast from the dry interior.',
    looks: ['Mostly low, rounded tablelands and hills covered in eucalyptus; deep sandstone gorges in the Blue Mountains; snow in the Australian Alps in winter.'],
    formed: ['Uplifted when Australia split from New Zealand and Antarctica; heavily eroded since.'],
    history: ['The Blue Mountains blocked British settlers from Sydney until Blaxland, Lawson and Wentworth found a way across in 1813.', 'The Snowy Mountains Scheme (1949–74) dammed rivers and bored tunnels to send water inland; over 100,000 people from 30 countries worked on it.'],
    facts: ['The Blue Mountains look blue because of eucalyptus oil haze in the air.', 'Mount Kosciuszko was named by the Polish explorer Strzelecki after the Polish national hero Tadeusz Kościuszko.'],
    tips: ['Eucalyptus hills with fog and sandstone cliffs: the Blue Mountains (NSW).'],
    remember: 'The Great Dividing Range divides Australia into the wet green coast and the dry red inside.',
    wikipedia: 'Great Dividing Range', photoSearch: 'Blue Mountains NSW road',
  }),
  range({
    id: 'southern-alps', name: 'Southern Alps', continent: 'Oceania', countries: ['NZ'], ne: ['SOUTHERN ALPS'],
    stats: [{ label: 'Highest', value: 'Aoraki / Mount Cook, 3,724 m' }, { label: 'Length', value: 'about 500 km' }],
    summary: 'The spine of New Zealand\'s South Island, rising straight out of the sea.',
    looks: ['Rainforest and glaciers on the wet west side; dry golden tussock, turquoise lakes and lupins on the east (Mackenzie Country).'],
    formed: ['The Alpine Fault, a plate boundary, lifts them about 1 cm a year; erosion removes almost as much.'],
    history: ['Edmund Hillary trained here before Everest.', 'Māori crossed the passes to fetch pounamu (greenstone), a treasured stone from the West Coast.'],
    facts: ['The west coast gets up to 10 m of rain a year; the east side, a few hours\' drive away, is dry enough for tussock grassland.', 'Franz Josef and Fox glaciers flow down into rainforest.'],
    tips: ['Turquoise lakes, tussock and snowy peaks: Canterbury/Otago; rainforest and glaciers: the West Coast.'],
    remember: 'The Southern Alps are a rain wall: jungle on one side, golden grass on the other.',
    wikipedia: 'Southern Alps', photoSearch: 'Lake Pukaki road',
  }),
  range({
    id: 'annamite', name: 'Annamite Range', continent: 'Asia', countries: ['VN', 'LA', 'KH'], ne: ['CHAÎNE ANNAMITIQUE'],
    stats: [{ label: 'Highest', value: 'Phou Bia, 2,819 m (Laos)' }, { label: 'Length', value: 'about 1,100 km' }],
    summary: 'The forested mountains along the Vietnam–Laos border.',
    looks: ['Steep, jungle-covered ridges, mist and karst; the Hải Vân Pass drops to the sea near Đà Nẵng.'],
    formed: ['Old mountains reshaped by the India–Asia collision.'],
    history: ['The Ho Chi Minh Trail ran through its forests during the Vietnam War; it was bombed heavily and left unexploded ordnance that still affects Laos.', 'The Hải Vân Pass was the old border between the kingdoms of Champa and Đại Việt.'],
    facts: ['New large mammals were discovered here in the 1990s: the saola (1992), one of the rarest animals on Earth, and the giant muntjac.'],
    tips: ['Misty jungle ridges and switchbacks in central Vietnam or Laos.'],
    remember: 'The Annamites hid the Ho Chi Minh Trail, and an animal science didn\'t know until 1992.',
    wikipedia: 'Annamite Range', photoSearch: 'Hai Van Pass',
  }),
]
