import type { Landform } from './types'

type River = Omit<Landform, 'kind'>
const river = (r: River): Landform => ({ ...r, kind: 'river' })

export const rivers: Landform[] = [
  river({
    id: 'amazon', name: 'Amazon', continent: 'South America', countries: ['BR', 'PE', 'CO'], ne: ['Amazonas', 'Ucayali'],
    stats: [{ label: 'Length', value: 'about 6,400 km' }, { label: 'Discharge', value: 'about 209,000 m³/s (the largest by far)' }, { label: 'Basin', value: 'about 7 million km²' }],
    summary: 'The river with the most water on Earth, flowing across the width of South America.',
    looks: ['Wide, brown, slow water with forest on both banks; towns on stilts and floating houses; in GeoGuessr mostly seen around Manaus, Santarém and Iquitos, or from boat coverage.'],
    formed: ['Fed by Andean snowmelt and the rainforest\'s rain. Once it flowed west into the Pacific; the rise of the Andes reversed it towards the Atlantic.'],
    history: ['Named by the Spanish explorer Francisco de Orellana, the first European to travel its length (1541–42), after he reported fighting female warriors he compared to the Amazons of Greek myth.', 'The rubber boom (about 1879–1912) made Manaus rich enough to build an opera house in the jungle, with tiles and iron shipped from Europe.', 'Archaeologists keep finding evidence of large pre-Columbian societies, including earthworks and fertile "terra preta" (dark earth) made by people.'],
    facts: ['It carries about a fifth of all the river water that reaches the oceans; its fresh water can be detected far out to sea.', 'There is not a single bridge across the main Amazon.', 'At the "Meeting of the Waters" near Manaus, the black Rio Negro and the brown Solimões run side by side without mixing for about 6 km.'],
    tips: ['Boat coverage on a wide brown river with rainforest: the Amazon or its tributaries in Brazil or Peru.'],
    remember: 'The Amazon is a sea pretending to be a river: one fifth of the world\'s river water, and no bridges.',
    wikipedia: 'Amazon River', photoSearch: 'Amazon river Manaus',
  }),
  river({
    id: 'parana', name: 'Paraná', continent: 'South America', countries: ['BR', 'PY', 'AR'], ne: ['Paraná', 'Paranaíba'],
    stats: [{ label: 'Length', value: 'about 4,900 km (with the Paranaíba)' }],
    summary: 'South America\'s second river, running south to the River Plate.',
    looks: ['Wide, muddy, flat and lined with wetlands in Argentina; big reservoirs behind dams in Brazil.'],
    formed: ['Drains southern Brazil, Paraguay and northern Argentina; joins the Uruguay to form the Río de la Plata.'],
    history: ['The Itaipu dam (1984) on the Brazil–Paraguay border was for decades the world\'s biggest producer of hydroelectricity. Paraguay sells most of its half of the power to Brazil.', 'The river was the highway of Spanish colonisation: Asunción (1537) was founded on its tributary before Buenos Aires was permanently settled.'],
    facts: ['Iguazú Falls are on the Iguazú river just before it joins the Paraná.', 'Rosario, Argentina\'s big grain port on the Paraná, is Messi\'s home town.'],
    tips: ['A huge brown river with flat wetlands in Argentina: the Paraná delta (Entre Ríos, Santa Fe).'],
    remember: 'The Paraná is the river that lights Brazil: Itaipu dam sits on it.',
    wikipedia: 'Paraná River', photoSearch: 'Paraná river Rosario',
  }),
  river({
    id: 'sao-francisco', name: 'São Francisco', continent: 'South America', countries: ['BR'], ne: ['São  Francisco'],
    stats: [{ label: 'Length', value: 'about 2,900 km' }],
    summary: 'The "river of national integration", flowing through Brazil\'s dry northeast.',
    looks: ['A green ribbon of irrigated farms and vineyards across dry caatinga scrub; the twin towns of Petrolina and Juazeiro face each other across it.'],
    formed: ['Rises in Minas Gerais and flows north through the semi-arid sertão before turning east to the Atlantic.'],
    history: ['It was the main route into the interior for cattle ranchers in colonial times.', 'Its traditional boats carried carved figureheads (carrancas) meant to scare off evil spirits.', 'A controversial transposition project (from 2007) diverts water through canals to the driest parts of the northeast.'],
    facts: ['Irrigation around Petrolina makes Brazil one of the few places growing wine grapes in the tropics, with two harvests a year.'],
    tips: ['Irrigated green fields and vines in a dry caatinga landscape: the São Francisco valley (Pernambuco/Bahia).'],
    remember: 'The São Francisco is the sertão\'s lifeline: a green stripe through the dry northeast.',
    wikipedia: 'São Francisco River', photoSearch: 'Rio São Francisco Petrolina',
  }),
  river({
    id: 'orinoco', name: 'Orinoco', continent: 'South America', countries: ['VE', 'CO'], ne: ['Orinoco'],
    stats: [{ label: 'Length', value: 'about 2,140 km' }],
    summary: 'The great river of Venezuela, with a huge delta on the Atlantic.',
    looks: ['Wide brown river across the flat llanos grasslands; forest in the south.'],
    formed: ['Connected to the Amazon basin by the Casiquiare canal, a natural channel.'],
    history: ['Columbus reached its mouth in 1498 and realised from the amount of fresh water that he had found a continent, not an island.', 'Alexander von Humboldt confirmed the Casiquiare connection in 1800.'],
    facts: ['The Casiquiare is the world\'s largest river bifurcation: part of the upper Orinoco flows into the Amazon system instead.', 'Angel Falls, the world\'s highest waterfall (979 m), is in its basin.'],
    tips: ['Venezuela has very little Street View; Colombia\'s llanos around its tributaries look similar.'],
    remember: 'The Orinoco leaks into the Amazon through a natural canal.',
    wikipedia: 'Orinoco',
  }),
  river({
    id: 'mississippi', name: 'Mississippi–Missouri', continent: 'North America', countries: ['US'], ne: ['Mississippi', 'Missouri'],
    stats: [{ label: 'Length', value: 'about 6,300 km (Missouri + lower Mississippi)' }, { label: 'Basin', value: 'about 3.2 million km², 31 states' }],
    summary: 'The river system that drains the middle of North America into the Gulf of Mexico.',
    looks: ['Wide, brown, lined with levees, barges and bluffs; flat cotton and rice land in the Delta; bridges between states.'],
    formed: ['Drains everything between the Rockies and the Appalachians.'],
    history: ['The Louisiana Purchase (1803) was really about controlling the river and New Orleans.', 'Steamboats made it America\'s great highway in the 1800s; Mark Twain (a riverboat pilot) took his pen name from "mark twain", the call for two fathoms of depth.', 'Control of the river was a key goal of the Civil War: the fall of Vicksburg in 1863 split the Confederacy.', 'The Great Flood of 1927 displaced hundreds of thousands and helped drive the Great Migration of Black Americans north.'],
    facts: ['Left alone, the Mississippi would have shifted into the Atchafalaya river; the Old River Control Structure has held it in its channel since 1963.', 'Its sediment built Louisiana, which is now losing land to the sea because levees stop the sediment from reaching the coast.'],
    tips: ['Flat Delta cotton land with levees: Mississippi, Arkansas, Louisiana.'],
    remember: 'The Mississippi is America\'s main street: Twain\'s pen name is a river depth call.',
    wikipedia: 'Mississippi River', photoSearch: 'Mississippi River bridge',
  }),
  river({
    id: 'st-lawrence', name: 'St. Lawrence', continent: 'North America', countries: ['CA', 'US'], ne: ['St. Lawrence', 'Niagara', 'St. Clair'],
    stats: [{ label: 'Length', value: 'about 1,200 km (from Lake Ontario)' }],
    summary: 'The outlet of the Great Lakes to the Atlantic, the heart of Quebec.',
    looks: ['A broad river with long narrow farm strips running down to it, silver church steeples and villages along the banks.'],
    formed: ['Drains the Great Lakes, which hold about a fifth of the world\'s surface fresh water.'],
    history: ['Jacques Cartier sailed up it in 1535; Quebec City was founded in 1608. Farmland was divided into long thin strips so every farm had river frontage.', 'The St. Lawrence Seaway (1959) lets ocean ships sail 3,700 km inland to the Great Lakes.'],
    facts: ['Niagara Falls is on the Niagara River, part of the same system, between Lakes Erie and Ontario.', 'Belugas live in the St. Lawrence estuary.'],
    tips: ['Long strip fields down to a wide river with French signs: Quebec.'],
    remember: 'The St. Lawrence is the Great Lakes\' drain, and why Quebec\'s fields are long thin strips.',
    wikipedia: 'Saint Lawrence River', photoSearch: 'St. Lawrence River Quebec village',
  }),
  river({
    id: 'yukon', name: 'Yukon', continent: 'North America', countries: ['CA', 'US'], ne: ['Yukon', 'Teslin'],
    stats: [{ label: 'Length', value: 'about 3,190 km' }],
    summary: 'The great river of the far north-west, from British Columbia across Alaska.',
    looks: ['Wide, silty grey river through spruce forest and mountains, frozen half the year.'],
    formed: ['Glacial meltwater gives it its milky colour.'],
    history: ['The Klondike gold rush (1896–99) sent about 100,000 prospectors north; Dawson City on the Yukon grew to 30,000 people.', 'Sternwheel steamboats carried people and supplies until the Alaska Highway was built (1942).'],
    facts: ['Salmon swim almost 3,000 km up it to spawn, one of the longest salmon migrations.'],
    tips: ['Spruce and a silty river in the far north: Yukon or Alaska.'],
    remember: 'The Yukon floated the Klondike gold rush.',
    wikipedia: 'Yukon River', photoSearch: 'Yukon River Whitehorse',
  }),
  river({
    id: 'rio-grande', name: 'Rio Grande', continent: 'North America', countries: ['US', 'MX'], ne: ['Rio Grande'],
    stats: [{ label: 'Length', value: 'about 3,000 km' }],
    summary: 'The river that forms the Texas–Mexico border (Río Bravo in Mexico).',
    looks: ['A thin green line of cottonwoods and irrigated fields through desert; canyons in Big Bend.'],
    formed: ['Rises in the Colorado Rockies; so much water is taken for irrigation that parts can run dry.'],
    history: ['It became the US–Mexico border after the Mexican–American War (1846–48).', 'Because rivers move, the border moved too; the Chamizal dispute over land at El Paso was only settled in 1963.'],
    facts: ['In some years the river has not reached the Gulf of Mexico at all.'],
    tips: ['Flat irrigated farmland and palms in South Texas: the Rio Grande Valley.'],
    remember: 'The Rio Grande is a border drawn on water: when the river moved, so did the countries.',
    wikipedia: 'Rio Grande', photoSearch: 'Rio Grande Big Bend',
  }),
  river({
    id: 'danube', name: 'Danube', continent: 'Europe', countries: ['DE', 'AT', 'SK', 'HU', 'HR', 'RS', 'RO', 'BG', 'MD', 'UA'], ne: ['Danube', 'Donau', 'Bratul Chillia', 'Bratul Sfintu Gheorghe', 'Bratul Sulina', 'Borcea'],
    stats: [{ label: 'Length', value: 'about 2,850 km' }, { label: 'Countries', value: '10, more than any other river' }],
    summary: 'Europe\'s second-longest river, flowing east from the Black Forest to the Black Sea.',
    looks: ['Castles and vineyards in Austria\'s Wachau; wide plains in Hungary and Serbia; the Iron Gates gorge between Serbia and Romania; a huge wild delta of reeds.'],
    formed: ['Rises in the Black Forest; carved the Iron Gates gorge through the Carpathians.'],
    history: ['It was the northern frontier of the Roman Empire for centuries, lined with forts.', 'Four capitals stand on it: Vienna, Bratislava, Budapest and Belgrade.', 'Johann Strauss II wrote "The Blue Danube" in 1866; the river is rarely blue.', 'The Iron Gates dams (1972) raised the water and drowned the island town of Ada Kaleh.'],
    facts: ['The Danube Delta is one of Europe\'s largest wetlands, home to pelicans.', 'Some of its water disappears underground through limestone near its source and resurfaces in the Rhine\'s basin, the "Danube sinkhole".'],
    tips: ['A huge river with Cyrillic on one bank and Latin on the other: the Serbia–Romania or Romania–Bulgaria border.'],
    remember: 'The Danube connects four capitals and ten countries: Europe\'s great corridor.',
    wikipedia: 'Danube', photoSearch: 'Danube Wachau',
  }),
  river({
    id: 'rhine', name: 'Rhine', continent: 'Europe', countries: ['CH', 'LI', 'AT', 'DE', 'FR', 'NL'], ne: ['Rhine', 'Rhein'],
    stats: [{ label: 'Length', value: 'about 1,230 km' }],
    summary: 'Europe\'s busiest waterway, from the Swiss Alps to the North Sea.',
    looks: ['Castles and steep vineyards in the Rhine Gorge; barges and industry around the Ruhr; flat and diked in the Netherlands.'],
    formed: ['Starts as Alpine meltwater, passes through Lake Constance, and ends in a delta shared with the Meuse.'],
    history: ['It was the Roman frontier: Cologne, Mainz and Bonn began as Roman camps.', 'The Lorelei rock was said to be home to a siren whose song lured boatmen onto the rocks.', 'Its industry was so polluted by the 1970s that it was called "the sewer of Europe"; salmon returned after decades of clean-up.'],
    facts: ['The Rhine Falls near Schaffhausen are one of the most powerful waterfalls in Europe.', 'Rotterdam, at its mouth, is Europe\'s biggest port.'],
    tips: ['Terraced vineyards and castles above a busy river: the Middle Rhine in Germany.'],
    remember: 'The Rhine is the Lorelei\'s river: castles, vines and barges from the Alps to Rotterdam.',
    wikipedia: 'Rhine', photoSearch: 'Rhine Gorge castle',
  }),
  river({
    id: 'volga', name: 'Volga', continent: 'Europe', countries: ['RU'], ne: ['Volga'],
    stats: [{ label: 'Length', value: 'about 3,530 km (Europe\'s longest)' }],
    summary: 'Russia\'s national river, flowing into the Caspian Sea.',
    looks: ['Very wide, turned into a chain of huge reservoirs; steep right bank, flat left bank; the reeds and melons of the delta.'],
    formed: ['Flows into the Caspian, which has no outlet to the ocean.'],
    history: ['Called "Mother Volga" (Volga-matushka); the "Song of the Volga Boatmen" is about the men who hauled barges upstream.', 'Stalingrad (now Volgograd) on the Volga was the site of the turning point of the Second World War in 1942–43.', 'The Volga–Don Canal (1952) connected it to the Black Sea.'],
    facts: ['About 40% of Russia\'s population lives in its basin.', 'The delta is the source of Caspian caviar.'],
    tips: ['A river as wide as a sea with Russian towns: a Volga reservoir (Samara, Tolyatti, Kazan).'],
    remember: 'The Volga is Mother Russia\'s river, and it flows into a lake, not an ocean.',
    wikipedia: 'Volga', photoSearch: 'Volga river bank',
  }),
  river({
    id: 'dnieper', name: 'Dnieper', continent: 'Europe', countries: ['RU', 'BY', 'UA'], ne: ['Dnipro'],
    stats: [{ label: 'Length', value: 'about 2,200 km' }],
    summary: 'The river of Kyiv, running through the middle of Ukraine to the Black Sea.',
    looks: ['Very wide, with steep hills on the right bank at Kyiv; a chain of reservoirs.'],
    formed: ['Rises in Russia\'s Valdai Hills near the sources of the Volga and Western Dvina.'],
    history: ['Kyiv was founded on it; Viking traders used it as the "route from the Varangians to the Greeks" to Constantinople.', 'Prince Volodymyr had the people of Kyiv baptised in the Dnieper in 988.', 'The Kakhovka dam was destroyed in June 2023, draining its huge reservoir.'],
    facts: ['The Zaporizhian Cossacks had their fortress (Sich) below the rapids of the lower Dnieper.'],
    tips: ['A very wide river with Ukrainian signs: the Dnieper at Kyiv, Dnipro or Zaporizhzhia.'],
    remember: 'The Dnieper was the Vikings\' road to Constantinople, and the cradle of Kyiv.',
    wikipedia: 'Dnieper', photoSearch: 'Dnieper Kyiv',
  }),
  river({
    id: 'nile', name: 'Nile', continent: 'Africa', countries: ['EG', 'SD', 'SS', 'UG', 'ET'], ne: ['Nile', 'El Bahr el Abyad', 'Bahr el Jebel', 'Victoria Nile', 'Albert Nile', 'Rosetta Branch', 'Damietta Branch', 'El Bahr el Azraq', 'Abay', 'Kagera'],
    stats: [{ label: 'Length', value: 'about 6,650 km (usually counted the longest)' }, { label: 'Basin', value: '11 countries' }],
    summary: 'The river that made ancient Egypt possible, flowing north through the Sahara.',
    looks: ['A thin band of intense green fields and palms right beside the river, and bare desert beyond: the edge is often sharp enough to stand on.'],
    formed: ['Two branches: the White Nile from Lake Victoria and the Blue Nile from Ethiopia, which join at Khartoum. The Blue Nile brings most of the water and the silt.'],
    history: ['Ancient Egypt depended on the yearly flood, which laid down fertile black mud; Egyptians called their land Kemet, "the black land".', 'The source of the Nile was one of the great questions of 19th-century exploration; Speke identified Lake Victoria in 1858, disputed for years.', 'The Aswan High Dam (1970) ended the floods and created Lake Nasser; the temples of Abu Simbel were cut up and moved to higher ground.'],
    facts: ['About 95% of Egyptians live within a few kilometres of the Nile or its delta.', 'Whether the Nile or the Amazon is longer depends on where you say each one starts.', 'Ethiopia\'s Grand Renaissance Dam on the Blue Nile (filled from 2020) is a major dispute with Egypt and Sudan.'],
    tips: ['Egypt has almost no Street View; in Uganda, the Victoria Nile at Jinja.'],
    remember: 'The Nile is a green thread through the Sahara: Egypt is the gift of the Nile (Herodotus).',
    wikipedia: 'Nile', photoSearch: 'Nile river green fields desert',
  }),
  river({
    id: 'congo', name: 'Congo', continent: 'Africa', countries: ['CD', 'CG', 'CF', 'AO'], ne: ['Congo', 'Lualaba', 'Ubangi', 'Kasai'],
    stats: [{ label: 'Length', value: 'about 4,700 km' }, { label: 'Discharge', value: 'about 41,000 m³/s (second after the Amazon)' }],
    summary: 'Africa\'s biggest river by volume, curving through the central African rainforest.',
    looks: ['Brown and very wide, with rainforest, riverboats piled with goods and people, and rapids near the coast.'],
    formed: ['Crosses the equator twice, so part of its basin is always in rainy season and its flow stays steady.'],
    history: ['Henry Morton Stanley followed it to the sea in 1874–77. Belgium\'s King Leopold II then ruled the Congo Free State as his personal property, with atrocities that killed millions (Joseph Conrad\'s "Heart of Darkness").', 'Kinshasa and Brazzaville face each other across it: the two closest capital cities in the world (apart from Rome and the Vatican).'],
    facts: ['It is the deepest river in the world, over 220 m deep in places.', 'Its rapids (Inga) have one of the largest hydropower potentials on Earth.'],
    tips: ['Almost no Street View in the Congo basin.'],
    remember: 'The Congo crosses the equator twice, so it never runs low.',
    wikipedia: 'Congo River',
  }),
  river({
    id: 'niger', name: 'Niger', continent: 'Africa', countries: ['GN', 'ML', 'NE', 'NG', 'BJ'], ne: ['Niger'],
    stats: [{ label: 'Length', value: 'about 4,180 km' }],
    summary: 'West Africa\'s great river, looping into the Sahara before turning south to Nigeria.',
    looks: ['A huge inland delta of flooded grassland in Mali; mud-brick towns; wide and sandy in Niger.'],
    formed: ['Rises only 240 km from the Atlantic in Guinea but flows away from it, north-east into the desert, then bends south.'],
    history: ['Timbuktu, near its northernmost bend, was a centre of trade and Islamic scholarship; the Mali Empire\'s Mansa Musa became legendary for his wealth in the 1300s.', 'Europeans puzzled for centuries over which way it flowed; Mungo Park reached it in 1796 and drowned on it in 1806.'],
    facts: ['Its strange boomerang course probably comes from two ancient rivers that joined.', 'The Great Mosque of Djenné, in its inland delta, is the largest mud-brick building in the world.'],
    tips: ['Nigeria and Senegal have Street View; Mali and Niger have almost none.'],
    remember: 'The Niger is a boomerang: it runs away from the sea into the desert, then turns back.',
    wikipedia: 'Niger River',
  }),
  river({
    id: 'zambezi', name: 'Zambezi', continent: 'Africa', countries: ['ZM', 'AO', 'NA', 'BW', 'ZW', 'MZ'], ne: ['Zambezi', 'Shire'],
    stats: [{ label: 'Length', value: 'about 2,570 km' }],
    summary: 'The river of Victoria Falls, flowing east to the Indian Ocean.',
    looks: ['Wide and slow with islands and hippos above the falls; deep basalt gorges below; huge reservoirs (Kariba, Cahora Bassa).'],
    formed: ['Victoria Falls drop into a crack in basalt; the falls have retreated upstream through a zig-zag of gorges.'],
    history: ['David Livingstone was the first European to see Victoria Falls (1855) and named them after the queen; the local name is Mosi-oa-Tunya, "the smoke that thunders".', 'The Kariba Dam (1959) created one of the world\'s largest artificial lakes and displaced the Tonga people.'],
    facts: ['Victoria Falls is the largest sheet of falling water in the world (about 1.7 km wide).', 'Four countries almost meet at one point on the Zambezi (Kazungula).'],
    tips: ['Botswana, Zambia and Zimbabwe have some coverage near the falls.'],
    remember: 'The Zambezi is "the smoke that thunders": Victoria Falls.',
    wikipedia: 'Zambezi', photoSearch: 'Victoria Falls Zambezi',
  }),
  river({
    id: 'ganges', name: 'Ganges', continent: 'Asia', countries: ['IN', 'BD'], ne: ['Ganges'],
    stats: [{ label: 'Length', value: 'about 2,500 km' }, { label: 'Basin population', value: 'about 400–500 million' }],
    summary: 'India\'s sacred river, flowing from the Himalayas across the northern plain to Bengal.',
    looks: ['Very flat, densely farmed and populated plain; bathing ghats with steps down to the water at Varanasi and Haridwar.'],
    formed: ['Meltwater from the Gangotri glacier plus monsoon rain; joins the Brahmaputra to form the world\'s largest delta (Sundarbans).'],
    history: ['Holy in Hinduism as the goddess Ganga; pilgrims bathe to wash away sins, and ashes are scattered at Varanasi, one of the oldest continuously inhabited cities.', 'Its plain was the heartland of India\'s great empires (Maurya, Gupta, Mughal).', 'The Kumbh Mela festival at its confluence with the Yamuna draws tens of millions of people, the largest gatherings on Earth.'],
    facts: ['The Sundarbans mangrove forest at its mouth is home to tigers that swim between islands.', 'It carries so much silt that the Bengal delta is still growing.'],
    tips: ['Flat, crowded plains with brick kilns and Hindi signs: the Ganges plain (Uttar Pradesh, Bihar).'],
    remember: 'The Ganges is a goddess: Varanasi\'s steps lead straight down into her.',
    wikipedia: 'Ganges', photoSearch: 'Varanasi ghats',
  }),
  river({
    id: 'indus', name: 'Indus', continent: 'Asia', countries: ['CN', 'IN', 'PK'], ne: ['Indus', 'Shiquan'],
    stats: [{ label: 'Length', value: 'about 3,180 km' }],
    summary: 'The river that gave India its name, flowing through Pakistan to the Arabian Sea.',
    looks: ['Grey glacial river in deep gorges in Ladakh and the Karakoram; irrigated green plains through Punjab and Sindh desert.'],
    formed: ['Rises in Tibet near Mount Kailash, crosses Ladakh and cuts a gorge between the Karakoram and Himalayas.'],
    history: ['The Indus Valley Civilisation (Harappa, Mohenjo-daro, about 2600–1900 BC) had planned cities with drains and baths; its script is still undeciphered.', 'Greek and Persian names for the river (Sindhu, Hindu, Indos) gave us "India" and "Hindu".', 'The Indus Waters Treaty (1960) divides the rivers between India and Pakistan and survived several wars.'],
    facts: ['The Indus river dolphin is almost blind and swims on its side.'],
    tips: ['Grey river in a brown mountain gorge with Buddhist stupas: Ladakh, India.'],
    remember: 'The Indus gave India its name, and one of the first cities with drains.',
    wikipedia: 'Indus River', photoSearch: 'Indus river Ladakh',
  }),
  river({
    id: 'brahmaputra', name: 'Brahmaputra', continent: 'Asia', countries: ['CN', 'IN', 'BD'], ne: ['Brahmaputra', 'Yarlung', 'Dihang'],
    stats: [{ label: 'Length', value: 'about 2,900 km' }],
    summary: 'The river that crosses Tibet, bursts through the Himalayas and floods Assam and Bangladesh.',
    looks: ['Very wide, braided channels with sandbanks in Assam; tea gardens nearby.'],
    formed: ['Flows east across Tibet as the Yarlung Tsangpo, then turns around the eastern end of the Himalayas through the world\'s deepest canyon.'],
    history: ['For decades nobody knew whether the Tsangpo and the Brahmaputra were the same river; Indian "pundit" explorers, secretly surveying for the British, helped prove it (1880s).', 'Majuli, in the river in Assam, is one of the largest river islands in the world and is shrinking from erosion.'],
    facts: ['The Yarlung Tsangpo Grand Canyon is deeper than the Grand Canyon (over 5,000 m in places).', 'Brahmaputra means "son of Brahma": it is one of the few rivers with a male name in India.'],
    tips: ['Wide braided river, tea gardens and Assamese script: Assam.'],
    remember: 'The Brahmaputra hides in Tibet under another name, then crashes through the Himalayas.',
    wikipedia: 'Brahmaputra River', photoSearch: 'Brahmaputra Guwahati',
  }),
  river({
    id: 'mekong', name: 'Mekong', continent: 'Asia', countries: ['CN', 'MM', 'LA', 'TH', 'KH', 'VN'], ne: ['Mekong', 'Lancang', 'Za'],
    stats: [{ label: 'Length', value: 'about 4,900 km' }],
    summary: 'The river of mainland Southeast Asia, from Tibet to Vietnam\'s delta.',
    looks: ['Brown and wide between Laos and Thailand; in Vietnam a delta of canals, rice, coconut palms and floating markets.'],
    formed: ['Rises in Tibet (as the Lancang in China) and forms much of the Laos–Thailand border.'],
    history: ['The Khmer Empire (Angkor) grew rich on its fish and floods.', 'French explorers of 1866–68 hoped it would be a trade route to China, but the Khone Falls and rapids made that impossible.', 'Chinese and Lao dams now trap sediment and fish, a major worry for Cambodia and Vietnam.'],
    facts: ['Cambodia\'s Tonlé Sap river reverses direction every rainy season when the swollen Mekong pushes water back into the lake.', 'It has one of the world\'s richest freshwater fisheries, including the giant Mekong catfish.'],
    tips: ['Canals, rice and coconuts in flat land: the Mekong Delta (Vietnam). A huge river with Thailand on one side: the Lao border.'],
    remember: 'The Mekong makes a lake flow backwards once a year (Tonlé Sap).',
    wikipedia: 'Mekong', photoSearch: 'Mekong Delta canal',
  }),
  river({
    id: 'yangtze', name: 'Yangtze', continent: 'Asia', countries: ['CN'], ne: ['Chang Jiang', 'Yangtze', 'Jinsha', 'Tongtian', 'Tuotuo'],
    stats: [{ label: 'Length', value: 'about 6,300 km (Asia\'s longest)' }],
    summary: 'China\'s longest river, from Tibet to Shanghai.',
    looks: ['Deep gorges in the west (Tiger Leaping Gorge, Three Gorges); wide and busy with ships across the plains to Shanghai.'],
    formed: ['Rises on the Tibetan Plateau and drops over 5,000 m to the sea.'],
    history: ['It roughly divides northern and southern China in culture, food (wheat vs rice) and dialects.', 'The Three Gorges Dam (completed 2006–2012) is the world\'s largest power station; it displaced about 1.3 million people and drowned towns and archaeological sites.', 'Mao Zedong swam in the Yangtze in 1966, aged 72, to show he was still fit.'],
    facts: ['In Chinese it is usually called Cháng Jiāng, "long river". "Yangtze" was the name of just its lower stretch.', 'The Yangtze river dolphin (baiji) was declared functionally extinct in 2006.'],
    tips: ['China has no Street View.'],
    remember: 'The Yangtze is China\'s long river, with the world\'s biggest dam across it.',
    wikipedia: 'Yangtze',
  }),
  river({
    id: 'yellow', name: 'Yellow River', continent: 'Asia', countries: ['CN'], ne: ['Huang'],
    stats: [{ label: 'Length', value: 'about 5,460 km' }],
    summary: 'The "cradle of Chinese civilisation", yellow with loess silt.',
    looks: ['Thick yellow-brown water through the loess plateau; raised above the surrounding land on the North China Plain.'],
    formed: ['Picks up huge amounts of wind-blown loess dust; the silt settles and raises the riverbed, so levees must keep getting higher.'],
    history: ['Early Chinese dynasties grew up along its middle course.', 'Its floods have killed millions: in 1887 and 1931 among the deadliest natural disasters ever. In 1938 Nationalist forces deliberately broke its dykes to slow the Japanese army.', 'It has changed its course to the sea many times, sometimes by hundreds of kilometres.'],
    facts: ['It is called "China\'s Sorrow" for its floods.', 'In the 1990s it often ran dry before reaching the sea because so much water was taken.'],
    tips: ['China has no Street View.'],
    remember: 'The Yellow River is China\'s Sorrow: a river on stilts that keeps jumping its banks.',
    wikipedia: 'Yellow River',
  }),
  river({
    id: 'red-river-vn', name: 'Red River (Sông Hồng)', continent: 'Asia', countries: ['CN', 'VN'], ne: ['Hong'],
    stats: [{ label: 'Length', value: 'about 1,150 km' }],
    summary: 'The river of Hanoi and northern Vietnam, red-brown with silt.',
    looks: ['Reddish-brown water; the densely farmed, flat Red River Delta with rice and villages.'],
    formed: ['Rises in Yunnan, China; the iron-rich silt gives it its colour.'],
    history: ['The delta is the cradle of Vietnamese civilisation; Hanoi ("inside the river") sits on its bank.', 'The Long Biên bridge (1903), built by the French, survived repeated bombing in the Vietnam War. It is often wrongly credited to Gustave Eiffel.'],
    facts: ['Dykes protecting Hanoi have been built up for about 1,000 years.'],
    tips: ['Flat rice plains, tall narrow houses, graves in fields: the Red River Delta.'],
    remember: 'The Red River is red with silt, and Hanoi means "inside the river".',
    wikipedia: 'Red River (Asia)', photoSearch: 'Red River Hanoi Long Bien',
  }),
  river({
    id: 'irrawaddy', name: 'Irrawaddy', continent: 'Asia', countries: ['MM'], ne: ['Ayeyarwady', 'Irrawaddy Delta'],
    stats: [{ label: 'Length', value: 'about 2,170 km' }],
    summary: 'Myanmar\'s great river, from the Himalayas to the Andaman Sea.',
    looks: ['A broad river past thousands of temples at Bagan and rice plains in the delta.'],
    formed: ['Flows almost entirely within one country, from north to south.'],
    history: ['Bagan, on its bank, has over 2,000 surviving Buddhist temples from the 9th–13th centuries.', 'Kipling\'s poem "Mandalay" made "the road to Mandalay" (the river) famous.', 'Cyclone Nargis (2008) killed over 130,000 people in the delta.'],
    facts: ['Irrawaddy dolphins cooperate with fishermen to herd fish into their nets.'],
    tips: ['Myanmar has very little Street View.'],
    remember: 'The Irrawaddy is the road to Mandalay, lined with Bagan\'s temples.',
    wikipedia: 'Irrawaddy River',
  }),
  river({
    id: 'tigris-euphrates', name: 'Tigris and Euphrates', continent: 'Asia', countries: ['TR', 'SY', 'IQ'], ne: ['Tigris', 'Dicle', 'Euphrates', 'Firat', 'Al Furat', 'Shatt al Arab'],
    stats: [{ label: 'Length', value: 'Euphrates about 2,800 km; Tigris about 1,850 km' }],
    summary: 'The twin rivers of Mesopotamia, "the land between the rivers".',
    looks: ['Green strips of palms and fields in brown desert in Iraq; reservoirs and canyons in Turkey.'],
    formed: ['Both rise in eastern Turkey, run through Syria and Iraq, and join as the Shatt al-Arab before the Persian Gulf.'],
    history: ['Sumer, Babylon and Assyria grew up here: some of the first cities, writing (cuneiform) and laws (Hammurabi\'s code).', 'Baghdad was founded on the Tigris in 762 as the capital of the Abbasid caliphate.', 'Turkey\'s dams (the Atatürk Dam, 1990) control much of the water, a source of tension with Syria and Iraq.'],
    facts: ['"Mesopotamia" is Greek for "between the rivers".', 'The Mesopotamian Marshes, once the size of Wales, were drained by Saddam Hussein in the 1990s and partly re-flooded after 2003.'],
    tips: ['Turkey\'s southeast (Diyarbakır, Şanlıurfa) has coverage near both rivers.'],
    remember: 'The Tigris and Euphrates hug the cradle of cities and writing: Mesopotamia.',
    wikipedia: 'Tigris–Euphrates river system', photoSearch: 'Tigris Hasankeyf',
  }),
  river({
    id: 'ob', name: 'Ob', continent: 'Asia', countries: ['RU', 'KZ', 'CN'], ne: ['Ob', 'Irtysh', 'Ertis', 'Ertix'],
    stats: [{ label: 'Length', value: 'about 5,410 km (with the Irtysh)' }],
    summary: 'The great river of western Siberia, flowing north to the Arctic.',
    looks: ['Enormously wide, flat, sandy banks, birch and pine forest, and swamp.'],
    formed: ['Flows north, so its lower course is still frozen when the upper course thaws, causing vast spring floods.'],
    history: ['Novosibirsk grew where the Trans-Siberian Railway bridged the Ob (1897).', 'Yermak\'s Cossacks sailed up the Irtysh in 1582, starting Russia\'s conquest of Siberia.'],
    facts: ['Its estuary, the Gulf of Ob, is about 1,000 km long.'],
    tips: ['Sandy riverbanks and birch in flat Siberia: Novosibirsk, Tomsk, Khanty-Mansi.'],
    remember: 'The Ob flows north into ice, so every spring it floods behind its own frozen mouth.',
    wikipedia: 'Ob (river)', photoSearch: 'Ob river Novosibirsk',
  }),
  river({
    id: 'yenisei', name: 'Yenisei', continent: 'Asia', countries: ['RU', 'MN'], ne: ['Yenisey', 'Angara', 'Selenga', 'Ideriyn'],
    stats: [{ label: 'Length', value: 'about 5,540 km (with the Angara and Selenga)' }],
    summary: 'The river that splits Siberia into the flat west and the plateaus of the east.',
    looks: ['Wide and fast between forested hills; the city of Krasnoyarsk and big dams.'],
    formed: ['The Angara drains Lake Baikal into it; its source rivers start in Mongolia.'],
    history: ['Russian explorers reached it in the early 1600s; Krasnoyarsk was founded in 1628.', 'Stalin-era Gulag camps lined its lower course (Norilsk).'],
    facts: ['It carries more water into the Arctic Ocean than any other river.', 'Lake Baikal, drained by the Angara, holds about a fifth of the world\'s unfrozen fresh surface water.'],
    tips: ['Krasnoyarsk and Irkutsk region coverage.'],
    remember: 'The Yenisei is Siberia\'s dividing line, and Lake Baikal\'s drain.',
    wikipedia: 'Yenisey', photoSearch: 'Yenisei Krasnoyarsk',
  }),
  river({
    id: 'lena', name: 'Lena', continent: 'Asia', countries: ['RU'], ne: ['Lena', 'Bykovskaya Protoka', 'Olenekskaya Protoka'],
    stats: [{ label: 'Length', value: 'about 4,400 km' }],
    summary: 'The river of Yakutia, flowing through permafrost to the Arctic.',
    looks: ['Very wide with the Lena Pillars, tall stone columns along the bank; frozen for about seven months.'],
    formed: ['Flows entirely over permafrost; its delta is a huge Arctic wetland.'],
    history: ['Yakutsk, the coldest large city on Earth, was founded on it in 1632.', 'Vladimir Ulyanov may have taken his revolutionary name "Lenin" from the Lena; the 1912 Lena goldfields massacre of striking miners was a spark for revolution.'],
    facts: ['In winter the frozen river is used as a road ("zimnik").'],
    tips: ['Yakutsk area coverage only.'],
    remember: 'The Lena may have given Lenin his name.',
    wikipedia: 'Lena (river)', photoSearch: 'Lena Pillars',
  }),
  river({
    id: 'amur', name: 'Amur', continent: 'Asia', countries: ['RU', 'CN', 'MN'], ne: ['Amur', 'Heilong Jiang', 'Argun’'],
    stats: [{ label: 'Length', value: 'about 2,820 km' }],
    summary: 'The border river between Russia and China, flowing to the Pacific.',
    looks: ['Wide and brown, Russian towns on one bank and Chinese cities in view on the other.'],
    formed: ['Chinese name Heilong Jiang means "Black Dragon River".'],
    history: ['The Treaty of Aigun (1858) and the Treaty of Peking (1860) moved the border to the Amur and Ussuri, giving Russia the Far East; China still remembers these as "unequal treaties".', 'Soviet and Chinese troops fought over an island in the Ussuri in 1969.'],
    facts: ['The Amur is home to the kaluga, one of the largest freshwater fish in the world (up to 1,000 kg).'],
    tips: ['Blagoveshchensk (Russia) looks across the river at Heihe (China).'],
    remember: 'The Amur is the Black Dragon: the river border between Russia and China.',
    wikipedia: 'Amur River', photoSearch: 'Amur river Khabarovsk',
  }),
  river({
    id: 'murray-darling', name: 'Murray–Darling', continent: 'Oceania', countries: ['AU'], ne: ['Murray', 'Darling', 'Barwon'],
    stats: [{ label: 'Length', value: 'Murray about 2,500 km; Darling about 1,500 km' }, { label: 'Basin', value: 'about 1 million km² (a seventh of Australia)' }],
    summary: 'Australia\'s great river system, the farmland of the inland south-east.',
    looks: ['Slow, brown rivers lined with huge river red gums; irrigated vineyards and citrus near Mildura; dry red plains around the Darling.'],
    formed: ['Rain on the Great Dividing Range flows inland rather than to the nearby coast.'],
    history: ['Paddle steamers carried wool on the Murray in the 1800s before railways.', 'Aboriginal peoples lived along the rivers for tens of thousands of years; fish traps at Brewarrina on the Barwon may be among the oldest human structures.', 'Over-extraction for irrigation led to the Murray–Darling Basin Plan (2012) to return water to the rivers.'],
    facts: ['The Darling sometimes stops flowing altogether in droughts; mass fish deaths at Menindee made headlines in 2019 and 2023.'],
    tips: ['Red gums along a brown river with vineyards: the Murray around Mildura or the Riverland (SA).'],
    remember: 'The Murray–Darling flows away from the sea it is closest to, and waters a seventh of Australia.',
    wikipedia: 'Murray–Darling basin', photoSearch: 'Murray River red gum',
  }),
]
