import type { CountryFeature, FeatureCategory } from './featureTypes'

// Notable features by area, per country. Mostly paraphrased from the PlonkIt guides
// (https://www.plonkit.net), plus a few general facts worth knowing (codes, crops, soils).
// "Common" means common, not exclusive: combine features before committing to a guess.

type Opts = Pick<CountryFeature, 'notable' | 'plant' | 'photoSearch'>

function maker(country: string) {
  return (id: string, category: FeatureCategory, title: string, regions: string, text: string, opts: Opts = {}): CountryFeature => ({
    id: `${country.toLowerCase()}-${id}`,
    title,
    category,
    regions: regions.split(/\s+/).filter(Boolean).map((r) => `${country}-${r}`),
    text,
    ...opts,
  })
}

// ---- Brazil ----------------------------------------------------------------------------------------
const br = maker('BR')
const brazil: CountryFeature[] = [
  br('ddd-1', 'Signs & codes', 'Phone area codes 11–19', 'SP', 'Every area code starting with 1 is in São Paulo state (11 is the city).', { notable: true }),
  br('ddd-2', 'Signs & codes', 'Phone area codes 21–28', 'RJ ES', 'Rio de Janeiro (21, 22, 24) and Espírito Santo (27, 28).', { notable: true }),
  br('ddd-3', 'Signs & codes', 'Phone area codes 31–38', 'MG', 'All of Minas Gerais (31 is Belo Horizonte).', { notable: true }),
  br('ddd-4', 'Signs & codes', 'Phone area codes 41–49', 'PR SC', 'Paraná (41–46) and Santa Catarina (47–49).', { notable: true }),
  br('ddd-5', 'Signs & codes', 'Phone area codes 51–55', 'RS', 'All of Rio Grande do Sul (51 is Porto Alegre).', { notable: true }),
  br('ddd-6', 'Signs & codes', 'Phone area codes 61–69', 'DF GO TO MT MS RO AC', 'The centre-west and west: Brasília 61, Goiás 62/64, Tocantins 63, Mato Grosso 65/66, Mato Grosso do Sul 67, Acre 68, Rondônia 69.', { notable: true }),
  br('ddd-7', 'Signs & codes', 'Phone area codes 71–79', 'BA SE', 'Bahia (71, 73, 74, 75, 77) and Sergipe (79).', { notable: true }),
  br('ddd-8', 'Signs & codes', 'Phone area codes 81–89', 'PE AL PB RN CE PI', 'The rest of the northeast: Pernambuco 81/87, Alagoas 82, Paraíba 83, Rio Grande do Norte 84, Ceará 85/88, Piauí 86/89.', { notable: true }),
  br('ddd-9', 'Signs & codes', 'Phone area codes 91–99', 'PA AM RR AP MA', 'The north: Pará 91/93/94, Amazonas 92/97, Roraima 95, Amapá 96, Maranhão 98/99.', { notable: true }),
  br('concrete-bins', 'Culture & shops', 'Concrete rubbish baskets', 'AC RO', 'The raised baskets outside houses for rubbish are made of concrete here; the rest of Brazil uses metal ones.', { notable: true }),
  br('rollercoaster', 'Roads', 'Rollercoaster road over grassy hills', 'AC', 'The BR-364 rides straight over small grass hills with scattered trees, instead of winding round them. A red-brick road surface appears in some towns.', { notable: true , photoSearch: 'BR-364 Acre' }),
  br('stilts', 'Architecture', 'Wooden houses on stilts', 'AC AM PA', 'Very common in Acre, less so in low-lying Amazonas and Pará.'),
  br('araucaria', 'Plants & crops', 'Araucaria pines', 'PR SC RS', 'Candelabra-shaped pines with long horizontal branches and leaves only at the tips.', { notable: true, plant: 'araucaria' }),
  br('carnauba', 'Plants & crops', 'Carnaúba palms', 'CE PI RN', 'Short, stiff fan leaves; trunk smooth at the top and spiky at the bottom. Also around Xique-Xique in Bahia.', { notable: true, plant: 'carnauba' }),
  br('babassu', 'Plants & crops', 'Babassu palms', 'MA PI TO PA', 'Big, robust feathery fronds, often left standing in pastures.', { plant: 'babassu' }),
  br('acai', 'Plants & crops', 'Açaí palms', 'PA AP AM', 'Very thin trunks in clumps with drooping leaflets; most common around Belém.', { plant: 'acai' }),
  br('buriti', 'Plants & crops', 'Buriti (moriche) palms', 'RR AM TO GO', 'Rounded fan leaves with dead leaves hanging down; in wet grassland.', { plant: 'buriti' }),
  br('macaw', 'Plants & crops', 'Macaw palms', 'MS TO MG', 'Thin leaves and a visible spear-shaped top; groups of them are a good sign.'),
  br('caatinga', 'Landscape & soil', 'Dry thorny scrub (caatinga)', 'CE RN PB PE AL SE BA PI', 'Grey dry shrubs and cacti inland in the northeast; deceptively green in the rainy season.', { plant: 'caatinga' , photoSearch: 'caatinga estrada' }),
  br('tall-grass', 'Landscape & soil', 'Very tall roadside grass', 'TO GO BA MG', 'Grass taller than a person along the road in the centre of the country.'),
  br('red-soil', 'Landscape & soil', 'Red soil', 'PR SP MG GO DF MT MS TO RO SC', 'Red to deep maroon soil across the centre and south; not red on the northeast coast or most of Rio Grande do Sul.', { plant: 'red-tropical-soil' }),
  br('white-sand', 'Landscape & soil', 'White sand with coconut palms', 'CE RN PB PE AL SE PI BA', 'Sandy grey-white ground near the northeast coast.', { plant: 'white-sand' }),
  br('coffee', 'Plants & crops', 'Coffee on hillsides', 'MG ES SP', 'Rows of dark bushes on hills; by far most common in Minas Gerais.', { plant: 'coffee' }),
  br('sugarcane', 'Plants & crops', 'Sugarcane', 'SP PR MS AL PE', 'Endless in São Paulo state; also on the northeast coast.', { plant: 'sugarcane' }),
  br('round-poles', 'Poles', 'Round concrete poles', 'SP PR MS', 'Cylindrical concrete poles alongside the usual ladder poles, especially in São Paulo.'),
  br('wood-poles', 'Poles', 'Wooden poles', 'RS RR AM RJ', 'Most Brazilian poles are concrete; wooden ones are common in these states.'),
  br('pole-letter', 'Poles', 'Long yellow pole ID starting with a letter', 'BA PE', 'Long yellow paint with a black code that starts with a letter. In Goiás the code starts with a number.'),
  br('beige-plate', 'Poles', 'Small beige number plate set into the pole', 'MA', 'Built into the concrete of most poles in Maranhão (rarely Pará and Piauí).', { notable: true }),
  br('mushroom', 'Poles', 'Mushroom-shaped insulators', 'PE BA', 'Brown mushroom insulators only in Pernambuco; white ones in Bahia.', { notable: true }),
  br('lollipop', 'Poles', '"Lollipop" insulators', 'RN PB PE', 'Round or cone insulators on a rod above the crossbar.'),
  br('pencil', 'Poles', 'Pencil poles and Γ poles', 'RJ', 'Poles with a smooth cone on top, and Γ-shaped poles with boxes at the end; Rio\'s street lamps curve along their whole arm.', { notable: true }),
  br('two-part-lamps', 'Roads', 'Two-part street lamps', 'MG GO', 'Lamps built in two parts (also some in Rio Grande do Norte, Ceará and Brasília).'),
  br('ceara-lamps', 'Roads', 'Colourful fancy lamp arms', 'CE', 'Decorated, colourful lamp arms, sometimes with the town\'s name.'),
  br('red-gravel', 'Roads', 'Red gravel shoulders', 'PI', 'Red gravel along the road edges.'),
  br('divided', 'Roads', 'Many divided highways', 'SP', 'São Paulo has far more dual carriageways than any other state.'),
  br('hexagon', 'Roads', 'Hexagonal concrete paving', 'SC MG', 'Found across Brazil but more common here.'),
  br('german', 'Architecture', 'German-style houses', 'SC RS', 'Half-timbered and alpine-looking houses from German immigration.', { photoSearch: 'Pomerode enxaimel' }),
  br('flori-poles', 'Poles', 'White poles with blue and red stripes', 'SC', 'On Florianópolis island.'),
  br('nests', 'Poles', 'Clay ball nests on poles', 'PR SC RS SP', 'Round mud nests of the rufous hornero (João-de-barro) on crossbars, common in the south.'),
]

// ---- Mexico ----------------------------------------------------------------------------------------
const mx = maker('MX')
const mexico: CountryFeature[] = [
  mx('three-line', 'Roads', 'Cobblestones with three lines along the road', 'OAX', 'A distinctive pavement of cobbles with three lines of stones running along the street.', { notable: true }),
  mx('blue-agave', 'Plants & crops', 'Blue agave fields', 'JAL NAY', 'Rows of blue-grey spiky agave for tequila, often on red soil.', { notable: true, plant: 'agave', photoSearch: 'blue agave field Tequila' }),
  mx('pulque', 'Plants & crops', 'Pulque agaves', 'MEX HID TLA PUE SLP QUE', 'Huge agaves with wide, smooth, curling leaves like a crown, in the central valleys.', { photoSearch: 'Agave salmiana field' }),
  mx('red-band', 'Bollards & markers', 'Bollards with a red band', 'NAY', 'White bollards with a red band near the top (one exception on Highway 190 on the Oaxaca–Chiapas border).', { notable: true }),
  mx('jalisco-bollard', 'Bollards & markers', 'Bollards with a crown and writing', 'JAL', 'Some bollards carry a crown and the state\'s name; no other state writes on its bollards.'),
  mx('hanging', 'Poles', 'Insulators hanging below the crossbar', 'YUC ROO CAM', 'Concrete poles with the insulators suspended under the crossbar.', { notable: true }),
  mx('hanging-wood', 'Poles', 'Wooden poles with hanging insulators', 'BCN BCS', 'The wooden version of the hanging-insulator pole.'),
  mx('stacked', 'Poles', 'Asymmetric crossbar with double-stacked insulators', 'CMX MEX HID MOR', 'Around Mexico City.'),
  mx('mesh', 'Poles', 'Mesh-bodied poles', 'SLP GUA QUE', 'Poles with an open lattice body.'),
  mx('low-crossbar', 'Poles', 'Wooden poles with a lowered crossbar', 'SIN SON', 'In Durango the lowered crossbar has one diagonal support instead.'),
  mx('acorn', 'Poles', 'White acorn-shaped insulators', 'MIC COL VER', 'Found on the coast, most of all in these states.'),
  mx('hexagon', 'Roads', 'Hexagonal paving tiles', 'PUE TLA', 'Streets paved with hexagonal tiles.'),
  mx('cobbles', 'Roads', 'Irregular cobblestones', 'NAY JAL COL QUE', 'Disorderly cobbles of mixed sizes.'),
  mx('tar', 'Roads', 'Black tar either side of the centre line', 'SIN DUR GRO', 'Most reliable when the tar is fresh.'),
  mx('grainy', 'Roads', 'Grainy blue-grey road surface', 'TAM NLE', 'In Tamaulipas big roads often have dashed outer lines too.'),
  mx('white-lines', 'Roads', 'White centre lines', 'TAB', 'Mexico normally uses yellow centre lines.'),
  mx('cross', 'Signs & codes', 'A cross on the back of signs', 'CHH', 'A thick cross painted or welded on sign backs.', { notable: true }),
  mx('ladas', 'Signs & codes', 'Two-digit area codes 55, 33, 81', 'CMX MEX JAL NLE', 'Only the big three cities have two-digit codes: 55 Mexico City, 33 Guadalajara, 81 Monterrey. Everywhere else has three digits.'),
  mx('red-brick', 'Architecture', 'Red brick buildings', 'JAL MIC GUA AGU', 'Unrendered red brick west of Mexico City.'),
  mx('mud-brick', 'Architecture', 'Mud-brick houses', 'DUR ZAC CHH COA', 'Whole houses of adobe, most of all in Durango.'),
  mx('thatch', 'Architecture', 'Thatched roofs and pale stone walls', 'YUC ROO CAM', 'Oval Maya houses with thatch, and walls of loose pale limestone.', { photoSearch: 'Yucatan maya house thatched' }),
  mx('saguaro', 'Plants & crops', 'Saguaro and organ pipe cacti', 'SON', 'Saguaros only in western Sonora; organ pipes too.', { notable: true, plant: 'saguaro' }),
  mx('cardon', 'Plants & crops', 'Giant cardón cacti and boojum trees', 'BCN BCS', 'Huge low-branching cacti; tentacle-like boojums in southern Baja California.', { notable: true, plant: 'cardon' }),
  mx('yucca', 'Plants & crops', 'Tree yuccas', 'SLP ZAC', 'Spiky rosettes on a trunk, lining the roads (Highway 54 in Zacatecas).', { photoSearch: 'Yucca filifera Zacatecas' }),
  mx('myrtle', 'Plants & crops', 'Blue myrtle cacti', 'SLP QUE HID', 'Short, bluish arms that all curve upwards.'),
  mx('red-fields', 'Landscape & soil', 'Red farm fields', 'ZAC DUR CAM', 'Red soil in Zacatecas and southern Durango; red fields in forest in northern Campeche.'),
  mx('dark-fields', 'Landscape & soil', 'Very dark fields', 'GUA', 'Extremely dark soil.'),
  mx('white-soil', 'Landscape & soil', 'Blinding white soil', 'ROO YUC', 'Pale limestone ground, most striking in Quintana Roo.', { plant: 'pale-limestone' }),
  mx('tree-fence', 'Culture & shops', 'Fences of red-barked trees', 'VER', 'Living fences of trees with red bark.'),
  mx('taxis', 'Culture & shops', 'Pink-and-white taxis', 'CMX MEX', 'Taxis with a pink upper half.'),
]

// ---- United States ---------------------------------------------------------------------------------
const us = maker('US')
const usa: CountryFeature[] = [
  us('ca-stripes', 'Poles', 'Three yellow stripes near the pole base', 'CA', 'Most poles in the state (except the far northeast) have three yellow stripes.', { notable: true }),
  us('pacificorp', 'Poles', 'Thick yellow metal pole plates', 'OR ID UT WY', 'PacifiCorp ID plates, alone or stacked.'),
  us('wi-plates', 'Poles', 'White pole plates with an orange rectangle and diamond', 'WI MI', 'Wisconsin and Michigan\'s Upper Peninsula.', { notable: true }),
  us('utah-bollard', 'Bollards & markers', 'Square reflector above a black rectangle', 'UT', 'A bollard found only in Utah.', { notable: true }),
  us('paddle', 'Bollards & markers', 'Black paddle-shaped bollards', 'UT WY NE', 'With a square reflector only in Wyoming.'),
  us('nv-stick', 'Bollards & markers', 'Thin stick with a black-outlined white rectangle', 'NV', 'Nevada\'s bollard.'),
  us('nm-three', 'Bollards & markers', 'Bollards with three round reflectors', 'NM', 'Common in New Mexico.'),
  us('square-refl', 'Bollards & markers', 'Square-reflector bollards', 'UT AZ ID', 'Two bolts in Utah, one in Arizona, either in Idaho.'),
  us('diamond-refl', 'Bollards & markers', 'Diamond-reflector bollards', 'SD MT', 'Two bolts in South Dakota, one in Montana.'),
  us('post-above', 'Bollards & markers', 'Post sticking up above a round reflector', 'CO WY', 'The top is sometimes painted white or grey in Wyoming.'),
  us('wa-bollard', 'Bollards & markers', 'Two small squares on the back of the bollard', 'WA', 'White or brown post with a white rectangle on the front.'),
  us('wi-bollard', 'Bollards & markers', 'Plain white bollards with black reflectors', 'WI', 'Only in Wisconsin.'),
  us('mn-triangles', 'Bollards & markers', 'Yellow signs with black vertical triangles', 'MN', 'Before bridges and at guardrail ends.'),
  us('guard-ends', 'Bollards & markers', 'Small green and red guardrail end markers', 'ME NH MA', 'At the ends of bridges and guardrails.'),
  us('county-letters', 'Signs & codes', 'Lettered county roads', 'WI MO', 'County roads named A–ZZZ; Wisconsin writes "County" above the letter, Missouri does not.', { notable: true }),
  us('ref-markers', 'Signs & codes', 'Green reference markers with three rows of numbers', 'NY VT', 'The top row is the route; in Vermont the second row starts with 0.'),
  us('grid-streets', 'Signs & codes', 'Street names like "400 South"', 'UT ID', 'Numbered grid addresses.'),
  us('i19-km', 'Signs & codes', 'Distances in kilometres', 'AZ', 'Interstate 19 south of Tucson: the only kilometre signs in the US.'),
  us('ok-numbers', 'Signs & codes', 'Three rows of numbers behind stop signs', 'OK', 'A green sign on the back of rural stop signs.'),
  us('salt-pepper', 'Roads', 'Grainy "salt and pepper" road surface', 'TX NM OK CO IL', 'Typical of Texas; also rural roads in Illinois.', { notable: true }),
  us('wide-gap', 'Roads', 'Wide gap between the yellow centre lines', 'TX AR LA MS OR', 'Noticeably spaced double yellow lines.'),
  us('outside-rpm', 'Roads', 'Reflectors outside the double yellow lines', 'GA FL TX CA', 'Elsewhere the reflectors sit between the lines.'),
  us('black-stripe', 'Roads', 'Black stripe between the yellow lines', 'CA', 'And some small roads have no centre line at all (also Kentucky).'),
  us('thick-yellow', 'Roads', 'Extra-thick yellow centre lines', 'WV MD DE VA', 'Not on every road.'),
  us('concrete-roads', 'Roads', 'Concrete-paved ordinary roads', 'IA', 'Rural roads paved in concrete, not only highways.'),
  us('hanging-signals', 'Roads', 'Signals hung from wires across intersections', 'MI', 'In yellow boxes; also common in the South.'),
  us('sq-guardrail', 'Roads', 'Square guardrails', 'NY WY', 'A bar on square legs.'),
  us('stone-walls', 'Landscape & soil', 'Low stone walls along the road', 'CT RI MA NH', 'Old field walls in New England woods.', { photoSearch: 'New England stone wall road' }),
  us('red-clay', 'Landscape & soil', 'Red clay and southern pines', 'GA AL SC NC VA TN MS', 'Orange-red road cuts with tall fluffy loblolly pines.', { plant: 'red-clay-southeast-us' }),
  us('sagebrush', 'Plants & crops', 'Sagebrush basins', 'NV UT ID OR WY', 'Blue-green shrubs on dry plains between mountain ranges.', { photoSearch: 'sagebrush Nevada highway' }),
  us('saguaro', 'Plants & crops', 'Saguaro cacti', 'AZ', 'Only southern Arizona (and Sonora in Mexico).', { notable: true, plant: 'saguaro' }),
  us('canola', 'Plants & crops', 'Yellow canola fields', 'ND MT', 'Along the Canadian border.'),
  us('rice', 'Plants & crops', 'Rice fields', 'AR LA MS TX CA', 'Only in the lower Mississippi valley, the Texas coast and north-central California.', { plant: 'rice' }),
  us('spanish-moss', 'Plants & crops', 'Spanish moss', 'LA FL GA SC MS AL TX', 'Grey beards hanging from oaks.', { plant: 'spanish-moss' }),
  us('pumpjacks', 'Landscape & soil', 'Oil pumpjacks', 'TX NM ND OK', 'Nodding oil pumps in fields.', { photoSearch: 'pumpjack Texas field' }),
  us('red-roofs', 'Architecture', 'Red metal roofs', 'VA WV OH KY TN AR NC', 'On farmhouses and barns in the mid-South.'),
  us('pueblo', 'Architecture', 'Adobe-style houses', 'NM AZ CO', 'Rounded edges, flat roofs, sand-brown walls.', { notable: true, photoSearch: 'Pueblo Revival house Santa Fe' }),
  us('stucco', 'Architecture', 'Pale stucco with red tile roofs', 'CA NV AZ TX FL', 'Spanish Colonial Revival.'),
  us('shotgun', 'Architecture', 'Shotgun houses', 'LA MS KY TX', 'Very narrow one-storey wooden houses.'),
  us('triplex', 'Architecture', 'Three-storey wooden triplexes', 'NY CT RI MA', 'Stacked flats in older Northeast cities.'),
  us('waffle', 'Culture & shops', 'Waffle House', 'GA AL SC NC TN MS LA FL TX', 'The yellow sign of the South (Georgia has the most).'),
  us('heb', 'Culture & shops', 'H-E-B, Whataburger and Buc-ee\'s', 'TX', 'Texas-only supermarkets and huge petrol stations.'),
  us('publix', 'Culture & shops', 'Publix', 'FL GA AL SC', 'Florida\'s supermarket.'),
  us('wawa-sheetz', 'Culture & shops', 'Wawa and Sheetz', 'PA NJ DE MD VA WV OH', 'Mid-Atlantic convenience stores.'),
  us('kwik', 'Culture & shops', 'Kwik Trip, Casey\'s and Hy-Vee', 'WI MN IA IL MO', 'Upper Midwest chains.'),
  us('in-n-out', 'Culture & shops', 'In-N-Out Burger', 'CA NV AZ UT', 'Two thirds of all branches are in California.'),
]

// ---- Canada ----------------------------------------------------------------------------------------
const ca = maker('CA')
const canada: CountryFeature[] = [
  ca('arret', 'Signs & codes', '"ARRÊT" stop signs and red-and-white chevrons', 'QC', 'French only; the rest of Canada uses yellow-and-black chevrons.', { notable: true }),
  ca('bilingual', 'Signs & codes', '"STOP ARRÊT" stop signs', 'NB', 'Bilingual stop and street signs.'),
  ca('grid-roads', 'Signs & codes', 'Numbered township and range roads', 'AB', 'Read your position straight off the road sign. Manitoba has a similar mile grid.'),
  ca('ab-bollard', 'Bollards & markers', 'Cylinder bollards with two thin black bands', 'AB', 'Very common at intersections.', { notable: true }),
  ca('bc-bollard', 'Bollards & markers', 'Thin curved black-and-white bollards', 'BC', 'Most common on Vancouver Island.'),
  ca('mb-bollard', 'Bollards & markers', 'Black-and-grey bollards with an orange stripe', 'MB', 'Wooden rectangular versions further north.'),
  ca('nt-bollard', 'Bollards & markers', 'Cylinder bollards with two thick black bands', 'NT', 'Like Alberta\'s, but the bands are wider.'),
  ca('qc-guardrail', 'Bollards & markers', 'Thin white posts with a red or green reflector', 'QC', 'Always attached to guardrails.'),
  ca('diamond-markers', 'Bollards & markers', 'Diamond-shaped roadside markers', 'ON', 'Quebec uses rectangular ones instead.'),
  ca('on-km', 'Signs & codes', 'Kilometre markers with a white square at the bottom', 'ON', 'Only in Ontario; speed signs can have a black "km/h" panel.'),
  ca('facing', 'Poles', 'Transformers facing the road', 'BC NB', 'Elsewhere they sit parallel to the wires.'),
  ca('angled', 'Poles', 'Transformers at 45°', 'PE NS', 'With red numbers on Prince Edward Island.'),
  ca('across', 'Poles', 'Insulators pointing across the road', 'QC NS PE', 'Other provinces point them along the road.'),
  ca('on-tops', 'Poles', 'Two side insulators and one on top', 'ON', 'With a distinctive side bracket; sometimes stacked.'),
  ca('alternating', 'Poles', 'Insulators alternating side from pole to pole', 'SK', 'One on the left and two on the right, then the reverse.', { notable: true }),
  ca('wire-guardrail', 'Roads', 'Round wooden posts with three wires', 'ON', 'Ontario\'s guardrail.'),
  ca('pyramid', 'Roads', 'Pyramid-topped wooden posts', 'NL', 'On guardrails and signposts.'),
  ca('concrete-barrier', 'Roads', 'Concrete barriers instead of guardrails', 'BC', 'And green sign backs (also PEI).'),
  ca('red-soil', 'Landscape & soil', 'Red soil and potato fields', 'PE', 'Brick-red ground all over the island.', { notable: true, plant: 'red-beds' , photoSearch: 'Prince Edward Island red soil field' }),
  ca('canola', 'Plants & crops', 'Yellow canola fields', 'SK MB AB', 'The central southern Prairies.'),
  ca('shield', 'Landscape & soil', 'Pink granite rock and lakes', 'ON QC MB NL', 'The Canadian Shield: bare rock cuts, pines and lakes.', { photoSearch: 'Canadian Shield highway rock cut' }),
  ca('balsam', 'Plants & crops', 'Balsam firs and octagonal wooden bins', 'NL', 'Christmas-tree firs everywhere, and wooden rubbish bins on driveways.'),
  ca('cones', 'Culture & shops', 'Striped traffic cones', 'ON QC', 'Orange-and-black in Ontario, orange-and-white in Quebec.'),
]

// ---- Indonesia -------------------------------------------------------------------------------------
const id = maker('ID')
const indonesia: CountryFeature[] = [
  id('uneven-insulators', 'Poles', 'Even crossbar, uneven insulators', 'SU', 'One insulator on one side and two on the other, on a symmetric bar.', { notable: true }),
  id('asym-two', 'Poles', 'Asymmetric poles with two supports', 'AC SU SB RI JA SS BE LA SN SG SR', 'Off-centre crossbars with two braces: Sumatra and southern Sulawesi; rare on Java and Kalimantan.'),
  id('long-support', 'Poles', 'Poles with an extra-long support', 'BA NB NT', 'The Lesser Sunda Islands; sometimes two supports.', { notable: true }),
  id('indent', 'Poles', 'Poles with an indent on both sides', 'JB JK BT', 'Western Java.'),
  id('trident', 'Poles', 'Trident pole tops', 'JT YO', 'Rare elsewhere.'),
  id('attachment', 'Poles', 'An extra attachment under the crossbar', 'SA ST GO', 'Northern and central Sulawesi.'),
  id('bali-paint', 'Poles', 'Rectangle attachment and blue pole paint with text', 'BA', 'Dark blue horizontal text painted on poles.'),
  id('a-frame', 'Poles', 'A-frame poles', 'KB KT KS KI KU NB NT', 'Common in Kalimantan and the Nusa islands.'),
  id('tiles', 'Architecture', 'Tiled roofs', 'BT JK JB JT YO JI BA NB LA SS KS', 'Java and nearby; the north uses sheet metal.', { photoSearch: 'Java village tiled roofs' }),
  id('metal-roofs', 'Architecture', 'Plain sheet-metal roofs', 'KB KT KS KI KU SA GO ST SR SN SG AC SU RI', 'Kalimantan, Sulawesi and northern Sumatra.'),
  id('minang', 'Architecture', 'Buffalo-horn roofs with spires', 'SB', 'Minangkabau roofs sweep up into points, even on offices.', { notable: true, photoSearch: 'Rumah Gadang Minangkabau' }),
  id('batak', 'Architecture', 'Boat-shaped roofs without spires', 'SU', 'Batak houses around Lake Toba; less upturned than Minangkabau roofs.'),
  id('tongkonan', 'Architecture', 'Huge saddle-shaped roofs on raised houses', 'SN', 'Toraja tongkonan around Rantepao.', { notable: true, photoSearch: 'Tongkonan Toraja' }),
  id('bali', 'Architecture', 'Split gates, shrines and carved grey stone', 'BA', 'Hindu temple gates, crown-like roof pinnacles and guardian statues.', { notable: true, photoSearch: 'Bali candi bentar gate street' }),
  id('slots', 'Architecture', 'Horizontal slots in the roof triangle', 'SN', 'Bugis roofs; often with gable horns.'),
  id('horns', 'Architecture', 'Roofs with gable horns', 'SN RI KT KS', 'Crossed wooden horns at the roof ends.'),
  id('fences', 'Culture & shops', 'White fences painted with blue or red', 'SA GO ST SR SN SG', 'Painted fences in front of houses on Sulawesi.'),
  id('churches', 'Culture & shops', 'Churches instead of mosques', 'SA NT SU MA PA PB', 'Christian areas in a Muslim-majority country: Minahasa, Flores and Timor, the Batak lands, Maluku and Papua.'),
  id('st-bollard', 'Bollards & markers', 'Black, white and yellow bollards', 'ST', 'Painted in three bands.'),
  id('uk-bollard', 'Bollards & markers', 'UK-style bollards', 'KB KT KS KI', 'Mostly in Kalimantan.'),
  id('green-bridges', 'Roads', 'Green paint on bridges', 'KT KS', 'Bridge railings painted green.'),
  id('oil-palm', 'Plants & crops', 'Oil palm plantations', 'AC SU RI JA SS BE KB KT KS KI', 'Sumatra and Kalimantan.', { plant: 'oil-palm' }),
  id('rice', 'Plants & crops', 'Rice paddies and terraces', 'JB JT JI YO BT BA', 'Most of Indonesia\'s rice is on Java.', { plant: 'rice' }),
  id('dry-nusa', 'Landscape & soil', 'Dry shrubby landscape', 'NB NT', 'Brown and scrubby compared with the rest of Indonesia.'),
  id('white-red', 'Landscape & soil', 'White soil on top of red soil', 'BB', 'Spilling onto the road.', { notable: true }),
  id('round-hills', 'Landscape & soil', 'Very rounded green hills', 'GO', 'Covered in palms, sugarcane or maize.'),
  id('plates-b', 'Signs & codes', 'Plate code B', 'JK BT JB', 'Greater Jakarta (including Tangerang, Bekasi and Depok).'),
  id('plates-bali', 'Signs & codes', 'Plate code DK', 'BA', 'Bali.'),
]

// ---- Australia -------------------------------------------------------------------------------------
const au = maker('AU')
const australia: CountryFeature[] = [
  au('stobie', 'Poles', 'Stobie poles (steel and concrete)', 'SA', 'Two steel beams with concrete between; trident or "E" pole tops. A few in Broken Hill and Tasmania.', { notable: true, photoSearch: 'Stobie pole Adelaide' }),
  au('rusty', 'Poles', 'Rusty metal poles full of holes', 'NT', 'Also some in northern Western Australia.', { notable: true }),
  au('trident', 'Poles', 'Trident tops with red insulators', 'WA', 'Black paint on the crossbar; green-painted pole bases.'),
  au('coils-up', 'Poles', 'Pole-top coils angled upwards', 'QLD', 'And round blue stickers on poles.'),
  au('concrete', 'Poles', 'Concrete poles', 'VIC', 'Two thirds of Australia\'s concrete poles are here; three-coil tops.'),
  au('l-crossbar', 'Poles', 'Thin metal crossbars bent into an L', 'TAS', 'And olive-green possum guards.', { notable: true }),
  au('qld-bollard', 'Bollards & markers', 'Black-and-yellow bollards', 'QLD', 'Only in Queensland.'),
  au('wa-bollards', 'Bollards & markers', 'Striped or brown-bottomed bollards', 'WA', 'Black-and-white striped, or with a big brown base; yellow signposts.'),
  au('property', 'Bollards & markers', 'Coloured property markers', 'WA SA', 'Dark green in Western Australia, white in South Australia.'),
  au('no-stopping', 'Signs & codes', 'Red "No Stopping" signs', 'NSW', 'Other states use white.'),
  au('fluoro', 'Signs & codes', 'Fluorescent yellow-green sign borders', 'QLD', 'Almost only in Queensland.'),
  au('white-dir', 'Signs & codes', 'White direction signs', 'TAS', 'The mainland uses green.'),
  au('130', 'Signs & codes', '130 km/h speed limits', 'NT', 'The only place in Australia.'),
  au('lights', 'Roads', 'Traffic lights with a white outline', 'WA QLD NSW ACT TAS', 'Victoria, South Australia and the NT use lights without the border.'),
  au('guard-end', 'Roads', 'Yellow guardrail ends with a black dash', 'NSW ACT', 'Almost only in New South Wales and the ACT.'),
  au('termites', 'Landscape & soil', 'Termite mounds', 'NT WA QLD', 'Brown spiky mounds rising from the grass.', { notable: true, photoSearch: 'termite mound Northern Territory road' }),
  au('red-soil', 'Landscape & soil', 'Red soil and outback', 'NT WA SA QLD NSW', 'The redder, the further inland.', { plant: 'red-desert-soil' , photoSearch: 'outback road red dirt' }),
  au('green-hills', 'Landscape & soil', 'Cool green hills', 'TAS VIC', 'Tasmania looks like New Zealand or southern Chile.'),
  au('sugarcane', 'Plants & crops', 'Sugarcane', 'QLD NSW', 'Northern Queensland, as far south as northern NSW.', { plant: 'sugarcane' }),
  au('grass-tree', 'Plants & crops', 'Grass trees', 'WA SA VIC NSW QLD', 'Black trunks with a mop of thin leaves.', { plant: 'grass-tree' }),
]

// ---- Russia ----------------------------------------------------------------------------------------
const ru = maker('RU')
const russia: CountryFeature[] = [
  ru('bilingual', 'Signs & codes', 'Bilingual signs in a local language', 'TA BA CU ME KO MO SA TY BU', 'Tatar and Bashkir "урамы", Chuvash "урамӗ", Mari "урем", Komi "улича" for street.', { notable: true }),
  ru('latin', 'Signs & codes', 'Town names also in Latin letters', 'MOW MOS SPE LEN PSK KGD', 'Near Moscow and the Baltic border.'),
  ru('black-bottom', 'Signs & codes', 'Black-coloured sign bottoms', 'STA CE DA', 'On traffic signs in the North Caucasus.'),
  ru('clips', 'Signs & codes', 'Clips on signpost edges', 'LEN SPE', 'Very rarely further afield.'),
  ru('dashed', 'Roads', 'Dashed outer road lines', 'KRS', 'Throughout Kursk Oblast (also Tuva).'),
  ru('slabs', 'Roads', 'Roads of concrete slabs', 'KO NEN YAN', 'Common in the far north.', { photoSearch: 'concrete slab road Russia' }),
  ru('yellow-plates', 'Poles', 'Yellow plates strapped to poles', 'TA', 'On most poles in Tatarstan.'),
  ru('red-white', 'Poles', 'Red-and-white painted poles', 'ULY MO', 'Alternating sections in Ulyanovsk; stripes in Saransk.'),
  ru('extended', 'Poles', 'Extended insulator bars', 'CHE ORE KEM', 'Southern Chelyabinsk, eastern Orenburg, southern Kemerovo.'),
  ru('mosques', 'Culture & shops', 'Mosques', 'TA BA CE DA IN KB KC', 'Most common in the Volga republics and the North Caucasus.'),
  ru('buddhist', 'Culture & shops', 'Buddhist temples', 'KL BU TY', 'Kalmykia, Buryatia and Tuva.', { notable: true, photoSearch: 'Elista Buddhist temple' }),
  ru('rhd', 'Culture & shops', 'Right-hand-drive Japanese cars', 'KYA IRK BU ZAB AMU YEV KHA PRI SAK KAM SA MAG', 'More and more common east of Novosibirsk.', { notable: true }),
  ru('birch', 'Plants & crops', 'Birch-only forests', 'CHE KGN TYU OMS NVS', 'Dense stands of nothing but birch east of the Urals.', { plant: 'birch-forest' , photoSearch: 'birch forest road Siberia' }),
  ru('larch', 'Plants & crops', 'Larch forests', 'SA IRK ZAB AMU KHA MAG BU KYA', 'More and more larch the further east.', { plant: 'larch' }),
  ru('butterbur', 'Plants & crops', 'Giant butterbur', 'SAK', 'Huge round leaves ("Sakhalin cabbage") along roads.', { notable: true, plant: 'giant-butterbur' }),
  ru('sunflowers', 'Plants & crops', 'Sunflower fields', 'BEL KRS VOR ROS KDA SAR VGG ULY SAM ORE', 'Along the Ukrainian border and on the Volga steppe.'),
  ru('black-earth', 'Landscape & soil', 'Black-earth farmland', 'VOR BEL KRS LIP TAM ORL KDA STA ROS', 'Very dark ploughed fields.', { plant: 'black-earth' }),
  ru('sandy', 'Landscape & soil', 'Sandy roadsides', 'KHM YAN KR MUR NIZ', 'Pale sand along the roads in the north.'),
  ru('rocks', 'Landscape & soil', 'Big rocks along the road', 'KR MUR', 'Granite boulders everywhere.'),
  ru('steppe', 'Landscape & soil', 'Extremely dry, flat steppe', 'KL AST DA', 'West of the Caspian.'),
  ru('volcanoes', 'Landscape & soil', 'Volcanoes and grey gravel', 'KAM', 'Cones visible from many roads.', { notable: true , photoSearch: 'Kamchatka volcano road' }),
  ru('palms', 'Plants & crops', 'Palm trees', 'KDA', 'Only on the Black Sea coast around Sochi.'),
  ru('limestone', 'Architecture', 'White limestone-brick buildings', 'DA', 'Dagestan and nearby.'),
  ru('oaks', 'Plants & crops', 'Oak-lined roads with a white stripe', 'KGD', 'And cobbled streets.'),
]

// ---- Argentina -------------------------------------------------------------------------------------
const ar = maker('AR')
const argentina: CountryFeature[] = [
  ar('red-soil', 'Landscape & soil', 'Red soil', 'N W', 'Only in the northeast (like southern Brazil and Paraguay).', { notable: true, plant: 'red-tropical-soil' }),
  ar('hook-poles', 'Poles', 'Hooked wooden poles', 'F M', 'Latvian-style poles with hooks.'),
  ar('side-insulator', 'Poles', 'One insulator on the side of the pole', 'M', 'In Mendoza.'),
  ar('stickers', 'Poles', 'White vertical pole stickers with digits', 'T', 'In Tucumán.'),
  ar('poplars', 'Plants & crops', 'Rows of poplars', 'Q R M J', 'Windbreaks around irrigated fields in the dry west.'),
  ar('cardon', 'Plants & crops', 'Andean cardón cacti', 'Y A T K', 'Candelabra cacti with golden spines, high in the northwest.', { notable: true, plant: 'andean-cardon' }),
  ar('wax-palm', 'Plants & crops', 'Caranday wax palms', 'P H W S', 'Short fan leaves in single-species groves.'),
  ar('yatay', 'Plants & crops', 'Yatay palms', 'W E', 'Arching feathery leaves, often leaning (El Palmar).'),
  ar('plantations', 'Plants & crops', 'Tree plantations', 'E N W', 'Most of Argentina\'s eucalyptus and pine plantations.'),
  ar('sugarcane', 'Plants & crops', 'Sugarcane', 'T A Y', 'Mostly Tucumán.', { plant: 'sugarcane' }),
  ar('vineyards', 'Plants & crops', 'Vineyards below mountains', 'M J A F', 'Vines with the Andes to the west and flat land to the east.', { photoSearch: 'Mendoza vineyard Andes' }),
  ar('pampas', 'Landscape & soil', 'Flat Pampas farmland', 'B S X E L', 'Flat to the horizon, with lines of trees.', { plant: 'pampas' }),
  ar('patagonia', 'Landscape & soil', 'Flat windy steppe', 'U Z R Q V', 'Barren, treeless and empty.', { photoSearch: 'Ruta 40 Patagonia steppe' }),
  ar('needle-grass', 'Roads', 'Reddish roads lined with needle-grass', 'D', 'Long grass along the verges.'),
  ar('stone-paving', 'Roads', 'Uneven square stone paving', 'N', 'As in western Rio Grande do Sul.'),
  ar('red-brick', 'Architecture', 'Red brick buildings', 'Y', 'Like neighbouring Bolivia.'),
  ar('mar-del-plata', 'Architecture', 'Stone-fronted houses with orange tiles', 'B', 'Quartzite facades and vaulted porches around Mar del Plata.'),
  ar('salt', 'Landscape & soil', 'Salt pans', 'Y', 'White salt flats in the puna.', { photoSearch: 'Salinas Grandes Jujuy road' }),
  ar('monkey-puzzle', 'Plants & crops', 'Monkey puzzle trees', 'Q', 'In the west, on road 23.'),
  ar('caldén', 'Plants & crops', 'Caldén trees', 'L', 'Large trees with small leaves and wavy branches.'),
]

// ---- Vietnam ---------------------------------------------------------------------------------------
const vn = maker('VN')
const NORTH = '01 71 05 14 02 06 03 04 53 09 07 69 68 54 13 HN HP 70 56 61 66 20 63 67 18'
const vietnam: CountryFeature[] = [
  vn('plates-north', 'Signs & codes', 'Plate codes 11–28, 34–35 and 88–99', '04 09 13 HP 20 67 68 69 06 07 03 02 01 05 71 14 70 66 63 53 54 56 61 18', 'The northern provinces outside Hà Nội (15–16 Hải Phòng, 17 Thái Bình, 18 Nam Định, 20 Thái Nguyên, 24 Lào Cai, 99 Bắc Ninh…).', { notable: true }),
  vn('plates-hanoi', 'Signs & codes', 'Plate codes 29–33 and 40', 'HN', 'Hà Nội.', { notable: true }),
  vn('plates-centre', 'Signs & codes', 'Plate codes 36–38, 43, 47–49, 73–82, 85–86, 92', '21 22 23 DN 33 72 35 24 25 26 29 31 32 34 30 28 36 40 27', 'The centre and the Central Highlands.', { notable: true }),
  vn('plates-south', 'Signs & codes', 'Plate codes 41, 50–72, 83–84, 93–95', 'SG 39 57 41 46 49 CT 45 44 47 59 37 50 43 51 52 58 55 73', 'The south, from Hồ Chí Minh City to the Mekong Delta.', { notable: true }),
  vn('big-holes', 'Poles', 'Poles with big holes all the way up', NORTH, 'The half-holey pole is everywhere; holes along the whole pole mean the north.', { notable: true }),
  vn('trapezoid', 'Poles', 'Upside-down trapezoid pole tops', `${NORTH} 21 22 23 24 25 26`, 'Common in the north and centre.'),
  vn('triangle', 'Poles', 'Triangle pole tops and off-centre crossbars', 'SG 39 57 58 37 43 41 46 50 51 49 45 44 47 CT 73 52 55 59', 'Southern Vietnam.'),
  vn('a-frame', 'Poles', 'An "A" above the crossbar', 'DN 27 29 31 32 34 26 25', 'Central Vietnam.'),
  vn('bamboo-poles', 'Poles', 'Thin bamboo poles', '01 71 05 02 06', 'Rural villages in the northwest mountains.'),
  vn('stickers', 'Poles', 'Black pole stickers', NORTH, 'Northern Vietnam.'),
  vn('spires', 'Architecture', 'Thin spires on house roofs', NORTH, 'Almost only in the north.'),
  vn('tube-houses', 'Architecture', 'Tall boxy houses with classical columns', 'HN HP 70 56 61 66 20 63 67 18', 'The Red River Delta.', { notable: true , photoSearch: 'Hanoi tube houses street' }),
  vn('graves', 'Landscape & soil', 'Graves in the middle of rice fields', 'HN 56 61 66 20 63 67 18 HP 70', 'Red River Delta.', { notable: true }),
  vn('canals', 'Landscape & soil', 'Straight canals and single-storey houses', '41 46 50 51 49 45 44 47 CT 73 52 55 59', 'The Mekong Delta: flat, watery, palms everywhere.', { notable: true, photoSearch: 'Mekong Delta canal village' }),
  vn('stilt', 'Architecture', 'Wooden stilt houses', '01 71 05 14 02 06 03', 'Ethnic minority villages in the northwest.'),
  vn('highlands', 'Landscape & soil', 'Red soil, coffee and pepper', '28 30 33 72 35 58', 'The Central Highlands; pepper vines smother tree trunks.', { notable: true, plant: 'coffee' }),
  vn('rubber', 'Plants & crops', 'Rubber plantations', '57 58 37 39 43 30 28 33 72', 'Neat grids of thin trunks wrapped in plastic.', { plant: 'rubber' }),
  vn('tea', 'Plants & crops', 'Tea plantations', '69 68 07 03 06 01 05 35', 'Several areas in the north, and Bảo Lộc in Lâm Đồng.', { plant: 'tea' }),
  vn('khasi', 'Plants & crops', 'Khasi pines on the hills', '09 13', 'The far northeast.'),
  vn('dragonfruit', 'Plants & crops', 'Dragon-fruit farms', '40 41 46', 'Look like upturned wet mops on posts.', { notable: true, photoSearch: 'dragon fruit farm Binh Thuan' }),
  vn('karst', 'Landscape & soil', 'Pointy karst mountains', '03 04 13 18 24 63', 'Dark exposed rock in Hà Giang; islands in Hạ Long Bay; towers in rice at Ninh Bình.', { photoSearch: 'Ha Giang karst road' }),
  vn('greenhouses', 'Landscape & soil', 'Hills covered in greenhouses', '35', 'Around Đà Lạt.', { notable: true , photoSearch: 'Da Lat greenhouses' }),
  vn('dunes', 'Landscape & soil', 'Sand dunes and dry coast', '40 34 36', 'Around Phan Thiết and Mũi Né, and northern Khánh Hòa.'),
  vn('cyrillic', 'Signs & codes', 'Signs in Cyrillic', '40', 'For Russian tourists near Mũi Né.'),
  vn('hoi-an', 'Architecture', 'Old yellow buildings with brown doors', '27', 'Hội An.'),
]

// ---- Philippines -----------------------------------------------------------------------------------
const ph = maker('PH')
const philippines: CountryFeature[] = [
  ph('yellow-black', 'Roads', 'Yellow-and-black concrete guardrails', '15', 'In the Cordillera.', { notable: true }),
  ph('three-stripes', 'Roads', 'White guardrails with three black stripes', '05', 'Only in Bicol.', { notable: true }),
  ph('ladder', 'Poles', 'Ladder-like pole tops', '00 03 40', 'Two tall L-section bars joined by thin wires, around Manila.'),
  ph('mesh', 'Poles', 'Square metal mesh poles', '09 10 11 12 13 14', 'Mainly on the Zamboanga peninsula; elsewhere on Mindanao highways.'),
  ph('indent', 'Poles', 'Square concrete poles with an indent', '03 01 06 07', 'North of Manila and around Bacolod.'),
  ph('pines', 'Plants & crops', 'Pines on dry mountainsides', '15', 'Northern Luzon\'s mountains.', { notable: true }),
  ph('dew', 'Culture & shops', 'Mountain Dew bottle decorations', '01 02 15', 'Neon-green bottles used as decorations in northern Luzon.'),
  ph('kuliglig', 'Culture & shops', 'Kuliglig tractor carts', '02', 'On the plains around Cauayan, Isabela.'),
  ph('moto-top', 'Signs & codes', 'Motorcycle plates with the colour strip on top', '00 15 01 02 03 40 41 05', 'The northern half of the country.'),
  ph('moto-bottom', 'Signs & codes', 'Motorcycle plates with the colour strip at the bottom', '06 07 08 09 10 11 12 13 14', 'The southern half.'),
  ph('amakan', 'Architecture', 'Diamond-pattern bamboo walls', '06 07 08 09 10 11 12 13 14', 'Woven amakan walls in the south; a diagonal weave (sawali) in the north and Palawan.'),
  ph('sugarcane', 'Plants & crops', 'Sugarcane', '06 07 10', 'Negros, Panay and Bukidnon.', { plant: 'sugarcane' }),
  ph('pineapple', 'Plants & crops', 'Pineapple and banana plantations', '10 11 12', 'Central and southern Mindanao.', { notable: true, plant: 'banana' }),
  ph('corn', 'Plants & crops', 'Corn fields', '01 02 10 11 12 13', 'Northern Luzon and Mindanao.'),
  ph('terraces', 'Landscape & soil', 'Rice terraces', '15', 'Banaue and the Ifugao terraces.', { photoSearch: 'Banaue rice terraces road' }),
  ph('chocolate', 'Landscape & soil', 'Rounded grassy hills', '07', 'The Chocolate Hills of Bohol.', { notable: true, photoSearch: 'Chocolate Hills Bohol' }),
  ph('volcanoes', 'Landscape & soil', 'Lone volcano cones', '05 03', 'Mayon\'s perfect cone in Bicol; Arayat alone on the Central Luzon plain.'),
  ph('muslim', 'Culture & shops', 'Mosques', '14 09', 'The Muslim-majority southwest.'),
]

export const countryFeatures: Record<string, CountryFeature[]> = {
  BR: brazil, MX: mexico, US: usa, CA: canada, ID: indonesia, AU: australia, RU: russia, AR: argentina, VN: vietnam, PH: philippines,
}
