import type { CountryStudy } from './types'

export const indonesia: CountryStudy = {
  country: 'ID',
  unit: 'provinces',
  plonkit: 'indonesia',
  quizGroups: true,
  intro: 'Indonesia is 17,000 islands. On the map it has 34 provinces (Papua has since been split further). Learn the big islands first (Sumatra, Java, Borneo/Kalimantan, Sulawesi, New Guinea/Papua) and then the provinces on each. Street View covers most of Java, Bali, Sumatra and Sulawesi well.',
  tips: [
    'Number plates start with a regional letter code: B = Jakarta area, D = Bandung, AB = Yogyakarta, L = Surabaya, DK = Bali, BK = North Sumatra. One or two letters, then numbers.',
    'Roofs and architecture are the other big clue: Minangkabau horn-shaped roofs (West Sumatra), Toraja boat roofs (South Sulawesi), Balinese temple gates, Batak houses (North Sumatra).',
    'Religion: Bali is Hindu (temples and offerings everywhere); Aceh is strictly Islamic; much of North Sulawesi, Papua, East Nusa Tenggara and the Batak lands are Christian (many churches).',
    'Oil palm and rubber = Sumatra and Kalimantan; rice terraces and volcanoes = Java and Bali; dry savanna with lontar palms = Nusa Tenggara.',
  ],
  groups: [
    { name: 'Sumatra', blurb: 'The big western island and the islands near it: volcanoes, oil palm and rubber plantations, Malay, Minangkabau, Batak and Acehnese cultures.' },
    { name: 'Java', blurb: 'The most crowded island on Earth: continuous villages, rice paddies, volcanoes and huge cities. More than half of Indonesians live here.' },
    { name: 'Bali & Nusa Tenggara', blurb: 'The chain of islands east of Java: Hindu Bali, then Lombok, Sumbawa, Flores, Sumba and Timor, getting drier and more savanna-like towards the east.' },
    { name: 'Kalimantan', blurb: 'Indonesian Borneo: flat and swampy, huge rivers, rainforest, oil palm and coal mines; few roads.' },
    { name: 'Sulawesi', blurb: 'The spider-shaped island: steep mountains right to the sea, Christian north and Toraja highlands, Muslim south.' },
    { name: 'Maluku', blurb: 'The Spice Islands: small volcanic islands of cloves and nutmeg, half Christian, half Muslim.' },
    { name: 'Papua', blurb: 'Western New Guinea: mountains, rainforest and Melanesian peoples; very few roads and little coverage.' },
  ],
  regions: [
    // Sumatra
    { id: 'ID-AC', name: 'Aceh', group: 'Sumatra', looks: 'The northern tip of Sumatra: rice fields, coconut palms, mountains, and large mosques; rebuilt coastal towns after the 2004 tsunami.', clues: ['Plate code BL', 'Sharia law: women in headscarves in every shot, Arabic script on signs', 'Big domed mosques with black roofs (Banda Aceh)'], remember: 'Aceh is the "porch of Mecca": the most Islamic province, at the very tip of Sumatra.' },
    { id: 'ID-SU', name: 'North Sumatra', group: 'Sumatra', looks: 'Medan, a big busy city; oil palm and rubber plantations; highlands around Lake Toba with Batak houses and many churches.', clues: ['Plate codes BK and BB', 'Batak houses with saddle-shaped roofs and Protestant churches around Lake Toba'], remember: 'North Sumatra is Lake Toba: a supervolcano crater, with Christian Batak villages around it.' },
    { id: 'ID-SB', name: 'West Sumatra', group: 'Sumatra', looks: 'Volcanic highlands with rice fields and forested valleys; Minangkabau houses with sweeping horn-shaped roofs; Padang on the coast.', clues: ['Plate code BA', 'Buffalo-horn roofs (rumah gadang), even on offices and shops'], remember: 'West Sumatra is Minangkabau land: "minang kabau" means "victorious buffalo", so the roofs look like buffalo horns.' },
    { id: 'ID-RI', name: 'Riau', group: 'Sumatra', capital: 'Pekanbaru', looks: 'Flat lowlands of endless oil palm and acacia pulp plantations, peat swamps and wide rivers.', clues: ['Plate code BM', 'Flat oil palm estates to the horizon'], remember: 'Riau is palm oil and pulp: flat plantations on peat.' },
    { id: 'ID-KR', name: 'Riau Islands', group: 'Sumatra', looks: 'Small islands near Singapore: Batam\'s factories and shipyards, Bintan\'s resorts, fishing villages on stilts.', clues: ['Plate code BP', 'Ferries to Singapore; industrial estates on Batam'], remember: 'The Riau Islands are Singapore\'s backyard: you can see its skyline from Batam.' },
    { id: 'ID-JA', name: 'Jambi', group: 'Sumatra', looks: 'Lowland rubber and oil palm plantations along the big Batang Hari river; some rainforest in the west.', clues: ['Plate code BH'], remember: 'Jambi is the quiet middle of Sumatra: rubber, palm oil and a big brown river.' },
    { id: 'ID-BE', name: 'Bengkulu', group: 'Sumatra', looks: 'A thin strip on the southwest coast of Sumatra: coconut palms and beaches, mountains behind.', clues: ['Plate code BD'], remember: 'Bengkulu is the thin coastal strip where Sukarno lived in exile and the giant Rafflesia flower blooms.' },
    { id: 'ID-SS', name: 'South Sumatra', group: 'Sumatra', looks: 'Palembang on the wide Musi river, then flat plantations of rubber and oil palm, coal mining, and highlands in the west.', clues: ['Plate code BG'], remember: 'South Sumatra is Palembang: the Ampera bridge and fish cakes (pempek).' },
    { id: 'ID-BB', name: 'Bangka Belitung Islands', group: 'Sumatra', looks: 'Two islands east of Sumatra: white-sand beaches with giant granite boulders, tin-mining pits and lakes.', clues: ['Plate code BN', 'Huge round granite boulders on beaches'], remember: 'Bangka Belitung is tin and granite: boulder beaches and tin-mine lakes.' },
    { id: 'ID-LA', name: 'Lampung', group: 'Sumatra', looks: 'The southern tip of Sumatra facing Java: coffee and pepper in the hills, cassava and sugarcane on the plains, busy ferry port.', clues: ['Plate code BE', 'Lots of Javanese-style villages (settled from Java)'], remember: 'Lampung is the gateway to Sumatra: the ferry lands here from Java.' },
    // Java
    { id: 'ID-BT', name: 'Banten', group: 'Java', looks: 'The western tip of Java: Tangerang\'s suburbs and factories next to Jakarta, then rice fields, beaches and rural villages.', clues: ['Plate code A (and B around Tangerang)'], remember: 'Banten is Java\'s west end, facing the Krakatoa volcano.' },
    { id: 'ID-JK', name: 'Jakarta', group: 'Java', capital: 'Jakarta', looks: 'A huge, flat, crowded city: skyscrapers, toll roads, motorcycles everywhere, kampung alleys and canals.', clues: ['Plate code B', 'Dense traffic of motorbikes, flyovers and TransJakarta bus lanes'], remember: 'Jakarta is B for Big: the plate code for the biggest city.' },
    { id: 'ID-JB', name: 'West Java', group: 'Java', looks: 'The Sundanese highlands: volcanoes, tea plantations, terraced rice fields and crowded towns (Bandung, Bogor).', clues: ['Plate codes D (Bandung), F (Bogor), E, T, Z', 'Sundanese script on some signs', 'Tea plantations on cool slopes'], remember: 'West Java is Sunda: tea on volcanoes, and D for Dago (Bandung).' },
    { id: 'ID-JT', name: 'Central Java', group: 'Java', looks: 'Rice paddies, volcanoes, dense villages and teak forests; Semarang on the coast, Solo inland; Borobudur is just over the border.', clues: ['Plate codes H (Semarang), AD (Solo), G, K, R, AA', 'Javanese script on some signs'], remember: 'Central Java is the Javanese heartland: rice, volcanoes and batik.' },
    { id: 'ID-YO', name: 'Yogyakarta', group: 'Java', looks: 'A small special region ruled by a sultan: the city of Yogyakarta, rice fields and Mount Merapi to the north.', clues: ['Plate code AB', 'Street signs in Latin and Javanese script'], remember: 'Yogyakarta still has a sultan, and AB on its plates.' },
    { id: 'ID-JI', name: 'East Java', group: 'Java', looks: 'Surabaya, sugarcane and rice plains, the Bromo and Ijen volcanoes, and the island of Madura.', clues: ['Plate codes L (Surabaya), N (Malang), M (Madura), P, S, W, AE, AG', 'Sugarcane fields and sugar mills'], remember: 'East Java is sugar and smoking volcanoes: Bromo at dawn.' },
    // Bali & Nusa Tenggara
    { id: 'ID-BA', name: 'Bali', group: 'Bali & Nusa Tenggara', capital: 'Denpasar', looks: 'Hindu island: temples and split temple gates everywhere, stone-carved statues, bamboo penjor poles, rice terraces, scooters and tourists.', clues: ['Plate code DK', 'Split gates (candi bentar) and offerings on the ground', 'Balinese script under the Latin on signs'], remember: 'Bali is the Hindu island: every house has a temple, and plates say DK.' },
    { id: 'ID-NB', name: 'West Nusa Tenggara', group: 'Bali & Nusa Tenggara', looks: 'Lombok (green, with the Rinjani volcano, many mosques) and drier Sumbawa with savanna and horses.', clues: ['Plate codes DR (Lombok) and EA (Sumbawa)', 'Lombok looks like Bali, but with mosques instead of temples'], remember: 'West Nusa Tenggara is Lombok, the "island of a thousand mosques", next to Hindu Bali.' },
    { id: 'ID-NT', name: 'East Nusa Tenggara', group: 'Bali & Nusa Tenggara', looks: 'Dry savanna islands (Flores, Sumba, Timor) with lontar palms, rugged hills, thatched houses and many Catholic churches.', clues: ['Plate codes DH, EB and ED', 'Brown dry grass and lontar palms in the dry season', 'Catholic churches and crosses'], remember: 'East Nusa Tenggara is dry, Catholic and home to the Komodo dragons.' },
    // Kalimantan
    { id: 'ID-KB', name: 'West Kalimantan', group: 'Kalimantan', looks: 'Pontianak on the equator, rivers, oil palm, rubber and rainforest; Dayak and Chinese communities.', clues: ['Plate code KB', 'Chinese temples and signs in Singkawang'], remember: 'West Kalimantan: Pontianak sits right on the equator (it has an equator monument).' },
    { id: 'ID-KT', name: 'Central Kalimantan', group: 'Kalimantan', looks: 'Flat peat swamp and rainforest, oil palm estates, long straight roads, rivers as highways; Palangka Raya.', clues: ['Plate code KH', 'Flat, swampy, sandy soil'], remember: 'Central Kalimantan is peat and orangutans.' },
    { id: 'ID-KS', name: 'South Kalimantan', group: 'Kalimantan', looks: 'Banjarmasin\'s floating markets and houses on stilts over rivers, coal mines, rice and rubber.', clues: ['Plate code DA', 'Houses on stilts along canals'], remember: 'South Kalimantan is the river city: Banjarmasin\'s floating markets.' },
    { id: 'ID-KI', name: 'East Kalimantan', group: 'Kalimantan', looks: 'Balikpapan and Samarinda, coal and oil, the Mahakam river, rainforest; the site of the new capital, Nusantara.', clues: ['Plate code KT', 'Hilly with red soil, coal trucks and oil installations'], remember: 'East Kalimantan is where Indonesia is building its new capital, Nusantara.' },
    { id: 'ID-KU', name: 'North Kalimantan', group: 'Kalimantan', looks: 'The newest province: rainforest, rivers and small towns on the border with Malaysian Sabah.', clues: ['Plate code KU', 'Very little coverage'], remember: 'North Kalimantan is the newest province (2012), next to Malaysia.' },
    // Sulawesi
    { id: 'ID-SA', name: 'North Sulawesi', group: 'Sulawesi', capital: 'Manado', looks: 'Mountains, volcanoes and coconut palms; mostly Christian Minahasa villages with neat wooden houses and churches; Manado\'s coral reefs.', clues: ['Plate codes DB and DL', 'Many churches and crosses'], remember: 'North Sulawesi is the Christian tip: churches, coconuts and Manado.' },
    { id: 'ID-GO', name: 'Gorontalo', group: 'Sulawesi', looks: 'A small province on Sulawesi\'s northern arm: maize fields on hills, coconuts, a Muslim town.', clues: ['Plate code DM'], remember: 'Gorontalo is the small Muslim piece of the northern arm, between Christian Manado and Central Sulawesi.' },
    { id: 'ID-ST', name: 'Central Sulawesi', group: 'Sulawesi', looks: 'Rugged mountains, lakes (Poso), cocoa and coconuts; Palu in a dry valley.', clues: ['Plate code DN', 'Palu: one of the driest valleys in Indonesia'], remember: 'Central Sulawesi is the body of the spider: mountains everywhere.' },
    { id: 'ID-SR', name: 'West Sulawesi', group: 'Sulawesi', looks: 'Narrow coastal strip with oil palm and cocoa, mountains behind; Mamuju.', clues: ['Plate code DC'], remember: 'West Sulawesi is the thin western coast of the spider.' },
    { id: 'ID-SN', name: 'South Sulawesi', group: 'Sulawesi', looks: 'Makassar, rice plains, limestone karst towers, and the Toraja highlands with boat-shaped roofs and cliff graves.', clues: ['Plate codes DD, DP and DW', 'Toraja houses (tongkonan) with huge curved boat-shaped roofs', 'Bugis wooden houses on stilts'], remember: 'South Sulawesi is Toraja: houses shaped like ships, and funerals that last for days.' },
    { id: 'ID-SG', name: 'Southeast Sulawesi', group: 'Sulawesi', capital: 'Kendari', looks: 'The southeastern leg: nickel mines with red earth, hills, coastal fishing villages; Kendari.', clues: ['Plate code DT', 'Red nickel-mining scars on hills'], remember: 'Southeast Sulawesi is nickel land: red scars on green hills.' },
    // Maluku
    { id: 'ID-MA', name: 'Maluku', group: 'Maluku', looks: 'Small volcanic islands (Ambon, Seram, Banda): cloves and nutmeg trees, white churches and mosques, blue bays.', clues: ['Plate code DE', 'Both churches and mosques; Ambon is on a small island'], remember: 'Maluku is the Spice Islands: nutmeg once cost more than gold.' },
    { id: 'ID-MU', name: 'North Maluku', group: 'Maluku', looks: 'Ternate and Tidore\'s cone volcanoes rising from the sea, the big K-shaped island of Halmahera; cloves, coconuts and nickel.', clues: ['Plate code DG', 'A perfect cone volcano behind the town'], remember: 'North Maluku is the clove islands: Ternate is one volcano in the sea.' },
    // Papua
    { id: 'ID-PA', name: 'Papua', group: 'Papua', looks: 'Jayapura on the north coast, then huge mountains (Carstensz, with a glacier) and rainforest; Melanesian people, few roads.', clues: ['Plate code PA', 'Melanesian faces and churches', 'Very little coverage outside Jayapura'], remember: 'Papua has glaciers just south of the equator: snow in the tropics.' },
    { id: 'ID-PB', name: 'West Papua', group: 'Papua', looks: 'The Bird\'s Head peninsula: Manokwari and Sorong, rainforest, and the reefs of Raja Ampat.', clues: ['Plate code PB'], remember: 'West Papua is the bird\'s head of New Guinea, with Raja Ampat\'s reefs.' },
  ],
}
