// Notable region-specific markers: poles, bollards, signs, road surfaces, architecture and shops that
// point to one state or province. Paraphrased from the community guides at PlonkIt
// (https://www.plonkit.net), which remain the best reference; see SPEC §7.4. "Common" means common,
// not exclusive: combine markers before committing to a guess.

/** Region id (ISO 3166-2, as on the map) → notable markers. */
export const regionMarkers: Record<string, string[]> = {
  // ---- Brazil ----
  'BR-AC': [
    'Rubbish baskets outside houses are made of concrete (elsewhere in Brazil they are usually metal). Rondônia does this too.',
    'Some town roads are paved with red brick.',
    'The BR-364 rides straight over small grassy hills like a rollercoaster instead of winding round them.',
    'Wooden houses on stilts are very common.',
    'Poles with one insulator on top and alternating side insulators (also Mato Grosso).',
  ],
  'BR-RO': ['Concrete rubbish baskets, as in Acre.', 'Rare asymmetric crossbar with no supports (metal, unlike Ceará\'s concrete one).'],
  'BR-AM': ['Wooden poles are common.', 'The BR-319 south of Manaus: flat, bright orange dirt road through dense rainforest.', 'Pencil-topped poles and Γ-shaped poles appear in Manaus.'],
  'BR-RR': [
    'Open grassy plains with thin bunch grass and big distant mountains.',
    'Town lamps are colour-coded: red in Boa Vista, blue in Rorainópolis, green in Pacaraima, yellow in Caracaraí.',
    'A zig-zag top bar over a flat crossbar on large poles (also Ceará).',
    'Around Uiramutã: dry landscape with big folded mountains.',
  ],
  'BR-PA': [
    'Horizontal insulators are very common.',
    'Lamp heads in Belém are often orange; Γ-shaped poles with electricity boxes are common in Belém.',
    'Electricity meters mounted on the poles in large towns.',
    'The BR-163: hilly, curvy, dry and hazy, with lots of trucks.',
    'Açaí palms (thin trunks, drooping leaflets) around Belém.',
  ],
  'BR-AP': ['Generation 4 coverage has a smudge at the front right, and the car is always white with a blue stripe.', 'Electricity meters on poles in Macapá; big eucalyptus plantations.'],
  'BR-TO': ['Very tall grass by the roadside.', 'Poles often have a single support under the crossbar.', 'Buriti (moriche) and macaw palms.'],
  'BR-MA': ['Most poles have a small beige number plate built into the concrete.', 'Black double-UFO insulators in a trident arrangement.', 'Lençóis Maranhenses: white dunes with pools of water (trekker coverage).'],
  'BR-PI': ['Red gravel on the road shoulders.', 'Teresina lamps: blue with an orange arm.', 'Carnaúba palms.'],
  'BR-CE': [
    'Fancy, colourful lamp arms, sometimes with the town name on them.',
    'An asymmetric concrete crossbar with no supports is found almost only here.',
    'Long, thin insulators; zig-zag top bars over a flat crossbar on large poles.',
    'Carnaúba palms and plants with long bare stems in the dry season.',
  ],
  'BR-RN': ['Small yellow or orange ID plates tied low on the poles.', '"Lollipop" insulators on rods above the crossbar.', 'Lamp arm attached directly to the pole.'],
  'BR-PB': ['"Lollipop" insulators on rods above the crossbar.'],
  'BR-PE': [
    'Brown mushroom-shaped insulators are found only here.',
    'Long yellow pole-ID paint with a black code that starts with a letter (also Bahia).',
    'Small yellow or orange ID plates tied high on the poles.',
    '"Lollipop" insulators.',
  ],
  'BR-AL': ['Transparent insulators (also Santa Catarina).', 'Rifts (stitching errors) are common in Generation 3.'],
  'BR-SE': ['Occasionally transparent or "lollipop" insulators.'],
  'BR-BA': ['White mushroom-shaped insulators.', 'Long yellow pole-ID paint with a black code starting with a letter (also Pernambuco).', 'Carnaúba palms around Xique-Xique; Γ-shaped poles in Salvador.'],
  'BR-MT': ['Alternating side insulators and horizontal insulators.', 'Cuiabá: light green lamps and poles carrying many electricity meters.', 'Lamp arms attached directly to the pole.'],
  'BR-MS': ['Macaw palms are very common.', 'Campo Grande: street names on stickers wrapped round poles, with a red and yellow stripe.'],
  'BR-GO': ['Long yellow pole-ID paint with a black code that starts with a number.', 'Two-part street lamps.', 'Very tall roadside grass.'],
  'BR-DF': ['Two-part street lamps.', 'Occasional white mushroom or transparent insulators.'],
  'BR-MG': ['Two-part street lamps (also Goiás).', 'Hexagonal concrete paving tiles and randomly sized cobbles.', 'Poles with a single support; coffee on hillsides; rolling grassy hills.', 'Belo Horizonte lamps can carry a white numbered plaque starting with 0 or 1 (Uberaba: 1 or 2).'],
  'BR-ES': ['Spool-shaped insulators (also Rio).', 'Large mountains with bare rock faces.'],
  'BR-RJ': ['Pencil-topped poles (a smooth cone on top).', 'Γ-shaped poles with electricity boxes at the end.', 'Street lamps whose whole arm is curved (found nowhere else).', 'Spool-shaped insulators; wooden poles.'],
  'BR-SP': [
    'Round concrete poles are common.',
    'Asymmetric crossbar with a support reaching the middle of the longer side is the most common pole top.',
    'Square yellow pole-ID paint: three letters, two numbers, a black line, four more numbers.',
    'By far the most divided highways in Brazil; phone numbers under kilometre markers.',
  ],
  'BR-PR': ['Pole IDs in black paint with yellow or white text; street names painted on poles at intersections.', 'Northern towns: lamps with no arm, either colourful plastic or ornate.', 'Very deep red soil near the Paraná river.'],
  'BR-SC': [
    'Poles on Florianópolis island are painted white with blue and red stripes.',
    'Dark brown insulators with grey bases (also Rio Grande do Sul); transparent insulators.',
    'Joinville: street names on stickers wrapped round poles.',
    'German-looking houses; hexagonal concrete paving.',
  ],
  'BR-RS': [
    'Wooden poles are common; dark brown insulators with grey bases.',
    'Uneven square stone paving in the west (also Misiones, Argentina); randomly sized cobbles in the southeast.',
    'Brown-tiled pavements; Caxias do Sul lamps with a zig-zag arm and yellow head.',
    'Flat coastal wetlands.',
  ],

  // ---- Mexico ----
  'MX-NAY': ['Bollards with a red band near the top (almost only here).', 'Irregular cobblestone streets.', 'Blue agave fields and sabal palms.'],
  'MX-JAL': ['Some bollards have a crown and the word "Jalisco" on them (no other state writes on its bollards).', 'Blue agave fields around Tequila; red brick buildings; irregular cobblestones.'],
  'MX-OAX': [
    'A distinctive cobblestone pavement with three lines of cobbles running along the road.',
    'Rolling hills with soil that switches between orange and beige (around San Cristóbal Suchixtlahuaca).',
    'Rows of wind turbines along the 190 around Juchitán (the biggest wind farm in Mexico).',
  ],
  'MX-PUE': ['Hexagonal paving tiles (also Tlaxcala).', 'Popocatépetl and Iztaccíhuatl on the horizon.'],
  'MX-TLA': ['Hexagonal paving tiles; teardrop-shaped grass clumps.', 'A Street View car with a yellow hood near La Malinche volcano.'],
  'MX-CHH': ['A thick cross on the back of road signs.', 'Chihuahua city: white pole paint with the street name in black or blue.', 'Orange dirt roads with low shrubs around Ciudad Juárez; stunted pines in the west.'],
  'MX-DUR': ['Poles with a lowered crossbar and one diagonal support beam.', 'Whole houses of mud brick.', 'Black tar on both sides of the yellow centre line.'],
  'MX-SIN': ['Wooden poles with a lowered crossbar.', 'Black tar along the yellow centre line.', 'The 40D towards Durango: cliffs, tunnels and double yellow lines.'],
  'MX-SON': ['Wooden poles with a lowered crossbar.', 'Saguaro, organ pipe cacti and silver-grey brittlebush around Hermosillo.', 'Hermosillo lamps with a zig-zag arm; pink-tan soil and canals around Ciudad Obregón; jagged cliffs at Guaymas.'],
  'MX-BCN': ['Wooden poles with the insulators hanging below the crossbar.', 'Boulder-strewn reddish hills; boojum trees in the south of the state.', 'Mexicali: flat farmland, Washingtonia palms and brown wooden poles.'],
  'MX-BCS': ['Wooden poles with hanging insulators.', 'Giant cardón cacti everywhere.'],
  'MX-YUC': ['Concrete poles with the insulators hanging below the crossbar (whole Yucatán peninsula).', 'Walls of loose pale limestone; thatched houses.', 'Pink lakes at Las Coloradas.'],
  'MX-ROO': ['Hanging-insulator poles.', 'Almost blindingly white soil; thin white-barked trees.', 'Cancún lamps with five round bulbs, like a dice.'],
  'MX-CAM': ['Hanging-insulator poles.', 'Red fields surrounded by dense tropical forest in the north.'],
  'MX-CMX': ['Poles with an asymmetric crossbar and double-stacked insulators.', 'Taxis with a pink upper half and white lower half.'],
  'MX-MEX': ['Poles with an asymmetric crossbar and double-stacked insulators.', 'Pink-and-white taxis near Mexico City.'],
  'MX-HID': ['Asymmetric crossbar with double-stacked insulators.', 'Blue myrtle cacti.'],
  'MX-MOR': ['Asymmetric crossbar with double-stacked insulators.', 'Cuernavaca: poles painted green at the bottom; black rectangular lamp heads.'],
  'MX-SLP': ['Mesh-bodied poles.', 'Tree yuccas, pulque agaves and blue myrtle cacti.', 'A very long flat ridge in the east (Sierra del Abra Tanchipa); thatched roofs.'],
  'MX-GUA': ['Mesh-bodied poles.', 'Extremely dark fields; red brick buildings.'],
  'MX-QUE': ['Mesh-bodied poles; irregular cobblestones.', 'Santiago de Querétaro lamps: black front and back edges, white middle.'],
  'MX-AGU': ['Most lamp posts and arms in the city are yellow.', 'Red brick buildings.'],
  'MX-ZAC': ['Red farm fields.', 'The 54: a divided highway lined with tree yuccas.'],
  'MX-COA': ['Gold tufts of grass lined up along the road edge.', 'The Maderas del Carmen ridge near the US border (Highway 53).'],
  'MX-NLE': ['Grainy, blue-grey road surface (also Tamaulipas).', 'Dramatic mountains around Monterrey.'],
  'MX-TAM': ['Grainy, blue-grey road surface; dashed outer lines on big roads.', 'Cerro del Bernal volcano near Tampico; Matamoros lamps with a ring-shaped bulb.'],
  'MX-TAB': ['White centre lines are most common here.', 'Huge Attalea palms with upright leaves.'],
  'MX-VER': ['Fences of trees with red bark.', 'White acorn-shaped insulators.', 'Sugarcane everywhere; citrus on hilltops around Poza Rica; Attalea palms.'],
  'MX-MIC': ['White acorn-shaped insulators.', 'Red brick buildings.'],
  'MX-COL': ['White acorn-shaped insulators.', 'Big groves of coconut palms.'],
  'MX-GRO': ['Black tar along the yellow centre line.', 'Coconut palm groves; the 95D to Acapulco has a divider with yellow top and bottom edges.'],
  'MX-CHP': ['Oil palm plantations.'],

  // ---- United States ----
  'US-CA': [
    'Utility poles marked with three yellow stripes near the bottom.',
    'A black stripe between the double yellow centre lines; some small roads have no centre line at all.',
    'Rectangular reflectors placed outside the double yellow lines.',
    'In-N-Out Burger (two thirds of all branches are here); Carl\'s Jr. rather than Hardee\'s.',
  ],
  'US-OR': ['"Speed" instead of "Speed Limit" on speed signs.', 'Bollards with a very long rectangular reflector.', 'Thick yellow PacifiCorp ID plates on poles.', 'Wide gap between the yellow centre lines.'],
  'US-WA': ['Bollards with a white rectangle on the front and two small white squares on the back.', 'Golden wheat hills in the east (the Palouse).'],
  'US-ID': ['Square-reflector bollards with one or two bolts.', 'PacifiCorp plates in the east.', 'Street names like "600 South".'],
  'US-UT': ['A white square reflector above a black rectangle: a bollard found only in Utah.', 'Square-reflector bollards with two bolts; black paddle-shaped bollards.', 'Grid street names like "400 South"; PacifiCorp pole plates.'],
  'US-WY': ['Square guardrails (a bar on square legs).', 'Black paddle bollards with a square reflector (only here); posts that stick up above a round reflector, sometimes with a white or grey top.', 'Devils Tower in the northeast.'],
  'US-CO': ['Dark metal bollard posts with a round white reflector set below the top of the post.', 'The Front Range ridge dividing plains from mountains.'],
  'US-NV': ['Bollards made of a thin stick with a white rectangle outlined in black.'],
  'US-AZ': ['Square-reflector bollards with one bolt.', 'I-19 south of Tucson signs distances in kilometres (the only place in the US).', 'Saguaros; Spanish-style stucco and tile roofs.'],
  'US-NM': ['Bollards with three round reflectors.', 'Pueblo Revival adobe houses with rounded edges.', 'Oil pumpjacks in the east.'],
  'US-TX': [
    'Grainy "salt and pepper" road surface.',
    'Yellow or red bands around signposts.',
    'A wide gap between the two yellow centre lines; reflectors outside the double lines.',
    'H-E-B, Whataburger and Buc-ee\'s; big sloped roofs.',
  ],
  'US-OK': ['A green sign with three rows of numbers on the back of rural stop signs.', 'Big sloped roofs; the steep Ouachita Mountains in the east and pinkish rocky peaks in the southwest.'],
  'US-KS': ['White reflectors on rural stop-sign posts.'],
  'US-NE': ['Black paddle-shaped bollards.', 'The Sandhills: rolling grass-covered dunes.'],
  'US-SD': ['Diamond-reflector bollards with two bolts.', 'The Black Hills and the Badlands.'],
  'US-ND': ['Yellow canola fields near the Canadian border.', 'Oil pumpjacks; Theodore Roosevelt National Park badlands with autumn colours.'],
  'US-MT': ['Diamond-reflector bollards with one bolt.', 'Glacier National Park\'s steep peaks.'],
  'US-MN': ['Yellow signs with black vertical triangles before bridges and guardrails.', 'A black-and-white marker on rural stop-sign posts; signs on two posts.', 'Hy-Vee, Kwik Trip and Pizza Ranch; prairie potholes.'],
  'US-WI': [
    'White metal pole plates with an orange rectangle and diamond.',
    'Plain white bollards with black reflectors (only here).',
    'Lettered county roads (A to ZZZ) with "County" above the letter; green ATV route signs.',
    'Driveway number signs that include the town or road name; Kwik Trip.',
  ],
  'US-MI': ['Signals hung from wires across intersections, in yellow boxes.', 'Upper Peninsula: orange-and-white pole plates like Wisconsin\'s.', 'Signs on two posts; driveway number signs.'],
  'US-IA': ['Concrete-paved ordinary rural roads.', 'Casey\'s, Kum & Go, Kwik Star, Hy-Vee and Pizza Ranch.'],
  'US-MO': ['Lettered county roads without the word "County".', 'Casey\'s; the Ozarks.'],
  'US-IL': ['Grainy "salt and pepper" rural road surface.', 'Casey\'s and Hy-Vee.'],
  'US-OH': ['Signs mounted on two posts.'],
  'US-NY': ['Small green reference markers with three rows of numbers (the second row starts with the DOT district).', 'Square guardrails; snowplowable road reflectors.', 'Three-storey wooden triplexes in cities.'],
  'US-VT': ['Small green reference markers whose second row almost always starts with 0.'],
  'US-NH': ['White "E-2" signs at bridge ends.', 'Small green and red end markers on bridges and guardrails.', 'Low stone walls along rural roads.'],
  'US-ME': ['Small green and red end markers on bridges and guardrails.'],
  'US-MA': ['Rectangular road reflectors (unusual for the Northeast).', 'Green and red guardrail end markers; stone walls; triplexes.'],
  'US-CT': ['Stone walls; three-storey triplexes.'],
  'US-RI': ['Stone walls; three-storey triplexes.'],
  'US-PA': ['White signs on intersection posts showing the crossing state route number.', 'Sheetz (and Wawa around Philadelphia).', 'Dark wooden plank fences in farm country.'],
  'US-NJ': ['Wawa and ShopRite.'],
  'US-DE': ['Extra-thick yellow centre lines.', 'ShopRite.'],
  'US-MD': ['Extra-thick yellow centre lines.'],
  'US-VA': ['White signs on intersection posts; extra-thick yellow lines.', 'Red metal roofs.'],
  'US-WV': ['Street signs with a fraction-like symbol in a circle.', 'Extra-thick yellow lines; red metal roofs.'],
  'US-KY': ['Long, thin recessed rumble strips at the road edges.', 'Some small roads have no centre line; red metal roofs.'],
  'US-TN': ['Red metal roofs.'],
  'US-NC': ['Street signs showing house-number ranges and arrows; white signs on posts.', 'Red metal roofs.'],
  'US-SC': ['Black street-name signs with white text.'],
  'US-GA': ['Reflectors outside the double yellow lines.', 'The most Waffle Houses and Zaxby\'s of any state; red clay.'],
  'US-FL': ['Reflectors outside the double yellow lines.', 'Publix supermarkets; white sand in the Keys; long straight roads through the Everglades; art deco in Miami.'],
  'US-MS': ['Wide gap between the yellow centre lines.', 'Shotgun houses.'],
  'US-LA': ['Wide gap between the yellow centre lines.', 'Houses on short stilts; shotgun houses in New Orleans; big sloped roofs.'],
  'US-AR': ['Wide gap between the yellow centre lines.', 'Red metal roofs; the Ouachita Mountains.'],
  'US-AK': ['Much Generation 2 coverage (rare in the rest of the US). PlonkIt has a separate Alaska guide.'],
  'US-HI': ['PlonkIt has a separate Hawaii guide.'],

  // ---- Canada ----
  'CA-AB': ['Cylindrical black-and-white bollards with two thin black bands (very common).', 'Township and range road numbers form a grid: you can read your position off a sign.', 'Rumble strips over the centre line; Drumheller badlands.'],
  'CA-BC': ['Thin, slightly curved black-and-white bollards.', 'Pole transformers face the road; sign backs are often green.', 'Concrete barriers instead of guardrails; signs hung from overhanging posts.'],
  'CA-SK': ['Pole-top insulators alternate from pole to pole (one on the left and two on the right, then the reverse).', 'White dashes between the yellow centre lines; white triangles on signposts.', 'Hilly river valleys in the south.'],
  'CA-MB': ['Black-and-grey bollards, usually with an orange stripe.', 'Poles with two hanging insulators; green-and-white striped stickers on signposts.', 'Grid roads named by miles north of the US border and east/west of the meridian.'],
  'CA-ON': [
    'Kilometre markers with a white square at the bottom (only here).',
    'Speed signs with a black "km/h" or "begins" panel.',
    'Diamond-shaped roadside markers; two side insulators and one on top.',
    'Guardrails of round wooden posts and three wires; orange-and-black cones.',
  ],
  'CA-QC': [
    '"ARRÊT" stop signs and red-and-white chevrons (the rest of Canada uses yellow).',
    'Thin white posts with a red or green reflector on guardrails; yellow fire-hydrant markers on signposts.',
    'Insulators pointing across the road; a black-and-yellow pole label with a small "Q".',
    'Orange-and-white cones; T-junction signs without a chequerboard.',
  ],
  'CA-NB': ['"STOP ARRÊT" stop signs and bilingual street signs.', 'Transformers facing the road; rectangular lamp heads.', 'Flat yellow bollards on the Trans-Canada; Acadian flags.'],
  'CA-NS': ['Transformers at a 45° angle; short curved lamp arms.', 'Insulators pointing across the road; lots of double yellow lines.', 'The Cape Breton Highlands.'],
  'CA-PE': ['Transformers at a 45° angle with red numbers; small white pole stickers.', 'Red soil and potato fields; green sign backs.'],
  'CA-NL': ['T-junction diamonds with a rectangular yellow border.', 'Pyramid-topped wooden guardrail posts; wooden boxes holding up signs.', 'Octagonal wooden rubbish bins; diamond markers next to hydrants; balsam firs.'],
  'CA-NT': ['Cylindrical bollards with two thick black bands.'],
  'CA-NU': ['Turquoise bilingual street signs in Iqaluit.'],

  // ---- Australia ----
  'AU-SA': ['Stobie poles (steel and concrete) with trident or "E"-shaped tops.', 'White property markers; flat signposts; yellow bus-stop posts.', 'Mount Gambier: white soil and pine plantations; the Nullarbor.'],
  'AU-NT': ['Rusty metal poles full of holes.', 'Yellow stickers on signposts; the only 130 km/h limits in Australia.', 'Termite mounds; Darwin: dark red soil and black-trunked trees; Alice Springs: orange rocks.'],
  'AU-WA': ['Trident pole tops with red insulators and black paint on the crossbar.', 'Poles with green-painted bases; yellow signposts.', 'Brown-bottomed or black-and-white striped bollards; dark green property markers.'],
  'AU-QLD': ['Pole-top coils angled upwards; round blue pole stickers.', 'Black-and-yellow bollards (only here); road signs with fluorescent borders.', 'Black pole markings around Brisbane, the Gold Coast and the Sunshine Coast; sugarcane.'],
  'AU-VIC': ['Concrete poles (two thirds of Australia\'s are here); three-coil pole tops.', 'Fire hydrants with red tops; white hydrant posts with a blue circle.', 'Melbourne poles with white stickers holding a small blue square; the Grampians.'],
  'AU-TAS': ['Thin metal crossbars bent into an L-shape.', 'Olive-green possum guards on poles.', 'White direction signs (only here).'],
  'AU-NSW': ['Red "No Stopping" signs (other states use white).', 'Yellow guardrail ends with a black dash (also ACT).', 'Triple broken centre lines on the Sturt Highway; Stobie poles in Broken Hill.'],
  'AU-ACT': ['"No Stopping" and "No Parking" signs with written text.', 'Yellow guardrail ends with a black dash.'],

  // ---- Indonesia ----
  'ID-BA': ['A rectangular attachment on pole tops.', 'Dark blue pole paint with horizontal text.', 'Crown-like roof pinnacles, guardian statues and carved grey andesite gates.'],
  'ID-NB': ['Poles with an extra-long support (Lesser Sunda Islands).', 'Drier, shrubby landscape; A-frame poles.'],
  'ID-NT': ['Poles with an extra-long support.', 'Dry, shrubby landscape; high-peaked roofs on Sumba.'],
  'ID-JK': ['Poles with an indent on both sides.'],
  'ID-JB': ['Poles with an indent on both sides.', 'Tiled roofs; rice fields.'],
  'ID-BT': ['Poles with an indent on both sides.'],
  'ID-JT': ['Trident pole tops.', 'Tiled roofs.'],
  'ID-YO': ['Trident pole tops.'],
  'ID-JI': ['Tiled roofs; rice fields.'],
  'ID-SU': ['Even crossbar but uneven insulators: one on one side, two on the other.', 'Batak boat-shaped roofs (less upturned, no spires) around Lake Toba.', 'Steep palm-leaf roofs on Nias.'],
  'ID-SB': ['Minangkabau boat-shaped roofs with spires.', 'Karst hills.'],
  'ID-RI': ['Roofs with gable horns.', 'Oil palm estates.'],
  'ID-BB': ['White soil lying on top of red soil, spilling onto the road.'],
  'ID-SA': ['An extra attachment just under the crossbar.', 'Painted white fences with blue or red.'],
  'ID-GO': ['An extra attachment under the crossbar.', 'Very rounded green hills with palms, sugarcane or maize.'],
  'ID-ST': ['An extra attachment under the crossbar.', 'Bollards painted black, white and yellow.', 'Thin black poles with blue and green tape on the east peninsula; Palu Bay.'],
  'ID-SN': ['Horizontal slots in the triangle of the roof.', 'Gable horns; Tongkonan boat-roof houses around Rantepao.', 'Asymmetric poles with two supports; karst.'],
  'ID-SG': ['Occasional thin black poles with coloured tape.'],
  'ID-KB': ['A-frame poles; UK-style bollards.', 'Wooden-shingle roofs.'],
  'ID-KT': ['Green paint on bridges; roofs with gable horns.', 'A moiré-pattern camera glitch.'],
  'ID-KS': ['Green paint on bridges; gable horns.', 'Karst formations in the east; flatter roof tiles.'],
  'ID-KI': ['A-frame poles; wooden-shingle roofs.'],

  // ---- Russia ----
  'RU-TA': ['Bilingual Tatar signs using "урамы" for street.', 'Yellow plates strapped to most poles.', 'Sparse larches along roads through open rolling fields.'],
  'RU-BA': ['Bilingual Bashkir signs using "урамы" for street (usually not abbreviated).'],
  'RU-CU': ['Bilingual Chuvash signs using "урамӗ" for street.', 'A distinctive bus stop design.'],
  'RU-ME': ['Bilingual Mari signs using "урем" for street.', 'Historic buildings with green roofs and red brick with white stone details.'],
  'RU-KO': ['Bilingual Komi signs using "улича" for street.', 'Roads made of concrete slabs.', 'Vorkuta: bleak winter coverage.'],
  'RU-MO': ['Saransk: round street signs in up to four languages; red-and-white striped poles.'],
  'RU-ULY': ['Poles painted in alternating red and white sections (Ulyanovsk city).'],
  'RU-KRS': ['Dashed outer road lines.'],
  'RU-STA': ['Black-coloured bottoms on traffic signs.'],
  'RU-CE': ['Black-coloured bottoms on traffic signs.'],
  'RU-DA': ['Black sign bottoms in the west; white limestone brick buildings.', 'Very dry, flat land by the Caspian.'],
  'RU-KL': ['Extremely dry, flat steppe.'],
  'RU-AST': ['Extremely dry, flat land; red soil near the Volga.'],
  'RU-LEN': ['Clips on the edges of signposts.', 'Red soil.'],
  'RU-SPE': ['Clips on signposts; street signs with a Latin transliteration on a black band.'],
  'RU-MOW': ['Blue tourist signs with English.'],
  'RU-MOS': ['Brown tourist-attraction signs; town names also in Latin letters.'],
  'RU-KGD': ['Oak trees lining roads, often with a white stripe on the trunk.', 'Cobblestones; a large red brake light on the car.'],
  'RU-KR': ['Big rocks along the road; sandy verges.', 'Two yellow bands on signposts (2018 coverage); mesh poles in Petrozavodsk.'],
  'RU-MUR': ['Big roadside rocks; low shrubs and fireweed on open hills.', 'Two yellow bands on signposts on the main road.'],
  'RU-KHM': ['Sandy verges; a blurred long antenna on the car.'],
  'RU-YAN': ['Sandy verges; concrete slab roads.'],
  'RU-NEN': ['Concrete slab roads.'],
  'RU-CHE': ['Pedestrian signs with a U-shaped hook; fences of rounded rectangles with a line through the middle.', 'Extended insulator bars in the south; dense birch-only forests.'],
  'RU-ORE': ['Extended insulator bars in the east; Chelyabinsk-style fences.', 'Sunflowers in the north.'],
  'RU-KEM': ['Extended insulator bars in the south.'],
  'RU-PSK': ['Decorative pedestrian sign holders.', 'Red soil.'],
  'RU-SAM': ['Rounded rectangular fences in Samara, Syzran and Tolyatti (yellow in Tolyatti).', 'Sunflowers.'],
  'RU-IRK': ['Bright orange decorative fences in Irkutsk.', 'Olkhon Island: sandy hills at sunset over Lake Baikal.'],
  'RU-ZAB': ['An angled extended insulator bar in Chita.'],
  'RU-VLA': ['Blue-pod lupines in the north; red-painted poles in Murom.'],
  'RU-IVA': ['Blue-pod lupines.'],
  'RU-KOS': ['Blue-pod lupines; a grey bollard with two red reflectors on the P100.'],
  'RU-PER': ['Red soil; hogweed; roadside rocks.'],
  'RU-UD': ['Red soil around Izhevsk.'],
  'RU-SAK': ['Giant butterbur ("Sakhalin cabbage") everywhere in the south.', 'Sandy road to Okha with stunted trees.'],
  'RU-KAM': ['Grey gravelly soil and volcanoes.'],
  'RU-MAG': ['Hazy hills and dark gravel on the Kolyma Highway.'],
  'RU-SA': ['Dark gravel near the mountains east of Yakutsk; orange or white haze around Mirny.'],
  'RU-BU': ['Open grassy landscape with shrubs and mountains; forest-fire haze near Lake Gusinoye.', 'Tunkinsky: green basin under jagged peaks.'],
  'RU-AL': ['The main road through the mountains, often foggy or rainy.'],
  'RU-TY': ['Dry steppe mountains; dashed outer lines.'],
  'RU-PRI': ['Lush, hilly forest; overcast coverage around Vladivostok.'],
  'RU-KDA': ['Palm trees around Sochi (the only tropical plants in Russia).'],
  'RU-KB': ['Mount Elbrus on the border.'],
  'RU-KC': ['Mount Elbrus on the border.'],
  'RU-YEV': ['Rainy, foggy coverage on the west side of the one main road.'],
  'RU-AMU': ['Sunset coverage on the P-297.'],
  'RU-KHA': ['Sunny mountainous road to Vanino; winter coverage in Sovetskaya Gavan.'],

  // ---- Argentina ----
  'AR-N': ['Deep red soil.', 'Uneven square stone paving (as in western Rio Grande do Sul).', 'Totai palms.'],
  'AR-P': ['Sandy soil with lots of low trees and bushes.', 'Caranday wax palms in single-species groves.'],
  'AR-H': ['Sandy soil with dense low scrub; sunflower fields in the south.', 'Caranday wax palms and toothpick cacti.'],
  'AR-W': ['Yatay palms; caranday wax palms.'],
  'AR-E': ['Most of Argentina\'s tree plantations; yatay palms at El Palmar.'],
  'AR-D': ['Reddish road surface lined with long needle-grass.'],
  'AR-L': ['Yellow T-junction signs with the road numbers and a chevron strip.', 'Caldén trees.'],
  'AR-X': ['Distinctive markers on provincial roads.', 'The Sierras de Córdoba west of the city; caranday palms.'],
  'AR-B': ['Small lakes by the road; semi-coastal grassy hills near Bahía Blanca.', 'Mar del Plata houses: quartzite stone facades, orange tile roofs, vaulted porches.'],
  'AR-T': ['White vertical pole stickers with digits.', 'Sugarcane; the RN65 climbing into the clouds.'],
  'AR-A': ['Red mountains along the RN68.', 'Wild sunflowers; cardón cacti.'],
  'AR-Y': ['Red brick buildings (like Bolivia); salt pans.', 'Cardón cacti; wild sunflowers.'],
  'AR-F': ['Latvian-style hooked wooden poles (also Mendoza).', 'Red soil and cliffs at Talampaya (RN76).'],
  'AR-M': ['Hooked wooden poles; poles with one insulator on the side.', 'Vineyards with mountains to the west and flat land to the east.'],
  'AR-Q': ['Single rows of poplars on flat land around Neuquén.', 'Monkey puzzle trees in the west (road 23).'],
  'AR-U': ['Rock formations around Villa Dique Florentino Ameghino; Comodoro Rivadavia on the slopes of Chenque hill.'],
  'AR-Z': ['Flat grass with few bushes in the southeast; melting snow on the RN293.'],
  'AR-V': ['Flat grass steppe; beech forests.', 'Snowy mountains to the north in Ushuaia.'],

  // ---- Vietnam ----
  'VN-HN': ['Tall, boxy multi-storey houses with pillars, pediments and classical balconies.', 'Black stickers on poles; poles with big holes along their whole length.'],
  'VN-56': ['Graves standing alone in the middle of rice fields.', 'Boxy multi-storey delta houses.'],
  'VN-61': ['Graves in the fields; completely flat open farmland.'],
  'VN-20': ['Graves in the fields; completely flat open farmland.'],
  'VN-67': ['Graves in the fields; boxy delta houses.'],
  'VN-63': ['Graves in the fields.'],
  'VN-66': ['Graves in the fields.'],
  'VN-HP': ['Coastal roads east of the city look out at Hạ Long Bay\'s rocky islands.'],
  'VN-13': ['Pointy, rocky islands rising from the sea along the coast roads.', 'Clusters of Khasi pines on the hills.'],
  'VN-09': ['Clusters of Khasi pines on the hills.'],
  'VN-03': ['Rounded, pointy mountains with dark bare rock (Đồng Văn Karst Geopark).', 'Wooden or bamboo grid fences; stilt houses.'],
  'VN-02': ['Sa Pa: a touristy mountain town full of signs and palace-like hotels.', 'Thin bamboo utility poles in rural villages.'],
  'VN-01': ['Thin bamboo poles; traditional stilt houses with triangular gable openings.'],
  'VN-71': ['Traditional wooden stilt houses; bamboo poles.'],
  'VN-05': ['Traditional wooden stilt houses; bamboo poles.'],
  'VN-69': ['Tea bushes in winding rows on the hills.'],
  'VN-35': ['Greenhouses cover the countryside around Đà Lạt.', 'Tea plantations around Bảo Lộc (the south\'s main tea area).', 'Wind turbines southeast of Đà Lạt.'],
  'VN-33': ['Black pepper vines covering tree trunks; coffee; red soil.', 'Wind turbines north of Buôn Ma Thuột.'],
  'VN-30': ['Pepper vines, coffee and rubber on red soil.', 'Wind turbines south of Pleiku.'],
  'VN-72': ['Pepper and coffee on red soil.'],
  'VN-28': ['Red soil and rubber.'],
  'VN-40': ['Dragon-fruit farms around Phan Thiết.', 'Dry, sandy and rocky coast northeast of Phan Thiết; signs in Cyrillic near the resorts.'],
  'VN-34': ['Sand dunes hugging the road on the peninsula in the far north.'],
  'VN-27': ['Hội An\'s old yellow buildings with dark brown doors.', '"A" over the crossbar on poles (central Vietnam).'],
  'VN-24': ['Wind turbines southeast of Đồng Hới.'],
  'VN-25': ['Wind turbines in the west.'],
  'VN-31': ['Wind turbines east of Quy Nhơn.'],
  'VN-37': ['A single large mountain rising out of totally flat land (Núi Bà Đen).', 'Rubber plantations.'],
  'VN-57': ['Rubber trees in dense grids with plastic wrapped round the trunks.'],
  'VN-58': ['Rubber plantations; triangle pole tops and off-centre crossbars (south).'],
  'VN-39': ['Rubber plantations.'],
  'VN-41': ['Dragon-fruit farms on the border with Tiền Giang.'],
  'VN-46': ['Dragon-fruit farms near the Long An border.', 'Straight canals with villages along them.'],
  'VN-50': ['Coconut palms everywhere; single-storey houses along canals.'],
  'VN-CT': ['Straight canals lined with linear villages; single-storey houses.'],
  'VN-73': ['Straight canals and single-storey concrete houses.'],

  // ---- Philippines ----
  'PH-15': ['Concrete guardrails striped yellow and black.', 'Pine trees on dry mountainsides.', 'Decorations made from green Mountain Dew bottles.'],
  'PH-02': ['Kuliglig (two-wheeled tractor carts) on the plains around Cauayan, Isabela.', 'Corn fields; Mountain Dew bottle decorations.'],
  'PH-01': ['Mountain Dew bottle decorations; corn.'],
  'PH-03': ['Square concrete poles with an indent on both sides (north of Manila).', 'Mount Arayat standing alone on flat fields.', 'White Bataan Death March markers.'],
  'PH-00': ['Ladder-like pole tops: two tall L-section bars joined by thin wires.'],
  'PH-05': ['White guardrails with three recurring black stripes (only here).', 'Mayon volcano\'s smooth cone.'],
  'PH-41': ['Diagonally woven bamboo (sawali) walls on Palawan.', 'Six-lane, near-empty highway south of Puerto Princesa with a double electric wire.', 'Roman soldier statues on Marinduque.'],
  'PH-06': ['Sugarcane (Panay, Negros Occidental).', 'Square indented concrete poles around Bacolod.'],
  'PH-07': ['The Chocolate Hills on Bohol.', 'Yellow lamp posts with black stripes on Siquijor.'],
  'PH-09': ['Square metal mesh utility poles (mainly on the Zamboanga peninsula).', 'Diamond-pattern amakan walls.'],
  'PH-10': ['Pineapple and banana plantations; sugarcane in Bukidnon.'],
  'PH-11': ['Banana plantations; light-trunked albizia trees.'],
  'PH-12': ['Pineapple and banana plantations.', 'A black Street View car with a roof rack around General Santos.'],
  'PH-13': ['Light-trunked albizia trees; oil palm.'],
  'PH-14': ['Mosques; destroyed buildings in Marawi from the 2017 siege.'],
}
