import type { GeoTopic } from './types'

// Geology explainers. Written from general geology knowledge (USGS, Wikipedia); spot-check (SPEC §7.4).

export const rocksAndSoils: GeoTopic[] = [
  {
    id: 'rock-types', title: 'The three kinds of rock, and how to tell them from the road', category: 'Rocks & soil chemistry',
    summary: 'Every landscape is built from igneous, sedimentary or metamorphic rock, and each weathers into its own shapes and colours.',
    science: [
      'Igneous rocks crystallise from molten magma. Cooled slowly underground they become coarse-grained granite (pale, speckled); erupted and cooled fast they become fine-grained basalt (dark grey to black).',
      'Sedimentary rocks form from layers of sand, mud, shells or salt laid down in water or by wind, then buried and cemented: sandstone, shale, limestone, chalk. They show horizontal layers (bedding), often in different colours.',
      'Metamorphic rocks are older rocks changed by heat and pressure deep in mountain belts: shale becomes slate, limestone becomes marble, granite becomes gneiss. They often show wavy bands or split into sheets.',
    ],
    looks: ['Granite: rounded boulders and bare domes, pale grey or pink.', 'Basalt: dark cliffs, black sand, sometimes six-sided columns.', 'Sandstone and shale: flat layers in road cuts and cliffs, red, buff or grey.', 'Limestone: white or grey crags, caves and sinkholes.', 'Slate: dark grey layers, used for roofs and fences in slate regions.'],
    where: 'Everywhere: the rock under a region decides its shapes, soil colour and building stone.',
    countries: [],
    history: ['People have always built with local stone, so buildings are a clue to the rock: grey granite in Aberdeen and Galicia, honey limestone in the Cotswolds, black basalt in the Azores and the Canaries, slate roofs in Wales, pink tuff in Armenia.'],
    facts: ['The oldest rocks on Earth (over 4 billion years) are in Canada (Acasta Gneiss); the oldest mineral grains (zircons, 4.4 billion years) come from Jack Hills in Western Australia.', 'Most of the continents\' surface is covered by sedimentary rock, but it makes up only a small fraction of the crust by volume.'],
    tips: ['Look at road cuts: flat layers mean sedimentary rock (plains, plateaus); rounded boulders mean granite; dark rubble means volcanic.', 'Walls and houses built of local stone give away the geology, and often the region.'],
    remember: 'Fire, layers and pressure: igneous is cooled lava, sedimentary is stacked mud, metamorphic is rock squeezed until it changes.',
    photoCategories: ['Road cuts'],
  },
  {
    id: 'soil-colour-chemistry', title: 'The chemistry of soil colour', category: 'Rocks & soil chemistry',
    summary: 'Soil colour is chemistry you can see: iron oxides, organic matter, water and lime decide whether ground is red, yellow, black, grey or white.',
    science: [
      'Iron is the main dye. When iron-bearing minerals weather in air, the iron oxidises (rusts) to Fe³⁺. In warm, well-drained soils it forms hematite (Fe₂O₃), which is strongly red even at 1–2%. In soils that stay moist it forms goethite (FeOOH), which is yellow-brown. That is why tropical plateaus are red and valley bottoms are yellow.',
      'Where soil is waterlogged, there is no oxygen. Bacteria use the iron instead, reducing it to Fe²⁺, which dissolves and washes away. What is left is grey or blue-green ("gleyed") soil, with rusty orange mottles where air gets in along roots.',
      'Black and dark brown comes from humus (decayed plant matter, mostly carbon). Grasslands build deep humus from their roots (chernozem); cold, wet places build peat. Volcanic ash binds humus tightly, so volcanic soils are dark too. Manganese oxides also give black specks and crusts.',
      'White and pale grey means the colouring agents are missing: quartz sand with everything else leached out, lime (calcium carbonate) that builds up in dry soils, gypsum or salt crusts in deserts, or chalk and limestone rock.',
      'Time matters: red soils are usually very old. Iron oxides accumulate as weathering removes everything else, so the reddest soils are on the oldest, most stable land surfaces (Brazil, Africa, Australia).',
    ],
    looks: ['Red road cuts: old, well-drained, iron-rich (tropics, subtropics, old desert sands).', 'Yellow-orange: wetter iron-rich soils (the Amazon, valley floors).', 'Black: humus-rich grassland or volcanic soil.', 'Grey-blue with orange streaks: waterlogged ground.', 'White: sand, chalk or salt.'],
    where: 'Red: Brazil, central Africa, India\'s south and east, Southeast Asia, Australia, the US Southeast. Black: Ukraine, Russia\'s south, the US Corn Belt, the Pampas, Java. White: Yucatán, Florida, deserts.',
    countries: ['BR', 'AU', 'IN', 'UA', 'US', 'AR', 'MX', 'ID'],
    history: ['Soil colour has long been used to judge farmland: Russian soil scientist Vasily Dokuchaev founded modern soil science in the 1880s by studying the black earth (chernozem).', 'Ochre (natural iron-oxide pigment) was one of the first pigments humans used, over 100,000 years ago in South Africa\'s Blombos Cave.'],
    facts: ['Mars is red for the same reason as Brazilian soil: iron oxide dust.', 'A Munsell soil colour chart, used by soil scientists worldwide, names colours by hue, value and chroma so that "red" can be recorded precisely.'],
    tips: ['Soil colour is one of the fastest regional clues: see the soil pages and the soil-colour map for country-by-country patterns.'],
    remember: 'Rust is red when dry, yellow when damp, gone when drowned; rotting plants make black; washed-out sand stays white.',
    related: [{ to: '/vegetation/soils', label: 'Soil-colour map' }, { to: '/vegetation?tab=soils', label: 'All soil types' }],
    photoCategories: ['Laterite', 'Gley'],
  },
  {
    id: 'desert-varnish', title: 'Why desert rocks are shiny black and cliffs are striped', category: 'Rocks & soil chemistry',
    summary: 'Dark streaks down desert cliffs and black-coated stones are desert varnish, a thin coating of clay and manganese and iron oxides.',
    science: [
      'Desert varnish is a paper-thin (a fraction of a millimetre) coating of clay minerals with manganese oxides (black) and iron oxides (red-brown). It builds up over thousands of years, probably helped by bacteria that concentrate manganese from dust and dew.',
      'Where rainwater runs down a cliff it leaves vertical black streaks; the unstained rock between stays red or buff.',
      'The same dry climate keeps red iron coatings on sand grains and lets lime and salt crusts form at the surface.',
    ],
    looks: ['Vertical black stripes on red sandstone cliffs.', 'Dark, shiny stones on flat gravel plains (desert pavement).'],
    where: 'Deserts worldwide: the US Southwest, the Sahara, the Atacama, Australia\'s outback, the Arabian desert.',
    countries: ['US', 'MX', 'AU', 'CL', 'MA', 'DZ', 'EG', 'JO'],
    history: ['Ancient peoples scratched through the dark varnish to make petroglyphs, which show pale against the black (Newspaper Rock in Utah, Wadi Rum in Jordan).'],
    facts: ['Desert varnish grows so slowly that scientists have used it to estimate the age of rock surfaces and petroglyphs.'],
    tips: ['Black streaks on red cliffs: a dry climate. Combined with the vegetation and road style, think US Southwest, Jordan or outback Australia.'],
    remember: 'Desert varnish is the desert\'s tan: thousands of years of dust and bacteria painting rocks black.',
    photoCategories: ['Desert varnish'],
  },
]

export const landforms: GeoTopic[] = [
  {
    id: 'karst', title: 'Why do some hills look like giant towers and teeth? (karst)', category: 'Landforms',
    summary: 'Steep, rounded limestone towers, sinkholes and caves: landscapes carved by rainwater dissolving rock.',
    science: [
      'Rainwater absorbs carbon dioxide from the air and soil and becomes a weak carbonic acid (H₂O + CO₂ → H₂CO₃). It dissolves limestone (calcium carbonate): CaCO₃ + H₂CO₃ → Ca²⁺ + 2HCO₃⁻.',
      'Water eats down along cracks, leaving isolated towers, cone hills, sinkholes (dolines) and caves. In hot, wet climates the process is fastest and produces the spectacular tower karst of southern China and Vietnam.',
      'The reverse reaction, where water loses CO₂ in caves, deposits calcite again as stalactites and stalagmites.',
    ],
    looks: ['Steep, green, rounded or pointed hills standing alone out of flat rice fields or the sea.', 'Few rivers on the surface, sinkholes, springs, and bare grey rock.'],
    where: 'Southern China (Guilin, Yangshuo), northern Vietnam (Hạ Long Bay, Ninh Bình, Hà Giang), Thailand (Krabi, Phang Nga), Laos (Vang Vieng), the Philippines (Palawan), the Dinaric Alps (Slovenia, Croatia), the Yucatán cenotes.',
    countries: ['CN', 'VN', 'TH', 'LA', 'PH', 'SI', 'HR', 'MX', 'ID', 'MY'],
    history: ['The word "karst" comes from the Kras plateau in Slovenia and Italy, where it was first studied.', 'Chinese landscape painting was inspired by the karst towers of Guilin.'],
    facts: ['Sơn Đoòng in Vietnam, first explored in 2009, is the largest known cave passage in the world, big enough to hold a 40-storey building.', 'The Yucatán has almost no rivers: its water flows underground through karst and surfaces in cenotes.'],
    tips: ['Tower karst with rice fields: Vietnam (Ninh Bình, Hà Giang) or Thailand/Laos. Karst sea stacks: Hạ Long Bay or Phang Nga.'],
    remember: 'Karst is limestone dissolved by fizzy rainwater: the hills are what the rain has not eaten yet.',
    related: [{ to: '/regions/VN?tab=features', label: 'Vietnam features' }],
    photoCategories: ['Moon Hill (Yangshuo)', 'Limestone islands in Ha Long Bay', 'South China Karst'],
  },
  {
    id: 'mesas', title: 'Why are some hills flat on top? (mesas, buttes and tepuis)', category: 'Landforms',
    summary: 'Flat-topped hills with steep sides: remnants of horizontal rock layers capped by a hard layer that resists erosion.',
    science: [
      'When sedimentary rocks lie flat, a hard layer (sandstone, basalt or quartzite) protects the softer rock below. As rivers and rain erode the plateau, pieces break away, leaving tables (mesas), smaller towers (buttes) and finally pinnacles.',
      'The cliffs are steep because the hard cap breaks off in blocks, while the soft rock beneath forms slopes of rubble.',
      'Tepuis in Venezuela and Guyana are extreme examples: tables of very hard quartzite about 1.5–2 billion years old.',
    ],
    looks: ['Flat skylines with sudden cliffs; layered red, white and buff rock; rubble slopes at the base.'],
    where: 'The US Southwest (Monument Valley, Arizona, Utah, New Mexico), Mexico\'s north, Argentina\'s northwest, the Gran Sabana (Venezuela), South Africa\'s Karoo, Australia\'s outback, the Sahara.',
    countries: ['US', 'MX', 'AR', 'VE', 'ZA', 'AU', 'DZ', 'LY', 'BR'],
    history: ['Monument Valley became the image of the American West through John Ford\'s Westerns (from 1939).', 'Mount Roraima, a tepui on the Venezuela–Brazil–Guyana border, inspired Arthur Conan Doyle\'s "The Lost World" (1912).', 'In South Africa and Namibia a flat-topped hill is called a "tafelberg" (table mountain), as in Cape Town\'s.'],
    facts: ['Tepuis are so isolated that many plants and frogs on their tops live nowhere else.', '"Mesa" is Spanish for table; "butte" is French for a small hill.'],
    tips: ['Flat-topped hills with the Karoo\'s dry scrub: South Africa. Red mesas with dry scrub and yellow centre lines: US Southwest.'],
    remember: 'A mesa is a table with a hard tablecloth: the cap rock keeps it flat while the rest washes away.',
    photoCategories: ['Monument Valley', 'Tepuis'],
  },
  {
    id: 'volcanoes', title: 'Why do volcanoes have such different shapes?', category: 'Landforms',
    summary: 'Steep perfect cones, broad gentle shields and small cinder cones: the shape depends on how runny the lava is.',
    science: [
      'Runny, silica-poor basalt lava flows far before cooling, building broad, gently sloping shield volcanoes (Hawaii, Iceland).',
      'Sticky, silica-rich andesite and dacite lava piles up near the vent and erupts explosively, building steep stratovolcanoes (composite cones) of alternating ash and lava layers: Fuji, Mayon, Cotopaxi, Popocatépetl.',
      'Cinder cones are small, steep piles of loose lava fragments from a single eruption.',
      'Most stratovolcanoes sit above subduction zones, where an ocean plate sinks and melts under another plate: the Pacific "Ring of Fire".',
    ],
    looks: ['A single steep snowy cone on the horizon: a stratovolcano. Wide, low domes and black lava fields: shield volcanoes. Small red-black cones: cinder cones.'],
    where: 'The Ring of Fire: Japan, the Philippines, Indonesia (Java, Bali), the Andes (Ecuador, Chile), Central America, Mexico, the Cascades (US), Kamchatka, New Zealand. Hotspots: Hawaii, Iceland, the Canary Islands, Réunion.',
    countries: ['JP', 'PH', 'ID', 'EC', 'CL', 'GT', 'MX', 'US', 'NZ', 'IS', 'ES', 'IT', 'CR', 'RU'],
    history: ['Vesuvius buried Pompeii and Herculaneum in 79 AD. Tambora (Indonesia) erupted in 1815, the largest eruption in recorded history; it caused the "Year Without a Summer" in 1816.', 'Krakatoa\'s 1883 eruption was heard nearly 5,000 km away.'],
    facts: ['Volcanic soils are among the most fertile on Earth, which is why so many people live on active volcanoes (Java, the slopes of Vesuvius and Etna).', 'Mauna Kea in Hawaii is the tallest mountain on Earth measured from its base on the sea floor (over 10,000 m).'],
    tips: ['A perfect snowy cone plus left-hand traffic and rice: Java/Bali. Plus yellow centre lines: Mexico, Guatemala or the US Cascades.'],
    remember: 'Runny lava makes flat shields; sticky lava makes steep cones and big bangs.',
    related: [{ to: '/topography/cascades', label: 'Cascade Range' }, { to: '/vegetation/volcanic-soil', label: 'Volcanic soil' }],
    photoCategories: ['Stratovolcanoes', 'Shield volcanoes'],
  },
  {
    id: 'granite-domes', title: 'Why do some hills look like giant smooth domes and boulder piles?', category: 'Landforms',
    summary: 'Bald rock domes, inselbergs and piles of rounded boulders: the typical shapes of granite.',
    science: [
      'Granite forms deep underground. When overlying rock erodes away, the pressure is released and the granite expands and cracks in curved sheets parallel to the surface (exfoliation), producing smooth domes.',
      'Where granite has vertical cracks, water weathers along them and rounds the blocks from the corners, leaving piles of rounded boulders (tors, kopjes).',
      'Isolated domes rising from flat plains are called inselbergs ("island mountains"): they are harder rock left behind when the surrounding land wore down.',
    ],
    looks: ['Bare, smooth grey or pink rock domes; balancing boulder piles; single rock mountains out of flat land.'],
    where: 'Rio de Janeiro (Sugarloaf) and Espírito Santo in Brazil, Yosemite (US), Zimbabwe\'s balancing rocks, the Namib, southwest Australia, Corsica and Sardinia, Seychelles, Joshua Tree (US), Mozambique and Malawi inselbergs, Nigeria (Zuma Rock), Kenya (Kit Mikayi), Malawi (Mount Mulanje), Tanzania (around Mwanza).',
    countries: ['BR', 'US', 'ZW', 'NA', 'AU', 'FR', 'IT', 'MZ', 'NG', 'KR', 'KE', 'MW', 'TZ'],
    history: ['Sugarloaf Mountain got its name from the conical moulds used to make sugar loaves in the colonial sugar trade.', 'Half Dome in Yosemite was first climbed in 1875 by George Anderson, who drilled holes and hammered in iron eyebolts.'],
    facts: ['Uluru, often thought to be granite, is actually arkose sandstone; Kata Tjuta next to it is conglomerate.', 'The Espírito Santo region of Brazil has so many granite domes that it is a world centre for granite quarrying and stone export.'],
    tips: ['Bare granite domes in green tropical hills: Rio de Janeiro or Espírito Santo (Brazil). Boulder piles in savanna: Zimbabwe, Mozambique or Nigeria.'],
    remember: 'Granite peels like an onion when the weight on top is removed: that is how you get a sugarloaf.',
    related: [{ to: '/regions/BR/BR-ES', label: 'Espírito Santo' }],
    photoCategories: ['Inselbergs', 'Tors'],
  },
  {
    id: 'young-old-mountains', title: 'Why are some mountains jagged and others rounded?', category: 'Landforms',
    summary: 'Jagged, snowy peaks are young mountains still being pushed up; rounded, forested ridges are old ones worn down over hundreds of millions of years.',
    science: [
      'Mountain ranges rise where tectonic plates collide. While the push continues (the Alps, Himalayas, Andes, Rockies), uplift outpaces erosion and peaks stay high and sharp; ice-age glaciers carved them into horns and knife-edge ridges.',
      'When the collision stops, erosion wins. After 200–400 million years the Appalachians, the Urals, the Scottish Highlands and Australia\'s Great Dividing Range have been worn to rounded, forested hills.',
      'Rock type matters too: hard granite and quartzite make bold peaks; soft shale makes gentle slopes.',
    ],
    looks: ['Young: sharp peaks, snow, bare rock, deep V-valleys and glaciers. Old: rounded, forest-covered ridges, parallel valleys, no permanent snow.'],
    where: 'Young: the Himalayas, Alps, Andes, Rockies, Southern Alps (NZ), Caucasus. Old: the Appalachians, Urals, Scandinavian and Scottish mountains, Australia\'s Great Dividing Range, Brazil\'s Serra do Mar.',
    countries: ['NP', 'IN', 'CH', 'AT', 'PE', 'CL', 'US', 'NZ', 'RU', 'GB', 'AU', 'NO'],
    history: ['The Appalachians, Scottish Highlands, Norway\'s mountains and Morocco\'s Anti-Atlas were once one range, formed when the continents collided to make Pangaea; the Atlantic later opened through it.'],
    facts: ['The Himalayas are still rising by a few millimetres a year.', 'Some Appalachian rocks are over a billion years old.'],
    tips: ['Rounded, forested parallel ridges: the Appalachians (US). Jagged snow peaks: the Alps, Rockies or Andes; use vegetation and road signs to pick.'],
    remember: 'Sharp mountains are teenagers still growing; round mountains are grandparents worn smooth.',
    related: [{ to: '/topography', label: 'Mountains & Rivers' }],
    photoCategories: ['Blue Ridge Mountains', 'Matterhorn'],
  },
  {
    id: 'glacial', title: 'How ice shaped the north: fjords, U-valleys, lakes and boulders', category: 'Landforms',
    summary: 'Much of Canada, Scandinavia, northern Europe and the northern US was scraped and moulded by ice sheets up to 3 km thick, until about 12,000 years ago.',
    science: [
      'Glaciers carve valleys into a U-shape (rivers make V-shapes). Where the sea flooded glacial valleys, fjords formed.',
      'Ice sheets scraped soil off hard old rock (the Canadian Shield, Finland, Sweden) and left bare, smoothed rock and thousands of lakes in scoured hollows.',
      'Melting ice dumped rubble: moraines (ridges), drumlins (egg-shaped hills), eskers (long gravel ridges), and erratics (lone boulders carried far from their source). Sandy glacial deposits are why pine forests on sand are so common from the Netherlands to Russia.',
      'The land is still rising after the weight of the ice was removed: parts of the Gulf of Bothnia rise almost 1 cm a year.',
    ],
    looks: ['Countless lakes, rounded bare rock with scratches, big lone boulders in fields, U-shaped valleys and fjords, pine forest on sandy ridges.'],
    where: 'Canada, Norway, Sweden, Finland, the Baltics, Poland and northern Germany, Scotland, Ireland, the northern US (Minnesota "10,000 lakes", New England), Patagonia, New Zealand\'s South Island; smaller ice-age glaciers also carved valleys in southern ranges such as Portugal\'s Serra da Estrela.',
    countries: ['CA', 'NO', 'SE', 'FI', 'EE', 'LV', 'LT', 'PL', 'DE', 'GB', 'IE', 'US', 'CL', 'AR', 'NZ', 'IS', 'PT'],
    history: ['Louis Agassiz convinced scientists in the 1830s–40s that huge ice sheets once covered northern Europe, explaining the mysterious erratic boulders.', 'New England\'s stone walls were built from glacial boulders cleared by farmers.'],
    facts: ['Finland is called the land of a thousand lakes; it has about 188,000.', 'Because the land rises, Finland gains about 7 km² of new land a year.'],
    tips: ['Lakes, pines and bare glaciated rock: Finland, Sweden, Ontario/Quebec (Canadian Shield). Fjords: Norway, Chile, New Zealand, Iceland.'],
    remember: 'The ice left behind lakes, boulders and U-shaped valleys, and the land is still bouncing back up.',
    photoCategories: ['Glacial erratics', 'U-shaped valleys'],
  },
  {
    id: 'basalt', title: 'Why are some places black and full of six-sided columns?', category: 'Landforms',
    summary: 'Black rock, black sand, lava fields and hexagonal columns: basalt, the Earth\'s most common volcanic rock.',
    science: [
      'Basalt is runny, iron- and magnesium-rich lava, dark grey to black. When a thick lava flow cools slowly, it shrinks and cracks into columns, usually six-sided because hexagons are the most efficient way to release the stress.',
      'Huge outpourings of basalt ("flood basalts") built plateaus such as the Deccan Traps in India, the Columbia Plateau in the US and the Paraná basalts in southern Brazil, which weather into deep red and black soils.',
      'Black sand beaches are ground-up basalt.',
    ],
    looks: ['Black lava fields with sparse plants, dark cliffs, hexagonal columns, black beaches, dark stone walls.'],
    where: 'Iceland, the Canary Islands, Hawaii, the Azores, Northern Ireland (Giant\'s Causeway), India\'s Deccan, the Columbia Plateau (US), southern Brazil, Ethiopia, Jordan\'s black desert (Harrat), Armenia (the Garni gorge columns).',
    countries: ['IS', 'ES', 'US', 'PT', 'GB', 'IN', 'BR', 'JO', 'ET', 'AM'],
    history: ['Legend says the Irish giant Finn McCool built the Giant\'s Causeway to walk to Scotland; the matching columns of Fingal\'s Cave on Staffa are the other end.', 'The Deccan Traps erupted around 66 million years ago; they may have contributed to the extinction of the dinosaurs alongside the asteroid impact.'],
    facts: ['About 70% of the Earth\'s surface (the ocean floor) is basalt.', 'The Deccan lava flows are up to 2 km thick in total.'],
    tips: ['Black lava fields with left-over lichen and moss: Iceland. With vineyards in black ash: Lanzarote (Canary Islands).', 'Black cotton soil in India and terra roxa in Brazil both come from basalt.'],
    remember: 'Basalt is cooled runny lava: black rock, black sand, and columns shaped like honeycomb.',
    related: [{ to: '/vegetation/black-cotton-soil', label: 'Black cotton soil' }],
    photoCategories: ['Columnar basalts', 'Lava fields in Iceland'],
  },
  {
    id: 'badlands', title: 'Why are some hills bare, striped and eroded? (badlands)', category: 'Landforms',
    summary: 'Bare, gullied hills with coloured stripes: soft rock in a dry climate, eroded by rare but violent rain.',
    science: [
      'Badlands form in soft sedimentary rock (clay, silt, volcanic ash) where there is too little rain for plants to hold the soil, but occasional heavy storms wash it away fast.',
      'The stripes are different layers: red and orange from iron oxides, grey and black from organic-rich clay or lignite (soft coal), white from ash or gypsum.',
    ],
    looks: ['Bare, steep, heavily gullied slopes and pinnacles, no vegetation, striped in red, grey, buff and white.'],
    where: 'The Dakotas (Badlands National Park, Theodore Roosevelt NP), Alberta (Drumheller), Utah, Argentina (Talampaya, Ischigualasto), Spain (Bardenas Reales, Tabernas), Italy (calanchi in Tuscany and Basilicata), Chile\'s Atacama.',
    countries: ['US', 'CA', 'AR', 'ES', 'IT', 'CL', 'CN', 'TR'],
    history: ['French-Canadian trappers called them "les mauvaises terres à traverser" (bad lands to cross); the Lakota name also means "bad land".', 'Badlands are great fossil beds because erosion constantly uncovers bones: Alberta\'s Dinosaur Provincial Park and Argentina\'s Ischigualasto hold some of the richest dinosaur finds.'],
    facts: ['Tabernas in Spain is Europe\'s only true desert and was the set for many "spaghetti Westerns".'],
    tips: ['Striped bare hills with prairie: the Dakotas or Alberta. With olive groves: southern Spain or Italy.'],
    remember: 'Badlands are soft rock with no plants to protect it: every storm carves new gullies.',
    photoCategories: ['Badlands National Park', 'Bardenas Reales'],
  },
  {
    id: 'loess', title: 'Why are some farmlands made of fine yellow dust? (loess)', category: 'Landforms',
    summary: 'Thick deposits of wind-blown silt that make the most fertile farmland on Earth, and steep, eroded yellow landscapes.',
    science: [
      'During the ice ages, glaciers ground rock into fine powder and cold, dry winds blew it across the plains, depositing thick layers of silt called loess (a German word, "loose").',
      'Loess is yellow-buff, very fertile, holds water well and stands in vertical cliffs, but erodes quickly into deep gullies when stripped of plants.',
    ],
    looks: ['Rolling fertile plains of wheat and maize; in China, yellow terraced hills and cave dwellings dug into cliffs.'],
    where: 'China\'s Loess Plateau (the thickest, up to 300 m), the US Midwest (Iowa\'s Loess Hills along the Missouri), Ukraine and southern Russia, the Danube plain (Hungary, Serbia), Argentina\'s Pampas, New Zealand.',
    countries: ['CN', 'US', 'UA', 'RU', 'HU', 'RS', 'AR', 'DE'],
    history: ['An estimated 30–40 million people in China still live in yaodong, cave homes dug into loess cliffs.', 'The Yellow River is yellow because it carries eroded loess: over a billion tonnes of silt a year.'],
    facts: ['Much of the world\'s best grain land (the Corn Belt, the Ukrainian steppe, the Pampas) sits on loess.'],
    tips: ['The loess under the black earth is why Ukraine and the Pampas look so flat and fertile.'],
    remember: 'Loess is ice-age dust: glaciers ground the rock, wind spread the flour, and farmers still eat from it.',
    related: [{ to: '/vegetation/black-earth', label: 'Black earth' }],
    photoCategories: ['Loess Plateau'],
  },
  {
    id: 'rift-valleys', title: 'Why is East Africa split by long valleys and lakes?', category: 'Landforms',
    summary: 'The East African Rift, where the continent is slowly tearing apart, creating long valleys, deep lakes and volcanoes.',
    science: [
      'Heat rising from the mantle stretches the crust until it cracks along faults; blocks drop down between them to form a rift valley with steep walls (escarpments) on each side.',
      'The rift fills with long, deep lakes (Tanganyika, Malawi) and is lined with volcanoes (Kilimanjaro, Kenya, Nyiragongo).',
      'In a few million years it may split off East Africa as a new plate, with the sea flooding in, as happened with the Red Sea.',
    ],
    looks: ['Steep escarpments dropping hundreds of metres to flat valley floors, long lakes, volcanic cones, soda lakes with flamingos.'],
    where: 'Ethiopia, Kenya, Uganda, Rwanda, Tanzania, Malawi, DR Congo; also the Jordan Valley and Dead Sea, Iceland (a rift on land), the Rhine Graben.',
    countries: ['ET', 'KE', 'UG', 'RW', 'TZ', 'MW', 'CD', 'JO', 'IL', 'IS'],
    history: ['Many of the most important early human fossils come from the rift: Lucy (Ethiopia, 3.2 million years), Olduvai Gorge (Tanzania), Turkana Boy (Kenya).'],
    facts: ['Lake Tanganyika is the second-deepest lake in the world (about 1,470 m).', 'The Dead Sea, in the northern end of the same rift system, is the lowest land on Earth (about 430 m below sea level).'],
    tips: ['A huge escarpment view with savanna below in Kenya: the Great Rift Valley (viewpoints on the Nairobi–Naivasha road).'],
    remember: 'The Rift is Africa\'s zipper coming undone: valleys, lakes and volcanoes along the seam.',
    photoCategories: ['Great Rift Valley in Kenya'],
  },
]

export const minerals: GeoTopic[] = [
  {
    id: 'copper', title: 'Copper', category: 'Mining',
    summary: 'The metal of electricity: mined mostly from huge open pits in the Andes.',
    uses: 'Electrical wiring, motors, electronics, plumbing; essential for electric cars and renewable energy.',
    producers: ['CL', 'CD', 'PE', 'CN', 'US', 'RU', 'ZM', 'MX', 'AU', 'KZ'],
    science: ['Most copper comes from porphyry deposits: magma under volcanoes releases hot, metal-rich fluids that spread copper minerals through the rock. That is why the richest belts follow old volcanic arcs (the Andes).', 'The ore contains less than 1% copper, so enormous amounts of rock are dug and crushed, leaving giant pits and tailings dams.'],
    looks: ['Terraced open pits kilometres wide, turquoise-green tailings ponds, mining towns in desert.'],
    where: 'Chile (Chuquicamata, Escondida in the Atacama), Peru (Cerro Verde, Antamina), DR Congo and Zambia (the Copperbelt), the US (Bingham Canyon, Utah; Arizona), Mexico (Sonora), Indonesia (Grasberg, Papua), Mongolia (Oyu Tolgoi).',
    countries: ['CL', 'PE', 'CD', 'ZM', 'US', 'MX', 'ID', 'MN', 'AU', 'RU', 'KZ', 'CN'],
    history: ['Copper was one of the first metals humans used (from about 9000 BC); mixed with tin it made bronze. Cyprus gave copper its name (Latin cuprum, "metal of Cyprus").', 'Chile\'s copper mines were nationalised in 1971; copper is still its biggest export.'],
    facts: ['Bingham Canyon in Utah is one of the largest human-made excavations, over 1 km deep and 4 km wide.', 'An electric car contains about four times as much copper as a petrol car.'],
    tips: ['Atacama desert with a vast terraced pit and trucks: northern Chile (Antofagasta region).'],
    remember: 'Copper is Chile\'s red gold: the Andes volcanoes cooked it, the Atacama keeps it.',
    photoCategories: ['Chuquicamata', 'Bingham Canyon Mine'],
  },
  {
    id: 'iron-ore', title: 'Iron ore', category: 'Mining',
    summary: 'The raw material of steel: mined in giant red pits in Australia\'s Pilbara and Brazil\'s Minas Gerais and Pará.',
    uses: 'Steel for buildings, cars, ships and railways (about 98% of iron ore goes into steel).',
    producers: ['AU', 'BR', 'CN', 'IN', 'RU', 'ZA', 'UA', 'CA', 'SE', 'KZ'],
    science: ['The biggest deposits are banded iron formations, laid down on the sea floor 2.5–1.8 billion years ago when the first oxygen made by bacteria reacted with dissolved iron and made it settle out as layers of iron oxide.', 'Red and black striped rock (hematite, magnetite and chert) is the evidence of Earth\'s first oxygen.'],
    looks: ['Deep red earth, red dust on everything, enormous stepped pits, very long ore trains.'],
    where: 'Australia (the Pilbara, Western Australia), Brazil (Minas Gerais "Iron Quadrangle"; Carajás in Pará, the world\'s largest), India (Odisha, Jharkhand, Chhattisgarh), Russia (the Kursk Magnetic Anomaly), Sweden (Kiruna), Canada (Labrador), South Africa (Sishen).',
    countries: ['AU', 'BR', 'IN', 'CN', 'RU', 'ZA', 'UA', 'CA', 'SE', 'KZ'],
    history: ['Minas Gerais ("general mines") was named for its gold and iron. Brazil\'s Vale began as a state company in 1942.', 'Kiruna in Sweden is being moved several kilometres because the mine is undermining the town.'],
    facts: ['Pilbara ore trains are among the longest in the world, up to 2.5 km.', 'The Kursk Magnetic Anomaly in Russia is so rich in iron that compasses go wrong there.'],
    tips: ['Red dust, spinifex and an ore train: the Pilbara, Western Australia. Red pits among green hills: Minas Gerais.'],
    remember: 'Iron ore is the rust of Earth\'s first breath: bacteria made oxygen, and the sea rusted into red layers.',
    related: [{ to: '/regions/AU/AU-WA', label: 'Western Australia' }, { to: '/regions/BR/BR-MG', label: 'Minas Gerais' }],
    photoCategories: ['Mount Tom Price mine', 'Brockman 4 mine', 'Carajás mine'],
  },
  {
    id: 'gold', title: 'Gold', category: 'Mining',
    summary: 'Mined from deep shafts in South Africa, giant pits in Australia and small-scale diggings across Africa and the Amazon.',
    uses: 'Jewellery, central bank reserves and investment, electronics.',
    producers: ['CN', 'RU', 'AU', 'CA', 'US', 'GH', 'PE', 'MX', 'KZ', 'UZ'],
    science: ['Gold is carried by hot fluids through cracks in rock and deposited in quartz veins. Erosion frees it into rivers, where it collects as placer gold (nuggets and flakes) because it is so heavy.', 'South Africa\'s Witwatersrand gold lies in ancient river gravels about 3 billion years old.'],
    looks: ['Headframes over deep shafts and pale mine dumps (South Africa), giant pits (Kalgoorlie\'s Super Pit), muddy river diggings with pumps (small-scale mining in Ghana, Peru, the Amazon).'],
    where: 'China, Russia (the Far East, Siberia), Australia (Kalgoorlie, Western Australia), Canada, the US (Nevada), Ghana, South Africa (Witwatersrand), Peru, Mexico, Uzbekistan (Muruntau).',
    countries: ['CN', 'RU', 'AU', 'CA', 'US', 'GH', 'PE', 'MX', 'KZ', 'UZ', 'ZA', 'BR', 'ID'],
    history: ['The 1886 Witwatersrand gold rush founded Johannesburg; the city\'s pale mine dumps were once its hills.', 'Gold rushes built California (1848), Victoria (1851), the Klondike (1896) and Kalgoorlie (1893).', 'Ghana was called the Gold Coast.'],
    facts: ['All the gold ever mined would fit in a cube about 22 m on each side.', 'South Africa\'s Mponeng mine goes down about 4 km, among the deepest mines on Earth.'],
    tips: ['Flat-topped pale mine dumps around a big city in South Africa: Johannesburg.'],
    remember: 'Gold is heavy enough to sink to the bottom of rivers, which is why prospectors pan for it.',
    photoCategories: ['Super Pit Gold Mine', 'Gold mining in Ghana'],
  },
  {
    id: 'coal', title: 'Coal', category: 'Mining',
    summary: 'Fossil plants turned to rock: mined in China, India, Indonesia, Australia, the US, Russia, South Africa and Poland.',
    uses: 'Electricity generation and steel making (coking coal).',
    producers: ['CN', 'IN', 'ID', 'US', 'AU', 'RU', 'ZA', 'KZ', 'DE', 'PL'],
    science: ['Coal formed from peat swamps, mostly 360–300 million years ago in the Carboniferous period, when vast forests of giant ferns and trees were buried before they could rot, then compressed and heated.', 'More heat and pressure turns soft brown lignite into black bituminous coal and then hard anthracite.'],
    looks: ['Open-cast strip mines with huge draglines, black spoil heaps, conveyor belts, coal trains, dust on roadsides; in the Appalachians, flattened mountaintops.'],
    where: 'China (Shanxi, Inner Mongolia), India (Jharkhand, Odisha, Chhattisgarh), Indonesia (East and South Kalimantan), Australia (Queensland\'s Bowen Basin, NSW\'s Hunter Valley), the US (Wyoming, West Virginia), Russia (Kuzbass), South Africa (Mpumalanga), Poland (Silesia), Germany (lignite, Rhineland).',
    countries: ['CN', 'IN', 'ID', 'US', 'AU', 'RU', 'ZA', 'KZ', 'DE', 'PL', 'CO', 'MN'],
    history: ['Coal powered the Industrial Revolution from Britain in the 1700s; Welsh, English and later German, Belgian and Polish coalfields shaped whole regions.', 'Germany\'s lignite mines have swallowed entire villages, which were moved elsewhere.'],
    facts: ['Kemerovo Oblast in Russia is called Kuzbass (Kuznetsk Basin), after its coal.', 'Wyoming\'s Powder River Basin mines are among the largest coal mines in the world.'],
    tips: ['Coal trucks and pits in hilly rainforest in Indonesia: Kalimantan.'],
    remember: 'Coal is buried ancient forest: 300-million-year-old swamps, pressed into black rock.',
    related: [{ to: '/regions/RU/RU-KEM', label: 'Kemerovo (Kuzbass)' }],
    photoCategories: ['Coal mines in Germany', 'Garzweiler surface mine'],
  },
  {
    id: 'lithium', title: 'Lithium', category: 'Mining',
    summary: 'The battery metal: pumped from salt flats in the "Lithium Triangle" of Chile, Argentina and Bolivia, and mined from rock in Australia.',
    uses: 'Rechargeable batteries (phones, electric cars), ceramics, glass.',
    producers: ['AU', 'CL', 'CN', 'AR', 'BR', 'ZW'],
    science: ['In the Andes, lithium dissolved from volcanic rocks collects in salty groundwater under salt flats (salares). Brine is pumped into huge ponds and evaporated by the sun, which turns them bright turquoise and yellow.', 'In Australia (Greenbushes, Pilbara) lithium is mined from a hard rock called spodumene pegmatite.'],
    looks: ['Grids of turquoise, green and yellow evaporation ponds on white salt flats, high in the Andes.'],
    where: 'Australia (Western Australia), Chile (Salar de Atacama), Argentina (Jujuy, Salta, Catamarca), Bolivia (Salar de Uyuni: huge reserves, little production), China, Zimbabwe.',
    countries: ['AU', 'CL', 'AR', 'BO', 'CN', 'ZW', 'BR'],
    history: ['Lithium was discovered in 1817 in Sweden; its demand exploded only with lithium-ion batteries (commercialised in 1991).'],
    facts: ['Salar de Uyuni in Bolivia is the largest salt flat on Earth, so flat it is used to calibrate satellites.', 'Making lithium from brine uses a lot of water in one of the driest places on Earth, a major local concern.'],
    tips: ['Coloured ponds on a salt flat in the Andes: the Atacama (Chile) or Jujuy/Salta (Argentina).'],
    remember: 'Lithium is evaporated from Andean salt flats in rainbow-coloured ponds.',
    photoCategories: ['Salar de Atacama', 'Salinas Grandes'],
  },
  {
    id: 'cobalt', title: 'Cobalt', category: 'Mining',
    summary: 'About three quarters of the world\'s cobalt comes from one place: the Copperbelt of southern DR Congo.',
    uses: 'Battery cathodes, superalloys for jet engines, blue pigment.',
    producers: ['CD', 'ID', 'RU', 'AU', 'PH', 'CU'],
    science: ['Cobalt is mostly a by-product of copper (in the Congo) and nickel (in Indonesia and elsewhere) mining.'],
    looks: ['Open pits and artisanal hand-dug mines around Kolwezi and Lubumbashi.'],
    where: 'DR Congo (Katanga: Kolwezi, Lubumbashi), Indonesia (Sulawesi, with nickel), Russia, Australia, the Philippines, Cuba.',
    countries: ['CD', 'ID', 'RU', 'AU', 'PH', 'CU'],
    history: ['The name comes from the German "Kobold" (goblin): miners blamed goblins for ores that looked valuable but gave off poisonous arsenic fumes when smelted.', 'Cobalt blue has coloured Chinese porcelain and Persian tiles for centuries.'],
    facts: ['Child labour in informal Congolese cobalt mines has made it one of the most scrutinised minerals in the world.'],
    tips: ['Not on Street View (DR Congo is uncovered).'],
    remember: 'Cobalt is named after goblins, and most of it comes from one corner of Congo.',
    related: [{ to: '/uncovered/dr-congo', label: 'DR Congo guide' }],
    photoCategories: ['Kolwezi Mine', 'Kamoto East Open Cut'],
  },
  {
    id: 'bauxite', title: 'Bauxite (aluminium)', category: 'Mining',
    summary: 'The ore of aluminium: a red tropical soil mined in Australia, Guinea, China and Brazil.',
    uses: 'Aluminium for cans, aircraft, cars, window frames and cables.',
    producers: ['AU', 'GN', 'CN', 'BR', 'IN', 'ID', 'JM'],
    science: ['Bauxite is an extreme laterite: tropical weathering over millions of years has washed out almost everything except aluminium hydroxides and iron oxides.', 'It is dug from shallow pits just below the surface; turning it into aluminium takes enormous amounts of electricity, so smelters are built near cheap hydropower.'],
    looks: ['Red, flat strip mines in tropical forest or savanna; red dust; bauxite railways and ports.'],
    where: 'Australia (Weipa in Queensland, Western Australia\'s Darling Range), Guinea (Boké), China, Brazil (Pará), India (Odisha), Indonesia (Kalimantan, Bintan), Jamaica.',
    countries: ['AU', 'GN', 'CN', 'BR', 'IN', 'ID', 'JM', 'MY'],
    history: ['Named after Les Baux-de-Provence in France, where it was first identified in 1821.', 'Aluminium was more precious than gold until the Hall–Héroult electrolysis process (1886) made it cheap; Napoleon III reportedly served honoured guests on aluminium plates.'],
    facts: ['Guinea has the largest bauxite reserves in the world.'],
    tips: ['Red strip mines in tropical Queensland or Pará: bauxite.'],
    remember: 'Bauxite is a laterite soil so weathered that only aluminium is left: aluminium is squeezed out of red dirt with electricity.',
    related: [{ to: '/vegetation/red-tropical-soil', label: 'Red tropical soil (laterite)' }],
    photoCategories: ['Mining in Weipa', 'Huntly Mine'],
  },
  {
    id: 'diamonds', title: 'Diamonds', category: 'Mining',
    summary: 'Carbon crushed deep in the mantle and blasted up in volcanic pipes: mined in Russia, Botswana, Canada, DR Congo, South Africa and Angola.',
    uses: 'Jewellery; industrial cutting and drilling (mostly synthetic diamonds today).',
    producers: ['RU', 'BW', 'CA', 'CD', 'AU', 'AO', 'ZA', 'NA'],
    science: ['Diamonds form 150–200 km down in the mantle under old, thick continents. Rare, fast eruptions of kimberlite magma carried them to the surface in carrot-shaped "pipes".', 'Erosion washes some diamonds into rivers and out to sea, so Namibia also mines them from the sea floor.'],
    looks: ['Huge round open pits (the Big Hole at Kimberley, Mir mine in Yakutia), fenced mining towns.'],
    where: 'Russia (Yakutia: Mirny, Udachny), Botswana (Jwaneng, Orapa), Canada (Northwest Territories), DR Congo (Kasai), Australia, Angola, South Africa (Kimberley), Namibia (marine).',
    countries: ['RU', 'BW', 'CA', 'CD', 'AU', 'AO', 'ZA', 'NA', 'SL'],
    history: ['The Kimberley diamond rush (1871) in South Africa produced the "Big Hole", dug largely by hand, and led to the founding of De Beers.', 'Diamonds turned Botswana from one of the poorest countries at independence (1966) into a middle-income one.'],
    facts: ['The Mir mine in Mirny (Russia) is about 525 m deep and 1.2 km wide; helicopters are reportedly banned from flying over it because of the downdrafts.'],
    tips: ['A giant round pit next to a town in Yakutia: Mirny.'],
    remember: 'Diamonds ride up from the mantle in volcanic "carrots": kimberlite pipes.',
    related: [{ to: '/regions/RU/RU-SA', label: 'Sakha (Yakutia)' }],
    photoCategories: ['Mir mine', 'Big Hole mine'],
  },
  {
    id: 'oil-gas', title: 'Oil and natural gas', category: 'Mining',
    summary: 'Ancient sea life cooked underground: the energy that shapes the landscapes of Texas, the Gulf, Siberia and the Caspian.',
    uses: 'Fuels (petrol, diesel, jet fuel, heating, electricity), plastics and chemicals.',
    producers: ['US', 'SA', 'RU', 'CA', 'IQ', 'CN', 'AE', 'BR', 'IR', 'KW'],
    science: ['Oil and gas form from tiny marine plankton buried in mud; heated to about 60–150 °C over millions of years, the organic matter turns into petroleum and gas, which rise until trapped under impermeable rock (often in folds or salt domes).', 'Modern fracking cracks tight shale rock with high-pressure water to release oil and gas (Texas, North Dakota).'],
    looks: ['Nodding pumpjacks in fields, drilling rigs, flares, pipelines, refineries, tank farms.'],
    where: 'The US (Texas Permian Basin, North Dakota), Saudi Arabia, Russia (western Siberia: Khanty-Mansi, Yamal), Canada (Alberta oil sands), Iraq, the UAE, Brazil (offshore), Venezuela (largest reserves), Kazakhstan, Azerbaijan, Nigeria.',
    countries: ['US', 'SA', 'RU', 'CA', 'IQ', 'CN', 'AE', 'BR', 'IR', 'KW', 'VE', 'KZ', 'AZ', 'NG', 'NO'],
    history: ['The first commercial oil wells were in Baku (1846) and Pennsylvania (1859). Around 1900 Baku produced about half the world\'s oil.', 'Oil discoveries in the 1930s transformed Saudi Arabia, Kuwait and the Gulf.'],
    facts: ['Alberta\'s oil sands cover an area about the size of England.', 'Venezuela has the largest proven oil reserves on Earth, much of it heavy oil in the Orinoco belt.'],
    tips: ['Pumpjacks in flat, dry country: West Texas, New Mexico, North Dakota, Alberta or Argentina (Neuquén\'s Vaca Muerta).'],
    remember: 'Oil is plankton pressure-cooked for millions of years and trapped under a rock lid.',
    related: [{ to: '/uncovered/azerbaijan', label: 'Azerbaijan: land of fire' }],
    photoCategories: ['Pumpjacks', 'Oil sands'],
  },
  {
    id: 'nickel', title: 'Nickel', category: 'Mining',
    summary: 'Now dominated by Indonesia: red laterite mines on Sulawesi and Halmahera; also Russia\'s Arctic Norilsk and New Caledonia.',
    uses: 'Stainless steel and electric-car batteries.',
    producers: ['ID', 'PH', 'RU', 'CA', 'AU', 'NC', 'CN'],
    science: ['Most nickel now comes from laterites: tropical weathering of iron- and magnesium-rich rock (from old ocean crust) concentrates nickel in red soil.', 'Norilsk in Russia mines sulphide ores from a huge ancient lava province (the Siberian Traps).'],
    looks: ['Red scars on green hills, red rivers and bays from runoff (Sulawesi, Halmahera), smelters.'],
    where: 'Indonesia (Sulawesi: Sorowako in South Sulawesi, Southeast and Central Sulawesi; North Maluku), the Philippines (Mindanao, Palawan), Russia (Norilsk, Kola), Canada (Sudbury, Ontario), Australia, New Caledonia.',
    countries: ['ID', 'PH', 'RU', 'CA', 'AU', 'CN'],
    history: ['Sudbury\'s nickel lies in the crater of a meteorite impact about 1.85 billion years old.', 'Norilsk was built by Gulag prisoners in the 1930s–50s; it is one of the most polluted and coldest cities in the world.'],
    facts: ['Indonesia banned raw nickel ore exports in 2020 to force smelting at home, and now produces about half the world\'s nickel.'],
    tips: ['Red mining scars on Sulawesi hills: Southeast or Central Sulawesi (nickel).'],
    remember: 'Nickel today means red Indonesian hills: the ore is a laterite soil.',
    related: [{ to: '/regions/ID/ID-SG', label: 'Southeast Sulawesi' }],
    photoCategories: ['Nickel mining in Indonesia', 'Norilsk'],
  },
  {
    id: 'silver-tin', title: 'Silver and tin', category: 'Mining',
    summary: 'The metals that built colonial Mexico, Peru and Bolivia; tin also from Indonesia\'s Bangka and Belitung islands.',
    uses: 'Silver: electronics, solar panels, jewellery, photography. Tin: solder in electronics, tin-plate cans, bronze.',
    producers: ['MX', 'PE', 'CN', 'BO', 'CL', 'RU', 'ID', 'MM'],
    science: ['Silver and tin ores form in hot-fluid veins around magma bodies in mountain belts like the Andes and the Sierra Madre.', 'Tin also collects in river and sea-floor gravels as cassiterite, dredged in Indonesia.'],
    looks: ['Colonial mining towns with baroque churches (Zacatecas, Guanajuato, Potosí); tin-mining pits and lakes on Bangka and Belitung.'],
    where: 'Mexico (Zacatecas, Chihuahua, Durango), Peru, Bolivia (Potosí, Oruro), China; tin: China, Indonesia (Bangka Belitung), Myanmar, Peru, Bolivia.',
    countries: ['MX', 'PE', 'BO', 'CN', 'CL', 'ID', 'MM', 'MY'],
    history: ['Potosí\'s Cerro Rico in Bolivia supplied much of the world\'s silver in the 1500s–1600s, making the city one of the largest in the world; millions of Indigenous workers were forced to work its mines (the mita).', 'Spanish silver (the "piece of eight") became the first global currency, traded as far as China.'],
    facts: ['"Vale un Potosí" ("worth a Potosí") became a Spanish phrase for something immensely valuable.', 'Mexico is the world\'s largest silver producer.'],
    tips: ['Pink-stone colonial towns in dry Mexican hills: Zacatecas or Guanajuato. Tin-pit lakes and white sand: Bangka Belitung.'],
    remember: 'Silver built the Spanish Empire: Potosí and Zacatecas paid for it.',
    related: [{ to: '/regions/MX/MX-ZAC', label: 'Zacatecas' }, { to: '/regions/ID/ID-BB', label: 'Bangka Belitung' }],
    photoCategories: ['Cerro Rico', 'Tin mining in Indonesia'],
  },
  {
    id: 'potash-phosphate-salt', title: 'Potash, phosphate and salt', category: 'Mining',
    summary: 'Minerals that feed crops and people: potash from Canada and Russia, phosphate from Morocco, salt from ancient seas.',
    uses: 'Fertilisers (potassium, phosphorus), table salt, road salt, chemicals.',
    producers: ['CA', 'RU', 'BY', 'CN', 'MA', 'US', 'JO', 'DE'],
    science: ['Potash and rock salt are evaporites: layers left when ancient seas dried up, hundreds of millions of years ago, now buried deep underground.', 'Phosphate rock comes from sea-floor sediments rich in the remains of marine life.'],
    looks: ['Tall headframes and white or reddish tailings piles on the prairie (Saskatchewan), salt pans and salt mountains, phosphate conveyor belts in desert.'],
    where: 'Potash: Canada (Saskatchewan), Russia (Perm Krai), Belarus, Germany. Phosphate: Morocco and Western Sahara (about 70% of known reserves), China, the US (Florida), Jordan. Salt: everywhere, e.g. Wieliczka (Poland), Khewra (Pakistan).',
    countries: ['CA', 'RU', 'BY', 'DE', 'MA', 'CN', 'US', 'JO', 'PL', 'PK'],
    history: ['Salt was so valuable that it was used as currency; the word "salary" is often linked to Roman soldiers\' salt allowances.', 'Wieliczka salt mine in Poland was worked for over 700 years and has chapels carved from salt.'],
    facts: ['Canada has about a third of the world\'s potash reserves, almost all of it in Saskatchewan.', 'The Bou Craa phosphate conveyor in Western Sahara, about 100 km long, is one of the longest in the world.'],
    tips: ['White or pink spoil heaps on flat prairie with grain fields: a potash mine in Saskatchewan.'],
    remember: 'Dried-up ancient seas still feed us: potash, salt and phosphate for fields and tables.',
    photoCategories: ['Wieliczka salt mine', 'Potash mines'],
  },
]
