// Countries referenced by language regions, with GeoGuessr (Google Street View) coverage.
// 'yes' = official car coverage; 'partial' = limited, trekker-only or unofficial; 'none' = none.
// Coverage changes over time; verify against a current coverage map when in doubt.

export type Coverage = 'yes' | 'partial' | 'none'

export const countries: Record<string, { name: string; coverage: Coverage }> = {
  AD: { name: 'Andorra', coverage: 'yes' },
  AL: { name: 'Albania', coverage: 'yes' },
  AR: { name: 'Argentina', coverage: 'yes' },
  AT: { name: 'Austria', coverage: 'yes' },
  AU: { name: 'Australia', coverage: 'yes' },
  AX: { name: 'Åland (Finland)', coverage: 'yes' },
  BA: { name: 'Bosnia and Herzegovina', coverage: 'partial' },
  BE: { name: 'Belgium', coverage: 'yes' },
  BG: { name: 'Bulgaria', coverage: 'yes' },
  BO: { name: 'Bolivia', coverage: 'yes' },
  BR: { name: 'Brazil', coverage: 'yes' },
  CA: { name: 'Canada', coverage: 'yes' },
  CH: { name: 'Switzerland', coverage: 'yes' },
  CL: { name: 'Chile', coverage: 'yes' },
  CO: { name: 'Colombia', coverage: 'yes' },
  CY: { name: 'Cyprus', coverage: 'partial' },
  CZ: { name: 'Czechia', coverage: 'yes' },
  DE: { name: 'Germany', coverage: 'yes' },
  DK: { name: 'Denmark', coverage: 'yes' },
  EC: { name: 'Ecuador', coverage: 'yes' },
  EE: { name: 'Estonia', coverage: 'yes' },
  ES: { name: 'Spain', coverage: 'yes' },
  FI: { name: 'Finland', coverage: 'yes' },
  FO: { name: 'Faroe Islands', coverage: 'yes' },
  FR: { name: 'France', coverage: 'yes' },
  GB: { name: 'United Kingdom', coverage: 'yes' },
  GL: { name: 'Greenland', coverage: 'yes' },
  GR: { name: 'Greece', coverage: 'yes' },
  GT: { name: 'Guatemala', coverage: 'yes' },
  HR: { name: 'Croatia', coverage: 'yes' },
  HU: { name: 'Hungary', coverage: 'yes' },
  IE: { name: 'Ireland', coverage: 'yes' },
  IN: { name: 'India', coverage: 'partial' },
  IS: { name: 'Iceland', coverage: 'yes' },
  IT: { name: 'Italy', coverage: 'yes' },
  KE: { name: 'Kenya', coverage: 'yes' },
  LI: { name: 'Liechtenstein', coverage: 'partial' },
  LT: { name: 'Lithuania', coverage: 'yes' },
  LU: { name: 'Luxembourg', coverage: 'yes' },
  LV: { name: 'Latvia', coverage: 'yes' },
  MC: { name: 'Monaco', coverage: 'yes' },
  MD: { name: 'Moldova', coverage: 'none' },
  ME: { name: 'Montenegro', coverage: 'yes' },
  MK: { name: 'North Macedonia', coverage: 'yes' },
  MT: { name: 'Malta', coverage: 'yes' },
  MX: { name: 'Mexico', coverage: 'yes' },
  NA: { name: 'Namibia', coverage: 'none' },
  NG: { name: 'Nigeria', coverage: 'partial' },
  NL: { name: 'Netherlands', coverage: 'yes' },
  NO: { name: 'Norway', coverage: 'yes' },
  NZ: { name: 'New Zealand', coverage: 'yes' },
  PE: { name: 'Peru', coverage: 'yes' },
  PH: { name: 'Philippines', coverage: 'yes' },
  PL: { name: 'Poland', coverage: 'yes' },
  PT: { name: 'Portugal', coverage: 'yes' },
  PY: { name: 'Paraguay', coverage: 'partial' },
  RO: { name: 'Romania', coverage: 'yes' },
  RS: { name: 'Serbia', coverage: 'yes' },
  RU: { name: 'Russia', coverage: 'yes' },
  SE: { name: 'Sweden', coverage: 'yes' },
  SG: { name: 'Singapore', coverage: 'yes' },
  SI: { name: 'Slovenia', coverage: 'yes' },
  SK: { name: 'Slovakia', coverage: 'yes' },
  SM: { name: 'San Marino', coverage: 'yes' },
  SR: { name: 'Suriname', coverage: 'none' },
  TR: { name: 'Turkey', coverage: 'yes' },
  UA: { name: 'Ukraine', coverage: 'yes' },
  US: { name: 'United States', coverage: 'yes' },
  UY: { name: 'Uruguay', coverage: 'yes' },
  VA: { name: 'Vatican City', coverage: 'partial' },
  XK: { name: 'Kosovo', coverage: 'none' },
  ZA: { name: 'South Africa', coverage: 'yes' },
  AO: { name: 'Angola', coverage: 'none' },
  MZ: { name: 'Mozambique', coverage: 'none' },
  CV: { name: 'Cape Verde', coverage: 'none' },
  AW: { name: 'Aruba', coverage: 'none' },
  CW: { name: 'Curaçao', coverage: 'yes' },
  SN: { name: 'Senegal', coverage: 'yes' },
  CD: { name: 'DR Congo', coverage: 'none' },
  IM: { name: 'Isle of Man', coverage: 'yes' },
}
