// Countries referenced by language regions, with GeoGuessr (Google Street View) coverage.
// 'yes' = official car coverage; 'partial' = limited, trekker-only or unofficial; 'none' = none.
// Coverage changes over time; verify against a current coverage map when in doubt.

export type Coverage = 'yes' | 'partial' | 'none'

export const countries: Record<string, { name: string; coverage: Coverage }> = {
  AD: { name: 'Andorra', coverage: 'yes' },
  AL: { name: 'Albania', coverage: 'yes' },
  AR: { name: 'Argentina', coverage: 'yes' },
  AT: { name: 'Austria', coverage: 'yes' },
  AU: { name: 'Australia', coverage: 'yes' },
  AX: { name: 'Åland (Finland)', coverage: 'yes' },
  BA: { name: 'Bosnia and Herzegovina', coverage: 'partial' },
  BE: { name: 'Belgium', coverage: 'yes' },
  BG: { name: 'Bulgaria', coverage: 'yes' },
  BO: { name: 'Bolivia', coverage: 'yes' },
  BR: { name: 'Brazil', coverage: 'yes' },
  CA: { name: 'Canada', coverage: 'yes' },
  CH: { name: 'Switzerland', coverage: 'yes' },
  CL: { name: 'Chile', coverage: 'yes' },
  CO: { name: 'Colombia', coverage: 'yes' },
  CY: { name: 'Cyprus', coverage: 'partial' },
  CZ: { name: 'Czechia', coverage: 'yes' },
  DE: { name: 'Germany', coverage: 'yes' },
  DK: { name: 'Denmark', coverage: 'yes' },
  EC: { name: 'Ecuador', coverage: 'yes' },
  EE: { name: 'Estonia', coverage: 'yes' },
  ES: { name: 'Spain', coverage: 'yes' },
  FI: { name: 'Finland', coverage: 'yes' },
  FO: { name: 'Faroe Islands', coverage: 'yes' },
  FR: { name: 'France', coverage: 'yes' },
  GB: { name: 'United Kingdom', coverage: 'yes' },
  GL: { name: 'Greenland', coverage: 'yes' },
  GR: { name: 'Greece', coverage: 'yes' },
  GT: { name: 'Guatemala', coverage: 'yes' },
  HR: { name: 'Croatia', coverage: 'yes' },
  HU: { name: 'Hungary', coverage: 'yes' },
  IE: { name: 'Ireland', coverage: 'yes' },
  IN: { name: 'India', coverage: 'yes' },
  IS: { name: 'Iceland', coverage: 'yes' },
  IT: { name: 'Italy', coverage: 'yes' },
  KE: { name: 'Kenya', coverage: 'yes' },
  LI: { name: 'Liechtenstein', coverage: 'partial' },
  LT: { name: 'Lithuania', coverage: 'yes' },
  LU: { name: 'Luxembourg', coverage: 'yes' },
  LV: { name: 'Latvia', coverage: 'yes' },
  MC: { name: 'Monaco', coverage: 'yes' },
  MD: { name: 'Moldova', coverage: 'none' },
  ME: { name: 'Montenegro', coverage: 'yes' },
  MK: { name: 'North Macedonia', coverage: 'yes' },
  MT: { name: 'Malta', coverage: 'yes' },
  MX: { name: 'Mexico', coverage: 'yes' },
  NA: { name: 'Namibia', coverage: 'none' },
  NG: { name: 'Nigeria', coverage: 'yes' },
  NL: { name: 'Netherlands', coverage: 'yes' },
  NO: { name: 'Norway', coverage: 'yes' },
  NZ: { name: 'New Zealand', coverage: 'yes' },
  PE: { name: 'Peru', coverage: 'yes' },
  PH: { name: 'Philippines', coverage: 'yes' },
  PL: { name: 'Poland', coverage: 'yes' },
  PT: { name: 'Portugal', coverage: 'yes' },
  PY: { name: 'Paraguay', coverage: 'yes' },
  RO: { name: 'Romania', coverage: 'yes' },
  RS: { name: 'Serbia', coverage: 'yes' },
  RU: { name: 'Russia', coverage: 'yes' },
  SE: { name: 'Sweden', coverage: 'yes' },
  SG: { name: 'Singapore', coverage: 'yes' },
  SI: { name: 'Slovenia', coverage: 'yes' },
  SK: { name: 'Slovakia', coverage: 'yes' },
  SM: { name: 'San Marino', coverage: 'yes' },
  SR: { name: 'Suriname', coverage: 'none' },
  TR: { name: 'Turkey', coverage: 'yes' },
  UA: { name: 'Ukraine', coverage: 'yes' },
  US: { name: 'United States', coverage: 'yes' },
  UY: { name: 'Uruguay', coverage: 'yes' },
  VA: { name: 'Vatican City', coverage: 'partial' },
  XK: { name: 'Kosovo', coverage: 'none' },
  ZA: { name: 'South Africa', coverage: 'yes' },
  AO: { name: 'Angola', coverage: 'none' },
  MZ: { name: 'Mozambique', coverage: 'none' },
  CV: { name: 'Cape Verde', coverage: 'none' },
  AW: { name: 'Aruba', coverage: 'none' },
  CW: { name: 'Curaçao', coverage: 'yes' },
  SN: { name: 'Senegal', coverage: 'yes' },
  CD: { name: 'DR Congo', coverage: 'none' },
  IM: { name: 'Isle of Man', coverage: 'yes' },
  // Asia
  AE: { name: 'United Arab Emirates', coverage: 'yes' },
  AF: { name: 'Afghanistan', coverage: 'none' },
  AM: { name: 'Armenia', coverage: 'partial' },
  AZ: { name: 'Azerbaijan', coverage: 'partial' },
  BD: { name: 'Bangladesh', coverage: 'yes' },
  BH: { name: 'Bahrain', coverage: 'none' },
  BN: { name: 'Brunei', coverage: 'none' },
  BT: { name: 'Bhutan', coverage: 'yes' },
  BY: { name: 'Belarus', coverage: 'none' },
  CN: { name: 'China', coverage: 'partial' },
  GE: { name: 'Georgia', coverage: 'partial' },
  HK: { name: 'Hong Kong', coverage: 'yes' },
  ID: { name: 'Indonesia', coverage: 'yes' },
  IL: { name: 'Israel', coverage: 'yes' },
  IQ: { name: 'Iraq', coverage: 'partial' },
  IR: { name: 'Iran', coverage: 'none' },
  JO: { name: 'Jordan', coverage: 'yes' },
  JP: { name: 'Japan', coverage: 'yes' },
  KG: { name: 'Kyrgyzstan', coverage: 'yes' },
  KH: { name: 'Cambodia', coverage: 'yes' },
  KP: { name: 'North Korea', coverage: 'none' },
  KR: { name: 'South Korea', coverage: 'yes' },
  KZ: { name: 'Kazakhstan', coverage: 'yes' },
  LA: { name: 'Laos', coverage: 'yes' },
  LB: { name: 'Lebanon', coverage: 'partial' },
  LK: { name: 'Sri Lanka', coverage: 'yes' },
  MM: { name: 'Myanmar', coverage: 'none' },
  MN: { name: 'Mongolia', coverage: 'yes' },
  MO: { name: 'Macau', coverage: 'yes' },
  MV: { name: 'Maldives', coverage: 'partial' },
  MY: { name: 'Malaysia', coverage: 'yes' },
  NP: { name: 'Nepal', coverage: 'partial' },
  OM: { name: 'Oman', coverage: 'partial' },
  PK: { name: 'Pakistan', coverage: 'partial' },
  PS: { name: 'Palestine', coverage: 'partial' },
  QA: { name: 'Qatar', coverage: 'yes' },
  SA: { name: 'Saudi Arabia', coverage: 'partial' },
  TH: { name: 'Thailand', coverage: 'yes' },
  TJ: { name: 'Tajikistan', coverage: 'none' },
  TM: { name: 'Turkmenistan', coverage: 'none' },
  TW: { name: 'Taiwan', coverage: 'yes' },
  UZ: { name: 'Uzbekistan', coverage: 'partial' },
  VN: { name: 'Vietnam', coverage: 'partial' },
  // Africa
  BW: { name: 'Botswana', coverage: 'yes' },
  DZ: { name: 'Algeria', coverage: 'none' },
  EG: { name: 'Egypt', coverage: 'partial' },
  ER: { name: 'Eritrea', coverage: 'none' },
  ET: { name: 'Ethiopia', coverage: 'none' },
  GH: { name: 'Ghana', coverage: 'yes' },
  LS: { name: 'Lesotho', coverage: 'yes' },
  MA: { name: 'Morocco', coverage: 'partial' },
  MG: { name: 'Madagascar', coverage: 'yes' },
  NE: { name: 'Niger', coverage: 'none' },
  RW: { name: 'Rwanda', coverage: 'yes' },
  RE: { name: 'Réunion (France)', coverage: 'yes' },
  SZ: { name: 'Eswatini', coverage: 'yes' },
  TN: { name: 'Tunisia', coverage: 'yes' },
  TZ: { name: 'Tanzania', coverage: 'partial' },
  UG: { name: 'Uganda', coverage: 'yes' },
  ZW: { name: 'Zimbabwe', coverage: 'none' },
  GM: { name: 'Gambia', coverage: 'none' },
  // Americas and Pacific
  PR: { name: 'Puerto Rico', coverage: 'yes' },
  CR: { name: 'Costa Rica', coverage: 'yes' },
  CU: { name: 'Cuba', coverage: 'partial' },
  DO: { name: 'Dominican Republic', coverage: 'yes' },
  SY: { name: 'Syria', coverage: 'none' },
  GA: { name: 'Gabon', coverage: 'none' },
  WS: { name: 'Samoa', coverage: 'partial' },
  TO: { name: 'Tonga', coverage: 'partial' },
  AS: { name: 'American Samoa', coverage: 'yes' },
  VE: { name: 'Venezuela', coverage: 'partial' },
  SD: { name: 'Sudan', coverage: 'none' },
  SS: { name: 'South Sudan', coverage: 'none' },
  CG: { name: 'Republic of the Congo', coverage: 'none' },
  CF: { name: 'Central African Republic', coverage: 'none' },
  GN: { name: 'Guinea', coverage: 'none' },
  ML: { name: 'Mali', coverage: 'partial' },
  BJ: { name: 'Benin', coverage: 'none' },
  ZM: { name: 'Zambia', coverage: 'partial' },
  PA: { name: 'Panama', coverage: 'yes' },
  SV: { name: 'El Salvador', coverage: 'none' },
  HN: { name: 'Honduras', coverage: 'none' },
  NI: { name: 'Nicaragua', coverage: 'none' },
  LY: { name: 'Libya', coverage: 'none' },
  PG: { name: 'Papua New Guinea', coverage: 'partial' },
  FJ: { name: 'Fiji', coverage: 'partial' },
  SB: { name: 'Solomon Islands', coverage: 'none' },
  VU: { name: 'Vanuatu', coverage: 'partial' },
}
