// Memory hooks: metaphors, mnemonics and silly images that make a clue stick.
// Shown in a "Remember it" box on each page and in quiz feedback. Keep each hook short and
// tied to something you actually see on a sign.

export const scriptRemember: Record<string, string[]> = {
  latin: ['Latin is the uniform everyone wears; look at the badges (ő, ř, ł, ß) to tell the regiments apart.'],
  cyrillic: ['Cyrillic is Latin in a funhouse mirror: И and Я are backwards N and R, and P, H, C, B are traps (r, n, s, v).'],
  greek: ['Greek is maths class on a road sign: π, Σ, Δ, λ. And every word wears an accent hat (ά, έ).'],
  armenian: ['Armenian is a row of horseshoes and hooks: n, u, h shapes like a mountain range of little arches (Ararat!).'],
  georgian: ['Georgian looks like bubbles rising in a glass of Georgian mineral water: round, no capitals.'],
  hebrew: ['Hebrew is built from square Lego blocks that never touch.'],
  arabic: ['Arabic is joined-up handwriting with sprinkles: letters hold hands and dots sit above and below.'],
  thaana: ['Thaana looks like someone sprinkled commas above every letter: each letter gets a slanted little tick.'],
  ethiopic: ['Ge\'ez letters are little stools and tables with legs; the vowel is a tiny foot or ring on the leg.'],
  tifinagh: ['Tifinagh looks like a geometry homework sheet: circles, crosses and lines. ⵣ is the stick-figure mascot of the Amazigh.'],
  devanagari: ['Devanagari is washing hung on a line: every letter hangs from one long bar.'],
  bengali: ['Bengali is Devanagari with sharpened elbows: the letters hang from a line but have pointy triangles.'],
  gurmukhi: ['Gurmukhi is Devanagari drawn with a ruler: simpler, boxier letters hanging from the line.'],
  gujarati: ['Gujarati took its hat off: Devanagari without the top line.'],
  odia: ['Odia letters carry umbrellas: every letter has a round dome on top (palm leaves hate straight lines).'],
  tamil: ['Tamil is angular and tidy, like letters bent from wire, with curly tails trailing right.'],
  telugu: ['Telugu letters wear a tick ✓ on their heads, as if marked correct.'],
  kannada: ['Kannada letters wear flat caps; Telugu letters wear ticks. Caps = Karnataka.'],
  malayalam: ['Malayalam is a string of soap bubbles: all round, all connected, very long words.'],
  sinhala: ['Sinhala letters are snails and curls: every letter has a spiral on top.'],
  tibetan: ['Tibetan puts a dot after every syllable, like a prayer flag string with knots between the flags.'],
  thai: ['Thai letters start with a little loop, like a pen that always begins with a knot.'],
  lao: ['Lao is Thai with the loops ironed flat: rounder, simpler, fewer letters.'],
  khmer: ['Khmer letters wear little hats and carry luggage underneath (letters stacked below).'],
  myanmar: ['Burmese is made of circles: rings and bubbles, like a chain of hoops.'],
  hangul: ['Korean is circles and sticks packed into square boxes: see ㅇ in a block = Korea.'],
  japanese: ['Japanese is kanji "rocks" with kana "pebbles" between them. Spot の (a little swirl) and you know it\'s Japan.'],
  han: ['Chinese is only rocks, no pebbles: dense blocks everywhere. Traditional characters are the heavier rocks (門 vs 门).'],
  mongolian: ['Traditional Mongolian hangs down like a necklace: vertical lines of letters on a string.'],
}

export const groupRemember: Record<string, string[]> = {
  'central-europe': ['Hungarian ő ű has "double ticks": twice as surprised. Czech ř is a buzzing bee (Dvořák). Polish ł is a crossed-out L that says "w". Slovak ä and ô are the only Slavic umlaut and hat.'],
  'ex-yugoslav': ['Same language, different flags: letters won\'t help, words will. Croatian says "ljekarna" and "kolodvor", Serbia says "apoteka" and "stanica".'],
  'baltic-finnic': ['Lithuanian vowels have tails (ą ę į ų): they\'re dragging luggage. Latvian vowels wear a flat roof (ā ē ī ū). Estonian has the õ with a wavy "wig".'],
  'nordic': ['Swedes dot, Danes and Norwegians slash: ä ö vs æ ø. Icelandic has the þ "thorn" that pricks.'],
  'iberian': ['ñ = Spain, ã = Portugal, l·l = Catalonia (the dot in the middle), tx/tz = Basque, x everywhere = Galicia.'],
  'other-romance': ['Romanian ș ț wear a comma underneath like a tiny beard; French wears hats (â ê ô); Italian only accents the last letter.'],
  'west-germanic': ['German has the ß "snake"; Dutch doubles its vowels and loves "ij"; Afrikaans says "die" for "the".'],
  'celtic': ['Welsh uses w and y as vowels (cwm, bryn) and doubles ll and dd. Irish accents lean right (á), Scottish Gaelic accents lean left (à).'],
  'turkic-latin': ['Turkish ı has no dot, like a candle with its flame blown out. Azerbaijani ə is an "e" doing a handstand.'],
  'cyrillic': ['Each Cyrillic language has a signature letter: Ukraine ї (two eyes), Belarus ў (a smile), Kazakhstan ә and ұ, Serbia ђ ћ, Macedonia ѓ ќ.'],
  'maritime-sea': ['Indonesia borrowed from the Dutch (polisi, stasiun), Malaysia from the English (polis, stesen).'],
  'mainland-sea': ['Thai loops, Lao is Thai ironed flat, Khmer wears hats, Burmese is all circles, Vietnamese is Latin with stacked accents.'],
  'north-indic': ['Line on top = Devanagari/Bengali/Gurmukhi. No line = Gujarati. Umbrellas = Odia. Assam adds ৰ with a slash through it.'],
  'south-indic': ['Tamil is wire, Malayalam is bubbles, Telugu wears ticks, Kannada wears caps, Sinhala has curls.'],
  'himalayan': ['Dots between syllables = Tibetan script. Signs with English = Bhutan; with Chinese = Tibet.'],
  'arabic-script': ['Each language adds its own "extra dots": Persian adds p/ch/zh/g, Urdu adds a tiny ط hat, Pashto adds rings, Kurdish adds vowel hats, Uyghur writes every vowel.'],
  'hebrew-script': ['Hebrew is vowel-free blocks; Yiddish fills them with vowels (אַ אָ) so it looks busier.'],
  'caucasus': ['Armenian = hooks and horseshoes; Georgian = bubbles.'],
  'east-asian': ['Circles = Korea, curly kana pebbles = Japan, only dense rocks = China.'],
  'bantu': ['Zulu and Xhosa click (c, q, x). Swahili starts nouns with ki-/m-. Rwanda\'s provinces are simply North, South, East, West.'],
  'west-african': ['Yoruba puts dots under ẹ ọ ṣ, Igbo under ị ụ, and Hausa bends its letters into hooks (ɓ ɗ ƙ).'],
  'horn-of-africa': ['Same script, different country: Ethiopia = Amharic, Eritrea = Tigrinya.'],
  'polynesian': ['Māori says "wh" (Whanganui), Hawaiian has only 13 letters, Samoan writes "ng" as g (Pago Pago = Pango Pango).'],
  'andean': ['Guaraní puts tildes on y and e (ỹ ẽ); Quechua and Aymara love q and apostrophes (q\', k\').'],
}

export const languageRemember: Record<string, string[]> = {
  cs: ['ř sounds like a buzzing bee saying "rzh" (Dvořák). ů is a u with a halo.'],
  sk: ['Slovak is Czech with hats and umlauts: ô, ä, ĺ, ŕ.'],
  pl: ['ł is an L with a strike-through, and it sounds like "w": Łódź is "Woodge".', 'Polish loves "sz" and "cz": signs look like a keyboard sneezed (Szczecin).'],
  hu: ['ő and ű: letters that saw a ghost (double accent = double shock). Only Hungarian.'],
  sl: ['Slovene is minimalist: only č š ž, no accents, no ć or đ.'],
  hr: ['Croatia fills its pharmacies with "ljekarna" and its stations with "kolodvor".'],
  sr: ['Serbia writes everything twice: once in Cyrillic, once in Latin.'],
  bs: ['Bosnian keeps the Turkish "h" others dropped: kahva (coffee), mahala.'],
  cnr: ['Montenegro invented two new letters in 2009 (ś ź), but you will rarely see them.'],
  mk: ['Macedonian letters wear a single accent: ѓ ќ, and ѕ looks like an s wearing Cyrillic clothes.'],
  lt: ['Lithuanian vowels drag tails (ą ę į ų) and its e has a dot on top (ė).'],
  lv: ['Latvian vowels wear flat roofs (ā ē ī ū) and its consonants have tails (ķ ļ ņ).'],
  et: ['Estonian õ is an o wearing a wavy wig.'],
  fi: ['Finnish is a stuttering language: double letters everywhere (Helsinki, Jyväskylä, kk tt pp).'],
  da: ['Danish roads are "vej", Norwegian roads are "vei". The j is Danish.'],
  no: ['Norway has two ways to write: Bokmål (vei) and Nynorsk (veg).'],
  sv: ['Swedish streets end in -gatan and -vägen: "the street" and "the road".'],
  is: ['Icelandic keeps two Viking letters: þ (thorn) and ð (eth). Þ only survives in Iceland.'],
  fo: ['Faroese is Icelandic\'s cousin who moved to Denmark: ð like Iceland, ø like Denmark.'],
  se: ['Sámi has a t with a slash (ŧ) and an n with a tail (ŋ): letters of the far north.'],
  es: ['¿Spanish asks questions upside down? ¡And exclaims too!'],
  pt: ['Portuguese has nasal ã õ: the tilde is a nose. -ção endings sing like "-sown".'],
  ca: ['Catalan puts a dot in the middle of double l (l·l), like a bullet between two posts.'],
  gl: ['Galician is Spanish and Portuguese\'s love child: ñ from Spain, "rúa" from Portugal, "x" of its own.'],
  eu: ['Basque sounds like a sneeze: tx, tz and k everywhere (Etxebarria, Getxo).'],
  fr: ['French wears hats (â ê î ô û) and elbows (ç), and its words end in silent letters.'],
  it: ['Italian words end in vowels and double their consonants: pizza, piazza.'],
  ro: ['Romanian ș and ț have a comma under them like a little beard, and ă has a smile.'],
  de: ['ß is a sharp snake: "Straße".'],
  nl: ['Dutch doubles vowels (straat) and glues i+j together (IJsselmeer).'],
  af: ['Afrikaans is Dutch that moved to Africa and simplified: "die" for every "the".'],
  lb: ['Luxembourgish: German words with Dutch double vowels and a sprinkling of ë.'],
  ga: ['Irish accents lean forward (á) and consonants get an h (bh, mh). "An Lár" = the centre.'],
  cy: ['Welsh is vowel-shy: w and y are vowels, so "cwm" and "bryn" are real words.'],
  gd: ['Scottish Gaelic accents lean backwards (à), the opposite of Irish.'],
  br: ['Breton is French Celtic: "ker" means village, "plou" means parish.'],
  tr: ['Turkish ı has no dot and İ has an extra dot: the candle and the lit candle.'],
  en: ['English is the language with no badges at all: plain A–Z.'],
  sq: ['Albanian loves ë and double letters (rr, ll, xh): "Rruga" = street.'],
  mt: ['Maltese is Arabic in Italian clothes: ħ is an h with a crossbar, ċ ġ ż wear dots.'],
  el: ['Greek puts an accent hat on almost every word.'],
  vi: ['Vietnamese stacks accents like a totem pole: ế, ộ, ữ.'],
  id: ['Indonesia learned from the Dutch: polisi, stasiun, apotek, and streets start with "Jl."'],
  ms: ['Malaysia learned from the English: polis, stesen, farmasi, and "Jalan" in full.'],
  fil: ['Filipino loves "ng" and "mga", and borrows Spanish with Tagalog spelling (kalye, simbahan).'],
  ru: ['Russian has ы: a b with a stick, like "bi" joined together.'],
  uk: ['Ukrainian ї has two eyes looking at you: Київ.'],
  be: ['Belarusian ў is a u with a smile.'],
  bg: ['Bulgarian uses ъ as a real vowel, like a swallowed "uh": път (road).'],
  kk: ['Kazakh adds ә, ғ, қ, ұ: Cyrillic with extra hooks and tails.'],
  ky: ['Kyrgyz doubles its vowels: тоо (mountain), оорукана (hospital).'],
  mn: ['Mongolian loves ө and ү and double vowels: Улаанбаатар.'],
  ar: ['Arabic starts half its words with "al-" (ال), like a door opening.'],
  fa: ['Persian adds four letters Arabic lacks: پ چ ژ گ (p, ch, zh, g).'],
  ur: ['Urdu hangs its words diagonally (Nastaliq) and adds a tiny ط hat for "hard" letters (ٹ ڈ ڑ).'],
  ps: ['Pashto puts little rings under letters (ټ ډ ړ): like a key ring.'],
  ckb: ['Kurdish writes vowels as letters and gives some consonants a little v-hat (ڕ ڵ).'],
  ug: ['Uyghur starts vowels with a "hamza on a tooth" (ئ) all the time.'],
  he: ['Hebrew blocks, right to left, next to Arabic and English on the same sign = Israel.'],
  hy: ['Armenian: a skyline of arches and hooks, and "և" (and) looks like a tiny wine glass.'],
  ka: ['Georgian: bubbles in a row, no capitals.'],
  hi: ['Hindi signs have Devanagari above English, especially in the "Hindi belt" (north India).'],
  mr: ['Marathi uses ळ all the time, a letter Hindi hardly ever needs.'],
  ne: ['Nepali police are "प्रहरी", not "पुलिस": the Nepal tell.'],
  bn: ['Bengali letters are pointy triangles hanging from a line.'],
  as: ['Assamese crosses out its r: ৰ.'],
  pa: ['Punjabi (Gurmukhi) has a little "u" bowl (ੰ) sprinkled everywhere.'],
  gu: ['Gujarati is Hindi without the washing line.'],
  or: ['Odia letters are all wearing umbrellas.'],
  ta: ['Tamil looks like it was bent from paperclips.'],
  te: ['Telugu = ticks ✓; Telangana and Andhra = ticks.'],
  kn: ['Kannada = caps; Karnataka = caps.'],
  ml: ['Malayalam is a soap-bubble chain, and it is a palindrome.'],
  si: ['Sinhala is snail shells: curls on everything.'],
  th: ['Thai starts every letter with a knot.'],
  lo: ['Lao is Thai without the knots.'],
  km: ['Khmer letters wear hats and carry suitcases underneath.'],
  my: ['Burmese is all circles.'],
  ko: ['Korean: circles in boxes.'],
  ja: ['Japanese: rocks (kanji) and pebbles (kana). の is the tell.'],
  zh: ['Chinese: all rocks, no pebbles.'],
  yue: ['Hong Kong Cantonese: traditional characters + English + odd characters like 嘅 冇.'],
  sw: ['Swahili nouns start with ki- or m- and "Karibu" means welcome.'],
  zu: ['Zulu clicks: c, q, x hiding in normal words.'],
  xh: ['Xhosa\'s name starts with a click: the X is a click.'],
  yo: ['Yoruba puts dots under its letters like footprints: ẹ ọ ṣ.'],
  ha: ['Hausa bends letters into hooks: ɓ ɗ ƙ.'],
  mg: ['Malagasy place names are super long and start with Ambo-, Anta- or Nosy.'],
  mi: ['Māori "wh" is pronounced "f": Whakatāne = "Fakatāne".'],
  haw: ['Hawaiian has only 13 letters and loves the ʻokina: Hawaiʻi.'],
  kl: ['Greenlandic makes whole sentences into one enormous word, full of q.'],
  az: ['Azerbaijani has ə, an "e" standing on its head.'],
  uz: ['Uzbek writes an apostrophe-like mark after o and g: oʻ, gʻ.'],
  tk: ['Turkmen has ý, ň, ž: accents from all over Europe in Central Asia.'],
}
