import type { WhyExplainer } from './types'

// "Why is it like this?" explainers. Written from general engineering and history knowledge and the
// PlonkIt guides; each should be spot-checked (SPEC §7.4).

export const explainers: WhyExplainer[] = [
  // ---------------------------------------------------------------- Roads
  {
    id: 'yellow-centre-lines', title: 'Why are centre lines yellow in the Americas and white in Europe?', category: 'Roads',
    observation: 'Roads in the US, Canada and most of Latin America have yellow lines separating the two directions; most of Europe, Africa and Asia use white.',
    why: [
      'The first painted centre line is usually credited to Michigan around 1911. For decades US states used white, yellow or black as they liked.',
      'In 1971 the US national standard (the MUTCD) made yellow mean "traffic on the other side of this line is coming towards you" and white mean "same direction". Canada and most of Latin America use the same system.',
      'Europe standardised through the 1968 Vienna Convention on Road Signs and Signals, which uses white for normal markings and keeps yellow for temporary roadworks and parking restrictions. A few countries kept yellow centre lines anyway: Norway, Finland (yellow separates opposing traffic), and outside Europe Japan uses yellow for "no overtaking" centre lines.',
    ],
    countries: ['US', 'CA', 'MX', 'BR', 'AR', 'CL', 'CO', 'PE', 'EC', 'BO', 'UY', 'PY', 'GT', 'CR', 'PA', 'DO', 'NO', 'FI', 'KR', 'JP', 'PH', 'TH'],
    where: 'Yellow centre lines: the Americas, Norway, Finland, South Korea; Japan (no-overtaking), Thailand and the Philippines (often). White: most of Europe, Africa, Australia, New Zealand (NZ uses white with yellow no-overtaking lines).',
    lookalikes: 'South Africa and Australia use white centre lines but South Africa has yellow edge lines.',
    tips: ['Double yellow centre line + white edges: almost certainly the Americas.', 'Yellow centre line in Europe: Norway or Finland.'],
    remember: 'In the Americas yellow means "oncoming traffic on the other side"; in Europe yellow means "roadworks".',
    photoCategories: ['Double yellow lines', 'Road markings in Norway'],
  },
  {
    id: 'frost-heave', title: 'Why are northern roads so cracked and bumpy, with black squiggles?', category: 'Roads',
    observation: 'Roads in the northern US, Canada, Scandinavia and Russia are often cracked, patched and wavy, with long black squiggly lines of sealant ("tar snakes") and signs warning of "frost heaves" or "bumps".',
    why: [
      'Water in the ground expands by about 9% when it freezes. Worse, freezing soil sucks up more water from below and grows layers of ice ("ice lenses") that push the road up unevenly: frost heave.',
      'In spring the ice melts from the top down, leaving a soaked, soft layer over still-frozen ground. Heavy trucks then break the road, so many cold countries post spring weight limits (Finland even has a word for the mud season: kelirikko).',
      'The cracks that form are filled with hot rubbery bitumen to keep water out: the black squiggles you see across US and Canadian roads.',
      'The "frost line" (how deep the ground freezes: up to 1–2 m in the northern US and Canada) also shapes houses: foundations must reach below it, and once you dig that deep a basement costs little extra. That is why basements are normal in the northern US and Canada but rare in the South, where houses sit on a slab.',
    ],
    countries: ['US', 'CA', 'RU', 'FI', 'SE', 'NO', 'EE', 'LV', 'LT', 'KZ', 'MN'],
    where: 'Cold climates: the northern US (Maine, Vermont, Minnesota…), Canada, the Nordics, the Baltics, Russia and Central Asia.',
    tips: ['Crack-sealant squiggles and patched, wavy asphalt: think northern US or Canada.', '"FROST HEAVE" or "BUMP" signs: New England (Vermont, New Hampshire, Maine).'],
    remember: 'Ice in the ground is a slow jack: it lifts the road every winter and drops it every spring.',
    photoCategories: ['Crack sealing', 'Frost heaves'],
  },
  {
    id: 'concrete-roads', title: 'Why are some roads concrete instead of asphalt?', category: 'Roads',
    observation: 'Pale grey roads made of concrete slabs with joints every few metres, instead of black asphalt: on rural roads in the Philippines, Thailand, Vietnam and Indonesia, on Iowa\'s country roads, and on older German, Belgian and Dutch motorways.',
    why: [
      'Concrete costs more to build but lasts much longer (30–40 years) and copes better with heavy trucks and floods. Asphalt is cheaper and quicker but needs resurfacing every 10–20 years.',
      'In the tropics, asphalt softens in the heat and is damaged by heavy rain and flooding, while cement is made locally and slabs can be laid by hand with little machinery. The Philippines builds most national roads in concrete, and villages across Southeast Asia pour narrow concrete lanes themselves.',
      'In Germany and Belgium many motorways were built in concrete for durability under heavy lorry traffic; Iowa built concrete farm-to-market roads because its limestone made cement cheap.',
    ],
    countries: ['PH', 'TH', 'VN', 'ID', 'KH', 'LA', 'MY', 'US', 'DE', 'BE', 'CN'],
    where: 'Very common on rural and village roads in the Philippines, Thailand and Vietnam; ordinary rural roads in Iowa; some motorways in Germany and Belgium.',
    tips: ['A narrow grey concrete lane through rice fields: Southeast Asia (Philippines, Thailand, Vietnam).', 'Concrete rural roads in the US: Iowa.'],
    remember: 'Concrete is the long-life option: expensive once, cheap for 40 years, and it doesn\'t melt in the tropical sun.',
    photoCategories: ['Concrete roads in the Philippines', 'Concrete roads in Thailand'],
  },
  {
    id: 'chip-seal', title: 'Why are some roads rough and gravelly instead of smooth asphalt?', category: 'Roads',
    observation: 'Coarse, stony road surfaces that look like gravel glued to the road, often with loose chips at the edges: typical in Australia, New Zealand, South Africa and rural US roads.',
    why: [
      'This is a chip seal (or "sealed road"): a thin layer of hot bitumen is sprayed on the road and stone chips are rolled into it. It costs a fraction of real asphalt concrete, which is mixed in a plant and laid thick.',
      'Countries with long distances and few people (Australia, New Zealand, rural America, southern Africa) cannot afford thick asphalt on quiet roads, so most of their rural roads are chip-sealed.',
      'The surface is noisy and sheds loose chips that crack windscreens, but it gives good grip in the rain.',
    ],
    countries: ['AU', 'NZ', 'ZA', 'US', 'CA', 'NA', 'BW'],
    where: 'Most rural roads in Australia and New Zealand; South Africa, Namibia, Botswana; rural roads in the US Midwest and West.',
    tips: ['Coarse, stony surface on a quiet road: Australia or New Zealand (then look at road lines and signs).'],
    remember: 'Chip seal is "tar with gravel sprinkled on": the budget road of big, empty countries.',
    photoCategories: ['Chipseal'],
  },
  {
    id: 'asphalt-colour', title: 'Why is asphalt black in some places and grey, red or pale in others?', category: 'Roads',
    observation: 'Fresh roads are jet black, older roads light grey; Dutch cycle paths are red; Texas roads look like "salt and pepper"; Icelandic roads are very dark.',
    why: [
      'Asphalt is about 95% stone held together by 5% bitumen. New bitumen is black and coats the stones; sun and air slowly oxidise it and traffic wears it off, so the road turns grey as the stone shows through.',
      'So the colour of an old road is really the colour of the local stone: dark basalt in Iceland and volcanic areas, pale limestone in many dry regions, and the coarse mixed stone of Texas and neighbouring states that gives the "salt and pepper" look.',
      'Red surfaces are coloured on purpose with red stone or iron-oxide pigment: the Netherlands paints its cycle paths red so they stand out from the road, and many countries use red or green for bus and bike lanes.',
    ],
    countries: ['NL', 'US', 'IS', 'BE', 'DK'],
    where: 'Red cycle paths: the Netherlands (also Belgium, Denmark). "Salt and pepper" roads: Texas and nearby states. Very dark roads: Iceland.',
    tips: ['Red asphalt bike path beside the road: the Netherlands or Flanders.', 'Grainy black-and-white road surface in the US: Texas.'],
    remember: 'Old asphalt shows its stones: the road is the colour of the local rock.',
    photoCategories: ['Bicycle paths in the Netherlands'],
  },
  {
    id: 'cobblestones', title: 'Why do some countries still have cobblestone roads?', category: 'Roads',
    observation: 'Streets and even country roads paved with stone setts: Belgium\'s "kasseien", villages in Poland and the Baltics, towns across Brazil, Portugal, and the Andes.',
    why: [
      'Cobbles (properly, "setts") were the standard hard road surface before asphalt spread in the 20th century. Where they were never replaced, they stayed.',
      'They last for a century, can be lifted and relaid after digging, let rainwater soak through, and need no oil-based products, just local stone and labour. Where labour is cheap and stone is local (northeast Brazil, rural Latin America), they are still laid today.',
      'Towns also keep or add them to slow traffic and for their historic look.',
    ],
    countries: ['BE', 'PL', 'LT', 'LV', 'BR', 'PT', 'NL', 'FR', 'CZ', 'MX'],
    where: 'Belgium (even rural roads), Poland, the Baltics, northeast and southern Brazil, Portugal, colonial towns in Latin America.',
    tips: ['Cobbled country road between fields in Europe: Belgium (think Paris–Roubaix) or Poland.'],
    remember: 'Cobbles are the road that never dies: lift them, fix the pipe, put them back.',
    related: [{ to: '/regions/BR?tab=features', label: 'Brazil road surfaces by state' }],
    photoCategories: ['Cobblestone roads in Belgium'],
  },
  {
    id: 'driving-left', title: 'Why do some countries drive on the left?', category: 'Roads',
    observation: 'Traffic keeps left in the UK, Ireland, Japan, India, Australia, South Africa, Indonesia, Thailand and about 75 countries in all: roughly a third of the world\'s people.',
    why: [
      'In the Middle Ages keeping left was common in Europe, possibly so a right-handed rider could draw a sword or greet oncoming people. Britain made it law in 1835 and spread it through its empire.',
      'Keeping right spread from 18th-century France and America, where large wagons were driven by a postilion riding the left horse, who wanted oncoming traffic on his left. Napoleon\'s conquests carried the rule across Europe.',
      'Japan drove on the left long before contact with Britain, and British engineers built its first railways on the left too; Okinawa switched to the right under US rule and back to the left in 1978. Sweden switched to the right overnight on 3 September 1967 ("Dagen H").',
    ],
    countries: ['GB', 'IE', 'MT', 'CY', 'JP', 'IN', 'BD', 'LK', 'NP', 'BT', 'TH', 'MY', 'SG', 'ID', 'AU', 'NZ', 'ZA', 'BW', 'NA', 'LS', 'SZ', 'KE', 'UG', 'TZ', 'MZ', 'ZW', 'ZM'],
    where: 'The UK and former British colonies (India, Australia, southern and eastern Africa…), plus Japan, Thailand and Indonesia.',
    tips: ['Left-hand traffic in Europe: UK, Ireland, Malta or Cyprus only.', 'Southeast Asia: left in Thailand, Malaysia, Indonesia; right in Vietnam, Cambodia, the Philippines.'],
    remember: 'The left is the British Empire\'s footprint (plus Japan, which chose it on its own).',
    photoCategories: ['Keep left signs'],
  },

  // ---------------------------------------------------------------- Pavements & kerbs
  {
    id: 'portuguese-pavement', title: 'Why do Portuguese and Brazilian pavements have black-and-white mosaic patterns?', category: 'Pavements & kerbs',
    observation: 'Sidewalks and squares laid with small black and white stones in waves, stripes and patterns: Lisbon, Rio\'s Copacabana promenade, towns across Brazil, Macau.',
    why: [
      'This is calçada portuguesa. The modern style began in Lisbon in the 1840s, when a military governor had prisoners pave a castle courtyard in a zig-zag of limestone and basalt; the city then paved its squares and streets the same way.',
      'Portugal took it to its colonies. Rio\'s famous wave pattern on Copacabana beach dates from 1906, and Roberto Burle Marx redesigned the promenade in 1970.',
      'The small hand-laid stones drain well, can be lifted and relaid, and use local white limestone and dark basalt.',
    ],
    countries: ['PT', 'BR', 'MO', 'CV', 'AO', 'MZ'],
    where: 'Portugal (including the Azores and Madeira), Brazil (especially Rio, São Paulo and Manaus), Macau and former Portuguese colonies.',
    tips: ['Black-and-white mosaic sidewalks: Portugal or Brazil, then use language details and the landscape.'],
    remember: 'The Portuguese paved their empire in black and white: follow the waves from Lisbon to Copacabana.',
    photoCategories: ['Portuguese pavement in Lisbon', 'Copacabana promenade'],
  },
  {
    id: 'painted-kerbs', title: 'Why are kerbs painted in stripes or colours in some countries?', category: 'Pavements & kerbs',
    observation: 'Kerbs painted black-and-white in Russia, Ukraine and Kazakhstan; white in Brazil; yellow in Mexico; red-and-white or blue-and-white in Israel; red for fire lanes in the US.',
    why: [
      'Two reasons: visibility and rules. Painted kerbs show drivers the edge of the road at night and in fog, and kerb colours are a cheap way to mark where parking is allowed.',
      'In Israel, red-and-white means no stopping and blue-and-white means paid parking; in the US, red kerbs mean no parking and yellow often means loading only.',
      'In post-Soviet countries black-and-white kerbs and fences are a standard for visibility, repainted every spring, often by volunteers during community clean-up days (subbotniks).',
    ],
    countries: ['RU', 'UA', 'BY', 'KZ', 'BR', 'MX', 'IL', 'ES', 'US', 'KG', 'UZ'],
    where: 'Black-and-white: Russia, Ukraine, Belarus, Kazakhstan, Kyrgyzstan. White: Brazil. Yellow: Mexico and parts of Latin America. Red/white/blue codes: Israel, the US.',
    tips: ['Black-and-white striped kerbs and railings: a post-Soviet country.', 'White-painted kerbs: very common in Brazil.'],
    remember: 'Striped kerbs are the post-Soviet zebra: repainted every spring clean-up.',
    photoCategories: ['Curbs in Russia', 'Painted curbs'],
  },
  {
    id: 'white-trunks', title: 'Why are tree trunks painted white?', category: 'Pavements & kerbs',
    observation: 'The bottom metre of roadside trees painted white: across Russia, Ukraine, Eastern Europe, Central Asia, the Middle East and Latin America.',
    why: [
      'The white is usually whitewash (lime). Gardeners have used it for centuries to protect bark: in late winter the sun heats the dark bark by day and it freezes at night, splitting it ("sunscald"); white reflects the sun.',
      'Lime also deters insects and fungi, and white trunks make roadsides visible at night.',
      'In the Soviet Union it became part of the spring clean-up ritual, so it is done on city trees whether they need it or not; it spread as a tidy look across the region.',
    ],
    countries: ['RU', 'UA', 'BY', 'KZ', 'KG', 'UZ', 'RO', 'BG', 'MD', 'TR', 'MX', 'GT', 'CU', 'PE', 'IN'],
    where: 'Post-Soviet countries, Romania, Bulgaria and the Balkans, Turkey, the Middle East, Mexico and much of Latin America, India.',
    tips: ['White-trunked roadside trees are a strong hint to look for Cyrillic, Romanian or Spanish; rare in Western Europe and North America.'],
    remember: 'White trunks are sunscreen for trees, and a Soviet spring-cleaning habit.',
    photoCategories: ['Whitewashed tree trunks'],
  },
  {
    id: 'no-sidewalks', title: 'Why do American suburbs often have no sidewalks?', category: 'Pavements & kerbs',
    observation: 'Residential streets in many US suburbs and rural towns have lawns running straight to the road, with no pavement at all.',
    why: [
      'Most US suburbs were built after the 1940s, designed around the car: long curving streets, cul-de-sacs, and houses far from shops. Developers left out sidewalks to save money, and many local rules did not require them.',
      'Older towns and city centres (built before cars) and newer suburbs with modern rules usually do have them.',
    ],
    countries: ['US'],
    where: 'Suburbs and rural areas across the US, especially the South and Southwest. Canada more often has sidewalks.',
    tips: ['Wide lawns straight to the road with a mailbox on a post and no sidewalk: US suburb.'],
    remember: 'No sidewalk = built for the car: the post-war American suburb.',
    photoCategories: ['Suburbs in the United States'],
  },

  // ---------------------------------------------------------------- Houses & roofs
  {
    id: 'rebar-roofs', title: 'Why do so many houses have steel bars sticking out of the roof?', category: 'Houses & roofs',
    observation: 'Flat-roofed concrete houses with rusty steel reinforcing bars (rebar) poking up from the columns, as if unfinished: across Latin America, the Middle East, Greece, the Balkans, Turkey, Egypt and Africa.',
    why: [
      'The bars are left so another floor can be added later. Many families build their house bit by bit as money comes in, without a mortgage, and add a floor when a child marries or the family grows.',
      'Leaving the rebar sticking out is much cheaper than cutting and re-joining it later. The flat concrete roof doubles as a terrace until the next floor is built.',
      'In some countries unfinished houses are said to pay less property tax, which is often given as the reason (for example in Greece and Egypt), but the main reason is simply building as you save.',
    ],
    countries: ['MX', 'GT', 'CO', 'PE', 'BO', 'EC', 'BR', 'GR', 'AL', 'TR', 'EG', 'JO', 'MA', 'TN', 'IN', 'NG', 'GH', 'KE'],
    where: 'Latin America, the Mediterranean (Greece, Albania, Turkey), North Africa and the Middle East, South Asia, much of sub-Saharan Africa.',
    tips: ['Rebar on flat roofs tells you a lot about the building culture, not a single country: combine it with language and road clues.'],
    remember: 'Rebar on the roof is a promise of a future floor: houses grow with the family.',
    photoCategories: ['Unfinished buildings', 'Protruding rebar'],
  },
  {
    id: 'flat-vs-pitched', title: 'Why are roofs flat in some places and steep in others?', category: 'Houses & roofs',
    observation: 'Flat roofs across dry regions (the Middle East, North Africa, Mexico, the Andes, the US Southwest); steep roofs in snowy and rainy places (the Alps, Scandinavia, Japan, Northern Europe).',
    why: [
      'A roof\'s slope is about getting rid of water and snow. Where it rains little, a flat roof is cheaper and becomes useful space: for drying clothes, water tanks, sleeping on hot nights, or adding a floor later.',
      'Heavy snow needs steep roofs so it slides off (or strong roofs designed to hold it, like wide Alpine chalet roofs that keep snow on as insulation). Heavy rain needs slopes and overhangs.',
      'Materials matter too: clay tiles need a slope; concrete slabs can be flat.',
    ],
    countries: ['MX', 'EG', 'MA', 'TN', 'JO', 'IL', 'PE', 'BO', 'AE', 'NO', 'CH', 'AT', 'JP'],
    where: 'Flat: dry climates. Steep: snowy or very rainy climates.',
    tips: ['Flat concrete roofs: a dry climate (and often rebar and water tanks).', 'Very steep roofs: snow country.'],
    remember: 'The roof slope is a rain gauge: flat where it barely rains, steep where snow piles up.',
    photoCategories: ['Flat roofs'],
  },
  {
    id: 'metal-roofs', title: 'Why are corrugated metal roofs so common in the tropics?', category: 'Houses & roofs',
    observation: 'Houses roofed with corrugated metal sheets, shiny or rusty: across Africa, Southeast Asia, the Pacific, rural Latin America and outback Australia.',
    why: [
      'Corrugated iron (invented in the 1820s) is light, cheap, quick to put up without special skills, and easy to transport to remote places: it was shipped across the British Empire and became the standard roof of the colonial frontier.',
      'It sheds heavy tropical rain and can collect it into water tanks. Newer houses use coloured or zinc-coated steel sheets.',
    ],
    countries: ['KE', 'UG', 'TZ', 'RW', 'GH', 'NG', 'SN', 'ZA', 'ID', 'PH', 'MY', 'KH', 'LA', 'AU', 'NZ', 'GT', 'BR'],
    where: 'Sub-Saharan Africa, Southeast Asia, the Pacific, rural Latin America, Australia and New Zealand.',
    tips: ['Tiled roofs vs metal roofs split Indonesia: tiles on Java and Bali, metal in Kalimantan, Sulawesi and northern Sumatra.'],
    remember: 'Corrugated iron is the roof you can carry on a donkey: light, cheap and everywhere in the tropics.',
    related: [{ to: '/regions/ID?tab=features', label: 'Indonesia roofs by region' }],
    photoCategories: ['Corrugated iron roofs'],
  },
  {
    id: 'falu-red', title: 'Why are so many Scandinavian houses red?', category: 'Houses & roofs',
    observation: 'Dark red wooden houses and barns with white trim across Sweden, and many in Norway and Finland.',
    why: [
      'The paint is Falu red (falu rödfärg), made from waste left over from the copper mine at Falun in Sweden, which was mined for about 1,000 years. The iron- and copper-rich slag gives a red pigment that also preserves wood.',
      'It was cheap, and red houses also imitated the brick houses of the rich. By the 1800s it had become the typical colour of the Swedish countryside.',
    ],
    countries: ['SE', 'NO', 'FI'],
    where: 'All over rural Sweden; common in Norway and Finland too.',
    tips: ['Red wooden houses with white corners: Sweden first, then Norway or Finland.'],
    remember: 'Swedish red is copper-mine waste turned into paint.',
    photoCategories: ['Falu red houses'],
  },
  {
    id: 'wooden-houses', title: 'Why are North American houses made of wood while European houses are brick and stone?', category: 'Houses & roofs',
    observation: 'US and Canadian houses are mostly timber-framed with siding; most European houses are brick, stone or concrete.',
    why: [
      'North America had vast forests and little labour, so wood was cheap. The "balloon frame" (invented in Chicago in the 1830s) and later "platform frame" let a few carpenters build a house quickly from standard sawn timber and nails.',
      'Much of Europe had cut down its forests centuries earlier, while clay for bricks and stone were abundant. Great fires (such as London\'s in 1666) led to rules favouring masonry in cities.',
      'Where forests remain, Europe builds in wood too: Scandinavia, the Baltics, Russia, the Alps.',
    ],
    countries: ['US', 'CA', 'SE', 'NO', 'FI', 'EE', 'LV', 'RU', 'NZ'],
    where: 'Wood: North America, the Nordics, the Baltics, rural Russia, New Zealand. Brick and stone: most of the rest of Europe.',
    tips: ['Wooden siding houses with a porch: North America. Wooden houses with carved window frames: rural Russia.'],
    remember: 'Houses are built from what is lying around: forests in North America, clay and stone in Europe.',
    photoCategories: ['Wood-framed houses in the United States'],
  },
  {
    id: 'stilt-houses', title: 'Why are houses built on stilts?', category: 'Houses & roofs',
    observation: 'Houses raised on posts: in the Amazon, Southeast Asia, Queensland ("Queenslanders"), the US Gulf Coast and the Pacific.',
    why: [
      'Stilts keep homes above floods and high tides, let cool air flow underneath in hot, humid climates, and keep out animals and insects.',
      'In Queensland the raised timber house became a regional style; along the US Gulf Coast, building codes after hurricanes require new houses to be raised.',
    ],
    countries: ['BR', 'PE', 'CO', 'TH', 'KH', 'LA', 'VN', 'MM', 'ID', 'MY', 'PH', 'AU', 'US'],
    where: 'Flood-prone and tropical areas: the Amazon, the Mekong, Malaysia and Indonesia, the Philippines, Queensland, Louisiana and the Carolinas coast.',
    tips: ['Wooden houses on stilts in rainforest: Acre or Amazonas (Brazil). Stilted timber houses with verandas in Australia: Queensland.'],
    remember: 'Stilts lift the house above floods, snakes and the heat.',
    photoCategories: ['Stilt houses'],
  },
  {
    id: 'bars-and-walls', title: 'Why do houses in Latin America and South Africa have walls, gates and window bars?', category: 'Houses & roofs',
    observation: 'Houses behind high walls, metal gates, razor wire or electric fences, and bars on every window.',
    why: [
      'Mostly security: where burglary rates are high and police coverage low, households protect themselves.',
      'It is also architectural tradition: Spanish and Portuguese colonial houses were built around an inner courtyard with blank walls to the street.',
      'In South Africa electric fences and signs from private security companies are almost universal in suburbs.',
    ],
    countries: ['ZA', 'BR', 'MX', 'CO', 'PE', 'GT', 'AR', 'EC', 'BO', 'KE', 'NG'],
    where: 'Latin America (especially cities), South Africa, and much of Africa.',
    tips: ['Electric fencing and security-company signs on suburban walls: South Africa.'],
    remember: 'The wall faces the street, the life faces the courtyard.',
    photoCategories: ['Burglar bars'],
  },

  // ---------------------------------------------------------------- Water & utilities
  {
    id: 'water-tanks', title: 'Why do Brazilian houses have blue water tanks (and Mexican ones black)?', category: 'Water & utilities',
    observation: 'Round plastic water tanks on roofs: blue ones in Brazil (brands like Fortlev), black ones in Mexico (Rotoplas) and India (Sintex), white or metal tanks in the Middle East.',
    why: [
      'In many countries the water supply is not reliable: pressure is low or the water is cut for hours or days. Every house stores water in a tank on the roof and uses gravity to feed its taps.',
      'Brazilian building rules call for a household reservoir (the caixa d\'água). Older tanks were grey fibre-cement (often asbestos); modern ones are polyethylene, and the blue of big brands such as Fortlev became the familiar look.',
      'Tank colour follows the dominant local brand: black Rotoplas in Mexico, black Sintex in India. Black tanks heat the water in the sun (and in India warm water is welcome in winter).',
    ],
    countries: ['BR', 'MX', 'IN', 'GT', 'PE', 'CO', 'EG', 'JO', 'TR', 'IL', 'LK', 'BD'],
    where: 'Blue: Brazil. Black: Mexico, Central America, India. Also common in the Middle East, Turkey and South Asia.',
    tips: ['Blue round tank on a Latin American roof: Brazil. Black cylinder: Mexico or Central America.'],
    remember: 'A roof tank means the tap is not always on: blue in Brazil, black in Mexico and India.',
    related: [{ to: '/regions/BR?tab=features', label: 'Brazil features by state' }],
    photoCategories: ['Water tanks in Brazil', 'Rooftop water tanks'],
  },
  {
    id: 'solar-heaters', title: 'Why do roofs in Israel, Cyprus, Turkey and Greece have water tanks lying on top of solar panels?', category: 'Water & utilities',
    observation: 'A flat panel with a horizontal cylinder tank just above it on almost every roof.',
    why: [
      'These are solar water heaters. The panel heats water, hot water rises naturally into the tank above (a thermosiphon), so the system needs no pump or electricity: which is why the tank always sits above the panel.',
      'Israel made them compulsory on new homes in 1980 after the oil crises; about 85–90% of Israeli homes have one. Cyprus has one of the highest rates in the world, and they are standard in Turkey, Greece, Jordan and China.',
    ],
    countries: ['IL', 'CY', 'TR', 'GR', 'JO', 'CN', 'PS'],
    where: 'The eastern Mediterranean (Israel, Cyprus, Turkey, Greece, Jordan) and China.',
    tips: ['Tank-on-panel water heaters on nearly every roof: Israel, Cyprus, Turkey or Greece.'],
    remember: 'Hot water rises: that is why the tank sits on top of the solar panel.',
    photoCategories: ['Solar water heaters in Israel', 'Solar water heaters in Cyprus'],
  },
  {
    id: 'water-towers', title: 'Why do American towns have big water towers with their name on them?', category: 'Water & utilities',
    observation: 'Tall water towers, often a round tank on legs or a "golf ball", painted with the town\'s name: across the US Midwest, and in Canada.',
    why: [
      'A water tower stores water high up so gravity provides pressure to every tap, even during a power cut, and it covers peak demand in the morning while pumps work steadily.',
      'Flat regions need towers because there are no hills to put a reservoir on. That is why they are everywhere in the Midwest and rarer in hilly places.',
      'Painting the town name on it became a tradition and a landmark for travellers and pilots.',
    ],
    countries: ['US', 'CA', 'FI', 'NL', 'DK'],
    where: 'US Midwest and Plains especially; Canada; historic towers in the Netherlands, Finland and Denmark.',
    tips: ['Read the water tower: it often names the town and the state.'],
    remember: 'A water tower is a hill for flat land.',
    photoCategories: ['Water towers in Iowa', 'Water towers in the United States'],
  },
  {
    id: 'gas-pipes', title: 'Why are gas pipes above ground in Russia and the Caucasus?', category: 'Water & utilities',
    observation: 'Yellow-painted gas pipes running along houses and streets on short posts, bending up into arches over driveways and roads: in Russia, Georgia, Armenia, Ukraine and Central Asia.',
    why: [
      'The Soviet Union connected millions of homes to natural gas from the 1960s to the 1980s. Laying pipes above ground was far cheaper and faster than digging, especially in frozen or rocky ground.',
      'Pipes above ground are easy to inspect and repair and do not corrode in damp soil. The yellow colour is the standard safety colour for gas.',
      'Italy and parts of the Balkans also run yellow gas pipes up house facades, for similar reasons (easy access and safety).',
    ],
    countries: ['RU', 'GE', 'AM', 'AZ', 'UA', 'KZ', 'KG', 'UZ', 'BY', 'MD', 'IT'],
    where: 'The former USSR, especially Georgia, Armenia, Russia and Central Asia; yellow pipes on building walls in Italy.',
    tips: ['Yellow pipe arching over a driveway: Georgia, Armenia, Russia or Central Asia.'],
    remember: 'Soviet gas went overground: yellow pipes arching over every gate.',
    photoCategories: ['Gas pipelines in Georgia (country)', 'Gas pipes in Armenia'],
  },
  {
    id: 'no-poles', title: 'Why does the Netherlands have almost no utility poles?', category: 'Water & utilities',
    observation: 'Dutch streets and country roads have no electricity poles or overhead wires at all, only occasional big transmission pylons.',
    why: [
      'The Netherlands buried almost its entire low- and medium-voltage network. Undergrounding costs several times more than overhead lines, but the country is dense, rich and flat, and its soft soil is easy to dig.',
      'Buried cables do not blow down in storms and need no tree trimming, so outages are very rare. Germany, Denmark, Belgian cities and Singapore have also buried most local lines.',
    ],
    countries: ['NL', 'DE', 'DK', 'SG'],
    where: 'The Netherlands above all; Germany and Denmark mostly; Belgium\'s cities; Singapore.',
    tips: ['A well-kept rural road with no poles at all in Western Europe: the Netherlands.'],
    remember: 'The Dutch buried their wires like they manage their water: everything neat and under control.',
    related: [{ to: '/poles/how', label: 'How a pole works: why some countries bury lines' }],
    photoCategories: ['Roads in the Netherlands'],
  },
  {
    id: 'satellite-dishes', title: 'Why do satellite dishes all point the same way (and how does that help)?', category: 'Water & utilities',
    observation: 'On every roof, dishes point in the same direction and at the same angle, steep or almost upright depending on the country.',
    why: [
      'TV satellites sit in a geostationary orbit, 35,786 km up, directly above the equator, so dishes point towards the equator: south in the northern hemisphere, north in the southern hemisphere.',
      'The further you are from the equator, the lower the dish points; near the equator it points almost straight up. So dishes tell you roughly which hemisphere you are in and how far from the equator.',
      'Brazil is known for large transparent or mesh dishes, used for free-to-air C-band TV.',
    ],
    countries: ['BR', 'ID', 'EG', 'MA', 'TR', 'RU'],
    where: 'Everywhere; most useful near the equator (Indonesia: dishes north or south of it point opposite ways).',
    tips: ['Dishes facing north mean you are south of the equator (and vice versa); almost vertical dishes mean you are close to it.'],
    remember: 'Dishes are compasses: they all look at the equator.',
    photoCategories: ['Satellite dishes'],
  },

  // ---------------------------------------------------------------- Signs & markers
  {
    id: 'stop-signs', title: 'Why do stop signs say "STOP" in English almost everywhere?', category: 'Signs & markers',
    observation: 'Red octagonal stop signs with the English word STOP in most of Europe, Africa and Asia; but ALTO in Mexico and Central America, PARE in South America, ARRÊT in Quebec, 止まれ on an upside-down triangle in Japan.',
    why: [
      'The red octagon came from the US (1920s–1950s). The 1968 Vienna Convention adopted it internationally and allowed the word STOP (in English) or the local-language equivalent.',
      'Most countries chose "STOP" so foreign drivers understand it. Spanish and Portuguese speakers kept their own words: ALTO (Mexico and Central America) and PARE (most of South America, Puerto Rico, Brazil).',
      'Japan never adopted the octagon: its stop sign is a red downward triangle saying 止まれ (tomare).',
    ],
    countries: ['MX', 'GT', 'CR', 'PA', 'SV', 'HN', 'NI', 'BR', 'AR', 'CL', 'CO', 'PE', 'EC', 'UY', 'PY', 'BO', 'DO', 'JP'],
    where: 'ALTO: Mexico, Central America. PARE: South America and Brazil. STOP: almost everywhere else (plus local scripts in some countries, such as قف in some Arab countries).',
    tips: ['ALTO vs PARE splits Latin America roughly into north and south.'],
    remember: 'ALTO in the north, PARE in the south, STOP for the rest of the world, and Japan says tomare.',
    photoCategories: ['Stop signs in Mexico', 'Stop signs in Brazil'],
  },
  {
    id: 'warning-sign-shapes', title: 'Why are warning signs yellow diamonds in some countries and red triangles in others?', category: 'Signs & markers',
    observation: 'Yellow diamond warning signs in the Americas, Australia, New Zealand, Japan and parts of Asia; white or yellow triangles with a red border across Europe, Africa and most of Asia.',
    why: [
      'Two sign systems grew up separately: the US system (MUTCD) with yellow diamonds, and the European system codified in the 1968 Vienna Convention with red-bordered triangles.',
      'Countries influenced by the US (Latin America, the Philippines, Japan, South Korea partly) or that designed their own early (Australia) use diamonds; most others adopted the Vienna triangles.',
      'Some countries use a yellow background inside the triangle for visibility (Sweden, Finland, Greece, Poland, parts of the Balkans).',
    ],
    countries: ['US', 'CA', 'MX', 'BR', 'AR', 'CL', 'CO', 'PE', 'AU', 'NZ', 'JP', 'PH', 'TH', 'MY', 'ID'],
    where: 'Diamonds: the Americas, Australia, New Zealand, Japan, the Philippines, Thailand, Malaysia, Indonesia. Triangles: Europe, Africa, most of Asia and the Middle East.',
    tips: ['Red-bordered triangle with yellow inside in Europe: Sweden, Finland, Poland or Greece.'],
    remember: 'Diamonds follow America; triangles follow Vienna.',
    photoCategories: ['Diamond-shaped warning signs'],
  },
  {
    id: 'snow-poles', title: 'Why are there tall striped poles along roads in the north?', category: 'Signs & markers',
    observation: 'Orange, yellow or striped poles every few metres along roadsides in Scandinavia, Canada, the Alps and Hokkaido; in Hokkaido, arrows hang over the road pointing down at its edge.',
    why: [
      'They are snow poles: they show snowplough drivers and motorists where the road edge is when everything is white and the snowbanks are higher than a car.',
      'Each country has its own colours and reflector patterns (Finland: orange with a thin white band near the top; Sweden and Norway: wider bands lower down), which makes them a clue.',
      'Hokkaido\'s downward arrows (yabane) are hung high so they stay visible above deep snow.',
    ],
    countries: ['NO', 'SE', 'FI', 'IS', 'CA', 'JP', 'AT', 'CH', 'US', 'RU'],
    where: 'Snowy regions: the Nordics, Iceland, Canada, the Alps, northern Japan, the northern US.',
    tips: ['Compare the reflector band on orange snow poles to tell Finland, Sweden and Norway apart.'],
    remember: 'Snow poles are the road edge on stilts, for when the road disappears.',
    related: [{ to: '/poles', label: 'Nordic poles' }],
    photoCategories: ['Snow poles'],
  },
  {
    id: 'mailboxes', title: 'Why do American houses have mailboxes on posts by the road?', category: 'Signs & markers',
    observation: 'A metal tunnel-shaped mailbox with a red flag on a post at the end of every driveway in rural and suburban US (and rural Canada).',
    why: [
      'Rural Free Delivery began in 1896: for the first time mail was carried to farms instead of waiting at the post office. Carriers drove along roads, so boxes were put at the roadside, reachable from the driver\'s seat.',
      'The familiar "tunnel" box was designed in 1915 by Roy Joroleman, a Post Office engineer. The red flag tells the carrier there is outgoing mail to collect.',
      'Towns and cities have wall-mounted boxes or door slots instead; much of Europe delivers to the door or to boxes on the house.',
    ],
    countries: ['US', 'CA'],
    where: 'Rural and suburban US; rural Canada.',
    tips: ['Mailbox on a post by the road: North America (look for other clues to split the US and Canada).'],
    remember: 'The mailbox walked to the road when the mail started coming to the farm in 1896.',
    photoCategories: ['Rural mailboxes in the United States'],
  },

  // ---------------------------------------------------------------- Landscape & layout
  {
    id: 'mile-grid', title: 'Why are roads in the American Midwest and Canadian Prairies a perfect grid?', category: 'Landscape & layout',
    observation: 'Straight gravel roads crossing at right angles every mile, with fields in perfect squares, across the US Midwest and West and the Canadian Prairies; roads occasionally jog sideways for no obvious reason.',
    why: [
      'The US Land Ordinance of 1785 divided the land west of the original states into townships of 6 × 6 miles and sections of 1 square mile before it was sold to settlers. Roads followed the section lines. Canada\'s Dominion Land Survey (1871) did the same for the Prairies.',
      'Because the Earth is round, north–south lines get closer together as you go north. Surveyors reset the grid every few townships along "correction lines", which is why north–south roads suddenly jog sideways.',
      'East of the Appalachians (surveyed earlier) roads wind freely, following old property lines.',
    ],
    countries: ['US', 'CA'],
    where: 'The US from Ohio westwards (not Texas, which had its own surveys), and the Canadian Prairies (Manitoba, Saskatchewan, Alberta).',
    tips: ['In Alberta and Manitoba the grid road numbers tell you your exact position.'],
    remember: 'The Midwest is graph paper: the land was drawn in mile squares before anyone farmed it.',
    related: [{ to: '/regions/CA?tab=features', label: 'Canada grid roads' }],
    photoCategories: ['Public Land Survey System'],
  },
  {
    id: 'long-lot-fields', title: 'Why are fields in Quebec long, thin strips?', category: 'Landscape & layout',
    observation: 'Very long, narrow farms running back from a river or road, with houses lined up along the front: along the St. Lawrence in Quebec, in Louisiana, and in parts of Europe.',
    why: [
      'French colonial land grants (seigneurial system) divided land into long lots so that every farm had a share of river frontage, the main transport route, and a mix of good and poorer land further back.',
      'The houses line up along the river or road like a village stretched out for kilometres (a "rang" in Quebec).',
    ],
    countries: ['CA', 'US', 'FR'],
    where: 'Quebec and French-settled parts of Canada, Louisiana; also "strip farming" in parts of Eastern Europe.',
    tips: ['Houses in a long line with narrow fields behind, with French signs: rural Quebec.'],
    remember: 'Every farmer wanted a slice of the river: so the land was cut like a loaf of bread.',
    photoCategories: ['Seigneurial system of New France'],
  },
]
