import type { Plant } from './types'

export const crops: Plant[] = [
  {
    id: 'sugarcane',
    photoSearch: 'sugarcane field',
    name: 'Sugarcane',
    scientific: 'Saccharum officinarum',
    wikipedia: 'Sugarcane',
    section: 'crop',
    kind: 'Grass',
    commonsCategory: 'Sugarcane fields',
    production: { owid: 'sugar-cane-production' },
    recognise: [
      'Dense fields of tall (3–5 m) grass with thick, jointed stems like bamboo and long, arching leaves.',
      'Fields at very different heights side by side, some freshly cut or burnt black.',
      'Feathery grey-purple flower plumes at the top in the dry season.',
    ],
    lookalikes: [
      { id: 'maize', name: 'Maize', tell: 'Maize is shorter, with broad leaves, tassels on top and cobs on the stalk.' },
      { id: 'bamboo', name: 'Bamboo', tell: 'Bamboo is much taller and woody, in clumps rather than fields.' },
    ],
    nativeRange: 'New Guinea, where it was domesticated about 8,000 years ago.',
    grownIn: 'Brazil (by far the largest producer, especially São Paulo state), India, Thailand, China, Pakistan, Mexico, Australia (Queensland), Colombia, Guatemala, the Philippines and southern Africa.',
    clueCountries: ['BR', 'IN', 'TH', 'MX', 'AU', 'CO', 'GT', 'PH', 'ZA', 'SZ'],
    science: [
      'Sugarcane needs a long, hot growing season with lots of water (1,500 mm or irrigation), then a cooler or drier period that makes the stems store sugar. That confines it to the tropics and warm subtropics.',
      'Fields are often burnt before harvest to remove leaves, which leaves blackened stubble.',
    ],
    history: [
      'Sugar spread from India to Persia and the Arab world, then to the Mediterranean. Columbus took sugarcane to the Caribbean in 1493. Sugar plantations in Brazil and the Caribbean were the main driver of the Atlantic slave trade, which brought over 10 million enslaved Africans to the Americas.',
      'Brazil now uses much of its cane to make ethanol for cars.',
    ],
    tips: [
      'Endless cane fields on flat red earth: São Paulo state in Brazil.',
      'Sugarcane with narrow-gauge cane railways: Queensland (Australia).',
    ],
    sources: ['https://en.wikipedia.org/wiki/Sugarcane'],
  },
  {
    id: 'coffee',
    photoSearch: 'coffee plantation Brazil',
    name: 'Coffee',
    scientific: 'Coffea arabica',
    wikipedia: 'Coffea arabica',
    section: 'crop',
    kind: 'Shrub',
    commonsCategory: 'Coffee plantations',
    production: { owid: 'coffee-bean-production' },
    recognise: [
      'Rows of dark, glossy-leaved shrubs 2–3 m tall, often on steep hillsides.',
      'Red "cherries" along the branches when ripe; white flowers after rain.',
      'Sometimes grown under shade trees, or in open, neatly contoured rows (Brazil).',
    ],
    lookalikes: [{ id: 'tea', name: 'Tea', tell: 'Tea is pruned into flat-topped, waist-high hedges covering hills like a green carpet.' }],
    nativeRange: 'Arabica: the highland forests of south-western Ethiopia. Robusta: Central and West Africa.',
    grownIn: 'Brazil (the largest producer: Minas Gerais, São Paulo, Espírito Santo), Vietnam (Central Highlands, robusta), Colombia, Indonesia, Ethiopia, Honduras, Peru, India (Karnataka), Uganda, Guatemala, Mexico, Kenya and Rwanda.',
    clueCountries: ['BR', 'VN', 'CO', 'ET', 'ID', 'GT', 'UG', 'KE', 'RW', 'IN', 'MX', 'PE'],
    science: [
      'Arabica coffee needs the "tierra templada": tropical highlands (roughly 1,000–2,000 m near the equator) with mild temperatures of 15–24 °C, no frost, and a dry season to trigger flowering. Robusta grows lower and hotter.',
      'Frost is its main enemy, which is why Brazil\'s coffee belt moved north after severe frosts in Paraná in 1975.',
    ],
    history: [
      'Coffee drinking began in Yemen in the 15th century. The Dutch took plants to Java; a French officer took one to Martinique in the 1720s; and coffee reached Brazil in 1727. By the 19th century Brazil dominated the world market, funding the growth of São Paulo.',
    ],
    tips: [
      'Neat coffee rows on rolling hills with red soil: southern Minas Gerais, Brazil.',
      'Coffee on steep Andean slopes with bamboo and wooden houses: the Colombian coffee region.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Coffea_arabica', 'https://en.wikipedia.org/wiki/History_of_coffee'],
  },
  {
    id: 'rice',
    photoSearch: 'rice terraces',
    name: 'Rice',
    scientific: 'Oryza sativa',
    wikipedia: 'Rice',
    section: 'crop',
    kind: 'Grass',
    commonsCategory: 'Rice paddies',
    production: { owid: 'rice-production' },
    recognise: [
      'Flat, flooded fields (paddies) divided by low earth banks, bright green when growing, golden when ripe.',
      'Terraced paddies stepping down hillsides in mountainous areas.',
      'Freshly planted fields look like mirrors with rows of seedlings.',
    ],
    lookalikes: [{ id: 'wheat', name: 'Wheat', tell: 'Wheat grows in dry fields, not flooded ones, and in cooler climates.' }],
    nativeRange: 'Domesticated in the Yangtze valley of China about 9,000 years ago (Asian rice); a separate species was domesticated in West Africa.',
    grownIn: 'China and India produce over half the world\'s rice; also Bangladesh, Indonesia, Vietnam, Thailand, Myanmar, the Philippines, Japan and Brazil.',
    clueCountries: ['CN', 'IN', 'BD', 'ID', 'VN', 'TH', 'PH', 'JP', 'KR', 'MY', 'LK', 'MG', 'NP'],
    science: [
      'Paddy rice is grown in standing water, which suppresses weeds and supplies nutrients. It needs high temperatures and abundant water, from monsoon rains, rivers or irrigation. Terraces allow flat flooded fields on slopes.',
    ],
    history: [
      'Rice spread from China across East and Southeast Asia and to India. Terraced rice landscapes such as Banaue (Philippines) and Bali\'s subak system are thousands or hundreds of years old and are UNESCO World Heritage Sites.',
    ],
    tips: [
      'Rice paddies with water buffalo or palms: Southeast Asia. With pine-covered hills and tiled houses: Japan or Korea.',
      'Rice fields also appear in Madagascar\'s highlands, a clue that sets it apart from mainland Africa.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Rice'],
  },
  {
    id: 'tea',
    name: 'Tea',
    scientific: 'Camellia sinensis',
    wikipedia: 'Camellia sinensis',
    section: 'crop',
    kind: 'Shrub',
    commonsCategory: 'Tea plantations',
    production: { mainProducers: ['CN', 'IN', 'KE', 'LK', 'TR', 'VN', 'ID', 'BD', 'AR', 'JP'] },
    recognise: [
      'Bushes pruned into flat-topped, waist-high hedges that cover hillsides like a quilted green carpet.',
      'Narrow paths between rows; tall shade trees scattered through some plantations.',
    ],
    lookalikes: [{ id: 'coffee', name: 'Coffee', tell: 'Coffee shrubs are taller and more open, in separate rows rather than a continuous hedge.' }],
    nativeRange: 'The borderlands of south-west China, northern Myanmar and north-east India (Assam).',
    grownIn: 'China, India (Assam, Darjeeling, the Nilgiris), Kenya (Kericho), Sri Lanka (central highlands), Turkey (Rize), Vietnam, Indonesia (Java), Bangladesh (Sylhet), Japan (Shizuoka), Malaysia (Cameron Highlands) and Rwanda.',
    clueCountries: ['CN', 'IN', 'KE', 'LK', 'TR', 'JP', 'ID', 'RW', 'VN', 'MY'],
    science: [
      'Tea grows best in warm, very rainy climates with acidic, well-drained soils, often on slopes. Highland tea (Darjeeling, Sri Lanka, Kenya) grows slowly in cool air, giving more flavour.',
    ],
    history: [
      'Tea has been drunk in China for thousands of years. The British East India Company, wanting to break China\'s monopoly, smuggled plants and seeds out of China in the 1840s–50s (partly through the botanist Robert Fortune) and developed plantations in Assam, Darjeeling and Ceylon, later in Kenya.',
    ],
    tips: [
      'Tea hedges on steep green hills: Sri Lanka\'s highlands, Darjeeling/Assam (India), Kenya, or the Black Sea coast of Turkey around Rize.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Camellia_sinensis', 'https://en.wikipedia.org/wiki/History_of_tea'],
  },
  {
    id: 'cocoa',
    name: 'Cocoa (cacao)',
    scientific: 'Theobroma cacao',
    wikipedia: 'Theobroma cacao',
    section: 'crop',
    kind: 'Tree',
    production: { owid: 'cocoa-bean-production' },
    recognise: [
      'A small understorey tree grown in the shade of taller trees.',
      'Large, ridged, rugby-ball-shaped pods growing directly from the trunk and thick branches.',
    ],
    lookalikes: [{ id: 'coffee', name: 'Coffee', tell: 'Coffee has small berries on the branches; cocoa has large pods on the trunk.' }],
    nativeRange: 'The upper Amazon basin (Ecuador, Peru, Colombia, Brazil).',
    grownIn: 'Côte d\'Ivoire and Ghana grow over half the world\'s cocoa; also Indonesia, Ecuador, Cameroon, Nigeria, Brazil (Bahia) and Peru.',
    clueCountries: ['GH', 'NG', 'ID', 'EC', 'BR', 'PE', 'DO'],
    science: ['Cocoa needs a hot, humid climate within about 20° of the equator, with rain all year and shade from taller trees. It cannot tolerate drought or cold.'],
    history: [
      'Cacao was domesticated in the upper Amazon and valued by the Maya and Aztecs, who used the beans as currency. The Spanish brought chocolate to Europe. In the 19th century cocoa was planted in West Africa, which now dominates production.',
    ],
    tips: ['Cocoa is usually hidden under forest trees, so it is rarely obvious from the road. Cocoa beans drying on mats by the road suggest Ghana or Côte d\'Ivoire.'],
    sources: ['https://en.wikipedia.org/wiki/Theobroma_cacao'],
  },
  {
    id: 'banana',
    name: 'Banana',
    scientific: 'Musa',
    wikipedia: 'Banana',
    section: 'crop',
    kind: 'Giant herb',
    commonsCategory: 'Banana plantations',
    production: { owid: 'banana-production' },
    recognise: [
      'A tree-like plant with a soft "trunk" of rolled leaf bases and huge paddle-shaped leaves, often torn into strips by wind.',
      'Hanging bunches of green fruit, often covered in blue plastic bags in plantations.',
    ],
    lookalikes: [{ name: 'Traveller\'s palm and bird of paradise', tell: 'Their leaves grow in a flat fan, not a spiral.' }],
    nativeRange: 'Southeast Asia and New Guinea, where bananas were domesticated.',
    grownIn: 'India (the largest producer), China, Indonesia, Brazil, Ecuador (the largest exporter), the Philippines, Guatemala, Colombia, Costa Rica, and East Africa (Uganda, Rwanda, Tanzania) where cooking bananas are a staple.',
    clueCountries: ['IN', 'CN', 'ID', 'BR', 'EC', 'PH', 'GT', 'CO', 'UG', 'RW', 'TZ'],
    science: ['Bananas need constant warmth (ideally 26–30 °C), lots of water and no frost; wind damages the big leaves. They grow from an underground corm and fruit about a year after planting.'],
    history: [
      'Bananas spread from Southeast Asia to Africa over 2,000 years ago. American companies such as United Fruit built huge export plantations in Central America in the late 19th and 20th centuries, giving rise to the term "banana republic".',
    ],
    tips: [
      'Banana plantations with blue bags: Ecuador, Central America or Colombia.',
      'Banana plants around every house in green hills: Uganda or Rwanda.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Banana'],
  },
  {
    id: 'maize',
    name: 'Maize (corn)',
    scientific: 'Zea mays',
    wikipedia: 'Maize',
    section: 'crop',
    kind: 'Grass',
    commonsCategory: 'Maize fields',
    production: { owid: 'maize-production' },
    recognise: [
      'Tall (2–3 m) stalks with broad, strap-like leaves in dense rows.',
      'A tassel of flowers on top and cobs wrapped in husks on the stalk.',
      'In late summer and autumn, dry brown standing stalks.',
    ],
    lookalikes: [{ id: 'sugarcane', name: 'Sugarcane', tell: 'Sugarcane is taller, perennial, with jointed stems and no cobs.' }],
    nativeRange: 'Southern Mexico, domesticated from the wild grass teosinte about 9,000 years ago.',
    grownIn: 'Worldwide: the US (the Corn Belt), China, Brazil, Argentina, Ukraine, India, Mexico, South Africa, and across East and southern Africa as a staple food.',
    clueCountries: ['US', 'CN', 'BR', 'AR', 'UA', 'MX', 'ZA', 'KE', 'RO', 'HU'],
    science: ['Maize needs warm summers (it is frost-sensitive) and moderate rain during growth. It is very efficient in heat (a C4 plant), which is why it dominates warm-summer farmland.'],
    history: [
      'Maize was the staple of the Maya, Aztec and Inca civilisations. After 1492 it spread worldwide within a century. It became the main staple of much of sub-Saharan Africa during the colonial period.',
    ],
    tips: [
      'Maize is grown almost everywhere, so it is weak as a clue alone. Huge flat maize fields: the US Midwest, Ukraine, or the Pannonian plain (Hungary, Romania, Serbia).',
      'Small maize plots around every homestead: East and southern Africa or Mexico.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Maize'],
  },
  {
    id: 'wheat',
    photoSearch: 'wheat field',
    name: 'Wheat',
    scientific: 'Triticum aestivum',
    wikipedia: 'Wheat',
    section: 'crop',
    kind: 'Grass',
    commonsCategory: 'Wheat fields',
    production: { owid: 'wheat-production' },
    recognise: [
      'Knee-to-waist-high grass in huge fields, green in spring and golden in summer.',
      'Dense ears at the top of each stalk; after harvest, pale stubble and round or square bales.',
    ],
    lookalikes: [
      { name: 'Barley', tell: 'Barley has long whiskers (awns) that make the ears look hairy and bend over.' },
      { id: 'rice', name: 'Rice', tell: 'Rice grows in flooded paddies in hot, wet climates.' },
    ],
    nativeRange: 'The Fertile Crescent (south-east Turkey, Syria, Iraq), where it was domesticated about 10,000 years ago.',
    grownIn: 'China, India, Russia, the US (Great Plains), France, Ukraine, Canada (the Prairies), Pakistan, Australia, Argentina, Germany, Kazakhstan and Turkey.',
    clueCountries: ['RU', 'UA', 'KZ', 'US', 'CA', 'AU', 'AR', 'FR', 'TR', 'IN'],
    science: ['Wheat grows best in cool, moderately dry climates. Winter wheat is sown in autumn and harvested in early summer; spring wheat is sown in spring in places with very cold winters (Canada, Kazakhstan).'],
    history: ['Wheat was one of the founder crops of agriculture in the Fertile Crescent. European settlers turned the grasslands of North America, Argentina, Australia and the Russian steppe into vast wheat belts in the 19th century.'],
    tips: ['Endless golden wheat fields to the horizon: the Russian and Kazakh steppe, the Canadian Prairies, the US Great Plains or the Australian wheat belt.'],
    sources: ['https://en.wikipedia.org/wiki/Wheat'],
  },
  {
    id: 'cotton',
    name: 'Cotton',
    scientific: 'Gossypium hirsutum',
    wikipedia: 'Gossypium hirsutum',
    section: 'crop',
    kind: 'Shrub',
    commonsCategory: 'Cotton fields',
    production: { mainProducers: ['IN', 'CN', 'US', 'BR', 'PK', 'UZ', 'TR', 'AU', 'AR', 'TM'] },
    recognise: [
      'Low, bushy plants about a metre tall in wide rows.',
      'In autumn, fields turn white with fluffy open bolls, and cotton wisps blow along the roadsides.',
    ],
    lookalikes: [{ name: 'Soybeans', tell: 'Soy is lower and turns yellow-brown without white bolls.' }],
    nativeRange: 'Upland cotton comes from Mexico and Central America; other cotton species were domesticated independently in South Asia, Africa and South America.',
    grownIn: 'India, China (Xinjiang), the US (Texas and the South), Brazil (Mato Grosso, Bahia), Pakistan, Uzbekistan, Turkey, Australia and Argentina.',
    clueCountries: ['IN', 'CN', 'US', 'BR', 'PK', 'UZ', 'TR', 'AU'],
    science: ['Cotton needs a long frost-free season, lots of sun and heat, and dry weather at harvest. In dry regions such as Xinjiang and Uzbekistan it depends on heavy irrigation.'],
    history: [
      'Cotton was the key crop of the plantation economy of the American South and the Industrial Revolution\'s mills. In Soviet Uzbekistan, irrigating cotton with water from the Amu Darya and Syr Darya rivers caused the Aral Sea to shrink dramatically.',
    ],
    tips: ['White cotton fields in a flat, dry landscape: Texas, Uzbekistan, south-east Turkey or Xinjiang.'],
    sources: ['https://en.wikipedia.org/wiki/Cotton', 'https://en.wikipedia.org/wiki/Aral_Sea'],
  },
  {
    id: 'tobacco',
    name: 'Tobacco',
    scientific: 'Nicotiana tabacum',
    wikipedia: 'Nicotiana tabacum',
    section: 'crop',
    kind: 'Herb',
    commonsCategory: 'Tobacco fields',
    production: { owid: 'tobacco-production' },
    recognise: [
      'Rows of tall plants with very large, broad, pale green leaves and pink flower clusters on top.',
      'Tall wooden or brick curing barns nearby, often with gaps for air.',
    ],
    lookalikes: [{ name: 'Cabbage-like vegetables', tell: 'Tobacco is much taller, with leaves spiralling up a single stem.' }],
    nativeRange: 'South America (the Andes), domesticated in the Americas.',
    grownIn: 'China, India, Brazil (Rio Grande do Sul, Santa Catarina), Zimbabwe, Indonesia, the US (Kentucky, North Carolina), Malawi, Pakistan and Turkey.',
    clueCountries: ['CN', 'IN', 'BR', 'ZW', 'ID', 'US', 'TR'],
    science: ['Tobacco needs a warm, frost-free season of about four months and well-drained soil. The leaves are cured (dried) in barns, by air, sun, fire or heated flues.'],
    history: ['Tobacco was smoked across the Americas long before Europeans arrived. It was the first cash crop of the English colony of Virginia (1612) and later spread to Africa and Asia.'],
    tips: ['Tobacco fields with curing barns in the green hills of southern Brazil, or in Malawi and Zimbabwe.'],
    sources: ['https://en.wikipedia.org/wiki/Nicotiana_tabacum'],
  },
  {
    id: 'grapevine',
    name: 'Grapevine',
    scientific: 'Vitis vinifera',
    wikipedia: 'Vitis vinifera',
    section: 'crop',
    kind: 'Climbing vine',
    commonsCategory: 'Vineyards',
    production: { owid: 'grapes-production' },
    recognise: [
      'Vines trained in long straight rows on wires and posts, or as low bushes.',
      'Lobed leaves; bunches of grapes in late summer; bare twisted stems in winter.',
      'Often on sunny slopes, sometimes terraced.',
    ],
    lookalikes: [{ name: 'Kiwi or hops', tell: 'Kiwi grows on high overhead pergolas; hops climb very tall poles and wires.' }],
    nativeRange: 'The Caucasus and the Near East (Georgia, Armenia, Iran), where wine was first made about 8,000 years ago.',
    grownIn: 'China, Italy, Spain, France, the US (California), Turkey, India, Chile, Argentina, South Africa, Australia, Germany, Portugal, Georgia and Moldova.',
    clueCountries: ['IT', 'ES', 'FR', 'PT', 'DE', 'CL', 'AR', 'ZA', 'AU', 'US', 'TR', 'GE'],
    science: ['Wine grapes grow best between about 30° and 50° latitude in both hemispheres, with warm dry summers and cool winters. Slopes facing the sun and near rivers get more warmth, which is why vineyards cover valley sides in Germany and France.'],
    history: ['Greeks and Romans spread vineyards across the Mediterranean and up the Rhine and Moselle. Spanish missionaries planted vines in Chile, Argentina and California; Dutch and Huguenot settlers brought them to South Africa\'s Cape.'],
    tips: [
      'Steep vineyards above a river: the Moselle or Rhine (Germany) or the Douro (Portugal).',
      'Vineyards in the Southern Hemisphere with mountains behind: Mendoza (Argentina), central Chile, or the Western Cape (South Africa).',
    ],
    sources: ['https://en.wikipedia.org/wiki/Vitis_vinifera'],
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    scientific: 'Ananas comosus',
    wikipedia: 'Pineapple',
    section: 'crop',
    kind: 'Herb (bromeliad)',
    commonsCategory: 'Pineapple plantations',
    production: { mainProducers: ['PH', 'CR', 'BR', 'ID', 'CN', 'IN', 'TH', 'NG', 'MX', 'CO'] },
    recognise: [
      'Knee-high rosettes of stiff, spiky, grey-green leaves in dense rows.',
      'A single fruit rising from the centre of each plant.',
    ],
    lookalikes: [{ name: 'Agave and sisal', tell: 'Agave and sisal are much larger rosettes with thick, fleshy leaves.' }],
    nativeRange: 'South America: southern Brazil and Paraguay.',
    grownIn: 'The Philippines, Costa Rica (the largest exporter), Brazil, Indonesia, China, India, Thailand, Nigeria and Mexico; historically Hawaii.',
    clueCountries: ['PH', 'CR', 'BR', 'ID', 'TH', 'MX'],
    science: ['Pineapple is a bromeliad adapted to dry spells: it stores water in its leaves and, like cacti, uses CAM photosynthesis. It needs warmth and cannot stand frost.'],
    history: ['Columbus met pineapple in Guadeloupe in 1493. It became a luxury in Europe. In the 20th century Hawaii was the world\'s pineapple capital (Dole), before production moved to the Philippines and Costa Rica.'],
    tips: ['Huge pineapple fields: northern Costa Rica, Mindanao (Philippines) or central Thailand.'],
    sources: ['https://en.wikipedia.org/wiki/Pineapple'],
  },
  {
    id: 'rubber',
    photoSearch: 'rubber plantation',
    name: 'Rubber tree',
    scientific: 'Hevea brasiliensis',
    wikipedia: 'Hevea brasiliensis',
    section: 'crop',
    kind: 'Tree',
    commonsCategory: 'Rubber plantations',
    production: { mainProducers: ['TH', 'ID', 'VN', 'IN', 'CN', 'MY', 'PH', 'KH', 'LA', 'LK'] },
    recognise: [
      'Plantations of straight, thin, pale grey trunks in perfectly regular rows, with a light canopy.',
      'Spiral cuts on the trunks with small cups attached to catch the white latex.',
      'Bare in the dry season (it drops its leaves).',
    ],
    lookalikes: [{ id: 'eucalyptus', name: 'Eucalyptus plantation', tell: 'Eucalyptus has peeling bark and narrow drooping leaves; rubber trunks have tapping cuts and cups.' }],
    nativeRange: 'The Amazon rainforest (Brazil, Peru, Bolivia, Colombia).',
    grownIn: 'Southeast Asia produces about 90% of natural rubber: Thailand, Indonesia, Vietnam, Malaysia; also India (Kerala), China (Yunnan, Hainan), Cambodia, Laos and Sri Lanka.',
    clueCountries: ['TH', 'ID', 'VN', 'MY', 'IN', 'KH', 'LA', 'LK'],
    science: ['Rubber trees need a hot, wet equatorial climate with rain through most of the year and deep, well-drained soils.'],
    history: [
      'The Amazon rubber boom (1879–1912) made Manaus rich. In 1876 Henry Wickham shipped about 70,000 seeds from Brazil to Kew Gardens in London; seedlings were sent to Ceylon and Malaya, where plantations soon outproduced the Amazon, ending the boom.',
    ],
    tips: ['Rows of thin, identical grey trunks with cups: southern Thailand, Malaysia, Vietnam or Kerala (India).'],
    sources: ['https://en.wikipedia.org/wiki/Hevea_brasiliensis', 'https://en.wikipedia.org/wiki/Amazon_rubber_boom'],
  },
]
