import type { Plant } from './types'

// Cacti and cactus-like desert plants. Many grow in only one region, so they pin down a guess.

export const desertPlants: Plant[] = [
  {
    id: 'cardon',
    name: 'Cardón (Mexican giant cardon)',
    scientific: 'Pachycereus pringlei',
    wikipedia: 'Pachycereus pringlei',
    section: 'tree',
    group: 'Cacti & desert plants',
    kind: 'Cactus',
    photoSearch: 'Pachycereus pringlei Baja California',
    recognise: [
      'The largest cactus in the world: a massive trunk up to 1 m thick and 15–20 m tall.',
      'Many thick arms that branch from low down on the trunk, like a giant candelabra.',
      'Grows in open desert scrub, often near the sea.',
    ],
    lookalikes: [{ id: 'saguaro', name: 'Saguaro', tell: 'Saguaro has a single tall trunk with arms starting higher up, and only grows in Arizona and Sonora; cardón branches low and is the Baja California giant.' }],
    nativeRange: 'The Baja California peninsula and the coast and islands of Sonora (Mexico).',
    grownIn: 'Wild.',
    clueCountries: ['MX'],
    science: [
      'Cardón lives in one of the driest parts of North America, where fog and rare rain are the only water. It relies on bacteria around its roots that help it grow on bare rock, and stores water in its pleated trunk.',
    ],
    history: ['Indigenous peoples of Baja California ate its fruit and ground its seeds. It gives its name to many places on the peninsula.'],
    tips: ['Huge low-branching cacti with the sea nearby: Baja California (Mexico), unmistakably.'],
    remember: ['Cardón = the "candelabra of Baja": arms start low like a chandelier sitting on the ground.'],
    sources: ['https://en.wikipedia.org/wiki/Pachycereus_pringlei'],
  },
  {
    id: 'organ-pipe',
    name: 'Organ pipe cactus',
    scientific: 'Stenocereus thurberi',
    wikipedia: 'Stenocereus thurberi',
    section: 'tree',
    group: 'Cacti & desert plants',
    kind: 'Cactus',
    recognise: [
      'Many slender stems rising straight up from the ground in a cluster, with no main trunk.',
      'Looks like the pipes of a church organ.',
    ],
    lookalikes: [{ id: 'saguaro', name: 'Saguaro', tell: 'Saguaro has one main trunk with arms; organ pipe has many stems from the base.' }],
    nativeRange: 'Sonora and Sinaloa (Mexico), Baja California, and a small area of southern Arizona (Organ Pipe Cactus National Monument).',
    grownIn: 'Wild.',
    clueCountries: ['MX', 'US'],
    science: ['Organ pipe is frost-sensitive, so in Arizona it only grows on warm south-facing slopes at the northern edge of its range.'],
    history: ['The Tohono O\'odham people harvested its fruit (pitaya). Organ Pipe Cactus National Monument in Arizona was created in 1937 to protect it.'],
    tips: ['Clusters of upright stems in the desert: Sonora or Sinaloa (Mexico), rarely southern Arizona.'],
    remember: ['Organ pipe: a bundle of pipes stuck in the ground, no trunk, just like a church organ.'],
    sources: ['https://en.wikipedia.org/wiki/Stenocereus_thurberi'],
  },
  {
    id: 'candelabra-cactus',
    name: 'Candelabra cactus (Tehuacán)',
    scientific: 'Pachycereus weberi',
    wikipedia: 'Pachycereus weberi',
    section: 'tree',
    group: 'Cacti & desert plants',
    kind: 'Cactus',
    photoSearch: 'Tehuacan-Cuicatlan columnar cactus forest',
    recognise: [
      'A huge tree-like cactus with a short trunk and dozens of upright arms, forming a massive candelabra.',
      'Grows together with forests of other columnar cacti on hills in southern Mexico.',
    ],
    lookalikes: [{ id: 'cardon', name: 'Cardón', tell: 'Cardón grows in Baja California by the sea; the candelabra cactus is in the highlands of Puebla and Oaxaca.' }],
    nativeRange: 'Southern Mexico: Puebla, Oaxaca and Guerrero, especially the Tehuacán–Cuicatlán valley.',
    grownIn: 'Wild.',
    clueCountries: ['MX'],
    science: ['The Tehuacán–Cuicatlán valley lies in the rain shadow of the Sierra Madre, so it is dry despite being in the tropics. It has one of the highest densities of columnar cacti in the world.'],
    history: ['The Tehuacán valley is where some of the earliest evidence of maize farming was found. It became a UNESCO World Heritage Site in 2018.'],
    tips: ['Hills covered in forests of tall columnar cacti, in green-brown tropical dry country: Puebla or Oaxaca (Mexico).'],
    remember: ['Southern Mexico has "cactus forests": if the cacti are so many they look like a forest, think Puebla/Oaxaca.'],
    sources: ['https://en.wikipedia.org/wiki/Pachycereus_weberi', 'https://en.wikipedia.org/wiki/Tehuac%C3%A1n-Cuicatl%C3%A1n_Biosphere_Reserve'],
  },
  {
    id: 'mandacaru',
    name: 'Mandacaru',
    scientific: 'Cereus jamacaru',
    wikipedia: 'Cereus jamacaru',
    section: 'tree',
    group: 'Cacti & desert plants',
    kind: 'Cactus',
    photoSearch: 'mandacaru caatinga',
    recognise: [
      'A tall, tree-like cactus with a woody trunk and upright blue-green arms.',
      'Stands out above the grey, leafless thorn scrub (caatinga) in the dry season.',
    ],
    lookalikes: [{ name: 'Xique-xique (Pilosocereus)', tell: 'A smaller, sprawling cactus of the same region, with woolly tips.' }],
    nativeRange: 'The caatinga of north-east Brazil: Ceará, Rio Grande do Norte, Paraíba, Pernambuco, Alagoas, Sergipe, Bahia, Piauí and northern Minas Gerais.',
    grownIn: 'Wild; also planted as a living fence around farms.',
    clueCountries: ['BR'],
    science: ['The caatinga has a long dry season and irregular rain, with droughts that can last years. The mandacaru stores water and is used to feed cattle in droughts, after the spines are burnt off.'],
    history: ['In sertão folklore, the mandacaru flowering means rain is coming. It appears in many forró songs as a symbol of the Northeast.'],
    tips: ['Tall cacti above grey thorny scrub: the sertão of north-east Brazil. Brazil has cacti, not only rainforest!'],
    remember: ['Mandacaru = the "cactus of the sertão": if Brazil looks like a desert with tree cacti, you are in the Northeast.'],
    sources: ['https://en.wikipedia.org/wiki/Cereus_jamacaru', 'https://en.wikipedia.org/wiki/Caatinga'],
  },
  {
    id: 'andean-cardon',
    name: 'Andean cardón',
    scientific: 'Leucostele atacamensis',
    wikipedia: 'Echinopsis atacamensis',
    section: 'tree',
    group: 'Cacti & desert plants',
    kind: 'Cactus',
    photoSearch: 'Los Cardones National Park',
    recognise: [
      'Tall columnar cacti, sometimes with a few arms, scattered across high, bare Andean valleys and plateaus.',
      'Often with mountains, red rock and dry grass in the background, at 2,000–4,000 m.',
    ],
    lookalikes: [{ id: 'saguaro', name: 'Saguaro', tell: 'Saguaro grows in the low Sonoran Desert; the Andean cardón grows high in the Andes, often with snowy peaks behind.' }],
    nativeRange: 'The high Andes of north-west Argentina (Jujuy, Salta, Catamarca, Tucumán), southern Bolivia and northern Chile.',
    grownIn: 'Wild; its wood is used for doors and furniture in Andean villages.',
    clueCountries: ['AR', 'BO', 'CL'],
    science: ['At high altitude it is dry, sunny and has frosty nights. The dense spines and hairs protect the stem from strong ultraviolet light and cold.'],
    history: ['Los Cardones National Park in Salta protects huge stands. Churches in the Quebrada de Humahuaca use cardón wood for doors and ceilings.'],
    tips: ['Columnar cacti with Andean mountains behind: north-west Argentina (Salta, Jujuy) or Bolivia.'],
    remember: ['Cacti with snow on the mountains behind them = the Andes, not Mexico.'],
    sources: ['https://en.wikipedia.org/wiki/Echinopsis_atacamensis', 'https://en.wikipedia.org/wiki/Los_Cardones_National_Park'],
  },
  {
    id: 'candelabra-euphorbia',
    name: 'Candelabra tree (euphorbia)',
    scientific: 'Euphorbia ingens',
    wikipedia: 'Euphorbia ingens',
    section: 'tree',
    group: 'Cacti & desert plants',
    kind: 'Succulent (not a cactus)',
    recognise: [
      'Looks like a big cactus tree: a short trunk and a dense, rounded crown of upright, ribbed green arms.',
      'Grows in African savanna and on rocky hills, often next to acacias.',
      'Not a cactus: it has milky, poisonous sap and no spine cushions.',
    ],
    lookalikes: [
      { id: 'saguaro', name: 'Saguaro and other cacti', tell: 'True cacti only grow wild in the Americas. A "cactus tree" in Africa is almost always a euphorbia.' },
      { name: 'Canary Island spurge', tell: 'A shrubby euphorbia forming low cactus-like clumps on the Canary Islands.' },
    ],
    nativeRange: 'Eastern and southern Africa: South Africa (Limpopo, Mpumalanga, KwaZulu-Natal), Eswatini, Botswana, Zimbabwe, Mozambique, Kenya and Tanzania; related species such as Euphorbia candelabrum grow across East Africa and Ethiopia.',
    grownIn: 'Wild; also planted as hedges.',
    clueCountries: ['ZA', 'SZ', 'BW', 'KE', 'TZ'],
    science: ['This is convergent evolution: euphorbias in Africa and cacti in the Americas evolved the same solution (fat green stems that store water, no leaves) to the same problem, drought, completely independently.'],
    history: ['The poisonous latex was used for fishing and arrow poison. Many euphorbias are protected in South Africa.'],
    tips: ['"Cactus trees" in Africa: South Africa\'s bushveld (Limpopo, Mpumalanga) or East African savanna.'],
    remember: ['Cacti are American; in Africa a "cactus" is an impostor: the euphorbia.'],
    sources: ['https://en.wikipedia.org/wiki/Euphorbia_ingens'],
  },
  {
    id: 'agave',
    name: 'Agave and sisal',
    scientific: 'Agave',
    wikipedia: 'Agave',
    section: 'tree',
    group: 'Cacti & desert plants',
    kind: 'Succulent',
    photoSearch: 'blue agave field Tequila Jalisco',
    recognise: [
      'A large rosette of thick, fleshy, sword-shaped leaves with sharp spines at the tips and edges.',
      'After many years it sends up a single enormous flower stalk, then dies.',
      'Planted in rows: blue-grey blue agave fields in Mexico, green sisal plantations in East Africa and Brazil.',
    ],
    lookalikes: [
      { id: 'pineapple', name: 'Pineapple', tell: 'Pineapple is knee-high with a fruit in the centre.' },
      { name: 'Aloe', tell: 'Aloes are smaller, often with orange or red flower spikes, and are native to Africa.' },
    ],
    nativeRange: 'Mexico and the south-western US.',
    grownIn: 'Blue agave for tequila in Jalisco (Mexico); sisal fibre in Tanzania, Kenya, Madagascar and Bahia (Brazil); ornamental agaves around the Mediterranean.',
    clueCountries: ['MX', 'BR', 'TZ', 'KE', 'MG', 'ES'],
    science: ['Agaves store water in their leaves and, like cacti and pineapple, use CAM photosynthesis to save water, taking in carbon dioxide only at night.'],
    history: ['Agave fibre, food and drinks (pulque, mezcal, tequila) are ancient in Mexico. Germans took sisal from Mexico to German East Africa (Tanzania) in 1893, starting a huge plantation industry.'],
    tips: ['Blue-grey agave fields on red soil: Jalisco (Mexico). Sisal plantations: Tanzania or north-east Brazil.'],
    remember: ['Tequila comes from Tequila, a town in Jalisco: blue agave fields = Jalisco.'],
    sources: ['https://en.wikipedia.org/wiki/Agave', 'https://en.wikipedia.org/wiki/Sisal'],
  },
  {
    id: 'joshua-tree',
    name: 'Joshua tree',
    scientific: 'Yucca brevifolia',
    wikipedia: 'Yucca brevifolia',
    section: 'tree',
    group: 'Cacti & desert plants',
    kind: 'Yucca',
    recognise: [
      'A shaggy, tree-like yucca with twisted, spiky branches ending in clusters of dagger-shaped leaves.',
      'Scattered across flat, high desert, often with mountains around.',
    ],
    lookalikes: [{ id: 'saguaro', name: 'Saguaro', tell: 'Saguaro is a smooth green column with arms; Joshua trees have spiky leaf clusters on branching limbs.' }],
    nativeRange: 'Only the Mojave Desert: south-eastern California, southern Nevada, and small parts of Arizona and Utah.',
    grownIn: 'Wild.',
    clueCountries: ['US'],
    science: ['The Joshua tree marks the Mojave Desert, which is higher and colder than the Sonoran Desert to the south, so saguaros and Joshua trees almost never grow together.'],
    history: ['Mormon settlers crossing the Mojave in the 1850s are said to have named it after the biblical Joshua raising his arms in prayer.'],
    tips: ['Joshua trees: the Mojave (California/Nevada). Saguaros: the Sonoran Desert (Arizona/Sonora).'],
    remember: ['Joshua = Mojave, saguaro = Sonoran: J for "Jagged", S for "Smooth column".'],
    sources: ['https://en.wikipedia.org/wiki/Yucca_brevifolia'],
  },
]

export const desertRegions: Record<string, string[]> = {
  'cardon': ['MX-BCN', 'MX-BCS', 'MX-SON'],
  'organ-pipe': ['MX-SON', 'MX-SIN', 'MX-BCS', 'MX-BCN', 'US-AZ'],
  'candelabra-cactus': ['MX-PUE', 'MX-OAX', 'MX-GRO'],
  'mandacaru': ['BR-CE', 'BR-RN', 'BR-PB', 'BR-PE', 'BR-AL', 'BR-SE', 'BR-BA', 'BR-PI', 'BR-MG'],
  'andean-cardon': ['AR-Y', 'AR-A', 'AR-K', 'AR-T', 'CL-AN', 'CL-AP', 'CL-TA'],
  'candelabra-euphorbia': ['ZA-LP', 'ZA-MP', 'ZA-KZN'],
  'agave': ['MX-JAL', 'MX-OAX', 'MX-MIC', 'MX-GUA', 'MX-NAY', 'MX-TAM', 'BR-BA', 'BR-PB', 'ES-AN', 'ES-MC', 'ES-CN'],
  'joshua-tree': ['US-CA', 'US-NV', 'US-AZ', 'US-UT'],
}
