import type { Plant } from './types'

// Forest types and biomes: what the landscape looks like, which latitude band it occupies and why.
// Photos come from Wikipedia and Commons searches only (no single species to look up).

export const forests: Plant[] = [
  {
    id: 'taiga',
    name: 'Taiga (boreal forest)',
    wikipedia: 'Taiga',
    section: 'forest',
    kind: 'Coniferous forest',
    latitude: 'About 50°–70° N',
    latitudeBands: [[50, 70]],
    photoSearch: 'taiga forest Russia',
    recognise: [
      'Endless dark forest of spruce, pine, fir and larch, with birch and aspen mixed in.',
      'Flat or gently rolling land, many lakes and bogs, sandy or peaty soil.',
      'Few buildings; long straight roads through the trees.',
    ],
    lookalikes: [{ id: 'temperate-broadleaf', name: 'Temperate broadleaf forest', tell: 'Broadleaf forest is lighter green with oak, beech and maple, and bare in winter; taiga is dark and mostly evergreen.' }],
    nativeRange: 'A belt around the whole Northern Hemisphere: Scandinavia, Finland, Russia (European north and Siberia), Canada and Alaska.',
    grownIn: 'The largest land biome on earth, about 30% of the world\'s forest.',
    clueCountries: ['RU', 'FI', 'SE', 'NO', 'CA', 'US', 'EE', 'LV'],
    science: [
      'Winters are long and brutally cold (often below −30 °C) and summers short and cool, with only 50–100 frost-free days. Conifers win here: their needles survive freezing, stay on the tree to photosynthesise as soon as it warms up, and their cone shape sheds snow.',
      'Cold slows decomposition, so soils are acidic and poor (podzols), with a thick layer of needles and moss.',
    ],
    history: ['The taiga was the source of the fur trade that drove Russian expansion across Siberia and French and British exploration of Canada. Today it is a huge source of timber and paper.'],
    tips: [
      'Dense conifer forest on flat land with lakes: Finland, northern Sweden, Russia or Canada.',
      'Check the sign language and road markings; the forest alone looks very similar across all of them.',
    ],
    remember: ['Taiga = "the green belt of the North": a dark ring of conifers wrapped around the top of the globe.'],
    sources: ['https://en.wikipedia.org/wiki/Taiga'],
  },
  {
    id: 'birch-forest',
    name: 'Birch forest',
    wikipedia: 'Betula pendula',
    section: 'forest',
    kind: 'Broadleaf forest',
    latitude: 'About 50°–70° N (mountain birch up to the tree line near 70° N)',
    latitudeBands: [[50, 70]],
    photoSearch: 'birch forest Russia',
    recognise: [
      'White-trunked birches, often in pure stands, with a light, airy canopy and grass underneath.',
      'In Siberia\'s forest-steppe, small islands of birch ("kolki") scattered across open fields.',
      'In northern Scandinavia and Iceland, low, twisted mountain birch woods near the tree line.',
    ],
    lookalikes: [{ id: 'taiga', name: 'Taiga', tell: 'Taiga is darker and dominated by conifers; birch forest is bright and white-trunked.' }],
    nativeRange: 'Northern and eastern Europe and northern Asia: Scandinavia, Finland, the Baltics, Belarus, Russia and Kazakhstan; mountain birch in Norway, Sweden, Finnish Lapland and Iceland.',
    grownIn: 'Pioneer forest on abandoned farmland and after fires or logging; the typical forest of West Siberia\'s forest-steppe.',
    clueCountries: ['RU', 'FI', 'EE', 'LV', 'LT', 'BY', 'SE', 'NO', 'IS', 'KZ'],
    science: [
      'Birch is a pioneer: its tiny winged seeds blow long distances and it grows fast in full sun, so it takes over open ground first. Later, spruce grows up under it and replaces it, unless fire or clearing resets the cycle.',
      'In the forest-steppe of West Siberia and northern Kazakhstan, it is too dry for dense conifer forest, so birch grows in patches where water collects, leaving grassland in between.',
      'Mountain birch forms the tree line in Scandinavia instead of conifers, because the maritime climate there has mild winters but cool summers.',
    ],
    history: ['Birch is Russia\'s unofficial national tree and appears in countless songs and paintings. Soviet farm abandonment after 1991 let birch reclaim millions of hectares of fields.'],
    tips: [
      'Patches of birch between flat fields: West Siberia (Omsk, Novosibirsk, Tyumen) or northern Kazakhstan.',
      'Birch along every road in flat country: Finland, the Baltics, Belarus or European Russia.',
    ],
    remember: ['Birch forest = "the white army of the north": thousands of white soldiers standing to attention in flat country.'],
    sources: ['https://en.wikipedia.org/wiki/Betula_pendula', 'https://en.wikipedia.org/wiki/Forest_steppe'],
  },
  {
    id: 'temperate-broadleaf',
    name: 'Temperate broadleaf forest (beech and oak)',
    wikipedia: 'Temperate deciduous forest',
    section: 'forest',
    kind: 'Broadleaf forest',
    latitude: 'About 40°–60° N (and a small band in the south)',
    latitudeBands: [[40, 60]],
    photoSearch: 'beech forest',
    recognise: [
      'Tall broadleaf trees such as beech, oak, maple and hornbeam, light green in summer and bare in winter.',
      'Brilliant autumn colours; a carpet of fallen leaves.',
      'Usually broken up into woods between farmland and villages.',
    ],
    lookalikes: [{ id: 'taiga', name: 'Taiga', tell: 'Taiga is dark, evergreen and coniferous.' }],
    nativeRange: 'Western and central Europe, the eastern United States, north-east China, Korea and Japan.',
    grownIn: 'Much of it was cleared for farming centuries ago, leaving patchwork landscapes.',
    clueCountries: ['DE', 'FR', 'GB', 'PL', 'CZ', 'SK', 'RO', 'SI', 'HR', 'US', 'JP', 'KR'],
    science: [
      'Moderate climate with four seasons, rain all year and cold (but not extreme) winters. Broad leaves capture a lot of light in summer; dropping them in autumn avoids frost damage and water loss when the ground is frozen.',
      'Leaf litter decomposes fast, giving rich brown soils, which is why these regions became prime farmland.',
    ],
    history: ['Most of Europe was once covered in this forest. Medieval and later clearing for farms and fuel reduced it to scattered woods; beech forests of the Carpathians are UNESCO-listed "primeval forests".'],
    tips: [
      'Beech and oak woods between fields: central and western Europe, or the eastern US.',
      'Bright red maples in autumn coverage: the eastern US, Canada, Korea or Japan.',
    ],
    remember: ['Broadleaf forest changes clothes every season: green in summer, fire colours in autumn, bare in winter.'],
    sources: ['https://en.wikipedia.org/wiki/Temperate_deciduous_forest'],
  },
  {
    id: 'mediterranean-woodland',
    name: 'Mediterranean woodland and scrub',
    wikipedia: 'Mediterranean forests, woodlands, and scrub',
    section: 'forest',
    kind: 'Woodland and scrub',
    latitude: 'About 30°–45° N and S, on the western sides of continents',
    latitudeBands: [[30, 45], [-45, -30]],
    photoSearch: 'maquis shrubland',
    recognise: [
      'Low, dense, evergreen shrubs (maquis, garrigue, chaparral, fynbos) with small, tough leaves.',
      'Scattered holm oaks, cork oaks, stone pines and olive trees; dry golden grass in summer.',
      'Rocky hills with white limestone or red soil.',
    ],
    lookalikes: [{ id: 'savanna', name: 'Savanna', tell: 'Savanna is in the tropics with grass and scattered flat-topped trees; Mediterranean scrub is dense shrubs on rocky hills.' }],
    nativeRange: 'The Mediterranean basin, California, central Chile, the Western Cape of South Africa and south-western and southern Australia.',
    grownIn: 'Heavily shaped by grazing, fire and olive and vine growing.',
    clueCountries: ['ES', 'PT', 'IT', 'GR', 'TR', 'HR', 'US', 'CL', 'ZA', 'AU'],
    science: [
      'The Mediterranean climate has hot, dry summers and mild, wet winters. It only occurs between about 30° and 45° latitude on the west side of continents, where cool ocean currents and subtropical high pressure block summer rain.',
      'Plants have small, waxy or hairy leaves to save water and often resprout after fire.',
    ],
    history: ['People have grazed goats and burned the Mediterranean scrub for thousands of years; many of the bare, rocky hills of Greece and Spain were once forest.'],
    tips: [
      'The same landscape appears on five continents: combine it with other clues. Fynbos with mountains: Western Cape. Chaparral with golden hills: California. Matorral: central Chile.',
    ],
    remember: ['Mediterranean climate = "wet winter, dry summer, west coast, 30–45°": the same recipe on five continents.'],
    sources: ['https://en.wikipedia.org/wiki/Mediterranean_forests,_woodlands,_and_scrub'],
  },
  {
    id: 'tropical-rainforest',
    name: 'Tropical rainforest',
    wikipedia: 'Tropical rainforest',
    section: 'forest',
    kind: 'Tropical forest',
    latitude: 'About 10° N – 10° S',
    latitudeBands: [[-10, 10]],
    photoSearch: 'Amazon rainforest road',
    recognise: [
      'A dense, tall, many-layered wall of green, with lianas, palms and giant trees.',
      'Red or orange clay roads, heavy clouds and wet ground.',
    ],
    lookalikes: [{ id: 'atlantic-forest', name: 'Atlantic Forest', tell: 'The Atlantic Forest looks similar but grows on the steep coastal mountains of south-eastern Brazil.' }],
    nativeRange: 'The Amazon basin, the Congo basin, West Africa, Southeast Asia (Borneo, Sumatra, New Guinea) and north-east Australia.',
    grownIn: 'Being cleared for cattle, soy and oil palm, especially in Brazil and Indonesia.',
    clueCountries: ['BR', 'CO', 'PE', 'EC', 'ID', 'MY', 'CD', 'GA'],
    science: [
      'Near the equator the sun is overhead all year, so it is hot (25–28 °C) and rising warm air brings rain almost every day (over 2,000 mm a year). With no winter, trees grow all year, supporting half of all land species.',
      'Surprisingly, the soils are poor: nutrients are held in the living plants and recycled quickly, which is why cleared land often degrades fast.',
    ],
    history: ['The Amazon rubber boom and later road building (the Trans-Amazonian Highway, 1970s) opened the rainforest to settlement. Deforestation follows roads in a "fishbone" pattern.'],
    tips: ['Rainforest with Portuguese signs and red dirt roads: Brazilian Amazon (Pará, Rondônia, Acre). With oil palm and Indonesian signs: Sumatra or Borneo.'],
    remember: ['Rainforest = "the greenhouse of the equator": hot, wet and growing every day of the year.'],
    sources: ['https://en.wikipedia.org/wiki/Tropical_rainforest'],
  },
  {
    id: 'atlantic-forest',
    name: 'Atlantic Forest (Mata Atlântica)',
    wikipedia: 'Atlantic Forest',
    section: 'forest',
    kind: 'Tropical forest',
    latitude: 'About 5°–30° S along the Brazilian coast',
    latitudeBands: [[-30, -5]],
    photoSearch: 'Mata Atlantica Serra do Mar',
    recognise: [
      'Lush, dense forest on steep, rounded coastal mountains, often with granite domes.',
      'Many bromeliads, tree ferns and embaúba (Cecropia) trees with silvery leaves.',
    ],
    lookalikes: [{ id: 'tropical-rainforest', name: 'Amazon rainforest', tell: 'The Amazon is flat lowland; the Atlantic Forest clings to steep coastal mountains.' }],
    nativeRange: 'The Brazilian coast from Rio Grande do Norte to Rio Grande do Sul, inland into Minas Gerais, plus eastern Paraguay and Misiones (Argentina).',
    grownIn: 'Only about 12% of the original forest remains, in fragments.',
    clueCountries: ['BR', 'AR', 'PY'],
    science: ['Moist air from the Atlantic rises over the coastal mountains (Serra do Mar), cools and drops heavy rain, supporting rainforest on the slopes even outside the equatorial belt.'],
    history: ['The forest was cleared for sugarcane, then coffee, and for cities: Rio de Janeiro and São Paulo sit in it. The Tijuca Forest in Rio was replanted in the 1860s to protect the city\'s water supply.'],
    tips: ['Green mountains with granite domes and Portuguese signs: south-eastern Brazil (Rio de Janeiro, São Paulo, Espírito Santo, Santa Catarina).'],
    remember: ['Atlantic Forest = "rainforest on a rollercoaster": the same jungle, but on steep coastal mountains.'],
    sources: ['https://en.wikipedia.org/wiki/Atlantic_Forest'],
  },
  {
    id: 'cerrado',
    name: 'Cerrado (Brazilian savanna)',
    wikipedia: 'Cerrado',
    section: 'forest',
    kind: 'Savanna',
    latitude: 'About 5°–25° S in central Brazil',
    latitudeBands: [[-25, -5]],
    commonsCategory: 'Cerrado',
    photoSearch: 'cerrado Chapada dos Veadeiros',
    recognise: [
      'Open grassland dotted with small, twisted trees with thick, corky bark.',
      'Red earth, flat plateaus (chapadas) and burnt patches in the dry season.',
      'Lines of buriti palms along streams (veredas).',
    ],
    lookalikes: [{ id: 'savanna', name: 'African savanna', tell: 'African savanna has flat-topped acacias and big game; the cerrado has twisted, corky little trees and Portuguese signs.' }],
    nativeRange: 'Central Brazil: Goiás, Tocantins, Mato Grosso, Mato Grosso do Sul, Minas Gerais, western Bahia and the Federal District, plus parts of Maranhão and Piauí; also eastern Bolivia and Paraguay.',
    grownIn: 'About half has been converted to soy, maize, cotton and pasture since the 1970s.',
    clueCountries: ['BR', 'BO', 'PY'],
    science: [
      'A strongly seasonal climate: rainy summers and a 5–6 month dry winter. Frequent natural fires and poor, acidic, aluminium-rich soils favour grass and fire-resistant trees with thick bark and deep roots.',
    ],
    history: ['Brasília was built in the middle of the cerrado in 1960. Liming the acidic soils from the 1970s turned the cerrado into one of the world\'s biggest farming regions.'],
    tips: ['Scrubby savanna with twisted trees and red soil, or huge soy fields: Goiás, Mato Grosso or western Bahia.'],
    remember: ['Cerrado = "the corky savanna": trees wear thick cork jackets to survive the fires.'],
    sources: ['https://en.wikipedia.org/wiki/Cerrado'],
  },
  {
    id: 'caatinga',
    name: 'Caatinga (thorn scrub)',
    wikipedia: 'Caatinga',
    section: 'forest',
    kind: 'Dry forest',
    latitude: 'About 3°–17° S in north-east Brazil',
    latitudeBands: [[-17, -3]],
    photoSearch: 'caatinga sertão',
    recognise: [
      'Grey, leafless, thorny scrub in the dry season that turns green within days after rain.',
      'Tree cacti (mandacaru, xique-xique) and rocky ground.',
    ],
    lookalikes: [{ id: 'cerrado', name: 'Cerrado', tell: 'The cerrado is grassier with corky trees; the caatinga is dense, grey and thorny with cacti.' }],
    nativeRange: 'The semi-arid interior (sertão) of north-east Brazil: Ceará, Rio Grande do Norte, Paraíba, Pernambuco, Alagoas, Sergipe, Bahia, Piauí and northern Minas Gerais.',
    grownIn: 'Grazed by goats and cattle.',
    clueCountries: ['BR'],
    science: ['The north-east lies in a rain shadow and at the edge of the reach of the equatorial rains; rain comes in a short season and often fails, causing severe droughts (secas). Plants drop their leaves to survive.'],
    history: ['Droughts in the sertão drove huge migrations to the Amazon and to São Paulo in the 19th and 20th centuries. "Caatinga" means "white forest" in Tupi, for its pale look in the dry season.'],
    tips: ['Grey thorny scrub with cacti and goats: the sertão of north-east Brazil.'],
    remember: ['Caatinga = "white forest": grey and dead-looking in the dry season, green overnight after rain.'],
    sources: ['https://en.wikipedia.org/wiki/Caatinga'],
  },
  {
    id: 'savanna',
    name: 'African savanna',
    wikipedia: 'Savanna',
    section: 'forest',
    kind: 'Savanna',
    latitude: 'About 5°–20° N and S of the equator',
    latitudeBands: [[5, 20], [-20, -5]],
    photoSearch: 'savanna Kenya acacia',
    recognise: [
      'Wide grassland dotted with flat-topped acacias, baobabs and termite mounds.',
      'Golden in the dry season, green in the wet season.',
    ],
    lookalikes: [{ id: 'cerrado', name: 'Cerrado', tell: 'The cerrado has twisted corky trees and Portuguese signs.' }],
    nativeRange: 'A belt around the Congo rainforest: the Sahel and Sudan zone, East Africa (Kenya, Tanzania, Uganda) and southern Africa (Botswana, Zimbabwe, northern South Africa).',
    grownIn: 'Grazing land and national parks.',
    clueCountries: ['KE', 'TZ', 'UG', 'BW', 'ZA', 'SN', 'NG', 'GH'],
    science: ['Between the rainforest and the desert, rain falls in only one season. Long dry seasons, fire and grazing animals keep trees scattered and let grass dominate.'],
    history: ['The savannas of East Africa are where humans evolved. Colonial-era national parks such as the Serengeti and Kruger protect some of the largest remaining areas.'],
    tips: ['Flat-topped acacias in golden grass: East Africa or northern South Africa and Botswana.'],
    remember: ['Savanna = "the lion\'s lawn": grass with a few umbrellas (acacias) set out for shade.'],
    sources: ['https://en.wikipedia.org/wiki/Savanna'],
  },
  {
    id: 'steppe',
    name: 'Steppe',
    wikipedia: 'Steppe',
    section: 'forest',
    kind: 'Grassland',
    latitude: 'About 40°–55° N in Eurasia',
    latitudeBands: [[40, 55]],
    photoSearch: 'Mongolian steppe grassland',
    recognise: [
      'Treeless, flat or rolling grassland to the horizon, green in spring and brown in summer.',
      'Huge skies, few villages, sometimes herds of horses or sheep.',
    ],
    lookalikes: [{ name: 'Prairie and pampas', tell: 'The American prairie and Argentine pampas look similar but are mostly farmland now.' }],
    nativeRange: 'From Ukraine and southern Russia across Kazakhstan to Mongolia and northern China.',
    grownIn: 'Much of the western steppe is now wheat fields; Mongolia and central Kazakhstan are still grazing land.',
    clueCountries: ['KZ', 'MN', 'RU', 'UA', 'KG', 'CN', 'TR'],
    science: ['Far from any ocean, the continental interior gets too little rain (250–500 mm) for trees, with very cold winters and hot summers. Grass survives drought and fire by regrowing from its roots.'],
    history: ['The steppe was the highway of nomadic empires: the Scythians, Huns and Mongols. In the 1950s the Soviet Virgin Lands campaign ploughed millions of hectares of Kazakh steppe for wheat.'],
    tips: ['Endless grass with no trees: Kazakhstan or Mongolia. Mongolia often has gers (yurts) and hills; Kazakhstan is flatter with long straight roads.'],
    remember: ['Steppe = "the sea of grass": flat and treeless to the horizon, like an ocean made of grass.'],
    sources: ['https://en.wikipedia.org/wiki/Steppe', 'https://en.wikipedia.org/wiki/Eurasian_Steppe'],
  },
  {
    id: 'tundra',
    name: 'Tundra',
    wikipedia: 'Tundra',
    section: 'forest',
    kind: 'Treeless',
    latitude: 'About 65°–75° N (and high mountains)',
    latitudeBands: [[65, 75]],
    photoSearch: 'tundra landscape',
    recognise: [
      'Treeless, low vegetation: mosses, lichens, grasses and dwarf shrubs, often with rocks and small lakes.',
      'Autumn turns it red and orange.',
    ],
    lookalikes: [{ id: 'taiga', name: 'Taiga', tell: 'Taiga has trees; the tundra begins where trees stop.' }],
    nativeRange: 'The Arctic north of the tree line: northern Russia, northern Canada, Alaska, Greenland, Iceland\'s highlands and northernmost Norway; also high mountains everywhere (alpine tundra).',
    grownIn: 'Grazed by reindeer.',
    clueCountries: ['NO', 'IS', 'GL', 'CA', 'US', 'RU', 'FI'],
    science: ['Summers are too short and cold (warmest month below about 10 °C) for trees to grow. Permanently frozen ground (permafrost) below the surface stops deep roots and drainage, making the ground boggy in summer.'],
    history: ['Sámi, Nenets and Inuit peoples have herded reindeer or hunted in the tundra for millennia. Warming is now pushing the tree line north.'],
    tips: ['Treeless, rocky, lake-dotted land with Nordic signs: Finnmark (Norway), Iceland or northern Finland. In North America: Alaska or northern Canada.'],
    remember: ['Tundra starts where the trees give up: "too cold to grow a trunk".'],
    sources: ['https://en.wikipedia.org/wiki/Tundra'],
  },
  {
    id: 'temperate-rainforest',
    name: 'Temperate rainforest',
    wikipedia: 'Temperate rainforest',
    section: 'forest',
    kind: 'Temperate forest',
    latitude: 'About 38°–60° N and S, on west-facing coasts',
    latitudeBands: [[38, 60], [-60, -38]],
    photoSearch: 'Valdivian temperate rainforest',
    recognise: [
      'Very tall, dense, dark green forest dripping with moss and ferns.',
      'Cool, misty, rainy weather; mountains close to the sea.',
    ],
    lookalikes: [{ id: 'tropical-rainforest', name: 'Tropical rainforest', tell: 'Tropical rainforest has palms and lianas in heat; temperate rainforest has giant conifers or southern beeches in cool mist.' }],
    nativeRange: 'The Pacific Northwest (Oregon, Washington, British Columbia, south-east Alaska), southern Chile (Valdivian forest), New Zealand, Tasmania, and small areas of Norway and Ireland.',
    grownIn: 'Partly logged; old-growth areas are protected in national parks.',
    clueCountries: ['CL', 'US', 'CA', 'NZ', 'AU'],
    science: ['Westerly winds carry moisture from the ocean onto west-facing coasts, where mountains force it to rise and rain (often over 2,000 mm a year). Mild temperatures and constant moisture grow some of the largest trees on earth, such as Sitka spruce and coast redwood.'],
    history: ['The Pacific Northwest\'s giant trees built the logging industry of Oregon and Washington. Chile\'s Valdivian forest has alerce trees more than 3,000 years old.'],
    tips: ['Mossy, giant-treed forest with Spanish signs: southern Chile (Los Ríos, Los Lagos, Aysén). With English: Oregon, Washington or British Columbia. With odd tree ferns: New Zealand.'],
    remember: ['Temperate rainforest = "rainforest in a raincoat": the jungle\'s cool, mossy cousin on rainy western coasts.'],
    sources: ['https://en.wikipedia.org/wiki/Temperate_rainforest'],
  },
  {
    id: 'eucalyptus-woodland',
    name: 'Australian bush (eucalyptus woodland)',
    wikipedia: 'Bushland',
    section: 'forest',
    kind: 'Woodland',
    latitude: 'About 10°–43° S in Australia',
    latitudeBands: [[-43, -10]],
    photoSearch: 'eucalyptus woodland Australia',
    recognise: [
      'Open woodland of eucalyptus (gum trees) with pale, peeling trunks and thin, grey-green crowns.',
      'Dry grass or low shrubs underneath, often red or orange soil; burnt trunks from bushfires.',
    ],
    lookalikes: [{ id: 'eucalyptus', name: 'Eucalyptus plantations', tell: 'Plantations elsewhere are dense, identical rows; the Australian bush is a natural, uneven mix of gums.' }],
    nativeRange: 'Most of Australia\'s wooded land, from the tropical north to Tasmania.',
    grownIn: 'Natural bush; also cleared for sheep and wheat in the south-east and south-west.',
    clueCountries: ['AU'],
    science: ['Australia is an old, dry continent with nutrient-poor soils and frequent fire. Eucalypts are adapted to both: they need few nutrients, resprout from buds hidden under the bark after fire, and even encourage fire with their flammable oils.'],
    history: ['Aboriginal Australians shaped the bush for over 50,000 years with "cultural burning", setting small fires that kept the woodland open.'],
    tips: ['Grey-green gums with peeling bark and red soil: Australia. The shade of the soil helps: red in the interior and Western Australia, paler in the south-east.'],
    remember: ['The Australian bush is "a forest that wants to burn": gum trees, dry grass and fire-blackened trunks.'],
    sources: ['https://en.wikipedia.org/wiki/Eucalypt_woodland'],
  },
  {
    id: 'pampas',
    name: 'Pampas',
    wikipedia: 'Pampas',
    section: 'forest',
    kind: 'Grassland',
    latitude: 'About 30°–39° S',
    latitudeBands: [[-39, -30]],
    photoSearch: 'pampa húmeda campo',
    recognise: [
      'Perfectly flat, fertile grassland and farmland to the horizon.',
      'Cattle, soy and wheat fields, lines of trees planted around farmsteads (estancias).',
    ],
    lookalikes: [{ id: 'steppe', name: 'Steppe', tell: 'The steppe is drier and often wild grassland; the pampas is greener and almost all farmed.' }],
    nativeRange: 'Buenos Aires province, La Pampa, southern Santa Fe, Córdoba and Entre Ríos (Argentina), plus Uruguay and Rio Grande do Sul (Brazil).',
    grownIn: 'Almost entirely farmland and cattle ranches.',
    clueCountries: ['AR', 'UY', 'BR'],
    science: ['Deep, fertile soils formed from wind-blown dust (loess), with rain spread through the year, make the pampas some of the best farmland in the world. It was naturally grassland because of the mix of dryness, grazing and fire.'],
    history: ['The pampas was gaucho country. After the late-19th-century "Conquest of the Desert" and European immigration, it became a huge exporter of beef and grain, making Argentina one of the richest countries in the world around 1900.'],
    tips: ['Totally flat green farmland with lines of eucalyptus around farmhouses: the Argentine pampas (Buenos Aires province), Uruguay or southern Brazil.'],
    remember: ['Pampas = "the flattest table in South America", set with cows and wheat.'],
    sources: ['https://en.wikipedia.org/wiki/Pampas'],
  },
]

export const forestRegions: Record<string, string[]> = {
  'taiga': ['RU', 'CA-QC', 'CA-ON', 'CA-MB', 'CA-SK', 'CA-AB', 'CA-BC', 'CA-NL', 'CA-YT', 'CA-NT', 'US-AK'],
  'birch-forest': ['RU-KGN', 'RU-OMS', 'RU-NVS', 'RU-TYU', 'RU-CHE', 'RU-SVE', 'RU-TOM', 'RU-ALT', 'RU-KEM', 'RU-KYA', 'RU-PER', 'RU-KIR', 'RU-KOS', 'RU-YAR', 'RU-VLA', 'RU-MOS', 'RU-TVE', 'RU-NIZ', 'RU-BA', 'RU-TA'],
  'temperate-broadleaf': ['US-PA', 'US-NY', 'US-OH', 'US-WV', 'US-VA', 'US-KY', 'US-TN', 'US-NC', 'US-MI', 'US-IN', 'US-VT', 'US-NH', 'US-MA', 'US-CT', 'US-MD'],
  'mediterranean-woodland': ['ES-AN', 'ES-CM', 'ES-EX', 'ES-CT', 'ES-VC', 'ES-MC', 'ES-IB', 'ES-MD', 'TR-35', 'TR-09', 'TR-48', 'TR-07', 'TR-33', 'TR-31', 'TR-17', 'TR-10', 'TR-45', 'US-CA', 'CL-VS', 'CL-RM', 'CL-LI', 'CL-CO', 'ZA-WC', 'AU-SA', 'AU-WA'],
  'tropical-rainforest': ['BR-AM', 'BR-PA', 'BR-AC', 'BR-RO', 'BR-RR', 'BR-AP', 'BR-MT', 'CO-AMA', 'CO-CAQ', 'CO-PUT', 'CO-GUV', 'CO-VAU', 'CO-GUA', 'CO-CHO', 'PE-LOR', 'PE-UCA', 'PE-MDD', 'ID-KB', 'ID-KT', 'ID-KI', 'ID-KU', 'ID-PA', 'ID-PB', 'ID-RI', 'ID-JA', 'MY-12', 'MY-13'],
  'atlantic-forest': ['BR-BA', 'BR-ES', 'BR-RJ', 'BR-SP', 'BR-PR', 'BR-SC', 'BR-RS', 'BR-MG', 'BR-PE', 'BR-AL', 'AR-N'],
  'cerrado': ['BR-GO', 'BR-TO', 'BR-MT', 'BR-MS', 'BR-MG', 'BR-DF', 'BR-BA', 'BR-MA', 'BR-PI'],
  'caatinga': ['BR-CE', 'BR-RN', 'BR-PB', 'BR-PE', 'BR-AL', 'BR-SE', 'BR-BA', 'BR-PI', 'BR-MG'],
  'savanna': ['ZA-LP', 'ZA-MP', 'ZA-NW', 'ZA-KZN'],
  'steppe': ['RU-ORE', 'RU-ALT', 'RU-VGG', 'RU-SAR', 'RU-ROS', 'RU-KL', 'RU-AST', 'RU-TY', 'RU-ZAB', 'CN-NM', 'CN-XJ', 'CN-QH', 'CN-GS', 'TR-42', 'TR-06', 'TR-26', 'TR-68', 'TR-70', 'TR-51'],
  'tundra': ['RU-MUR', 'RU-NEN', 'RU-YAN', 'RU-CHU', 'RU-SA', 'RU-KYA', 'RU-MAG', 'CA-NU', 'CA-NT', 'CA-YT', 'CA-QC', 'CA-NL', 'US-AK'],
  'temperate-rainforest': ['CL-LR', 'CL-LL', 'CL-AI', 'CL-AR', 'US-WA', 'US-OR', 'US-CA', 'US-AK', 'CA-BC', 'AU-TAS'],
  'eucalyptus-woodland': ['AU'],
  'pampas': ['AR-B', 'AR-L', 'AR-S', 'AR-X', 'AR-E', 'BR-RS'],
}
