import type { Plant } from './types'

// Ferns and "outlier" plants: unusual plants that only grow (or only grow by the roadside) in a few
// places, so one sighting narrows the guess a lot.

const JP_NOT_HOKKAIDO = Array.from({ length: 47 }, (_, i) => `JP-${String(i + 1).padStart(2, '0')}`).filter((c) => c !== 'JP-01')

export const oddities: Plant[] = [
  // ---- Ferns ----
  {
    id: 'tree-fern',
    name: 'Tree ferns',
    scientific: 'Cyathea',
    wikipedia: 'Tree fern',
    section: 'tree',
    group: 'Ferns',
    kind: 'Fern',
    photoSearch: ['tree ferns forest New Zealand road', 'Dicksonia antarctica forest Tasmania', 'tree fern forest Hawaii'],
    recognise: [
      'A crown of huge, lacy fern fronds on top of a thick, hairy, fibrous trunk, 2–10 m tall.',
      'Grows in wet, shady gullies and forest edges, often many together along the road.',
      'New fronds unroll from tight spirals ("koru").',
    ],
    lookalikes: [
      { name: 'Palms', tell: 'Palm leaves are stiff and fan- or feather-shaped; tree fern fronds are soft, finely divided and lacy.' },
      { id: 'bracken', name: 'Bracken', tell: 'Bracken is a knee-to-head-high fern with no trunk.' },
    ],
    nativeRange: 'Wet temperate and tropical mountain forests of the Southern Hemisphere and tropics: New Zealand, southeastern Australia and Tasmania, Hawaii, Réunion, Costa Rica, southern Brazil\'s araucaria forests, Sri Lanka and Malaysia\'s highlands.',
    grownIn: 'Wild in wet forest; also planted in gardens in the UK and Ireland.',
    clueCountries: ['NZ', 'AU', 'US', 'RE', 'CR', 'BR', 'LK', 'MY'],
    science: [
      'Tree ferns are an ancient group that has changed little since the time of the dinosaurs. They need constant moisture and mild temperatures without hard frost, because their fronds and trunk have no protection against drying out.',
      'The "trunk" is a column of old leaf bases and roots, not wood, so they grow slowly (a few cm a year).',
    ],
    history: [
      'The silver fern (Cyathea dealbata) is New Zealand\'s national symbol, on the All Blacks\' shirts. Māori used the silver undersides of its fronds to mark paths at night.',
      'In Brazil, the trunks of the xaxim tree fern were overharvested for plant pots and are now protected.',
    ],
    tips: [
      'Tree ferns along the road in a temperate place: New Zealand (almost everywhere), Tasmania, Victoria or NSW. In the tropics: Hawaii\'s wet slopes, Réunion, Costa Rica\'s mountains or highland Sri Lanka.',
    ],
    remember: ['Tree ferns are dinosaur umbrellas: a lacy green umbrella on a hairy stick, in wet places down south.'],
    sources: ['https://en.wikipedia.org/wiki/Tree_fern', 'https://en.wikipedia.org/wiki/Cyathea_dealbata'],
  },
  {
    id: 'bracken',
    name: 'Bracken',
    scientific: 'Pteridium aquilinum',
    wikipedia: 'Pteridium aquilinum',
    section: 'tree',
    group: 'Ferns',
    kind: 'Fern',
    photoSearch: ['bracken hillside Wales', 'bracken autumn Scotland hills'],
    recognise: [
      'Knee- to head-high ferns covering whole hillsides in a dense carpet.',
      'Bright green in summer, then rusty orange-brown from autumn through winter.',
    ],
    lookalikes: [{ id: 'heather', name: 'Heather', tell: 'Heather is a low, fine-leaved shrub that turns purple in late summer; bracken is taller, with big fronds, and turns orange-brown.' }],
    nativeRange: 'Almost worldwide, but it dominates the open hills of Britain and Ireland.',
    grownIn: 'Wild.',
    clueCountries: ['GB', 'IE'],
    science: [
      'Bracken spreads by underground stems and is poisonous to grazing animals, so it takes over pasture that sheep avoid. It thrives in the mild, wet climate of Britain and Ireland.',
    ],
    history: ['Bracken was once cut for animal bedding and roofing; as that stopped, it spread over many hillsides.'],
    tips: ['Whole hillsides of rusty-brown fern in winter or spring: Britain or Ireland (Wales, Scotland, the Lake District).'],
    remember: ['Bracken turns the British hills the colour of rust every autumn, like a fox\'s coat.'],
    sources: ['https://en.wikipedia.org/wiki/Pteridium_aquilinum'],
  },
  // ---- Regional oddities ----
  {
    id: 'giant-butterbur',
    name: 'Giant butterbur ("Hokkaido cabbage")',
    scientific: 'Petasites japonicus',
    wikipedia: 'Petasites japonicus',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Herb',
    photoSearch: ['Akita-buki Hokkaido', 'Petasites japonicus giganteus', 'giant butterbur Hokkaido roadside'],
    recognise: [
      'Huge round leaves, up to 1–1.5 m across on stalks up to 2 m tall, in dense patches along roadsides, streams and forest edges.',
      'From a distance the patches look like giant cabbages or rhubarb growing wild.',
    ],
    lookalikes: [
      { name: 'Burdock and rhubarb', tell: 'Their leaves are heart-shaped or wavy and much smaller; giant butterbur leaves are round, like an umbrella.' },
      { name: 'Skunk cabbage', tell: 'Asian skunk cabbage (Lysichiton) has upright, paddle-shaped leaves and a white flower hood, in wetlands.' },
    ],
    nativeRange: 'Japan, Sakhalin and Korea; the giant variety (Akita-buki, Ezo-buki) grows in Hokkaido and northern Honshu (Akita, Aomori, Iwate).',
    grownIn: 'Wild. The young stalks are eaten (fuki).',
    clueCountries: ['JP', 'RU'],
    science: [
      'The giant form grows in the cool, snowy north with plenty of summer moisture. Deep snow protects the roots in winter, and long summer days fuel the huge leaves.',
    ],
    history: [
      'The Ainu of Hokkaido tell of the Koropokkuru, little people who lived under butterbur leaves. The stalks are a traditional spring vegetable, and Akita\'s butterbur is famous: the leaves were used as umbrellas.',
    ],
    tips: [
      'Giant round-leaved plants along a Japanese road: Hokkaido or northern Tohoku (Akita, Aomori, Iwate). You will not see them in southern Japan.',
    ],
    remember: ['Hokkaido\'s "cabbage" is an umbrella plant: leaves big enough for a small person to hide under, as in the Ainu legend.'],
    sources: ['https://en.wikipedia.org/wiki/Petasites_japonicus', 'https://en.wikipedia.org/wiki/Koro-pok-guru'],
  },
  {
    id: 'cabbage-tree',
    name: 'Cabbage tree (tī kōuka)',
    scientific: 'Cordyline australis',
    wikipedia: 'Cordyline australis',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Tree',
    photoSearch: ['cabbage trees paddock New Zealand', 'Cordyline australis landscape'],
    recognise: [
      'A tall, slender trunk that branches a few times, each branch ending in a tuft of long, narrow, sword-like leaves.',
      'Often stands alone in farm paddocks or in wet ground.',
      'Dead leaves hang down like a skirt under each tuft.',
    ],
    lookalikes: [{ name: 'Palms and yuccas', tell: 'Palms do not branch; cabbage trees branch into several tufts. Yuccas are stiffer and grow in dry places.' }],
    nativeRange: 'New Zealand only.',
    grownIn: 'Planted in gardens and seafronts in mild parts of Britain and Ireland (where it is called the "Torbay palm") and in southeastern Australia.',
    clueCountries: ['NZ', 'GB', 'IE'],
    science: ['It is not a palm: it is related to agaves and asparagus. It tolerates wind, salt, wet soils and light frost, so it survives in open farmland where forest was cleared.'],
    history: ['Early European settlers ate the young shoots like cabbage, hence the name. Māori cooked the roots in earth ovens for their sugar.'],
    tips: [
      'Lone "palm-like" trees with branching tufts in green, grazed paddocks: New Zealand.',
      'In a seaside town in Cornwall, Devon, Wales, western Scotland or Ireland, it is a planted "Torbay palm".',
    ],
    remember: ['The cabbage tree is New Zealand\'s fake palm: a palm that forks like a candelabra.'],
    sources: ['https://en.wikipedia.org/wiki/Cordyline_australis'],
  },
  {
    id: 'kudzu',
    name: 'Kudzu',
    scientific: 'Pueraria montana',
    wikipedia: 'Kudzu',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Vine',
    photoSearch: ['kudzu Georgia roadside', 'kudzu covered trees Alabama'],
    recognise: [
      'A vine that smothers everything: trees, poles and abandoned buildings become green "topiary" monsters.',
      'Big leaves in threes, covering whole roadside slopes in summer; brown and bare in winter.',
    ],
    lookalikes: [{ name: 'Other climbing vines', tell: 'Few vines cover whole hillsides and treetops as completely as kudzu.' }],
    nativeRange: 'East Asia: Japan, China and Korea.',
    grownIn: 'Invasive across the southeastern US.',
    clueCountries: ['US', 'JP'],
    science: ['Kudzu can grow 30 cm a day in hot, humid summers. It fixes its own nitrogen, so it thrives on the poor, eroded red clay of the South, and mild winters do not kill its roots.'],
    history: ['It was introduced to the US in 1876 and planted by the millions in the 1930s to stop soil erosion. It became "the vine that ate the South".'],
    tips: ['Trees buried under green vines along a US highway: the Southeast (Georgia, Alabama, Mississippi, the Carolinas, Tennessee). In Japan it is common on roadsides everywhere except Hokkaido.'],
    remember: ['Kudzu is "the vine that ate the South": green ghosts along Southern highways.'],
    sources: ['https://en.wikipedia.org/wiki/Kudzu', 'https://en.wikipedia.org/wiki/Kudzu_in_the_United_States'],
  },
  {
    id: 'lupins',
    name: 'Roadside lupins',
    scientific: 'Lupinus polyphyllus',
    wikipedia: 'Lupinus polyphyllus',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Flower',
    photoSearch: ['lupins Lake Tekapo', 'lupine Iceland field', 'lupins roadside Patagonia'],
    recognise: [
      'Tall spikes of purple, blue, pink and white flowers in dense masses along roadsides and riverbeds in early summer.',
      'Iceland\'s Nootka lupin makes whole hillsides blue-purple in June–July.',
    ],
    lookalikes: [{ name: 'Foxgloves and fireweed', tell: 'Foxgloves have hanging bell flowers; fireweed is pink with no pea-like flowers.' }],
    nativeRange: 'Western North America.',
    grownIn: 'Invasive in New Zealand\'s South Island (Canterbury, Otago), Iceland, Patagonia (Chile\'s Aysén and Los Lagos, Argentina\'s Neuquén and Río Negro), and Norway and Finland.',
    clueCountries: ['NZ', 'IS', 'CL', 'AR', 'NO', 'FI'],
    science: ['Lupins fix nitrogen, so they spread on poor gravel riverbeds and volcanic soils where little else grows. Iceland planted the Nootka lupin to stop soil erosion.'],
    history: ['A New Zealand farmer\'s wife scattered lupin seeds around Lake Tekapo in the 1950s; they are now a famous (and invasive) sight.'],
    tips: [
      'Masses of multicoloured lupins with dry mountains and turquoise lakes: New Zealand\'s South Island (Tekapo, Mackenzie Country).',
      'Blue-purple hillsides with no trees: Iceland. With forests and gravel roads: Patagonia (Carretera Austral) or Norway.',
    ],
    remember: ['Lupins are escaped garden flowers that painted Iceland and New Zealand purple.'],
    sources: ['https://en.wikipedia.org/wiki/Lupinus_polyphyllus', 'https://en.wikipedia.org/wiki/Lupinus_nootkatensis'],
  },
  {
    id: 'gorse',
    name: 'Gorse',
    scientific: 'Ulex europaeus',
    wikipedia: 'Ulex europaeus',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Shrub',
    photoSearch: ['gorse hillside New Zealand', 'gorse Ireland hills', 'Ulex europaeus landscape'],
    recognise: [
      'Dense, very spiny dark green shrubs, covered in bright yellow flowers (strongest in spring), smelling of coconut.',
      'Forms thickets on hillsides, road banks and field edges.',
    ],
    lookalikes: [{ name: 'Broom', tell: 'Broom has similar yellow flowers but no spines and thin green twigs.' }],
    nativeRange: 'Western Europe: Britain, Ireland, western France, northwestern Spain and Portugal.',
    grownIn: 'Invasive in New Zealand, southern Chile, Hawaii and the Oregon coast.',
    clueCountries: ['NZ', 'CL', 'IE', 'GB', 'ES', 'US'],
    science: ['Gorse likes mild, wet, windy climates and poor acid soils. It fixes nitrogen and its seeds survive decades in the soil and sprout after fires.'],
    history: ['Settlers brought gorse to New Zealand and Chile as hedging; it escaped and is now one of the worst weeds in both.'],
    tips: ['Bright yellow spiny scrub on green hills: Britain, Ireland, Galicia/Asturias (Spain), New Zealand or southern Chile (Los Lagos, Los Ríos, Araucanía).'],
    remember: ['"When gorse is out of bloom, kissing\'s out of fashion": it flowers almost all year.'],
    sources: ['https://en.wikipedia.org/wiki/Ulex_europaeus'],
  },
  {
    id: 'pampas-grass',
    name: 'Pampas grass',
    scientific: 'Cortaderia selloana',
    wikipedia: 'Cortaderia selloana',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Grass',
    photoSearch: ['Cortaderia selloana Cantabria', 'plumero de la pampa carretera', 'pampas grass roadside'],
    recognise: [
      'Huge clumps of long, arching grass leaves with tall creamy-white feathery plumes on 2–3 m stems.',
      'Lines road verges, motorway slopes and abandoned land.',
    ],
    lookalikes: [{ name: 'Giant reed (Arundo)', tell: 'Giant reed has tall bamboo-like canes with leaves along the stem; pampas grass has a fountain of leaves at the base.' }],
    nativeRange: 'South America: Argentina, Uruguay and southern Brazil.',
    grownIn: 'Invasive along roads in northern Spain (Cantabria, Asturias, the Basque Country, Galicia), Portugal, New Zealand\'s North Island and coastal California.',
    clueCountries: ['ES', 'PT', 'NZ', 'AR', 'UY', 'US'],
    science: ['It loves mild, humid climates and disturbed ground like road cuts. One plant can release millions of wind-blown seeds.'],
    history: ['It was planted as an ornamental in gardens and on motorway embankments; in Cantabria it spread so fast that it became the region\'s worst invasive plant.'],
    tips: ['Pampas grass plumes lining a motorway in green, hilly Spain: the north coast (Cantabria, Asturias, the Basque Country). In New Zealand: Northland, Auckland, Waikato or Bay of Plenty.'],
    remember: ['Pampas grass left the Pampas and moved to the Spanish north coast, where it now lines every motorway like feather dusters.'],
    sources: ['https://en.wikipedia.org/wiki/Cortaderia_selloana'],
  },
  {
    id: 'grass-tree',
    name: 'Grass tree',
    scientific: 'Xanthorrhoea',
    wikipedia: 'Xanthorrhoea',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Shrub',
    photoSearch: ['grass trees Western Australia bush', 'Xanthorrhoea landscape'],
    recognise: [
      'A black, blackened trunk topped by a round mop of long thin grass-like leaves, sometimes with a tall spear-like flower spike.',
      'Grows in dry eucalyptus bush and heath, often scorched by fire.',
    ],
    lookalikes: [{ id: 'cabbage-tree', name: 'Cabbage tree', tell: 'Cabbage trees branch into several tufts on a pale trunk; grass trees have one mop on a black trunk.' }],
    nativeRange: 'Australia only.',
    grownIn: 'Wild, especially in Western Australia, South Australia, Victoria, New South Wales and southeastern Queensland.',
    clueCountries: ['AU'],
    science: ['Grass trees grow only 1–2 cm a year and survive bushfires: the trunk is made of old leaf bases glued together with resin, and fire actually triggers flowering.'],
    history: ['Aboriginal people used the resin as glue for spears and the flower spikes for fishing spears and fire-making.'],
    tips: ['Black-trunked "mop" plants in the bush: Australia, especially the southwest (around Perth).'],
    remember: ['A grass tree is a burnt matchstick with a green mop of hair: Australia\'s fire survivor.'],
    sources: ['https://en.wikipedia.org/wiki/Xanthorrhoea'],
  },
  {
    id: 'spanish-moss',
    name: 'Spanish moss',
    scientific: 'Tillandsia usneoides',
    wikipedia: 'Spanish moss',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Epiphyte',
    photoSearch: ['Spanish moss live oaks road', 'Spanish moss Louisiana'],
    recognise: ['Grey, beard-like strands hanging from the branches of live oaks and cypress trees, often over roads.'],
    lookalikes: [{ name: 'Lichens (old man\'s beard)', tell: 'Lichen beards are shorter and greener and grow in cool, wet forests; Spanish moss is long, grey and in the warm South.' }],
    nativeRange: 'The Americas from the southeastern US to Argentina.',
    grownIn: 'Most visible in the US Southeast.',
    clueCountries: ['US'],
    science: ['It is not a moss but a bromeliad (pineapple family). It has no roots and takes water and nutrients from humid air and rain, so it needs warm, humid climates.'],
    history: ['It was once used to stuff mattresses and car seats.'],
    tips: ['Grey beards hanging from oaks over the road: coastal Louisiana, Florida, Georgia, South Carolina, Mississippi or East Texas.'],
    remember: ['Spanish moss is neither Spanish nor moss: it is a pineapple relative wearing a grey beard.'],
    sources: ['https://en.wikipedia.org/wiki/Spanish_moss'],
  },
  {
    id: 'frailejon',
    name: 'Frailejón',
    scientific: 'Espeletia',
    wikipedia: 'Espeletia',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Shrub',
    photoSearch: ['frailejones páramo Colombia', 'páramo de Sumapaz frailejones'],
    recognise: [
      'Furry, silver-grey rosettes of thick leaves on a short trunk wrapped in dead leaves, standing in high cold grassland.',
      'Often many together, like a crowd of hooded figures in the mist.',
    ],
    lookalikes: [{ id: 'grass-tree', name: 'Grass tree', tell: 'Grass trees have thin grass-like leaves in Australia; frailejón has thick furry leaves in the Andes.' }],
    nativeRange: 'The páramos (high Andean grasslands above about 3,000 m) of Colombia, Venezuela and northern Ecuador.',
    grownIn: 'Wild.',
    clueCountries: ['CO', 'EC'],
    science: ['The furry leaves trap heat and protect against freezing nights and strong ultraviolet light; the dead leaves around the trunk insulate it. The páramo soaks up rain and mist and feeds the rivers that supply Bogotá.'],
    history: ['The name means "big friar": from a distance they look like hooded monks.'],
    tips: ['Silvery furry rosettes in misty high grassland: the Colombian Andes (Boyacá, Cundinamarca, Santander, Nariño) or northern Ecuador.'],
    remember: ['Frailejones are the "friars" of the páramo: a crowd of furry monks standing in the fog.'],
    sources: ['https://en.wikipedia.org/wiki/Espeletia', 'https://en.wikipedia.org/wiki/P%C3%A1ramo'],
  },
  {
    id: 'heather',
    name: 'Heather moorland',
    scientific: 'Calluna vulgaris',
    wikipedia: 'Calluna',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Shrub',
    photoSearch: ['heather moorland Scotland', 'heather moor purple Yorkshire'],
    recognise: [
      'Low, dense shrub covering treeless hills, dark brown most of the year and purple in late summer (August–September).',
      'Patchwork of burned strips on grouse moors in Scotland and northern England.',
    ],
    lookalikes: [{ id: 'bracken', name: 'Bracken', tell: 'Bracken is taller, with big fern fronds that turn orange-brown.' }],
    nativeRange: 'Europe: most extensive in Scotland, northern England, Wales, Ireland, Norway, and heaths in the Netherlands and northern Germany.',
    grownIn: 'Wild on moors and heaths.',
    clueCountries: ['GB', 'IE', 'NO', 'NL'],
    science: ['Heather grows on acidic, nutrient-poor, often peaty soils in cool, wet, windy places where trees were cleared long ago and grazing keeps them from returning.'],
    history: ['Moors were managed for sheep and grouse shooting by burning strips of heather, so young shoots grow for the birds.'],
    tips: ['Treeless brown-purple hills with no fences: Scotland, the Pennines, Wales or Ireland. Flat purple heath with pines: the Netherlands (Veluwe) or northern Germany.'],
    remember: ['Heather paints the Scottish Highlands purple every August.'],
    sources: ['https://en.wikipedia.org/wiki/Calluna', 'https://en.wikipedia.org/wiki/Moorland'],
  },
  {
    id: 'norfolk-pine',
    name: 'Norfolk Island pine',
    scientific: 'Araucaria heterophylla',
    wikipedia: 'Araucaria heterophylla',
    section: 'tree',
    group: 'Regional oddities',
    kind: 'Conifer',
    photoSearch: ['Norfolk Island pines beach Australia', 'Norfolk pines Manly'],
    recognise: [
      'Very symmetrical, tall conifer with flat tiers of horizontal branches, like a tidy Christmas tree.',
      'Planted in rows along beaches and seafronts.',
    ],
    lookalikes: [{ id: 'araucaria', name: 'Paraná pine (araucaria)', tell: 'The Brazilian araucaria has a flat-topped candelabra crown inland; the Norfolk Island pine is a neat pyramid by the sea.' }],
    nativeRange: 'Norfolk Island, between Australia and New Zealand.',
    grownIn: 'Planted on coasts in Australia (NSW, Queensland, WA), New Zealand, Hawaii, California, South Africa and the Mediterranean.',
    clueCountries: ['AU', 'NZ', 'US'],
    science: ['It tolerates salt wind and sandy soils, so it is one of the few big trees that thrives right on the beachfront in warm climates.'],
    history: ['Captain Cook hoped its trunks would make ship masts. Australian beach towns planted long avenues of them in the 1900s.'],
    tips: ['Rows of perfectly symmetrical pines along a sunny beachfront: Australia\'s east coast (Manly, the Gold Coast), New Zealand\'s North Island or Hawaii.'],
    remember: ['The Norfolk Island pine is the beach\'s Christmas tree, lined up along every Aussie surf beach.'],
    sources: ['https://en.wikipedia.org/wiki/Araucaria_heterophylla'],
  },
]

/** Where each oddity is a clue inside the countries split on the vegetation map. */
export const oddityRegions: Record<string, string[]> = {
  'tree-fern': ['NZ', 'AU-TAS', 'AU-VIC', 'AU-NSW', 'AU-QLD', 'US-HI', 'BR-SC', 'BR-PR', 'BR-RS', 'BR-SP', 'MY-06', 'MY-12'],
  bracken: ['GB'],
  'giant-butterbur': ['JP-01', 'JP-02', 'JP-03', 'JP-05', 'RU-SAK'],
  'cabbage-tree': ['NZ', 'GB-ENG', 'GB-WLS', 'GB-SCT'],
  kudzu: ['US-GA', 'US-AL', 'US-MS', 'US-SC', 'US-NC', 'US-TN', 'US-KY', 'US-VA', ...JP_NOT_HOKKAIDO],
  lupins: ['NZ-CAN', 'NZ-OTA', 'NZ-STL', 'CL-AI', 'CL-LL', 'CL-LR', 'AR-Q', 'AR-R', 'AR-U'],
  gorse: ['NZ', 'CL-LL', 'CL-LR', 'CL-AR', 'CL-BI', 'GB', 'ES-GA', 'ES-AS', 'ES-CB', 'US-OR', 'US-HI'],
  'pampas-grass': ['ES-CB', 'ES-AS', 'ES-PV', 'ES-GA', 'NZ-NTL', 'NZ-AUK', 'NZ-WKO', 'NZ-BOP', 'AR-B', 'AR-E', 'AR-S', 'US-CA'],
  'grass-tree': ['AU-WA', 'AU-SA', 'AU-VIC', 'AU-NSW', 'AU-QLD', 'AU-TAS'],
  'spanish-moss': ['US-LA', 'US-FL', 'US-GA', 'US-SC', 'US-MS', 'US-AL', 'US-TX', 'US-NC'],
  frailejon: ['CO-BOY', 'CO-CUN', 'CO-SAN', 'CO-NSA', 'CO-NAR', 'CO-CAU', 'CO-TOL'],
  heather: ['GB-SCT', 'GB-ENG', 'GB-WLS', 'GB-NIR'],
  'norfolk-pine': ['AU-NSW', 'AU-QLD', 'AU-WA', 'NZ-AUK', 'NZ-NTL', 'NZ-BOP', 'NZ-HKB', 'NZ-GIS', 'US-HI'],
}
