// Memory hooks for the trees and crops: metaphors and mnemonics that make a plant stick.
// (Cacti, desert plants and forests carry theirs inline.)

export const plantRemember: Record<string, string[]> = {
  'coconut-palm': ['The coconut palm leans towards the sea "to drop its nut in the water": beaches and a lean = coconut.'],
  'oil-palm': ['Oil palm looks like a pineapple top on a hairy trunk: the old leaf stubs make the trunk look "unshaven".', 'Oil palm = money trees in rows: straight grids of palms = plantation = Malaysia/Indonesia.'],
  'date-palm': ['Date palm: "feet in water, head in fire". Oases and desert-city roundabouts.', 'Diamond pattern trunk, like a pineapple skin stretched tall.'],
  'royal-palm': ['Royal palm = "a concrete lamp post with a crown": a smooth grey column topped by a green collar.'],
  'babassu': ['Babassu = "feathers in the pasture": giant feather fronds left standing alone in cleared fields of Maranhão.'],
  'carnauba': ['Carnaúba wears wax like a raincoat against the sun: fan palms of the dry Northeast (Ceará).'],
  'acai': ['Açaí grows in "skinny families": clumps of pencil-thin palms along Amazon rivers.'],
  'buriti': ['Buriti is a water diviner: a line of buriti palms across dry grassland shows exactly where the stream is.'],
  'eucalyptus': ['Eucalyptus sheds its skin like a snake: peeling bark in strips, and leaves that hang like keys edge-on to the sun.', 'Where eucalyptus is planted, it is usually for paper: plantations = pulp mills nearby.'],
  'scots-pine': ['Scots pine has a "sunburnt neck": grey trunk below, bright orange bark at the top.'],
  'norway-spruce': ['Norway spruce = the Christmas tree with its arms hanging down, shedding snow like a closed umbrella.'],
  'radiata-pine': ['Radiata pine: a Californian that emigrated and got rich in New Zealand and Chile.'],
  'larch': ['Larch is the conifer that "takes its coat off" in winter: golden in autumn, bare like a skeleton in winter.'],
  'birch': ['Birch trunks look like they were painted white with black tally marks.'],
  'lombardy-poplar': ['Lombardy poplars stand in line like exclamation marks along the road!!!'],
  'italian-cypress': ['Italian cypress = a dark green candle flame. Rows of candles on a hill = Tuscany.'],
  'stone-pine': ['Stone pine = an open umbrella over Rome.'],
  'araucaria': ['Araucaria looks like a candelabra holding up the sky of Paraná, or a tree drawn by a child with arms raised.'],
  'olive': ['Olive leaves are silver on one side: an olive grove "shimmers" in the wind like a sequinned dress.', 'Olives mark the Mediterranean climate like a boundary line: no olives, no Mediterranean.'],
  'umbrella-thorn': ['Umbrella thorn = the "Lion King tree": a flat umbrella over the savanna.'],
  'baobab': ['Baobab = the upside-down tree: it looks planted with its roots in the air.'],
  'jacaranda': ['Jacaranda = purple streets in spring: Pretoria turns purple in October, Lisbon in May.'],
  'mango': ['Mango trees are the "village umbrellas" of the tropics: a dark dome where everyone sits in the shade.'],
  'bamboo': ['Bamboo is a grass that thinks it is a tree: jointed stems like green scaffolding.'],
  'saguaro': ['Saguaro = the cartoon cactus with its arms up ("hands up!"). Only Arizona and Sonora.'],
  'prickly-pear': ['Prickly pear = cactus made of ping-pong paddles. Paddles on a Mediterranean fence = Sicily/Malta/Andalusia.'],
  'mangrove': ['Mangroves stand on stilts to keep their feet out of the salty mud.'],
  'sugarcane': ['Sugarcane = bamboo\'s sweet little cousin, planted in fields and burnt before harvest.'],
  'coffee': ['Coffee likes "eternal spring": tropical, but high enough to be mild. Coffee = tropical mountains.'],
  'rice': ['Rice fields are mirrors: flooded paddies reflect the sky.'],
  'tea': ['Tea plantations look like a green sofa cushion laid over the hills.'],
  'cocoa': ['Cocoa pods grow straight out of the trunk, like rugby balls glued to the tree.'],
  'banana': ['Bananas wear blue raincoats: plastic bags over the bunches = export plantation (Ecuador, Central America).'],
  'maize': ['Maize wears a feather on top (the tassel) and carries its cobs in its armpits.'],
  'wheat': ['Wheat fields are "golden oceans": big flat waves of gold in summer = steppe, prairie or wheat belt.'],
  'cotton': ['Cotton fields look like it snowed in the hot sun.'],
  'tobacco': ['Tobacco has leaves the size of elephant ears and a barn to dry them.'],
  'grapevine': ['Vineyards are combed hillsides: straight rows like a comb pulled through the slope.'],
  'pineapple': ['Pineapple plants are spiky crowns on the ground, each wearing its fruit like a jewel in the middle.'],
  'rubber': ['Rubber trees "bleed milk into cups": spiral cuts and little cups on every trunk.'],
}
