import type { Plant } from './types'

export const trees: Plant[] = [
  // ---- Palms ------------------------------------------------------------------------------------
  {
    id: 'coconut-palm',
    name: 'Coconut palm',
    scientific: 'Cocos nucifera',
    wikipedia: 'Coconut',
    section: 'tree',
    kind: 'Palm',
    recognise: [
      'A single slender, often curved or leaning grey trunk with ring scars, up to 30 m tall.',
      'A crown of long feather-shaped fronds, with clusters of green, yellow or brown coconuts just below it.',
      'Usually on or near the coast, often in large groves.',
    ],
    lookalikes: [
      { id: 'oil-palm', name: 'Oil palm', tell: 'Oil palm has a shorter, rough trunk covered in old leaf bases, and grows in straight plantation rows inland.' },
      { id: 'royal-palm', name: 'Royal palm', tell: 'Royal palm has a perfectly straight, smooth, pale trunk that bulges and a green "crownshaft" below the leaves.' },
    ],
    nativeRange: 'Probably the islands of Southeast Asia and the western Pacific; it has been spread so widely by people that its exact origin is debated.',
    grownIn: 'Tropical coasts worldwide: South and Southeast Asia, the Pacific, East and West Africa, the Caribbean, Central America and north-east Brazil.',
    clueCountries: ['PH', 'ID', 'LK', 'IN', 'TH', 'MY', 'BR', 'MX', 'KE', 'TZ'],
    science: [
      'Coconut palms need year-round warmth (they are damaged below about 13 °C), high humidity and plenty of sun. They tolerate salty, sandy soil and salt spray far better than most trees, which is why they dominate beaches.',
      'The seed is a floating fruit: a fibrous husk keeps the nut buoyant and waterproof for months, so coconuts can drift between islands and sprout on new shores.',
    ],
    history: [
      'Austronesian sailors carried coconuts across the Pacific and Indian Oceans, and Arab, Indian, Portuguese and Spanish traders spread them further. In the 19th and 20th centuries colonial copra (dried coconut meat) plantations covered huge areas of the Philippines, Indonesia and the Pacific.',
    ],
    tips: [
      'Coconut palms point to the humid tropics. They do not grow in the Mediterranean or in dry climates without irrigation.',
      'Dense coconut groves along the road are very typical of the Philippines, Sri Lanka, Kerala (India) and coastal Thailand.',
    ],
    facts: ['The Philippines and Indonesia are the largest coconut producers.'],
    sources: ['https://en.wikipedia.org/wiki/Coconut'],
  },
  {
    id: 'oil-palm',
    name: 'Oil palm',
    scientific: 'Elaeis guineensis',
    wikipedia: 'Elaeis guineensis',
    section: 'tree',
    alsoCrop: true,
    kind: 'Palm',
    commonsCategory: 'Oil palm plantations',
    production: { owid: 'palm-oil-production' },
    recognise: [
      'A thick, rough trunk covered in the stubs of old leaf bases, often with ferns growing on it.',
      'A dense, fountain-like crown of long arching fronds; young plantation palms look like big green shuttlecocks close to the ground.',
      'Planted in huge, regular grids stretching over hills, with red-orange fruit bunches near the trunk.',
    ],
    lookalikes: [
      { id: 'coconut-palm', name: 'Coconut palm', tell: 'Coconut palms have a smooth, slender, often leaning trunk and grow mostly by the coast.' },
    ],
    nativeRange: 'The rainforests and wetter savannas of West and Central Africa, from Guinea to Angola.',
    grownIn: 'Industrial plantations in Malaysia and Indonesia (over 80% of world palm oil), plus Thailand, Colombia, Nigeria, Ghana, Ecuador, Guatemala and Papua New Guinea.',
    clueCountries: ['MY', 'ID', 'TH', 'CO', 'NG', 'GH', 'EC', 'GT'],
    science: [
      'Oil palm needs a hot, wet equatorial climate: rain spread through the year (2,000 mm or more), temperatures of 24–32 °C and lots of sunshine. That confines commercial growing to about 10° north and south of the equator.',
      'It produces more oil per hectare than any other oil crop, which is why it replaced rainforest so quickly in Borneo and Sumatra.',
    ],
    history: [
      'West Africans used palm oil for thousands of years. The British and Dutch took the palm to Southeast Asia in the 19th century; a few palms planted at Bogor Botanical Garden in Java in 1848 are said to be the ancestors of much of the Asian industry. Large-scale plantations took off in Malaysia from the 1960s.',
    ],
    tips: [
      'Endless palm plantations on hills with red laterite roads: think Malaysia or Indonesia (Sumatra, Borneo).',
      'In Latin America, oil palm plantations are a clue for Colombia, Ecuador and Guatemala.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Elaeis_guineensis', 'https://en.wikipedia.org/wiki/Palm_oil'],
  },
  {
    id: 'date-palm',
    name: 'Date palm',
    scientific: 'Phoenix dactylifera',
    wikipedia: 'Date palm',
    section: 'tree',
    kind: 'Palm',
    recognise: [
      'A tall, straight trunk patterned with diamond-shaped scars from old leaf bases.',
      'A crown of stiff, grey-green feather leaves; suckers often sprout around the base.',
      'Grown in oases and in neat rows along roads and roundabouts in desert cities.',
    ],
    lookalikes: [
      { name: 'Canary Island date palm', tell: 'Its cousin Phoenix canariensis has a much thicker trunk and a big, round, dark-green crown. It is the ornamental palm of the Mediterranean.' },
    ],
    nativeRange: 'Probably the Persian Gulf region and Mesopotamia, where it was domesticated.',
    grownIn: 'North Africa, the Arabian Peninsula, Iraq and Iran; also planted in southern Spain (Elche), Israel, California and Arizona.',
    clueCountries: ['AE', 'SA', 'QA', 'OM', 'JO', 'EG', 'TN', 'MA', 'IL', 'IQ'],
    science: [
      'Date palms need long, extremely hot, dry summers to ripen fruit, but also water at the roots, from oases, rivers or irrigation. The Arab saying is that they need "their feet in water and their heads in the fire of the sky".',
      'They tolerate salty soil and very high temperatures (above 45 °C), but rain during ripening spoils the fruit.',
    ],
    history: [
      'Dates were among the first cultivated fruit trees, grown in Mesopotamia over 5,000 years ago. Arab expansion spread them across North Africa and into Spain; Spanish missionaries later took them to the Americas.',
    ],
    tips: [
      'Rows of date palms along a straight desert road or in city medians: the Gulf states, Jordan, Egypt or North Africa.',
      'In the Mediterranean, the fat, round-crowned Canary Island palm is much more common than the true date palm.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Date_palm'],
  },
  {
    id: 'royal-palm',
    name: 'Royal palm',
    scientific: 'Roystonea regia',
    wikipedia: 'Roystonea regia',
    section: 'tree',
    kind: 'Palm',
    recognise: [
      'A smooth, pale grey trunk like a concrete column, often slightly swollen in the middle.',
      'A shiny green "crownshaft" (the sheath of the leaf bases) on top of the trunk, then a crown of feather leaves.',
      'Planted in stately avenues.',
    ],
    lookalikes: [
      { id: 'coconut-palm', name: 'Coconut palm', tell: 'Coconut palms lean and have no green crownshaft.' },
    ],
    nativeRange: 'Cuba, other Caribbean islands, southern Florida and parts of Central America.',
    grownIn: 'Planted as an ornamental avenue palm throughout the tropics, famously in Brazil (palmeira-imperial).',
    clueCountries: ['CU', 'DO', 'PR', 'BR', 'MX'],
    science: [
      'Royal palms like hot, humid lowlands with seasonal rain and tolerate brief light frosts only. They grow fast in open sun.',
    ],
    history: [
      'Prince regent Dom João VI planted a royal palm in the Rio de Janeiro Botanical Garden around 1809, after the Portuguese court fled to Brazil. Its seeds were jealously guarded, and the "imperial palm" became a status symbol planted along the avenues of Brazilian estates and cities.',
    ],
    tips: ['Avenues of tall, grey, column-like palms are common in Brazil and the Caribbean. It is the national tree of Cuba.'],
    sources: ['https://en.wikipedia.org/wiki/Roystonea_regia'],
  },
  {
    id: 'babassu',
    name: 'Babassu palm',
    scientific: 'Attalea speciosa',
    wikipedia: 'Attalea speciosa',
    section: 'tree',
    kind: 'Palm',
    recognise: [
      'A tall palm with huge, upright, arching fronds that look like giant feathers.',
      'Often the only trees left standing in cleared pasture, dotted across the landscape.',
    ],
    lookalikes: [
      { id: 'carnauba', name: 'Carnaúba palm', tell: 'Carnaúba has fan-shaped leaves; babassu has long feather leaves.' },
    ],
    nativeRange: 'The transition between the Amazon rainforest and the dry north-east of Brazil, especially Maranhão, Piauí and Tocantins ("Mata dos Cocais"); also Bolivia and the Guianas.',
    grownIn: 'Mostly wild; left standing when forest is cleared for pasture.',
    clueCountries: ['BR'],
    science: [
      'Babassu thrives in the transition zone between rainforest and savanna, with a marked dry season. It resprouts after fire and clearing, which is why it spreads in pastures.',
    ],
    history: [
      'Women coconut-breakers (quebradeiras de coco) in Maranhão and Piauí have long cracked babassu nuts for oil; their right to harvest on private land became a social movement.',
    ],
    tips: ['Pastures full of scattered tall feather palms in northern Brazil: Maranhão or Piauí.'],
    sources: ['https://en.wikipedia.org/wiki/Attalea_speciosa'],
  },
  {
    id: 'carnauba',
    name: 'Carnaúba palm',
    scientific: 'Copernicia prunifera',
    wikipedia: 'Copernicia prunifera',
    section: 'tree',
    kind: 'Palm',
    recognise: [
      'A slender trunk topped by a round crown of stiff, fan-shaped leaves.',
      'The lower trunk often keeps a criss-cross pattern of old leaf stalks.',
      'Grows in groves on dry, flat river plains.',
    ],
    lookalikes: [
      { id: 'babassu', name: 'Babassu palm', tell: 'Babassu has long feather leaves, not fans.' },
    ],
    nativeRange: 'North-east Brazil, especially Ceará, Piauí and Rio Grande do Norte.',
    grownIn: 'Mostly wild, in the semi-arid sertão river valleys.',
    clueCountries: ['BR'],
    science: [
      'Carnaúba lives in the semi-arid north-east, where it survives the long dry season by coating its leaves with a thick wax that stops them losing water. It grows along seasonally flooded river plains.',
    ],
    history: [
      'Carnauba wax, scraped from the dried leaves, has been exported since the 19th century and is used in car polish, sweets and cosmetics. It is called the "tree of life" in Ceará because every part is used.',
    ],
    tips: ['Fan palms in dry, scrubby lowland: north-east Brazil (Ceará, Piauí).'],
    sources: ['https://en.wikipedia.org/wiki/Copernicia_prunifera'],
  },
  {
    id: 'acai',
    name: 'Açaí palm',
    scientific: 'Euterpe oleracea',
    wikipedia: 'Euterpe oleracea',
    section: 'tree',
    kind: 'Palm',
    recognise: [
      'Very slender, multi-stemmed clumps of palms, each trunk only 10–15 cm thick.',
      'Drooping leaflets that hang down like tassels.',
      'Grows along rivers and in flooded forest.',
    ],
    lookalikes: [
      { id: 'buriti', name: 'Buriti palm', tell: 'Buriti is a single, much thicker trunk with fan leaves.' },
    ],
    nativeRange: 'The Amazon estuary and floodplains: Pará and Amapá (Brazil), and north-eastern South America.',
    grownIn: 'Wild and managed stands around Belém; increasingly planted.',
    clueCountries: ['BR'],
    science: [
      'Açaí tolerates regularly flooded soils (várzea) thanks to special roots that take in oxygen. It needs a hot, very humid equatorial climate.',
    ],
    history: [
      'Açaí berries have been a staple food in the Amazon for centuries. Since the 1990s they have become a global "superfood", turning açaí into a major crop for Pará.',
    ],
    tips: ['Clumps of skinny palms along muddy rivers: the Brazilian Amazon, especially around Belém.'],
    sources: ['https://en.wikipedia.org/wiki/Euterpe_oleracea'],
  },
  {
    id: 'buriti',
    name: 'Buriti palm',
    scientific: 'Mauritia flexuosa',
    wikipedia: 'Mauritia flexuosa',
    section: 'tree',
    kind: 'Palm',
    recognise: [
      'A tall, straight, smooth trunk with a round crown of huge fan leaves.',
      'Grows in lines or clumps along wet valley floors (veredas) in otherwise dry savanna.',
    ],
    lookalikes: [
      { id: 'carnauba', name: 'Carnaúba palm', tell: 'Carnaúba grows in dry plains of the north-east; buriti marks wet ground and is much bigger.' },
    ],
    nativeRange: 'Northern South America: the Amazon basin, the Orinoco, and wet valleys of the Brazilian cerrado.',
    grownIn: 'Wild.',
    clueCountries: ['BR', 'PE', 'CO'],
    science: [
      'Buriti needs permanently waterlogged soil. In the cerrado, lines of buriti trace springs and streams through dry grassland (veredas), so a row of these palms shows exactly where the water is.',
    ],
    history: [
      'Called the "tree of life" by many Amazonian peoples: the fruit is eaten, the leaves are woven and the trunk is used for building. In Peru it is called aguaje.',
    ],
    tips: ['A line of tall fan palms across a dry grassy plain: the Brazilian cerrado (Goiás, Tocantins, Minas Gerais, Bahia).'],
    sources: ['https://en.wikipedia.org/wiki/Mauritia_flexuosa'],
  },
  // ---- Broadleaf and conifer trees ---------------------------------------------------------------
  {
    id: 'eucalyptus',
    photoSearch: 'eucalyptus plantation',
    name: 'Eucalyptus',
    scientific: 'Eucalyptus',
    wikipedia: 'Eucalyptus',
    section: 'tree',
    kind: 'Broadleaf (evergreen)',
    commonsCategory: 'Eucalyptus plantations',
    recognise: [
      'Tall, straight trunks with smooth bark peeling off in long strips, revealing white, grey or orange patches.',
      'Thin, open, grey-green crowns with narrow, drooping, sickle-shaped leaves that hang edge-on to the sun.',
      'Often in dense plantations of identical trees in straight rows.',
    ],
    lookalikes: [
      { id: 'lombardy-poplar', name: 'Poplar', tell: 'Poplars have broad, fluttering leaves and are leafless in winter; eucalyptus is evergreen with narrow hanging leaves.' },
    ],
    nativeRange: 'Australia (almost all 700+ species), plus a few in New Guinea, Indonesia and the Philippines.',
    grownIn: 'Plantations for timber and pulp in Brazil, Uruguay, Portugal, Spain (Galicia, Huelva), Chile, South Africa, Ethiopia, Kenya, Rwanda, India and China. Also along roads across the Mediterranean, California and East Africa.',
    clueCountries: ['AU', 'PT', 'ES', 'BR', 'UY', 'ZA', 'ET', 'KE', 'RW', 'CL', 'IN'],
    science: [
      'Eucalyptus evolved in fire-prone, often poor soils in Australia. It regrows from buds under the bark and from a woody underground swelling after fire. Its oils make it burn fiercely.',
      'It grows extremely fast in warm climates with some rain (a plantation can be harvested in 7 years in Brazil), which is why it is planted for pulp and firewood worldwide. It is not frost-hardy, so it is absent from cold continental climates.',
    ],
    history: [
      'Eucalyptus seeds were sent around the world in the 19th century. Emperor Menelik II of Ethiopia planted it massively around Addis Ababa in the 1890s to solve a firewood shortage. Portugal, Spain and Brazil planted huge areas in the 20th century for the paper industry.',
    ],
    tips: [
      'Eucalyptus is common in many GeoGuessr countries, so it is not decisive alone. Combine it with other clues: dense plantations with red soil suggest Brazil or Uruguay; with green hills and granite, Galicia or northern Portugal.',
      'In Ethiopia, Kenya and Rwanda, eucalyptus woodlots are everywhere around towns.',
    ],
    facts: ['Koalas feed almost only on eucalyptus leaves.'],
    sources: ['https://en.wikipedia.org/wiki/Eucalyptus', 'https://en.wikipedia.org/wiki/Eucalyptus_in_Ethiopia'],
  },
  {
    id: 'scots-pine',
    name: 'Scots pine',
    scientific: 'Pinus sylvestris',
    wikipedia: 'Pinus sylvestris',
    section: 'tree',
    kind: 'Conifer',
    recognise: [
      'Upper trunk and branches have distinctive orange-red, flaky bark; lower trunk is grey-brown and fissured.',
      'Mature trees lose their lower branches and have a flat or rounded crown high up.',
      'Short, blue-green needles in pairs, often twisted.',
    ],
    lookalikes: [
      { id: 'norway-spruce', name: 'Norway spruce', tell: 'Spruce is a dark, dense, perfect cone with drooping branches down to the ground and no orange bark.' },
    ],
    nativeRange: 'The widest range of any pine: from Scotland and Spain across Scandinavia and Russia to eastern Siberia.',
    grownIn: 'Dominates sandy lowland forests in Poland, northern Germany, the Baltics and Scandinavia; planted widely.',
    clueCountries: ['FI', 'SE', 'NO', 'RU', 'PL', 'DE', 'LT', 'LV', 'EE', 'GB'],
    science: [
      'Scots pine tolerates poor, dry, sandy soils and very cold winters, where other trees struggle. It needs lots of light, so it forms open forests on sand and peat.',
    ],
    history: [
      'After the last Ice Age, Scots pine was one of the first trees to recolonise northern Europe. Large pine plantations on sandy soils were planted in Germany and Poland from the 18th century.',
    ],
    tips: ['Tall pines with orange upper trunks in flat, sandy land: Poland, northern Germany, the Baltics or southern Finland and Sweden.'],
    sources: ['https://en.wikipedia.org/wiki/Pinus_sylvestris'],
  },
  {
    id: 'norway-spruce',
    photoSearch: 'Picea abies forest',
    name: 'Norway spruce',
    scientific: 'Picea abies',
    wikipedia: 'Picea abies',
    section: 'tree',
    kind: 'Conifer',
    recognise: [
      'A dark green, narrow, conical tree, the classic Christmas tree shape.',
      'Branches sweep down and then up at the tips, with hanging side shoots.',
      'Long cones hanging down from the upper branches.',
    ],
    lookalikes: [
      { id: 'scots-pine', name: 'Scots pine', tell: 'Pine has orange upper bark and an open crown high up.' },
      { name: 'Silver fir', tell: 'Fir cones stand upright on the branches, and needles have two white lines underneath.' },
    ],
    nativeRange: 'Scandinavia, Finland and western Russia, and the mountains of central Europe: the Alps, Carpathians and Balkans.',
    grownIn: 'Planted far outside its range for timber, especially in Germany, Czechia, Denmark and the UK.',
    clueCountries: ['NO', 'SE', 'FI', 'CH', 'AT', 'DE', 'CZ', 'SK', 'PL', 'RO'],
    science: [
      'Spruce needs cool, moist conditions and tolerates heavy snow: its downward-sloping branches shed snow. In the south of its range it only grows in mountains, where it is cool enough.',
      'It is shallow-rooted, so it is vulnerable to windthrow and drought; recent hot summers have caused bark-beetle die-offs across Czechia and Germany, visible as grey dead forest.',
    ],
    history: [
      'From the 19th century, foresters replaced mixed forests in Germany and Czechia with fast-growing spruce monocultures for timber, far below the altitude where spruce naturally grows.',
    ],
    tips: [
      'Dark conical trees on mountain slopes: the Alps or the Carpathians. In lowlands with lots of spruce: Scandinavia or the Baltics.',
      'Large areas of dead grey spruce: bark-beetle damage, very visible in Czechia and Germany.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Picea_abies'],
  },
  {
    id: 'radiata-pine',
    photoSearch: 'Pinus radiata plantation',
    name: 'Monterey (radiata) pine',
    scientific: 'Pinus radiata',
    wikipedia: 'Pinus radiata',
    section: 'tree',
    kind: 'Conifer',
    recognise: [
      'A fast-growing pine with long, bright green needles in threes, giving a soft, bushy look.',
      'Usually in dense, uniform plantations on rolling hills, often with clear-felled patches.',
    ],
    lookalikes: [
      { id: 'scots-pine', name: 'Scots pine', tell: 'Scots pine has short blue-green needles and orange upper bark, and grows in the cold north.' },
    ],
    nativeRange: 'Only three tiny areas on the central California coast and two Mexican islands.',
    grownIn: 'The world\'s most planted pine: New Zealand, Chile, Australia, South Africa and northern Spain (Basque Country).',
    clueCountries: ['NZ', 'CL', 'AU', 'ZA', 'ES'],
    science: [
      'In its native mild, foggy coastal climate it grows slowly, but in the similar climates of New Zealand and Chile, with no natural pests, it grows extraordinarily fast, reaching harvest size in 25–30 years.',
    ],
    history: [
      'Planted from the late 19th century in New Zealand and Chile, where native trees were slow-growing. Today plantations cover about 1.5 million hectares in New Zealand and more in Chile.',
    ],
    tips: ['Neat pine plantations on green hills with clear-cut patches: New Zealand, southern Chile, or south-east Australia.'],
    sources: ['https://en.wikipedia.org/wiki/Pinus_radiata'],
  },
  {
    id: 'larch',
    photoSearch: 'larch forest autumn',
    name: 'Larch',
    scientific: 'Larix',
    wikipedia: 'Larch',
    section: 'tree',
    kind: 'Conifer (deciduous)',
    recognise: [
      'A conifer that turns golden-yellow in autumn and is bare in winter.',
      'Soft, bright green needles in tufts in spring; small upright cones.',
      'Open, light crowns, letting lots of light reach the ground.',
    ],
    lookalikes: [
      { id: 'norway-spruce', name: 'Norway spruce', tell: 'Spruce stays dark green all year and is much denser.' },
    ],
    nativeRange: 'Cold regions of the Northern Hemisphere: the Alps and Carpathians (European larch), Siberia and Mongolia (Siberian and Dahurian larch), Canada (tamarack).',
    grownIn: 'Also planted for timber in Scotland, Japan and central Europe.',
    clueCountries: ['RU', 'MN', 'CH', 'AT', 'IT'],
    science: [
      'Dropping its needles lets larch survive the most extreme cold on earth: Dahurian larch forests grow in eastern Siberia where winters fall below −60 °C, beyond the limit of evergreen conifers.',
    ],
    history: ['Larch wood is very durable, and Venice was partly built on larch piles from the Alps.'],
    tips: [
      'Golden conifers in autumn coverage: the Alps, Siberia or Mongolia.',
      'Open larch forest on mountain slopes with grassland below is typical of northern Mongolia.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Larch'],
  },
  {
    id: 'birch',
    name: 'Silver birch',
    scientific: 'Betula pendula',
    wikipedia: 'Betula pendula',
    section: 'tree',
    kind: 'Broadleaf (deciduous)',
    recognise: [
      'Brilliant white bark with black diamond-shaped marks and dark, rough bark at the base.',
      'Slender, drooping twigs and small triangular leaves that turn yellow in autumn.',
      'Often in pure stands along roads and field edges.',
    ],
    lookalikes: [
      { name: 'Aspen', tell: 'Aspen has smooth grey-green bark without black marks, and round leaves that tremble.' },
    ],
    nativeRange: 'Most of Europe and across northern Asia to Siberia.',
    grownIn: 'Wild; very common in Scandinavia, Finland, the Baltics, Russia and Belarus.',
    clueCountries: ['FI', 'SE', 'RU', 'EE', 'LV', 'LT', 'NO', 'BY'],
    science: [
      'Birch is a pioneer tree: it grows fast in full light on bare ground after fire, clearing or abandonment of farmland, and tolerates cold and poor soils. The white bark reflects sunlight, which may protect the trunk from overheating and cracking in late winter.',
    ],
    history: ['Birch is a national symbol of Russia and Finland, and birch bark was used for writing in medieval Novgorod.'],
    tips: ['Lots of white-barked trees along a road: Finland, Russia, the Baltics or Scandinavia.'],
    sources: ['https://en.wikipedia.org/wiki/Betula_pendula'],
  },
  {
    id: 'lombardy-poplar',
    photoSearch: 'Lombardy poplars row',
    name: 'Lombardy poplar',
    scientific: 'Populus nigra',
    wikipedia: 'Populus nigra',
    section: 'tree',
    kind: 'Broadleaf (deciduous)',
    recognise: [
      'Tall, very narrow, column-shaped trees, often in long lines along roads, canals and field edges.',
      'Leaves flutter in the wind and turn yellow in autumn; bare in winter.',
    ],
    lookalikes: [
      { id: 'italian-cypress', name: 'Italian cypress', tell: 'Cypress is dark green all year and darker; poplar is lighter green and loses its leaves.' },
    ],
    nativeRange: 'The black poplar is native to Europe, North Africa and western Asia; the narrow Lombardy form arose in northern Italy in the 18th century.',
    grownIn: 'As windbreaks and roadside rows in France, Italy, Spain, Turkey, the Caucasus and Central Asia (Kyrgyzstan, Kazakhstan, Xinjiang).',
    clueCountries: ['FR', 'IT', 'ES', 'TR', 'KG', 'KZ'],
    science: [
      'Poplars need lots of water and grow along rivers, irrigation canals and ditches. In dry regions, lines of poplars show where there is irrigation.',
    ],
    history: [
      'The narrow Lombardy form spread across Europe as a fashionable avenue tree. In Soviet Central Asia, poplars were planted in huge numbers along roads and fields as windbreaks.',
    ],
    tips: ['Long rows of tall, narrow trees along roads in dry, mountainous country: Kyrgyzstan, Kazakhstan or eastern Turkey.'],
    sources: ['https://en.wikipedia.org/wiki/Populus_nigra'],
  },
  {
    id: 'italian-cypress',
    photoSearch: 'cypress avenue Tuscany',
    name: 'Italian cypress',
    scientific: 'Cupressus sempervirens',
    wikipedia: 'Cupressus sempervirens',
    section: 'tree',
    kind: 'Conifer',
    recognise: [
      'A very narrow, dark green, flame-shaped column.',
      'Planted in rows along drives and roads, in cemeteries and around villas.',
    ],
    lookalikes: [
      { id: 'lombardy-poplar', name: 'Lombardy poplar', tell: 'Poplar is lighter green, has broad leaves and is bare in winter.' },
    ],
    nativeRange: 'The eastern Mediterranean: Greece, Crete, Cyprus, southern Turkey, the Levant and parts of Iran.',
    grownIn: 'Planted across the Mediterranean, famously in Tuscany.',
    clueCountries: ['IT', 'GR', 'TR', 'HR', 'ES', 'IL', 'AL', 'ME', 'CY'],
    science: [
      'Cypress is adapted to hot, dry Mediterranean summers and mild winters. Its narrow shape and scale leaves reduce water loss and help it shed snow.',
    ],
    history: [
      'Since Roman times the cypress has been associated with death and eternity, which is why it lines cemeteries around the Mediterranean. In Tuscany, cypress-lined roads were planted by estate owners from the Renaissance on.',
    ],
    tips: ['Dark columnar trees on rolling hills with vineyards or olives: Tuscany, or elsewhere in the Mediterranean.'],
    sources: ['https://en.wikipedia.org/wiki/Cupressus_sempervirens'],
  },
  {
    id: 'stone-pine',
    name: 'Stone pine (umbrella pine)',
    scientific: 'Pinus pinea',
    wikipedia: 'Pinus pinea',
    section: 'tree',
    kind: 'Conifer',
    recognise: [
      'A broad, flat, umbrella-shaped crown on a bare trunk.',
      'Reddish, deeply plated bark.',
    ],
    lookalikes: [
      { id: 'umbrella-thorn', name: 'Umbrella thorn acacia', tell: 'The acacia is also flat-topped but grows in savanna, with tiny leaves and thorns.' },
    ],
    nativeRange: 'The Mediterranean, from Portugal and Spain to Turkey, Lebanon and Israel.',
    grownIn: 'Planted in Italian parks and along roads; also in South Africa\'s Cape.',
    clueCountries: ['IT', 'ES', 'PT', 'TR', 'GR', 'HR', 'IL', 'LB'],
    science: ['Stone pine thrives on sandy coastal soils with hot, dry summers, and its thick bark protects it from fire.'],
    history: ['Planted by the Romans for its edible pine nuts; the umbrella pines of Rome\'s parks and Appian Way are iconic.'],
    tips: ['Umbrella-shaped pines along a road: Italy (especially around Rome), Spain or Portugal.'],
    sources: ['https://en.wikipedia.org/wiki/Pinus_pinea'],
  },
  {
    id: 'araucaria',
    photoSearch: 'Araucaria angustifolia forest',
    name: 'Paraná pine (araucária)',
    scientific: 'Araucaria angustifolia',
    wikipedia: 'Araucaria angustifolia',
    section: 'tree',
    kind: 'Conifer',
    recognise: [
      'A tall straight trunk with branches only at the top, curving upwards like a candelabra or a flat umbrella.',
      'Clusters of spiky leaves at the branch tips.',
    ],
    lookalikes: [
      { name: 'Monkey puzzle (Araucaria araucana)', tell: 'The monkey puzzle of southern Chile and Argentina has rope-like branches covered in thick scales.' },
    ],
    nativeRange: 'The southern Brazilian highlands (Paraná, Santa Catarina, Rio Grande do Sul) and Misiones in Argentina.',
    grownIn: 'Wild remnants and planted trees across the southern Brazilian plateau.',
    clueCountries: ['BR', 'AR'],
    science: [
      'Araucaria grows on the cool, rainy plateau of southern Brazil at 500–1,800 m, with frost in winter. It is a relic of ancient Gondwanan forests.',
    ],
    history: [
      'Once covering about 200,000 km², the araucaria forest was logged heavily in the 20th century; less than 5% remains. The tree is a symbol of Paraná state, whose capital Curitiba takes its name from it in Tupi.',
    ],
    tips: ['Candelabra-shaped trees on a green plateau: southern Brazil (Paraná, Santa Catarina).'],
    sources: ['https://en.wikipedia.org/wiki/Araucaria_angustifolia'],
  },
  {
    id: 'olive',
    photoSearch: 'olive grove',
    name: 'Olive tree',
    scientific: 'Olea europaea',
    wikipedia: 'Olive',
    section: 'tree',
    alsoCrop: true,
    kind: 'Broadleaf (evergreen)',
    commonsCategory: 'Olive groves',
    production: { mainProducers: ['ES', 'IT', 'GR', 'TR', 'MA', 'TN', 'PT', 'EG', 'DZ', 'SY'] },
    recognise: [
      'A small, gnarled tree with a twisted grey trunk.',
      'Silvery grey-green leaves that shimmer in the sun.',
      'Planted in neat groves on dry, pale soil, often on terraces.',
    ],
    lookalikes: [
      { name: 'Holm oak', tell: 'Holm oak is darker green and bigger, often scattered in pasture (dehesa).' },
    ],
    nativeRange: 'The Mediterranean basin; domesticated in the Levant about 6,000–8,000 years ago.',
    grownIn: 'All around the Mediterranean; also California, Chile, Argentina, Australia and South Africa.',
    clueCountries: ['ES', 'IT', 'GR', 'PT', 'TN', 'TR', 'MA', 'IL', 'JO', 'HR', 'AL', 'CY'],
    science: [
      'The olive defines the Mediterranean climate: it needs hot, dry summers, mild wet winters and a short cool period to fruit, and it dies in hard frost. The range of olive trees is often used to map the Mediterranean climate zone.',
      'Small leathery leaves with silvery hairs underneath limit water loss in summer drought.',
    ],
    history: [
      'Phoenicians, Greeks and Romans spread olive growing across the Mediterranean. Spanish missionaries took it to the Americas. Andalusia (Jaén province) is now the world\'s largest olive-growing area.',
    ],
    tips: [
      'Endless olive groves on rolling hills: Andalusia (Spain). Olive terraces on rocky slopes: Greece, Italy or the Adriatic coast.',
      'Olives mean a Mediterranean climate: they rule out northern Europe.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Olive'],
  },
  {
    id: 'umbrella-thorn',
    name: 'Umbrella thorn acacia',
    scientific: 'Vachellia tortilis',
    wikipedia: 'Vachellia tortilis',
    section: 'tree',
    kind: 'Broadleaf (thorny)',
    recognise: [
      'A flat-topped, umbrella-shaped crown on one or several trunks.',
      'Tiny feathery leaves and paired long white thorns.',
      'Scattered across dry grassland (savanna) or desert wadis.',
    ],
    lookalikes: [
      { id: 'stone-pine', name: 'Stone pine', tell: 'Stone pine also has an umbrella crown, but has needles and grows in the Mediterranean.' },
    ],
    nativeRange: 'Dry savannas and semi-deserts of Africa, from the Sahel and East Africa to South Africa, plus Arabia and the Negev.',
    grownIn: 'Wild.',
    clueCountries: ['KE', 'TZ', 'ZA', 'BW', 'SN', 'IL', 'JO'],
    science: [
      'The flat crown spreads the leaves to catch sunlight and shade the roots, and deep roots reach groundwater. Thorns protect it from browsing animals, and giraffes are one of the few that can reach the top.',
    ],
    history: ['The umbrella thorn is the iconic tree of the East African safari landscape.'],
    tips: ['Flat-topped thorny trees in dry grassland: East Africa (Kenya, Tanzania) or southern Africa (Botswana, South Africa).'],
    sources: ['https://en.wikipedia.org/wiki/Vachellia_tortilis'],
  },
  {
    id: 'baobab',
    name: 'Baobab',
    scientific: 'Adansonia digitata',
    wikipedia: 'Adansonia digitata',
    section: 'tree',
    kind: 'Broadleaf (deciduous)',
    recognise: [
      'An enormously thick, bottle- or barrel-shaped trunk, smooth and grey.',
      'Short, stubby branches that look like roots, especially when leafless in the dry season.',
    ],
    lookalikes: [
      { name: 'Malagasy baobabs', tell: 'Madagascar has six endemic baobab species, like the tall, column-trunked Grandidier\'s baobab of the Avenue of the Baobabs.' },
    ],
    nativeRange: 'Savannas of mainland Africa, from Senegal to Sudan and down to South Africa; related species in Madagascar and northern Australia.',
    grownIn: 'Wild; also around villages, where it is valued for fruit and leaves.',
    clueCountries: ['SN', 'MG', 'TZ', 'BW', 'ZA', 'KE'],
    science: [
      'The swollen trunk stores huge amounts of water (up to 120,000 litres) to survive long dry seasons. The tree drops its leaves in the dry season to save water.',
    ],
    history: [
      'Baobabs can live for over 1,500 years. Several of the oldest and largest died suddenly in the 2000s–2010s, possibly linked to climate change.',
    ],
    tips: [
      'Baobabs in dry savanna with red soil: Senegal (very common around Dakar and Thiès), southern Madagascar, Tanzania or northern South Africa.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Adansonia_digitata', 'https://en.wikipedia.org/wiki/Adansonia'],
  },
  {
    id: 'jacaranda',
    photoSearch: 'jacaranda street',
    name: 'Jacaranda',
    scientific: 'Jacaranda mimosifolia',
    wikipedia: 'Jacaranda mimosifolia',
    section: 'tree',
    kind: 'Broadleaf (deciduous)',
    recognise: [
      'A medium-sized tree covered in violet-blue flowers in spring, often before its leaves.',
      'Fern-like, finely divided leaves.',
      'Planted as a street tree; fallen flowers make purple carpets.',
    ],
    lookalikes: [{ name: 'Flame tree (Delonix)', tell: 'Similar fern-like leaves, but bright red flowers.' }],
    nativeRange: 'South-central South America: northern Argentina and southern Bolivia.',
    grownIn: 'Street tree in Pretoria and Johannesburg (South Africa), Harare (Zimbabwe), Lisbon, Brisbane and Grafton (Australia), Mexico City and Buenos Aires.',
    clueCountries: ['ZA', 'AR', 'MX', 'AU', 'PT'],
    science: ['Jacaranda needs a subtropical climate with warm summers and only light frost. Flowering is triggered by warming spring temperatures after a dry season.'],
    history: [
      'Pretoria\'s famous jacarandas date back to trees imported in the 1880s–1890s; the city is nicknamed "Jacaranda City". Japanese gardener Tatsugoro Matsuda popularised them in Mexico City in the early 20th century.',
    ],
    tips: ['Streets lined with purple-flowering trees in October–November: Pretoria/Johannesburg (South Africa) or Australia; in April, Mexico City.'],
    sources: ['https://en.wikipedia.org/wiki/Jacaranda_mimosifolia'],
  },
  {
    id: 'mango',
    photoSearch: 'mango tree',
    name: 'Mango tree',
    scientific: 'Mangifera indica',
    wikipedia: 'Mango',
    section: 'tree',
    alsoCrop: true,
    kind: 'Broadleaf (evergreen)',
    recognise: [
      'A large tree with a very dense, dark green, dome-shaped crown that casts deep shade.',
      'Long, narrow, glossy leaves; new leaves are reddish-bronze.',
      'Often standing alone in yards, villages and fields, used as a shade tree.',
    ],
    lookalikes: [{ name: 'Cashew and other tropical fruit trees', tell: 'Mango is usually larger, denser and darker than most village trees.' }],
    nativeRange: 'South Asia: north-east India, Bangladesh and Myanmar.',
    grownIn: 'Throughout the tropics and subtropics: India (the largest producer), Thailand, the Philippines, Mexico, Brazil, West and East Africa.',
    clueCountries: ['IN', 'BD', 'TH', 'PH', 'MX', 'BR', 'KE', 'NG', 'GH', 'SN'],
    science: ['Mangoes need a frost-free climate with a distinct dry season to trigger flowering. Deep roots let them survive long dry spells.'],
    history: ['Cultivated in India for over 4,000 years. Portuguese traders took mangoes to Africa and Brazil in the 16th century.'],
    tips: ['Big, dark, domed shade trees in tropical villages, especially in West Africa and India. Not decisive alone.'],
    sources: ['https://en.wikipedia.org/wiki/Mango'],
  },
  {
    id: 'bamboo',
    name: 'Bamboo',
    scientific: 'Bambusoideae',
    wikipedia: 'Bamboo',
    section: 'tree',
    kind: 'Giant grass',
    recognise: [
      'Tall, jointed, hollow green stems (culms) growing in dense clumps or groves.',
      'Feathery foliage that arches over roads; stems often lean in all directions.',
    ],
    lookalikes: [{ id: 'sugarcane', name: 'Sugarcane', tell: 'Sugarcane is also a jointed grass but grows in fields only 3–4 m tall.' }],
    nativeRange: 'Tropical and warm temperate regions worldwide, most diverse in East and Southeast Asia; also native to Latin America (e.g. Guadua) and Africa.',
    grownIn: 'Wild and planted; groves are common in southern China, Japan, Taiwan, Southeast Asia, India, Colombia and Ecuador.',
    clueCountries: ['CN', 'JP', 'TW', 'VN', 'TH', 'ID', 'IN', 'CO', 'EC'],
    science: ['Bamboo is the fastest-growing plant on earth (some species grow almost a metre a day). It needs warmth and plenty of rain, and spreads by underground rhizomes.'],
    history: ['Bamboo has been used for building, scaffolding, paper and food in Asia for thousands of years; in Colombia, Guadua bamboo is a traditional building material in the coffee region.'],
    tips: ['Clumps of bamboo along the road: East and Southeast Asia, or the Andean coffee regions of Colombia and Ecuador.'],
    sources: ['https://en.wikipedia.org/wiki/Bamboo'],
  },
  {
    id: 'saguaro',
    name: 'Saguaro cactus',
    scientific: 'Carnegiea gigantea',
    wikipedia: 'Saguaro',
    section: 'tree',
    kind: 'Cactus',
    recognise: [
      'A giant, column-shaped cactus up to 12 m tall, often with upward-curving "arms".',
      'Pleated green stem covered in spines.',
    ],
    lookalikes: [{ name: 'Cardón (Pachycereus pringlei)', tell: 'The cardón of Baja California is even bigger, with arms branching from low down.' }],
    nativeRange: 'Only the Sonoran Desert: southern Arizona (US) and Sonora (Mexico).',
    grownIn: 'Wild.',
    clueCountries: ['US', 'MX'],
    science: ['The pleated stem expands like an accordion to store water after rain. The saguaro is limited by frost: it cannot survive more than about a day below freezing, which sets its northern and upland limits.'],
    history: ['The saguaro blossom is the state flower of Arizona. Saguaros can live 150–200 years and only grow arms after 50–75 years.'],
    tips: ['Giant armed cacti: Arizona or Sonora. Nowhere else in the world.'],
    sources: ['https://en.wikipedia.org/wiki/Saguaro'],
  },
  {
    id: 'prickly-pear',
    photoSearch: 'prickly pear hedge',
    name: 'Prickly pear',
    scientific: 'Opuntia',
    wikipedia: 'Opuntia',
    section: 'tree',
    kind: 'Cactus',
    recognise: [
      'A shrubby cactus made of flat, oval, paddle-like pads.',
      'Red or yellow fruit along the edges of the pads.',
      'Often planted as hedges around fields and houses.',
    ],
    lookalikes: [{ name: 'Agave', tell: 'Agave has a rosette of long, pointed, fleshy leaves, not flat pads.' }],
    nativeRange: 'The Americas, especially Mexico.',
    grownIn: 'Naturalised around the Mediterranean (Sicily, Malta, southern Spain, Morocco, Tunisia), the Canary Islands, South Africa, Ethiopia, Eritrea, southern Madagascar and Australia (as an invasive weed).',
    clueCountries: ['MX', 'IT', 'MT', 'ES', 'MA', 'TN', 'ZA', 'MG'],
    science: ['Prickly pear stores water in its pads and uses CAM photosynthesis, opening its pores only at night to lose less water. It survives long droughts and spreads easily from fallen pads.'],
    history: [
      'The Spanish brought prickly pear to Europe in the 16th century, partly for the cochineal insect, which lives on it and produces a red dye. Its fruit (tuna) and pads (nopales) are staple foods in Mexico, and it appears on the Mexican flag.',
    ],
    tips: ['Cactus hedges in a Mediterranean landscape: Sicily, Malta, Andalusia or North Africa.'],
    sources: ['https://en.wikipedia.org/wiki/Opuntia'],
  },
  {
    id: 'mangrove',
    name: 'Mangroves',
    scientific: 'Rhizophora',
    wikipedia: 'Mangrove',
    section: 'tree',
    kind: 'Coastal trees',
    recognise: [
      'Dense, low, dark green forest right at the water\'s edge in muddy estuaries and lagoons.',
      'Arching stilt roots (red mangrove) or pencil-like breathing roots sticking up from the mud.',
    ],
    lookalikes: [{ name: 'Reeds and swamp forest', tell: 'Only mangroves grow directly in salty tidal water with visible stilt roots.' }],
    nativeRange: 'Tropical and subtropical coasts worldwide, roughly between 30° N and 30° S.',
    grownIn: 'Wild; largest areas in Indonesia, Brazil, Australia, Mexico, Nigeria, Malaysia and the Sundarbans (Bangladesh and India).',
    clueCountries: ['ID', 'BR', 'MX', 'MY', 'TH', 'PH', 'BD', 'SN'],
    science: ['Mangroves tolerate salt water by filtering it at the roots or excreting salt through their leaves. Stilt and breathing roots bring oxygen to roots in waterlogged mud. They need frost-free climates.'],
    history: ['Mangroves have been cleared for shrimp farms and rice fields, especially in Southeast Asia; they protect coasts from storms and tsunamis.'],
    tips: ['Mangroves along a coastal road: tropical coasts only. They rule out anywhere with frost.'],
    sources: ['https://en.wikipedia.org/wiki/Mangrove'],
  },
]
